### ISSUE TITLE
Dependent Form Fields - Error 422

### ISSUE THREAD

**Issue by seb-jean** [symfony/ux#1026]
On the https://ux.symfony.com/live-component/demos/dependent-form-fields page, I have a 422 error code when I do the following steps:

Meal: `Breakfast`                --> Code 200
Main food: `Eggs`              --> Code 200 
Meal: `Second Breakfast`   --> Code 422

I don't think that's normal.

**Comment by seb-jean** [comment]
Also, the error message is empty:

![Capture](https://github.com/symfony/ux/assets/12116264/2bbb6e7d-1dea-43e5-a999-24bcf8b7c2e6)

**Comment by weaverryan** [comment]
It's expected - though hopefully we can improve on this in the future. Behind the scenes, when you change the meal to `Second Breakfast`, the `Main Food` of `Eggs` is still submitted, so `mainFood` fails validation. We hide that validation error, but it's still technically invalid.

I'm working on a library to help make dynamic forms easier (independent of live components). I hope to (but haven't yet) clear out the submitted data or reset that validation error in these situations to avoid that.
