### ISSUE TITLE
[live-components] JavaScript Component Hooks not fired ?

### ISSUE THREAD

**Issue by Gulivertx** [symfony/ux#1038]
Hello,

I tried to use live component javascript hooks from custom stimulus controller without any success. It seems that the hook is not fired from stimulus controller.

On my twig component I added my custom controller
```twig
<div class="flex-1 overflow-auto" {{ attributes.defaults(stimulus_controller('medisupport-sync')) }}>
...
</div>
```

And here my medisupport-sync_controller.ts
```typescript
import {Controller} from '@hotwired/stimulus';
import {Component, getComponent} from '@symfony/ux-live-component';

export default class extends Controller<HTMLDivElement> {
    private component: Component;

    async initialize() {
        // Get Symfony live component
        this.component = await getComponent(this.element);

        this.component.on('connect', (component) => {
            console.log('connect', component);
        });

        this.component.on('render:finished', (component) => {
            console.log('render:finished', component);
        });
    }
}
```

I should get a console.log on connect and on render finished, but I do not have any thing.
Any ideas ?

<img width="391" alt="Screenshot 2023-08-07 at 10 08 42" src="https://github.com/symfony/ux/assets/7717886/3932b3d2-b53c-45b2-971a-152da3bb62b1">

EDIT : I used live-component 2.10 (current last version)

**Comment by weaverryan** [comment]
Hmm, if you add `console.log(this.component)` after the `this.component = ` line in your controller, do you see the controller instance?

**Comment by Gulivertx** [comment]
Hello Ryan,
Thank's for your reply.

Yes, I see it...


<img width="380" alt="Screenshot 2023-08-07 at 19 20 49" src="https://github.com/symfony/ux/assets/7717886/f45e7355-c9b7-4dcc-ad52-065afaf7a6a2">

EDIT : for info, my live-component is inside a turbo-frame, could be the problem ?

**Comment by weaverryan** [comment]
Hmm.

> EDIT : for info, my live-component is inside a turbo-frame, could be the problem ?

Hmm, it's possible? I can't think of why this would create a problem - but does removing it make a difference?

So, to be clear, after your component re-renders (i.e. after you change some model or submit a LiveAction), your `render:finished` callback isn't hit? I'd focus on debugging that one first (vs `connect`) as it's a bit easier tor repeat/trigger. I'm not sure what could be going wrong.

**Comment by Gulivertx** [comment]
I close this. Thank's for your help.
For this live-component I finally not used custom stimulus controller and did not investigate anymore.

But I now use component listeners in another live-components and it works as expected. I don't know why it was not working on this...
