### ISSUE TITLE
Consider moving TwigComponent out of ux

### ISSUE THREAD

**Issue by jmsche** [symfony/ux#104]
Hi, 

As discussed on Slack yesterday I don't see why the TwigComponent is part of the ux initiative, as it's "just" a Symfony bundle.

To quote the UX readme:

> Symfony UX is an initiative and set of libraries to seamlessly integrate JavaScript tools into your application.

But the TwigComponent does not include any JavaScript, hence my issue.

I already proposed something like twig/component-extra, but as it is a Symfony bundle, maybe it could be eg. symfony/twig-component-bundle or twig/component-bundle?

Thanks for reading this until the end and taking my proposal in consideration :)

**Comment by weaverryan** [comment]
You're right that it doesn't fit the definition of the UX libraries. Having it as a separate library makes maintenance a bit harder ( the macro-repo idea of many repositories being a bit easier). Still, I would be in favor of moving this.

**Comment by wouterj** [comment]
Just an idea: move TwigComponent to the twig bridge of Symfony?

**Comment by jmsche** [comment]
@wouterj Move it to twig-bridge would imply waiting for ^5.4, right?

**Comment by kbond** [comment]
I agree, what about as `twig/component` and wired up for Symfony in `twig/extra-bundle`?

**Comment by kbond** [comment]
Unfortunately, too much time has passed with this component where it is to move now.
