### ISSUE TITLE
[TogglePassword] Icon class

### ISSUE THREAD

**Issue by seb-jean** [symfony/ux#1042]
Hello,

It would be interesting to be able to modify the icon class.
For example, if I want to put a red icon and a blue icon, I can't do that.

Thanks 😃

**Comment by stloyd** [comment]
AFAIK those values can be changed, no? https://github.com/symfony/ux/blob/2.x/src/TogglePassword/src/Form/TogglePasswordTypeExtension.php#L45-L46

**Comment by feymo** [comment]
Yes, this level of customization can be achieved by passing your own custom icon(s) using the `hidden-icon` and `visible-icon` options 👍🏼
