### ISSUE TITLE
[TwigComponent] Anonymous Components  - Extensions

### ISSUE THREAD

**Issue by seb-jean** [symfony/ux#1050]
Hi,
Anonymous components support the `.html.twig` extension. How about supporting only `.twig` instead. Because we could also use `.svg.twig`.

Thanks

**Comment by kbond** [comment]
Does this not work?

```twig
<twig:Some:Thing.svg.twig/>
```

**Comment by seb-jean** [comment]
@kbond Indeed, it works.
