### ISSUE TITLE
[LiveComponent] 2.8 - not able anymore to change some model value from another js controller

### ISSUE THREAD

**Issue by sabat24** [symfony/ux#1051]
Use case:

I have got an Author component which is responsible for rendering some information about an author basing on his ID.
```php
#[LiveProp(writable: true)]
public ?int $id;
```
I have got also an AuthorList component which is responsible for listing all authors. If you select one author from list, this component will send to Author component new ID and request Author component to rerender itself

```js
// author-list_controller.js

async initialize() {
    this.authorComponent = await getComponent(document.querySelector('[data-live-component="author-single"]'));
}

setAuthor(event) {
    this.authorComponent.set('id', event.currentTarget.dataset.authorid);
    this.authorComponent.render();
}
```

In 2.7.1 it worked very well. However since 2.8 (checked in 2.10 as well) I've got an error with that line `this.authorComponent.set('id', event.currentTarget.dataset.authorid);`

> Error invoking action "click->author-list#setAuthor"
> Error: The model name "id" was never initialized. Did you forget to expose "id" as a LiveProp? Available models values are: (none)

I dumped the `authorComponent` object into console and there is an `id` in live props values

![obraz](https://github.com/symfony/ux/assets/6381661/584371a3-d76e-4186-bed8-653667e7c50d)

I even tried to set `updatesFromParent: true` in my Author component for ID model.

Any idea how can I fix this behaviour?

**Comment by sabat24** [comment]
For some reason the problem is with data on component's initialization.

In 2.7.1 in that line
```js
this.component = new Component(this.element, this.propsValue, this.dataValue, this.fingerprintValue, id, new Backend(this.urlValue, this.csrfValue), new StandardElementDriver());
```
property `this.dataValue` contains a valid correct value: `{id: 1}`

In 2.8.1 without making any changes `this.dataValue` contains an empty object `{}`

This is why then the `setDeepData` throws an exception, becuase the `data` object retrieved from `valueStore` contains an empty object `{}`.

I also changed the model name from `id` to `authorId` because I think the `id` may be reserved for entities. However it didn't solve the problem.

I can't figure out why there is empty object in `this.dataValue` on controller initialization.

**Comment by weaverryan** [comment]
Hi!

Try this:

```diff
#[LiveProp(writable: true)]
- public ?int $id;
+ public ?int $id = null;
```

And let me know if it fixes things. I believe, because the property is never initialized, the prop isn't sent to the frontend. if I'm correct, we'll need to do something about that - probably make the JavaScript more permissive (i.e. allow it to accept new values that weren't there before).

**Comment by sabat24** [comment]
I found a mistake in deployment script. For some reason Yarn didn't rebuilt all files after upgrading to 2.8.x. So I had got assets from 2.7.1.

The following declaration `public ?int $id` is fine. There is no bug. Just my fault.
