### ISSUE TITLE
[TwigComponent] unable to use outerBlock from the top most component

### ISSUE THREAD

**Issue by rdavaillaud** [symfony/ux#1053]
This issue is a follow-up of the [slack discussion](https://symfony-devs.slack.com/archives/C01FN4EQNLX/p1690473416896079).

As stated in the doc, the top most component should be able to use the "outer" template blocks
```twig
{% extends 'base.html.twig' %}

{% block call_to_action %}<strong>Attention! Free Puppies!</strong>{% endblock %}

{% block body %}
  {% component Alert %}
    {% block content %}{{ block(outerBlocks.call_to_action) }}{% endblock %}
  {% endcomponent %}
{% endblock %}
```

It seems not to work, and the `outerBlocks.call_to_action` variable return "outer__block_fallback" instead of the "outer_[block_name]_[random_id]" we obtain with component inside component.

From the slack thread:

> @sneakyvv: I looked into the issue and I found the problem, seems some code hasn't made it to the release (yet)... I'll DM you @weaverryan

**Comment by weaverryan** [comment]
Code is released now :)
