### ISSUE TITLE
Live-Components: Firefox reload caches form-values (autocomplete?) and form is not re-rendered afterwards 

### ISSUE THREAD

**Issue by jorismak** [symfony/ux#1056]
I don't know if this really is an issue for live-components to fix, but:

I have a form in a live-component, where in twig one of the form fields is rendered or not, by looking at the `formValues` array. So if a user selects a certain entry from a radio-button-group, a text-field appears.

Everything is working fine. Refreshing the form also the initialState seems to work OK. 

But Firefox behaves a bit differently. Form-values are cached when hitting reload.

So, radio button 'button 1', 'button 2', 'button 3', 'button 4'. If button 4 is selected, a text field appears. If I set the default to 'button 4' and I reload the page, Chrome neatly shows the text-field. If I change the form to 'button 2' for example, the text-field disappears. If I then reload the page, Chrome sets 'button 4' as selected again and the text-field appears again. Nice so far.

Firefox, after selecting 'button 2' and then reloading, _keeps the button 2 selected_, even if the HTML from Symfony says button 4 is `checked="checked"`.

When you hard-reload, it works fine. But Firefox apparently caches form-values for a simple reload. But no 'change' events get fired, so live-components never see that something changed on the form from the state in HTML and will not re-render the form.

In a way I can see this as a bug in Firefox, but that sounds so harsh :). But they don't fire any events while changing input controls to a different state/value than is in the HTML that's loaded, so.....

Is there something that can be done in the live-component side of things?

**Comment by weaverryan** [comment]
Hmm, yea, I’m not familiar with this behavior in Firefox. It sounds like it effectively loads the form with button 4 selected (because that’s what the HTML from the server says), then it changes to button 2 due to some caching, but doesn’t trigger a change. If that’s true, that feels like bad behavior by Firefox. The question is whether there is any way to disable it.

**Comment by jmsche** [comment]
Already fixed this a few times, IIRC setting autocomplete="off" on the form tag should work. (Or on inputs directly)

**Comment by jorismak** [comment]
Yeah I've read that to, but turning autocomplete off isn't a good option
IMHO. The chance that a user reloads is less then annoying a user with
disabling features or their browser.

Then again, it's a radio group.... Its not like those are auto filled. I
can at least try.

**Comment by jorismak** [comment]
Yeah, `autocomplete=off` in the `choice_attr` of the ChoiceType/EnumType does make Firefox behave better.

And since it's on the `input` level, it's not like turning off autocomplete for the whole form (what I really don't want to do).
So it's a workaround. Still feels like weird behaviour from Firefox though.

I get wanting to save the data entered in a form when someone reloads (how many times I didn't lose a big typed forum post because of things like that). But if you  - as a browser - decide to change an input control away from what the HTML tells you, at least send the proper events to let code react to it.
