### ISSUE TITLE
[LiveComponent] JsonException after upgrade from v2.10 to v2.11

### ISSUE THREAD

**Issue by ybouilhac** [symfony/ux#1081]
Hi everyone,

I have a LiveComponent for a search engine form with some LiveProp and a LiveAction that was working fine until I upgraded yesterday.
Since then, the first load of the component is ok but after changing any form field I got an error when then component tries to refresh:
```
JsonException
Could not decode request body.
```

The request Payload is the same as before.

After digging into the LiveComponent source code, changes in `parseDataFor` method in `LiveComponentSubscriber` seem to be the cause:

in v2.10:
`php
$requestData = $request->toArray();
`

in v2.11:
```php
try {
    $requestData = json_decode($request->request->get('data'), true, 512, \JSON_BIGINT_AS_STRING | \JSON_THROW_ON_ERROR);
} catch (\JsonException $e) {
    throw new JsonException('Could not decode request body.', $e->getCode(), $e);
}
```

`$request->request->get('data')` always returns null, causing `json_decode` to throw the exception.

Since other packages have been updated at the same time, I don't know if the root cause is in the ux-live-component one or not:
```
  - Upgrading symfony/polyfill-mbstring (v1.27.0 => v1.28.0): Extracting archive
  - Upgrading symfony/polyfill-php83 (v1.27.0 => v1.28.0): Extracting archive
  - Upgrading symfony/http-foundation (v6.3.2 => v6.3.4): Extracting archive
  - Upgrading symfony/var-dumper (v6.3.3 => v6.3.4): Extracting archive
  - Upgrading symfony/http-kernel (v6.3.3 => v6.3.4): Extracting archive
  - Upgrading symfony/var-exporter (v6.3.2 => v6.3.4): Extracting archive
  - Upgrading symfony/dependency-injection (v6.3.2 => v6.3.4): Extracting archive
  - Upgrading symfony/cache (v6.3.2 => v6.3.4): Extracting archive
  - Upgrading symfony/framework-bundle (v6.3.2 => v6.3.4): Extracting archive
  - Upgrading symfony/polyfill-intl-normalizer (v1.27.0 => v1.28.0): Extracting archive
  - Upgrading symfony/polyfill-intl-grapheme (v1.27.0 => v1.28.0): Extracting archive
  - Upgrading symfony/console (v6.3.2 => v6.3.4): Extracting archive
  - Upgrading doctrine/dbal (3.6.5 => 3.6.6): Extracting archive
  - Upgrading symfony/doctrine-bridge (v6.3.2 => v6.3.4): Extracting archive
  - Upgrading symfony/validator (v6.3.2 => v6.3.4): Extracting archive
  - Upgrading symfony/polyfill-uuid (v1.27.0 => v1.28.0): Extracting archive
  - Upgrading twig/twig (v3.7.0 => v3.7.1): Extracting archive
  - Upgrading symfony/security-http (v6.3.2 => v6.3.4): Extracting archive
  - Upgrading symfony/clock (v6.3.1 => v6.3.4): Extracting archive
  - Upgrading symfony/security-bundle (v6.3.3 => v6.3.4): Extracting archive
  - Upgrading symfony/polyfill-intl-icu (v1.27.0 => v1.28.0): Extracting archive
  - Upgrading doctrine/orm (2.16.1 => 2.16.2): Extracting archive
  - Upgrading phpdocumentor/type-resolver (1.7.2 => 1.7.3): Extracting archive
  - Upgrading nikic/php-parser (v4.16.0 => v4.17.1): Extracting archive
  - Upgrading phpunit/phpunit (9.6.10 => 9.6.11): Extracting archive
  - Upgrading symfony/dom-crawler (v6.3.1 => v6.3.4): Extracting archive
  - Upgrading symfony/messenger (v6.3.3 => v6.3.4): Extracting archive
  - Upgrading symfony/polyfill-intl-idn (v1.27.0 => v1.28.0): Extracting archive
  - Upgrading symfony/process (v6.3.2 => v6.3.4): Extracting archive
  - Upgrading symfony/stimulus-bundle (v2.10.0 => v2.11.0): Extracting archive
  - Upgrading symfony/ux-autocomplete (v2.10.0 => v2.11.0): Extracting archive
  - Upgrading symfony/ux-twig-component (v2.10.0 => v2.11.0): Extracting archive
  - Upgrading symfony/serializer (v6.3.3 => v6.3.4): Extracting archive
  - Upgrading symfony/ux-live-component (v2.10.0 => v2.11.0): Extracting archive
  - Upgrading twig/extra-bundle (v3.7.0 => v3.7.1): Extracting archive
  - Upgrading twig/intl-extra (v3.7.0 => v3.7.1): Extracting archive
```

**Comment by ker0x** [comment]
I had the same problem with one of my live components. This was due to the fact that one of the component's properties had a nullable type: `?Profile $profile`. After removing the nullable type, everything works fine.

**Comment by weaverryan** [comment]
> This was due to the fact that one of the component's properties had a nullable type: ?Profile $profile. After removing the nullable type, everything works fine

That seems really odd...

About the main issue - could you triple-check that your frontend JavaScript is also updated? Assuming you're using Encore:

```
npm install --force
```

Then restart Encore and do a force refresh. We did change the format of how we send the data, but that was also changed on the frontend as well.

**Comment by ybouilhac** [comment]
@weaverryan thank you, the issue was, indeed, with the frontend

What I did:
```
composer update
yarn install --force
yarn build
```

**Comment by ybouilhac** [comment]
> I had the same problem with one of my live components. This was due to the fact that one of the component's properties had a nullable type: `?Profile $profile`. After removing the nullable type, everything works fine.

I do have a nullable property and everything is working fine after updating the frontend
