### ISSUE TITLE
[TwigComponent] Undefined var `$name` in ComponentExtension ?

### ISSUE THREAD

**Issue by smnandre** [symfony/ux#1115]
In TwigComponent/src/Twig/[ComponentExtension](https://github.com/symfony/ux/blob/7412bd2384aac5c0f41d5f6321218b54dd603006/src/TwigComponent/src/Twig/ComponentExtension.php#L83
), there is this method 

```php
    public function finishEmbeddedComponentRender(): void
    {
        try {
            $this->container->get(ComponentRenderer::class)->finishEmbeddedComponentRender();
        } catch (\Throwable $e) {
            $this->throwRuntimeError($name, $e);
        }
    }
```

I fear this won't work as `$name` is not defined... or am I missing something ?

**Comment by kbond** [comment]
Looks like a bug to me. Either we need to change the catch logic or or pass the name to the method. I don't know the context of this logic off the top of my head. @sneakyvv?

**Comment by smnandre** [comment]
Same thing  @kbond :)

I'd code that, but i have no idea how to test that correctly, with LiveComponents, ...

> 
        $compiler->write('$this->extensions[')
            ->string(ComponentExtension::class)
            ->raw(']->finishEmbeddedComponentRender(')
            ->string($this->getAttribute('component'))
            ->string(')')
            ->raw(";\n")
        ;

**Comment by kbond** [comment]
Did you hit this _try...catch_ and get an `\ArgumentCountError` thrown?

**Comment by smnandre** [comment]
Hmm where ? Around this one or in throwRuntimeError ? Sorry i'm not sure how to handle that.. :|

**Comment by kbond** [comment]
I'm just wondering how you stumbled upon this bug. Just by looking at code or did an app actually run this and throw an exception.

(I'm trying to gauge how important it is to require the name here - can we just remove the try catch and let the caught exception be thrown as normal?)

**Comment by smnandre** [comment]
Reading code, and PhpStorm alerted me with some red wavy line :)

**Comment by smnandre** [comment]
I have to leave, i can try your solution in a couple of hours
