### ISSUE TITLE
Chart JS doesn't work

### ISSUE THREAD

**Issue by deividgp** [symfony/ux#112]
I'm developing my first Symfony project and just installed all needed packages for Chart JS but I still can't see the example chart, might be a packages problem. The project is located on my [repository](https://github.com/deividgp/Bookings) (AdminHomeController specifically)  and I'm using 
"@symfony/webpack-encore": "^1.0.0"
"@symfony/stimulus-bridge": "^2.0.0"
"symfony/webpack-encore-bundle": "^1.12"
"stimulus": "^2.0.0"
Thanks a lot in advance.

**Comment by weaverryan** [comment]
Hi @deividgp!

I think you're missing the `{{ encore_entry_script_tags('app') }} in your `base.html.twig`. So probably you are doing everything correct, including executing Encore to package up all of your JavaScript, but you're missing this line, which includes the JavaScript. You should also add `{{ encore_entry_link_tags('app') }}`. Here's the example `base.html.twig` - https://github.com/symfony/recipes/blob/master/symfony/twig-bundle/3.3/templates/base.html.twig - you basically want what's here, but of course with the 2 `encore_entry...` function uncommented :).

Cheers!

**Comment by deividgp** [comment]
> 
> 
> Hi @deividgp!
> 
> I think you're missing the `{{ encore_entry_script_tags('app') }} in your `base.html.twig`. So probably you are doing everything correct, including executing Encore to package up all of your JavaScript, but you're missing this line, which includes the JavaScript. You should also add `{{ encore_entry_link_tags('app') }}`. Here's the example `base.html.twig`- https://github.com/symfony/recipes/blob/master/symfony/twig-bundle/3.3/templates/base.html.twig - you basically want what's here, but of course with the 2`encore_entry...` function uncommented :).
> 
> Cheers!

Much appreciated, going to close the issue now.
