### ISSUE TITLE
[LiveComponent] Funny bug with browser translation

### ISSUE THREAD

**Issue by Warps73** [symfony/ux#1120]
Hello, our users have found a funny bug! It took me a while to find it and reproduce it. 😄 

You can't see it in the video, but I've activated the browser translation.

[screencast-ux.symfony.com-2023.09.16-18_20_56.webm](https://github.com/symfony/ux/assets/35427178/15be810b-0482-4da6-ac2c-102d0e25d122)

If you possess a different approach or solution to this problem, I would greatly appreciate your input.

**Comment by smnandre** [comment]
Do you do something particular at 0'06 (when the lang switch from EN to FR) ? Does the console show any bugs ?

**Comment by Warps73** [comment]
>Do you do something particular at 0'06

No, nothing in particular, I just right-clicked and activated the translation.

> Does the console show any bugs ?

 I've checked the console and there's no error.

**Comment by weaverryan** [comment]
Hmm. I'm not sure how this feature works behind the scenes. But if the browser translator is actually mutating the Dom (and triggering the `MutationObserver`), then to LiveComponents, this will look like some external JavaScript is mutating DOM. And so, on re-render, it will try not to remove the custom-added stuff. This is a guess, but it looks like I might be correct - https://github.com/facebook/react/issues/11538

Immediately, I'm not sure what to do here. LiveComponents watches for mutation changes and tries to keep them on purpose: it's the smart rendering system. But I haven't checked yet to see precisely how the DOM is being mutated by the translations. Perhaps if it mutates in some predictable way, we can code to avoid that.

**Comment by smnandre** [comment]
I played with it and the bug is only in Chrome, because Google Translate inject some <font> tags where there was only text nodes.

Safari & Firefox seem immune (on macOS)

A quick fix, before a cleaner solution, could be to add "`notranslate`" class to some elements... if you want Google to _not_ translate them... I tested: it works.
