### ISSUE TITLE
Not possible to use options defined by `AutocompleteChoiceTypeExtension` when using a `AsEntityAutocompleteField` field

### ISSUE THREAD

**Issue by bendavies** [symfony/ux#1129]
Hi,

If you define an `AsEntityAutocompleteField` as per [the docs](https://symfony.com/bundles/ux-autocomplete/current/index.html#usage-in-a-form-with-ajax), but add some `tom_select_options` at point of use:

<details>
<summary>FoodAutocompleteField.php</summary>

```php
<?php

// src/Form/FoodAutocompleteField.php
// ...

use Symfony\UX\Autocomplete\Form\AsEntityAutocompleteField;
use Symfony\UX\Autocomplete\Form\ParentEntityAutocompleteType;

#[AsEntityAutocompleteField]
class FoodAutocompleteField extends AbstractType
{
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'class' => Food::class,
            'placeholder' => 'What should we eat?',
        ]);
    }

    public function getParent(): string
    {
        return ParentEntityAutocompleteType::class;
    }
}
```
</details>

<details>
<summary>SomeForm.php</summary>

```php
<?php

// src/Form/SomeForm.php
// ...

class SomeForm extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder->add('food', FoodAutocompleteField::class, [
            'label' => 'Food'',
            'tom_select_options' => [
                'plugins' => ['dropdown_input'],
            ],
        ]);
    }

}
```
</details>

You will receive:

```
An error has occurred resolving the options of the form "App\Form\FoodAutocompleteField": The option "tom_select_options" does not exist
```

Thanks,
Ben

**Comment by weaverryan** [comment]
I haven’t looked quickly enough yet to see if this helps, but we have a refactoring of the autocomplete form internals here https://github.com/yceruto/symfony-ux/tree/autocomplete - it needs a champion to check this and create a PR using it. yceruto gave me the code with the understanding that we would take it and integrate it.

if anyone wants to take this on, that would be great. If it wouldn’t solve this issue anyway, sorry for the noise :)

**Comment by bendavies** [comment]
finally looked at this. the above PR doesn't fix the the issue, unfortuantely.

**Comment by bendavies** [comment]
@norkunas do you know where i might start hunting this down?

**Comment by bendavies** [comment]
ah, this issue is fixed, but now we get a different error: https://github.com/symfony/ux/issues/1128
