### ISSUE TITLE
[Question] How to refer to assets from an UX Controller

### ISSUE THREAD

**Issue by Spomky** [symfony/ux#1137]
Let say I have an UX Controller that uses Leaflet for rendering a map with a marker.

```js
'use strict';

import {Controller} from '@hotwired/stimulus';
import L from 'leaflet';
import MarkerIcon from '../images/marker-icon.png';
import MarkerShadow from '../images/marker-shadow.png';

export default class extends Controller {
  static values = {
    latitude: {type: Number, default: 0},
    longitude: {type: Number, default: 0},
  };

  connect() {
    L.Marker.prototype.options.icon = L.icon({
      iconUrl: MarkerIcon,
      shadowUrl: MarkerShadow,
      iconSize: [24, 36],
      iconAnchor: [12, 36]
    });
    const map = L.map(this.element, { zoomControl: false }).setView([this.latitudeValue, this.longitudeValue], 13);
    L.marker([this.latitudeValue, this.longitudeValue]).addTo(map);
    L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
      maxZoom: 19,
      attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
    }).addTo(map);
  }
}
```

I would like to get rid of Webpack a only refer to the images.
At first sight, I imagined that using `iconUrl:  '../images/marker-icon.png',` would be fine, but this is not the case.
The link to the image is not correct.

Is it possible and how would you do that ?

**Comment by weaverryan** [comment]
That’s a great question. Importing image files doesn’t work with native JavaScript/importmaps/AssetMapper. It’s kind of a thing webpack invented, but I totally understand that we got used to the convenience.

Anyway, the answer is to pass the images as values to the stimulus controller. Is that simple - though I realize if you are rendering this controller frequently, that could be annoying.

i don’t know if it’s worth it, but we could create a system to help with this. The only thing you’re missing if you do the iconUrl: ../… solution is the version hash. AssetMapper dumps a manifest.json file with a map to the versioned filenames (though maybe not in dev), which could be used in JavaScript to find the final name.

Or… we could add something to AssetMapper to actually support importing images… in a similar way to the upcoming CSS support in 6.4. Hmm…

**Comment by Spomky** [comment]
Many thanks for your anwser.
I now pass the assets as values, but it becomes less readable. I do not call it many times, so still accepable.

> Or… we could add something to AssetMapper to actually support importing images… in a similar way to the upcoming CSS support in 6.4. Hmm…

By "Hmm...", do you mean you have something in mind? Let me know if I can help finding a more elegant solution than using values.

**Comment by weaverryan** [comment]
Yea, I have something in mind, I just don’t know if it’s a good idea or not :). So for now, let’s stick with values as, like you mentioned, it’s fairly rare.

**Comment by Spomky** [comment]
👍
Thanks. I close this for now.
