### ISSUE TITLE
[TwigComponent] Anonymous component props and Class backed component properties different behavior

### ISSUE THREAD

**Issue by rdavaillaud** [symfony/ux#1138]
Hi,

It seems that when using anonymous component, with the tag and HTML syntax, any defined property with a default value that is also defined in the parent/caller template is overridden by the parent template value.  
This behavior is not consistent with the function syntax and the class backed one, they should show the component default value.

## How to reproduce

The class backed define a property `message` with a default value 'foo'.
```php
// ClassBacked.php
#[AsTwigComponent]
final class ClassBacked
{
    public string $message = "foo";
}
```

```twig
{# ClassBacked.html.twig #}
{{ message }}
```

The anonymous one define a prop `message` 
```twig
{# Anonymous.html.twig #}
{% props message="foo" %}
{{ message }}
```

The parent template call each one in each available syntax:  

```twig
{# test.html.twig #}
{% set message = 'bar' %}

Function:
{{ component('ClassBacked')  }}
{{ component('Anonymous')  }}

<br>
tag:
{% component ClassBacked  %}
{% endcomponent %}
{% component Anonymous  %}
{% endcomponent %}

<br>
HTML:
<twig:ClassBacked></twig:ClassBacked>
<twig:Anonymous></twig:Anonymous>
```
## Result expected

```text
Function: foo foo
tag: foo foo
HTML: foo foo
```

## Result obtain instead

```text
Function: foo foo
tag: foo bar
HTML: foo bar
```

**Comment by weaverryan** [comment]
@WebMamba you may be able to help here and the bug makes sense. For the anonymous components, when determining whether or not we should set the default value, we need to check if that prop was passed when rendering the component, not just whether or not it’s in the context at all. Do we have the info already to make that determination?

btw, great bug report 👍

**Comment by WebMamba** [comment]
Yes I am on it 😁
