### ISSUE TITLE
[Autocomplete] Add a way to translate "Loading more results"

### ISSUE THREAD

**Issue by lukepass** [symfony/ux#1159]
Hello, as per title it could be useful to customize the "Loading more results" message that appears when scrolling down the select.

Thanks.

**Comment by weaverryan** [comment]
Yea, it looks like under `render` - https://github.com/symfony/ux/blob/2.x/src/Autocomplete/assets/src/controller.ts#L220 - we need to specify the `loading_more` from https://tom-select.js.org/plugins/virtual_scroll/ - set it to a value that can be passed in. PR welcome :)
