### ISSUE TITLE
Does registerReactControllerComponents can specify the Stimulus controller folder itself?

### ISSUE THREAD

**Issue by gremo** [symfony/ux#1176]
[Documentation](https://symfony.com/bundles/ux-react/current/index.html#usage) give us an example on how to call `registerReactControllerComponents`, using `./react/controllers` as folder:

```js
// assets/app.js
import { registerReactControllerComponents } from '@symfony/ux-react';

registerReactControllerComponents(require.context('./react/controllers', true, /\.(j|t)sx?$/));
```

> This will load all React components located in the assets/react/controllers directory.

But **doesn't give us any indication about using it with Stimulus** controllers, that is if using  `controllers` as folder would create any kind of problem with Stimulus ones. 

Complete example:

```js
import { startStimulusApp } from '@symfony/stimulus-bridge';
import { registerReactControllerComponents } from '@symfony/ux-react';

// Registers Stimulus controllers from controllers.json and in the controllers/ directory
export const app = startStimulusApp(
  require.context('@symfony/stimulus-bridge/lazy-controller-loader!./controllers', true, /\.[jt]sx?$/),
);
// register any custom, 3rd party controllers here
// app.register('some_controller_name', SomeImportedController);

// Registers React controllers in the controllers/ directory
registerReactControllerComponents(require.context('./controllers', true, /\.(j|t)sx?$/));
```

**The regular expression seems the same**, so `MyController.jsx` would be matched by `startStimulusApp `and `registerReactControllerComponents`.

Thoughts?

**Comment by weaverryan** [comment]
Hi there!

To make sure I understand, are you wondering whether using `assets/controllers/` to store a mixture of React "controller components" and Stimulus controllers would be ok? My guess is... maybe? :). Stimulus should ignore any files that don't end with `-controller.js` or `_controller.js`, so I think Stimulus would ignore the React components. For the other way around, I'm guessing that the React UX code WOULD see the Stimulus controllers and think they might be a component, but I'm not sure this would cause a problem unless you tried to render a React component using the name of a stimulus controller.

Anyway, I'm not sure mixing them is a great idea - as they're two different concepts. But if you did, probably you could tweak the regex to match only what you want - e.g. make the React always look for .jsx - so `/\.jsx?$/` - and make Stimulus always look for `.js` - so `/\.js?$/`.

**Comment by gremo** [comment]
Thanks @weaverryan for the answer. 

Of course I can live with two folders having the same "conceptual" meaning, but I think that having `/controllers` and `/react/controllers` isn't good, they are both controllers, so not a "mixture" in the wrong way :)

So thanks for the clarification. I may change the regex eventually.
