### ISSUE TITLE
bin/console config:dump not supported?

### ISSUE THREAD

**Issue by melbings** [symfony/ux#1206]
After requiring `symfony/ux-twig-component`, running

`php bin/console config:dump twig_component`

tells me

`The extension with alias "twig_component" does not have its getConfiguration() method setup.`

Is this the same for everyone, and if so, should config:dump be supported in the future?

**Comment by smnandre** [comment]
It will be supported in the 2.13 (you can already test it with the 2.x-dev if you want)

Also in 2.13:  
* an interactive `debug:twig-component` command 
* a dedicated debug toolbar / profiler panel

**Comment by weaverryan** [comment]
Yea, previous to 2.13, there simply wasn't any config for `twig_component` at all :)
