### ISSUE TITLE
[Live] Dependent fields demo: add dependency requirement

### ISSUE THREAD

**Issue by jmsche** [symfony/ux#1207]
On the demo: https://ux.symfony.com/demos/live-component/dependent-form-fields

It must be indicated that a `composer require symfonycasts/dynamic-forms` is required to make the example work.

**Comment by weaverryan** [comment]
You're right! It's a matter of where - @smnandre any idea where we could put this and make it look good? We could also just put it in the description near the top - e.g. in the `Say goodbye to the hassle of dependent` area.

**Comment by smnandre** [comment]
I'd rather group the (many) modifications of these pages and handle them with an "horizontal" approach 
(the need to display "requirements" is something we may need really soon on other pages)

So i just add links and a dedicated (and more visible) comment
