### ISSUE TITLE
[LiveComponent] Normalize true/false model values?

### ISSUE THREAD

**Issue by weaverryan** [symfony/ux#1211]
Via a question from Slack:

```html
<button
    data-model="isDeleting"
    data-value="false"
    data-action="live#update"
/>
```

This sends the string `false` for the field. I think we should be careful trying to "guess" types and coerce them. But perhaps we should for `true` and `false`? We could do this in JavaScript (ALWAYS change `true` to a boolean), or in PHP (i.e. look at the type of the property, and if it is `bool`, add some code to coerce `true`/`false`. Heck that might be pretty easy - https://github.com/symfony/ux/blob/2.x/src/LiveComponent/src/LiveComponentHydrator.php#L448-L450

**Comment by smnandre** [comment]
Stimulus does it too https://stimulus.hotwired.dev/reference/values
