### ISSUE TITLE
[AssetMapper] link tags not generated in 6.4-dev

### ISSUE THREAD

**Issue by tacman** [symfony/ux#1217]
```bash
symfony new ux-link-bug --webapp --version=next && cd ux-link-bug
composer req symfony/asset-mapper:^6.4 symfony/stimulus-bundle:2.x-dev

bin/console importmap:require bootstrap
cat importmap.php
bin/console make:controller AppController
sed -i "s|Route('/app'|Route('/'|" src/Controller/AppController.php

cat > templates/app/index.html.twig <<END
{% extends 'base.html.twig' %}
{% block body %}
<h3>ux_controller_link_tags()</h3>
<textarea>{{ ux_controller_link_tags()|raw }}</textarea>
{% endblock %}
END
symfony server:start -d
symfony open:local
```

There are no link tags generated.  This may be related to #1191, but I figured I'd add this in case it helps with testing.

**Comment by weaverryan** [comment]
Hey Tac!

Check your HTML source - you WILL see a `<link rel="stylesheet" href="/assets/styles/app-713d9828d7058036a44786836080554c.css">`.

The confusion comes from the fact that, with AssetMapper 6.4, `ux_controller_link_tags()` does nothing. It'll be removed. The link tags actually come from `{{ importmap() }}`. 

Also, if you want bootstrap to be a CSS file, also import it from `assets/app.js`:

```
import 'bootstrap/dist/css/bootstrap.min.css';
```

Cheers!
