### ISSUE TITLE
Demo with both AssetMapper and Webpack (6.4/7)

### ISSUE THREAD

**Issue by tacman** [symfony/ux#1231]
I have a version of this demo working with Symfony 7

```bash
git clone git@github.com:tacman/symfony-demo.git --branch=symfony7 symfony7-demo && cd symfony7-demo
composer install && yarn install && yarn dev
symfony server:start -d
symfony open:local
```

The PHP part works fine, but there are issues with stimulus.  I imagine others who are migrating to Symfony 7 may run into the same issues, so maybe this issue can be the beginning of a migration guide.

In particular, when using both webpack and AssetMapper, should there be TWO app.js files, once that's the entrypoint for the importmap and the other that's for webpack?  If I load javascript dependencies via Assetmapper / importmap, will they be available in my webpack-handled javascript?

            {{ encore_entry_script_tags('app') }}

And in particular, how should the stimulus bootstrap file (which of course needs to change from the bridge to the stimulus-bundle).    Currently it fails:

```
 ERROR  Failed to compile with 1 errors                                                                                                                       8:16:37 AM

Module build failed: Module not found:
"./assets/bootstrap.js" contains a reference to the file "@symfony/stimulus-bundle".
This file can not be found, please check it for typos or update it if the file got moved.
```

Of course, I'd eventually love to get rid of the whole yarn install && yarn dev step, but in practice I'm sure I'll need it in my own projects for a while, and so understanding how to use them both will be important.

I know stimulus-bundle is still under development, but if you have some guidance on having both active at the same time, it would be very helpful.

Thanks.

**Comment by weaverryan** [comment]
> In particular, when using both webpack and AssetMapper, should there be TWO app.js files, once that's the entrypoint for the importmap and the other that's for webpack

Simple answer is: you should NOT have both Webpack & AssetMapper. That's just not something we're going to support - it's effectively to competing "bundling" types of systems. You should stick with Webpack or fully convert to AssetMapper. It's, in theory possible, but it's complex enough that we don't want to go down that road.

**Comment by tacman** [comment]
Thanks, that makes sense.  

I have an issue now with a javascript library that works with webpack but not with assetmapper.  I'm 99% sure it's because webpack offered the autoIncludeJQuery().  jQuery is still ubiquitous -- if you look at the most popular packages on jsdeliver, not only is jquery near the top but some of the others are jquery plugins.

I assume that's something the library authors will need to fix.  Here's an example:

https://datatables.net/forums/discussion/77434/typeerror-t-is-not-a-function#latest

I'll close the issue since it's not related to the topic, and try to come up with some test cases for jquery plugins.  Maybe there's some way to inject jquery like webpack did?

**Comment by weaverryan** [comment]
That's an interesting example you pointed to. The `import t from "jquery";` in the offending library looks perfectly fine. As does the `jquery` in your importmap. It doesn't *look*, on the surface, like a library that needs us to hack it (with a jquery autprovider type of thing. I wonder what `console.log(t)` prints if you hacked that into the vendor file. I'm interested to find these poorly-behaving libraries to get to the bottom of what's happening.

**Comment by tacman** [comment]
>> you should NOT have both Webpack & AssetMapper

can that be qualified with "on the same page"?  That is, if I'm migrating an application, can I have two base files, one that uses a layout.html.twig that calls assetmapper, and the other that uses webpack?  For example, I could incrementally migrate the pages that only uses bootstrap and stimulus to assetmapper (obviously including the custom stimulus dependencies).

For example, in the case of the Symfony Demo, could the admin pages could be on one system and the public pages be on the other?  package.json would be used for the webpack ones, and importmap.php for the others.

One complication is what the 3rd-party bundles, but I think if assetmapper is installed, it simply prepends the namespace to resolve the javascript paths.

Obviously, I _want_ to drop webpack asap, and am trying to figure out a migration path.

**Comment by weaverryan** [comment]
Using them both is possible, yes. Mentally, it's more to juggle, that's why I don't recommend it. I'd rather, at least at first, try to figure out & fix any asset mapper problems you're having.

**Comment by tacman** [comment]
> That's an interesting example you pointed to. The `import t from "jquery";` in the offending library looks perfectly fine. As does the `jquery` in your importmap. It doesn't _look_, on the surface, like a library that needs us to hack it (with a jquery autprovider type of thing

Here's the JSFiddle: https://jsfiddle.net/tacman1123/qnh16kog/

I _think_ the issue is javascript plugins that expect a global jQuery or $ object.  Perhaps there's some way to add the plugin to jQuery or initialize the plugin with your own copy of jQuery.  I'm hoping the author will provide some guidance.

```js
<script type="module">
        import jQuery from 'https://cdn.jsdelivr.net/npm/jquery@3.7.1/+esm'
        import DataTable from 'https://cdn.jsdelivr.net/npm/datatables.net-bs5@1.13.6/+esm'

    </script>
```

Maybe I need something like

```js
const $ = jQuery;
global.jQuery = global.$ = $;
```

Of course, I think that was the reason that .autoIncludeJQuery() existed.

**Comment by weaverryan** [comment]
Ok, I found the issue - https://github.com/DataTables/DataTablesSrc/issues/246

So, it's a "bug" on their side. Really, an accident - but it's something that should be fixed on their end. The workaround, in AssetMapper, is, after running `importmap:require datatables.net-bs5`, manually go into `importmap.php`, adjust the `datatables.net` version to 1.13.6 (to match `datatables.net-bs5`), then run `importmap:install`.
