### ISSUE TITLE
[LiveComponet] [Autocomplete] Bug when combining live with autocomplete select field

### ISSUE THREAD

**Issue by tdumalin** [symfony/ux#1261]
Hi there,

I'don't find the reason but in some cases when a field has the 'autocomplete' => true option in a live component the real value selected in the form is not the value sent when submitting.

I've created a repository to reproduce the bug:
 [https://github.com/tdumalin/bug-ux-live-plus-autocomplete](https://github.com/tdumalin/bug-ux-live-plus-autocomplete)
All the installation informations are setted in the README file.

I've notice the bug multiple times but always on select input, noticed on:
ChoiceType
EnumType
EntityType

Adding a random data-live-id on the row_attr seems to resolve the bug but it's not convenient to set globally
```twig
{{ form_row(form.type, {row_attr: {
        'data-live-id': random()
}}) }}
```
If needed here is my work around:

```php
<?php

namespace App\Form\Extension;

use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractTypeExtension;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\EnumType;
use Symfony\Component\OptionsResolver\Options;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AddAutocompleteExtension extends AbstractTypeExtension
{

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'autocomplete' => true,
        ]);


        $resolver->setNormalizer('row_attr', function (Options $options, $value) {
            if ($options['autocomplete']) {
                $value['data-live-id'] = uniqid('autocomplete-');
            }

            return $value;
        });
    }

    public static function getExtendedTypes(): iterable
    {
        return [
            ChoiceType::class,
            EntityType::class,
            EnumType::class,
        ];
    }
}

```

NB: This work around making you lost the focus of the input

**Comment by luchidalgo** [comment]
Related with #1241

**Comment by tdumalin** [comment]
Hi @luchidalgo 

Yes it seems related with your issue, but I'm not sure it has something to do with the LiveCollectionType.
Did you try the data-live-id work around ?

It's some kind of odd that nobody noticed this, because these two UX bundles are very likely to be used together

**Comment by Pierre90** [comment]
Hi @luchidalgo 

I got the same problem with an EntityType. When `autocomplete => true`, the value send to the form is always the last option value of the select list. 

With a field like this : 

```

            ->add('product', EntityType::class, [
                'class'         => Product::class,
                'autocomplete'  => true,
                'required'      => false,
                'placeholder'   => 'common.none',
                'label'         => 'event.product',
                'query_builder' => fn (ProductRepository $repository) => $repository
                    ->createQueryBuilder('product')
                    ->orderBy('product.section', 'ASC')
                    ->addOrderBy('product.name', 'ASC'),
            ])
```

I actually manage to fix it just by adding ` 'attr'  => ['data-live-ignore' => true],`. 

Or for some obscure reason, if I add a 'group_by', it seems to work well even without the data-live-ignore. I don't know why...

**Comment by rvmourik** [comment]
I combined the solution from @Pierre90 and @tdumalin to the following:

```php
<?php

namespace App\Form\Extension;

use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractTypeExtension;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\EnumType;
use Symfony\Component\OptionsResolver\Options;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * This is a temporary fix for the issue that with both an Autocomplete field and form as
 * LiveComponent activated the autocomplete field always selects the last option.
 *
 * For more details:
 * @see https://github.com/symfony/ux/issues/1261
 */
class AutocompleteLiveComponentFixExtension extends AbstractTypeExtension
{
    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setNormalizer('row_attr', function (Options $options, $value) {
            if ($options['autocomplete']) {
                $value['data-live-ignore'] = true;
            }

            return $value;
        });
    }

    /**
     * @return array<class-string>
     */
    public static function getExtendedTypes(): iterable
    {
        return [
            ChoiceType::class,
            EntityType::class,
            EnumType::class,
        ];
    }
}

````

**Comment by tdumalin** [comment]
Hi @rvmourik 

Yes that should do the job, just be aware that when using data-live-ignore, the field will never be re-rendered on a LiveComponent, so if you what to use a dynamic form modification like the sport/position doc example:
[https://symfony.com/doc/current/form/dynamic_form_modification.html#dynamic-generation-for-submitted-forms](https://symfony.com/doc/current/form/dynamic_form_modification.html#dynamic-generation-for-submitted-forms)

The field 'position' will never be re-rendered and so will not be depending on the sport field value

**Comment by rvmourik** [comment]
> Hi @rvmourik
> 
> Yes that should do the job, just be aware that when using data-live-ignore, the field will never be re-rendered on a LiveComponent, so if you what to use a dynamic form modification like the sport/position doc example: https://symfony.com/doc/current/form/dynamic_form_modification.html#dynamic-generation-for-submitted-forms
> 
> The field 'position' will never be re-rendered and so will not be depending on the sport field value

Thanks for the clarification

**Comment by RehArk** [comment]
Hello, I have encountered the same bug, but I need to rerender my field as choices depend on it. Do you have any solutions to provide? If not, could you please notify when the bug is fixed ? 😁

Edit : this bug affect also ChoiceType, and possibly other select field type

**Comment by tdumalin** [comment]
@weaverryan ,

Good news and good job!
How can we know on which symfony/ux-autocomplete version the patch will be deployed ?
