### ISSUE TITLE
[LiveComponent] LiveAction argument do not allow a closing parenthesis

### ISSUE THREAD

**Issue by easis** [symfony/ux#1283]
Hi! I have a component where I list some strings and a user selects one of them.

I found that if I have a Live Action argument with a closing parenthesis like this
```html
<button type="button" data-action="live#action" data-action-name="myAction(foo=bar(123))">Action</button>
```
it throws the error: [`Missing space after myAction`](https://github.com/symfony/ux-live-component/blob/67372d192aeb8a4216bbc6f64ba34e438afe7cec/assets/src/Directive/directives_parser.ts#L224) due to [this](https://github.com/symfony/ux-live-component/blob/67372d192aeb8a4216bbc6f64ba34e438afe7cec/assets/src/Directive/directives_parser.ts#L183).

I was expecting to enclose the argument values with single or double quotes but checking the directive parser it seems this is not supported (_yet?_):
```html
<button type="button" data-action="live#action" data-action-name="myAction(foo='bar(123)')">Action</button>
```

To workaround this I'm encoding the strings in hex (with a custom Twig filter) and decoding in the component function.

**Comment by smnandre** [comment]
Hello @easis : it's something we are working on, currently you're right it wont work. 

I do hope to bring you some good news next week :)

**Comment by easis** [comment]
Good to hear, thank you!

**Comment by smnandre** [comment]
@easis i did not forget you don't worry :)

**Comment by easis** [comment]
> @easis i did not forget you don't worry :)

No worries! Take your time :)

**Comment by melbings** [comment]
Also, is there a way to pass an argument value that contains a comma (",")?

**Comment by smnandre** [comment]
After ~~weeks~~ monthes (😅) of hesitation, it's been acted to use Stimulus format for the action / parameters :) 

(cf the PR before your message)

So it should allow spaces, comas, accents, symbols etc.. easily :)

**Comment by smnandre** [comment]
@easis just so you know we did not forgot you ... we started to work on a full grammar parser to compute those args... but in the end we felt it was not worth it to develop such a tool only for a custom syntax, when other implementations already existed.

**Comment by melbings** [comment]
> After ~weeks~ monthes (😅) of hesitation, it's been acted to use Stimulus format for the action / parameters :)
> 
> (cf the PR before your message)
> 
> So it should allow spaces, comas, accents, symbols etc.. easily :)

Thank you @smnandre :)

Unfortunately, I could not get this to work.

I replaced ...

```html
<button data-action="live#action" data-action-name="updateOrderBy(orderBy=matchCount)">
  ...
</button>
```

... with ...

```html
<button data-action="live#action" data-live-action-param="updateOrderBy" data-live-order-by-param="matchCount">
  ...
</button>
```

... but the action does not work anymore. I see the `live #action` log in my browser console, but no request is performed anymore.

Can you spot any mistake here?
