### ISSUE TITLE
Symfony UX React with .tsx file not working?

### ISSUE THREAD

**Issue by Wimble84** [symfony/ux#1285]
I'm currently trying "Symfony UX React" bundle on Symfony 6.3 and Webpack Encore bundle

The bundle create a default component named Hello in .jsx with this structure Hello.jsx and all work great.

Here is the default structure :
![rDxdQ](https://github.com/symfony/ux/assets/6002621/dd46f117-41c6-4036-9419-a6eaa29ad2fc)

But when I try to change Hello.jsx file extension to .tsx, component loading gives a console error on page loading (I don't get any Webpack compilation error)

![8aaxK](https://github.com/symfony/ux/assets/6002621/e4e1a929-97a1-49e3-9a13-f0f7b47f041d)

Here is the content of my webpack.config.json:
```js
const Encore = require('@symfony/webpack-encore');

// Manually configure the runtime environment if not already configured yet by the "encore" command.
// It's useful when you use tools that rely on webpack.config.js file.
if (!Encore.isRuntimeEnvironmentConfigured()) {
    Encore.configureRuntimeEnvironment(process.env.NODE_ENV || 'dev');
}

Encore
    // directory where compiled assets will be stored
    .setOutputPath('public/build/')
    // public path used by the web server to access the output path
    .setPublicPath('/build')
    // only needed for CDN's or subdirectory deploy
    //.setManifestKeyPrefix('build/')

    /*
     * ENTRY CONFIG
     *
     * Each entry will result in one JavaScript file (e.g. app.js)
     * and one CSS file (e.g. app.css) if your JavaScript imports CSS.
     */
    .addEntry('app', './assets/app.js')
    .addEntry('login', './assets/login.js')

    // When enabled, Webpack "splits" your files into smaller pieces for greater optimization.
    .splitEntryChunks()

    .enableReactPreset()

    // enables the Symfony UX Stimulus bridge (used in assets/bootstrap.js)
    .enableStimulusBridge('./assets/controllers.json')

    // will require an extra script tag for runtime.js
    // but, you probably want this, unless you're building a single-page app
    .enableSingleRuntimeChunk()

    /*
     * FEATURE CONFIG
     *
     * Enable & configure other features below. For a full
     * list of features, see:
     * https://symfony.com/doc/current/frontend.html#adding-more-features
     */
    .cleanupOutputBeforeBuild()
    .enableBuildNotifications()
    .enableSourceMaps(!Encore.isProduction())
    // enables hashed filenames (e.g. app.abc123.css)
    .enableVersioning(Encore.isProduction())

    // configure Babel
    // .configureBabel((config) => {
    //     config.plugins.push('@babel/a-babel-plugin');
    // })

    // enables and configure @babel/preset-env polyfills
    .configureBabelPresetEnv((config) => {
        config.useBuiltIns = 'usage';
        config.corejs = '3.23';
    })

    // enables Sass/SCSS support
    .enableSassLoader()

    // uncomment if you use TypeScript
    .enableTypeScriptLoader()

    // uncomment if you use React
    .enableReactPreset()

    // uncomment to get integrity="..." attributes on your script & link tags
    // requires WebpackEncoreBundle 1.4 or higher
    .enableIntegrityHashes(Encore.isProduction())

    // uncomment if you're having problems with a jQuery plugin
    //.autoProvidejQuery()
;

module.exports = Encore.getWebpackConfig();
```

My tsconfig.json

```json
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es6",
        "sourceMap": true,
        "jsx": "react"
    },
    "exclude": [
        "node_modules"
    ]
}
```

I tried to put different js files into ts or tsx but it not solve the error. Did I do somethong wrong ? Did I missed something ?

**Comment by smnandre** [comment]
The source code of UX React **_seems_** to handle `.jsx` and `.tsx` exaclty the same way.

Could you create a little reproducer ? I'm not sure where to search there i must admit :|

**Comment by Wimble84** [comment]
Sure !

I made this basic repo to reproduce the issue
[https://github.com/Wimble84/symfony-ux](https://github.com/Wimble84/symfony-ux)

**Comment by smnandre** [comment]
Arf... little thing :) You should put your tsconfig.json in the project root, no ? 

At least, it worked for me that way

**Comment by Wimble84** [comment]
You mean beside **webpack.config.js** ?

(like commit I just add)

Because I still get the console error

**Comment by smnandre** [comment]
Yes! The `yarn run build` then works for me (it does not compile when the config file is in the assets folder)



Then it seems that your problem is ... that your file is not a valid TSX file :)

**Comment by smnandre** [comment]
It may have been a small conflict with the "Hello" stimulus controller and your, to be sure i deleted the one in assets/controller


My template call: 



```twig

        <div {{ react_component('FooBar', {foo: 'bar'}) }}>
            Loading ...
        </div>

        <div {{ react_component('Hello', {fullName: 'Miss Moneypennie'}) }}>
            Loading ...
        </div>      
```

FooBar.jsx

```jsx
import React from 'react';

export default function (props) {
    return <div>Hello FooBar: {props.foo} !!</div>;
}
```

Hello.tsx

```tsx
import * as React from "react";

export default function ({fullName}: { fullName: string }) {
    return (
        <p>Hello, dear {fullName}</p>
    );
}
```

Result: 
<img width="1303" alt="Capture d’écran 2023-11-19 à 18 27 13" src="https://github.com/symfony/ux/assets/1359581/8c2c559a-c468-4b5a-b6d2-b96d7804708d">

**Comment by smnandre** [comment]
Hi @Wimble84 ! Did you find a way to solve your problem ?

**Comment by Wimble84** [comment]
Hi !

Sorry for my late answer but yes it solves my problem. Not when moving the tsconfig.json file in project root but when replacing 

```ts
import React from 'react';
```
by
```ts
import * as React from 'react';
```
