### ISSUE TITLE
[Svelte] onMount not fired?

### ISSUE THREAD

**Issue by jimbo2150** [symfony/ux#1291]
I have a controller that is being rendered by the onMount lifecycle event is not fired:

assets/svelte/controllers/Test.svelte:
```svelte
<script>
    import { onMount } from 'svelte';
        
    console.log('test');

    onMount(() => {
        console.log("mounted");
    });
</script>
```

I get 'test' in the console but never 'mounted'. Is this a bug or does something else need to be done to get it to work?

**Comment by ChqThomas** [comment]
Hi!

It's supposed to work out of the box, I tried to run your code with:

```twig
<div {{ svelte_component('Test') }} />
```

And I get both logs in the console

Which version of Svelte are you using?  ux-svelte is not (yet) compatible with Svelte 5 Alpha

**Comment by jimbo2150** [comment]
4.2.7

**Comment by jimbo2150** [comment]
I have "Test" and "Test mounted" as the messages, but only "Test" is coming through:

![Test-svelte-component](https://github.com/symfony/ux/assets/25777094/191c0109-b821-48a8-9a67-b2a963b807b0)

**Comment by ChqThomas** [comment]
Ok that's weird!

You can try to render your component directly with Svelte from a javascript file so that we can see whether the problem comes from Svelte or ux-svelte :

```js
import Test from "./svelte/controllers/Test.svelte";

new Test({
    target: document.getElementById('app'),
})
```

And if you want, you can create a repo that reproduces your issue and I'll take a look

**Comment by jimbo2150** [comment]
Mounting Svelte directly still doesn't work.

However, when I set up a barebones symfony app it works. They are both setup the same as far as outputting scripts  so it must be some conflict with some other package that is installed that is not required in the base install.

**Comment by jimbo2150** [comment]
I was able to fix the issue. I had code at the bottom of my `webpack.config.js` file to correct a warning about "svelte" not being in the `resolve.conditionNames`. Unfortunately it looks like adding that string causes the `onMount` event to stop functioning. Not sure why. Removing it fixes the issue.

```js
const webpackConfig = Encore.getWebpackConfig();

webpackConfig.resolve.conditionNames = (webpackConfig.resolve.conditionNames??[]);
if(webpackConfig.resolve.conditionNames.indexOf('svelte') < 0) {
	webpackConfig.resolve.conditionNames.push('svelte');
}

module.exports = webpackConfig;
```

**Comment by aniolekx** [comment]
not sure why this is closed, I have hit the same issue for the same reasons
