### ISSUE TITLE
[TwigComponent] Poorly formatted deprecation in toolbar

### ISSUE THREAD

**Issue by tacman** [symfony/ux#1296]
### Symfony version(s) affected

6.4-RC

### Description

I'm seeing a deprecation error in the toolbar that is poorly formatted

![image](https://github.com/symfony/symfony/assets/619585/02598b05-44b2-4144-af8d-7f4f29c1ac2a)

Even in the profiler page, it looks wrong:

![image](https://github.com/symfony/symfony/assets/619585/02ef84c0-3fce-4502-82a9-0c4c8dd29bee)

The actual error is in vendor/symfony/ux-twig-component/src/DataCollector/TwigComponentDataCollector.php
on line 93, which I imagine will get fixed soon, but a related question is why this deprecation is showing up as it is.

### How to reproduce

I can provide a repo if that helps, but at the moment I haven't been able to reproduce it with a simple repo.

(This issue was originally reported at https://github.com/symfony/symfony/issues/52757)

**Comment by smnandre** [comment]
As i said there, i'llfix tonight.

The weird thing is i cannot reproduce myself ...

**Comment by smnandre** [comment]
Could you share the TwigComponent profiler screen ? (in private if needed)

And the versions of  profiler and  twig-component you're on ?

**Comment by tacman** [comment]
![image](https://github.com/symfony/ux/assets/619585/cf4a35f4-6f8d-48ad-a257-31c7fd99f753)

profiler: 6.4-RC1
twig-component v2.13.1

**Comment by smnandre** [comment]
@tacman can you check this PR fixes things ? https://github.com/symfony/ux/pull/1297

**Comment by tacman** [comment]
I forget how to test another fork/branch!
```json
   "symfony/web-profiler-bundle": "dev-twig-component-profiler-int-float"

 "repositories": {
        "profiler":   {
            "type": "vcs",
            "url": "git@github.com:smnandre/ux.git"
        },
```

I get

composer update
Loading composer repositories with package information
Restricting packages listed in "symfony/symfony" to "^6.4"
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires symfony/web-profiler-bundle dev-twig-component-profiler-int-float, found symfony/web-profiler-bundle[2.0.7, ..., 2.8.x-dev, v3.0.0-BETA1, ..., 3.4.x-dev, v4.0.0-BETA1, ..., 4.4.x-dev, v5.0.0-BETA1, ..., 5.4.x-dev, v6.0.0-BETA1, ..., 6.4.x-dev, v7.0.0-BETA1, ..., 7.1.x-dev] but it does not match the constraint.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

even with minimum-stability set to dev.

**Comment by smnandre** [comment]
As UX is on a monorepo, it can be a bit trickier i guess

What i advice you is:

Let's say your app is in /home/your-app

### Create a directory outside your app's one
```
mkdir /home/ux-fix
```

### ChoiceA: If you use the github cli 

```
cd /home/ux-fix
gh repo clone symfony/ux
gh pr checkout 1297
```

### ChoiceB: or if you want to do it manually

Download the source code of the UX monorepo (of my PR)
--> https://github.com/smnandre/ux/archive/refs/heads/fix/twig-component-profiler-int-float.zip

### link the symfony UX packages to your vendors 
```
cd /home/ux-fix/ux
php link /home/your-app
```

### test if everything is OK 

### restore your vendors where they were

```
php link /home/your-app --rollback
```



Update: just to insist, it is not in the profiler component, but in the TwigComponent 

Every component has its own code related to the profiler

**Comment by tacman** [comment]
Thanks!  I wasn't familiar with the gh pr checkout command, so much easier than the approach I was trying.

Yep, that fix works: 

![image](https://github.com/symfony/ux/assets/619585/6a7c519b-65b7-490d-8dcc-4275ea89c802)
