### ISSUE TITLE
wierd recipe behavior, package.json modified after every composer update run

### ISSUE THREAD

**Issue by mmarton** [symfony/ux#130]
Hi!

I have aproject where I already had cropperjs as a dependency.
I added symfony/ux-cropperjs to the project and it added cropperjs as devdependency.
Ok, deleted it from dev and left it in normal dependencies.
But now after a composer update it keeps readding it. Like it works differently than the 'non ux' recipes.

How can I solve this? Do I really need to move cropper as a devdependency with the symfony enforced version?

**Comment by BigMichi1** [comment]
I see some similar behaviour every time I run `composer update` the versions in `package.json` are getting updated. for example, I have `"symfony/ux-chartjs": "1.3.0"` installed so in `package.json` there is the dependency written for `chart.js` which I upgraded to a newer version
```
"chart.js": "3.6.0",
```
after running the composer command it is changed to 
```
"chart.js": "^2.9.4",
```

would be nice if this change can somehow be avoided/suppressed

**Comment by benr77** [comment]
I'm experiencing a related issue. I have a standard Symfony type app, which outputs HTML via Twig templates. I then use Webpack Encore to build the client side assets.

What I find really useful to do, in in my `package.json` I put packages that are for _building_ the front-end in `devDependencies`, and then stuff that is used in the actual _execution_ of the front-end in `dependencies`. 

Now I realise technically for my kind of build this is irrelevant, as it all gets built by Webpack and outputted to the `build` directory anyway, presumably with whatever tree-shaking is needed to avoid getting the JS build tools in the final dist version.

However, I find it very useful to do this, as it distinguishes the two types of package.

Installing Symfony UX always adds stuff to the `devDependencies` section, whereas it is all runtime stuff, so personally I would much prefer that it targetted the main `dependencies` section instead.

Is there a good reason for adding to `devDependencies` ?

**Comment by weaverryan** [comment]
I've got this issue over here: https://github.com/symfony/flex/issues/843

> What I find really useful to do, in in my package.json I put packages that are for building the front-end in devDependencies, and then stuff that is used in the actual execution of the front-end in dependencies.

I agree. That is actually why the packages are added to `devDependencies`. If you install something like ux-chartjs, its npm package is added to `devDependencies`. That may seem incorrect at first, but that dependency only needs to be present during *build*. Encore uses it - at *build* time - to create the final, built CSS and JS files. That package does NOT need to be present at runtime. So, I think your philosophy is correct and the packages are already following it.
