### ISSUE TITLE
[TwigComponent] Configuration with PHP ConfigBuilders fails

### ISSUE THREAD

**Issue by rarila** [symfony/ux#1304]
I use configuration with PHP ConfigBuilders and tried to add configuration for symfony/ux. That failed, ``TwigComponentConfig`` could not be loaded.

So I was digging around (not knowing anything about it), comparing how others do it and finally found a working solution:

I created

``ux/src/TwigComponent/src/DependencyInjection/Configuration.php``

with content like this

```
class Configuration implements ConfigurationInterface
{
}
```

and then moved the [``getConfigTreeBuilder()``](https://github.com/symfony/ux/blob/1f326f06e36a52c2df42d176e388f1378019d484/src/TwigComponent/src/DependencyInjection/TwigComponentExtension.php#L132-L190) method from

``ux/src/TwigComponent/src/DependencyInjection/TwigComponentExtension.php``

into that class.

I don’t know if this the correct way, if that would break anything else, but at least now ``TwigComponentConfig`` gets built and configuration works.

**Comment by smnandre** [comment]
Normally, the TwigComponentConfig class is generated in your var/cache/dev/Symfony/Config directory... is that not the case ?

**Comment by rarila** [comment]
@smnandre It is. But clearing the cache crashes.

Just to be safe that not something else in my app is wrong, I just set up a clean v6.3 skeleton+webapp project and added ux-twig-component.

Then I replaced ``twig_component.yaml`` with ``twig_component.php``

```
<?php

use Symfony\Config\TwigComponentConfig;

return static function (TwigComponentConfig $cnf): void {
};
```

Then I ran ``php bin/console cache:clear`` and ended up with:

> [critical] Uncaught Error: Symfony\Component\Config\Builder\ConfigBuilderGenerator::build(): Argument #1 ($configuration) must be of type Symfony\Component\Config\Definition\ConfigurationInterface, null given, called in /foo/bar/vendor/symfony/dependency-injection/Loader/PhpFileLoader.php on line 195

**Comment by smnandre** [comment]
Ok i see the problem and reproduced, thanks for the details :)

I'd like to have @weaverryan and @kbond inputs..  because we could either add a Configuration class as you suggested, or keep a single Extension class and move things a bit to implement ConfigurableExtension, but i'm not sure what is the best way forward ? 

(i personnaly like the separated Configuration classes)

**Comment by smnandre** [comment]
In the Extension, we just have to add this method and everything seems to work 

```php
// src/DependencyInjection/TwigComponentExtension.php

final class TwigComponentExtension extends Extension implements ConfigurationInterface
{

// ...

public function getConfiguration(array $config, ContainerBuilder $container): ConfigurationInterface
    {
        return $this;
    }

```

Can you confirm it works for you @rarila ?

**Comment by rarila** [comment]
@smnandre   **Works!** 👍 

_Looks like I’m the only one using ConfigBuilders_ 😄

**Comment by smnandre** [comment]
@rarila do you use other UX Packages ? 👼 

You may be the only one... but you are a great beta-tester :)
