### ISSUE TITLE
[TwigComponent] Check if component exist

### ISSUE THREAD

**Issue by alinceDev** [symfony/ux#1305]
Hi,

Just a question, I can't find a way to check if a component exist, when we have a dynamic name. I want to render another twig if the component is not implemented.
How can I handle that ?

Tanks

**Comment by smnandre** [comment]
To be sure to understand, could you give an example of what you would like to do, and how ?

**Comment by alinceDev** [comment]
With this code :
```php
#[AsTwigComponent('my_widget', template: '@MyBundle/components')]
class MyWidget
{
    public string $message;
}
```
And in a twig template or twigExtension, I want to check if component `my_widget` exist.
Something like this :

```php
// my_twig_file.html.twig

{% if component_exist('my_widget') %}
    {{ component('my_widget') }}
{% else %
// ugly code here
    {{ render_widget('my_widget');
{% endif %}
```
You have to consider here my_widget as a dynamic widget name.
There is already some widgets implemented with ugly code and I want to move to twigCompoents for the new widgets.

Thanks

**Comment by smnandre** [comment]
There is no direct way to test if a component exists currently.

I don't know how are organized your classes / templates, but you may want to inverse the logic (as you already have a `render_widget`, maybe you can do a `widget_exist` ?)

You could also, as a temporary solution, do something like this

`{% if source('your_template.html.twig', true) %}`

As the [source function](https://twig.symfony.com/doc/3.x/functions/source.html) will return either the raw content of the template or null if the template does not exists.... 
But i would not recommand it for anything else than a temporary quick fix on small set of calls (and even... i would not _recommand_ it)

**Comment by alinceDev** [comment]
Ok I think I will go with an enum list of new widget with twig component
