### ISSUE TITLE
[TwigComponent] Feature request: boolean attributes in html syntax

### ISSUE THREAD

**Issue by DemonTPx** [symfony/ux#1310]
I've got a Button component with some boolean properties. Let's say I have `public bool $set = false` added to it. To set that to `true` I have to use one of these methods in the html syntax:

```
<twig:Button set="1" />
<twig:Button :set="true" />
```

I would expect to also be able to do this:

```
<twig:Button set />
```

Would that even be possible? :)

**Comment by smnandre** [comment]
I just tried and... it works already :)

```php
<?php
// ... 

#[AsTwigComponent]
final class FooBar
{
    public bool $set = false;

    public bool $isFoo = false;

    public bool $withBar = false;

    public bool $bazzed = false;
}
```

```twig
{# in base.html.twig #}
       <twig:FooBar
            set=""
            enabled
            isFoo="0"
            withBar
            bazzed
       />
 ```
 
 ```php
 // dump() inside Foobar.html.twig
   "set" => false
  "isFoo" => false
  "withBar" => true
  "bazzed" => true
  ```
  
Is there something more you'd want ? Or maybe something is not working as expected ?

**Comment by lyrixx** [comment]
I does not work with anonymous component

**Comment by smnandre** [comment]
This issue was explicitely about class-based component, but let's ignore that :) 

The same test with an anonymous component 

```twig
<twig:FooBar
      set=""
      enabled
      isFoo="0"
      withBar
      bazzed
 />
```
when dumped from inside the component, renders like this... 

```html

  "set" => ""
  "enabled" => true
  "isFoo" => "0"
  "withBar" => true
  "bazzed" => true
  
  ```
  
I'm not sure to see where is the problem, or i may have missunderstood something (more than possible) ?

**Comment by norkunas** [comment]
>   "set" => ""
  "enabled" => true
  "isFoo" => "0"
  "withBar" => true
  "bazzed" => true

so `isFoo` should be `false` isn't it? :)

**Comment by smnandre** [comment]
Why ? If you pass `"0"` to an anonymous component.. why should it be casted to `false` ?

**Comment by norkunas** [comment]
> Why ? If you pass `"0"` to an anonymous component.. why should it be casted to `false` ? 

Oops,misread

**Comment by WebMamba** [comment]
Maybe we need to add a better way to cast `props` in a anonymous component:
`{% props label = 'Click' as 'string'` ? WDYT?

**Comment by DemonTPx** [comment]
Yes, it seems to work! I have no idea why it didn't seem work for me before, so sorry for the confusion...

**Comment by WebMamba** [comment]
@DemonTPx can be closed then?
