### ISSUE TITLE
[LiveComponent] Feature Request: Make #[LiveListener] repeatable

### ISSUE THREAD

**Issue by barbieswimcrew** [symfony/ux#1323]
Hey folks! Wouldn't it make sense to make the #[LiveListener] attribute repeatable? Let's say there is a method that needs to listen to different events. Would be great if I'd do like so:

```php
#[LiveListener(eventName: 'rocket:launched')]
#[LiveListener(eventName: 'rocket:landed')]
public function foo(){
    // do something...
}
```

What do you think? 😃

**Comment by smnandre** [comment]
@barbieswimcrew you can try with the PR #1343 if you want :-)

**Comment by barbieswimcrew** [comment]
@smnandre that is gorgeous! really looking forward to this being merged :-)

**Comment by smnandre** [comment]
It's merged @barbieswimcrew :)
