### ISSUE TITLE
How to render a component from PHP code?

### ISSUE THREAD

**Issue by mahono** [symfony/ux#1348]
Hi!

Is there a way to render a component from PHP code?

I have some pages that just render a single component. In these cases I render a Twig template that just contains the call to render the component.

To be honest I would love to be able to call:

    return $this->renderComponent('MyComponent');

inside a controller.

But.. until then, is there an easy way to render a component from PHP, so that I can at least save the "useless" template?

**Comment by smnandre** [comment]
Absolutely ! 

If you have a `Foo:Bar` component, in your controller (or any service), you can inject and use the ComponentRenderer like this : 

```php
public function yourAction(ComponentRendererInterface $componentRenderer): Response
{
   $html = $componentRenderer->createAndRender('Foo:Bar', ['your' => 'args']);       
    // ...
}
```

Naturally, that can only work with component with no inner blocks

**Comment by mahono** [comment]
Cool! Thanks. 👍
