### ISSUE TITLE
[TURBO] UX Turbo does not re-render form on error

### ISSUE THREAD

**Issue by ghost** [symfony/ux#1349]
I'm adding an error to the form using `$form->addError(new FormError('message'))` but is not shown,

Yesterday everything was working, but today I changed the code a bit and the form stopped displaying errors. I tried to return everything to the state before the change but it didn't help. First of all, I noticed that even after adding an error with the addError(), the server returns the code 200 instead of 422 (yesterday it returned 422). As far as I understand, for UX Turbo to re-render the form, it needs to get code 422. I tried returning the response with code 422 manually (`$this->render('template', [$data], new Response(null, 422)`), but the error was still not shown.

```php
// Controller

#[Route('/', name: 'app_index')]
public function index(Request $request): Response
{
    $authForm = $this->createForm(AuthType::class);

    $authForm->handleRequest($request);

    $disclaimer = $this->renderView('index/disclaimer.html.twig');
    if ($authForm->isSubmitted() && $authForm->isValid()) {

        // removed logic for testing
        $authForm->addError(new FormError('ERR'));

        if (TurboBundle::STREAM_FORMAT == $request->getPreferredFormat()) {
            $request->setRequestFormat(TurboBundle::STREAM_FORMAT);
            return $this->render('index/main_block_contents.stream.html.twig', [ 'contents' => $disclaimer]);
        }
    }

    return $this->render('index/base.html.twig', [
        'authForm' => $authForm,
        'contents' => $disclaimer
    ]);
}
```

![image](https://github.com/symfony/ux/assets/140304335/325ddae8-ae7e-456c-a489-31aa862490ff)

![image](https://github.com/symfony/ux/assets/140304335/c8cefb97-c211-4d8e-8c1e-7f75417731bd)

Form has no errors

Symfony 6.4.*
@hotwired/turbo 7.3.0

**Comment by smnandre** [comment]
The render method can only set the HTTP 422 if you pass the form in the render() arguments. 

You should try 

```php
if (TurboBundle::STREAM_FORMAT == $request->getPreferredFormat()) {
    $request->setRequestFormat(TurboBundle::STREAM_FORMAT);
     return $this->render('index/main_block_contents.stream.html.twig', [ 'contents' => $disclaimer, 'form' => $authForm]);
}
```

**Comment by ghost** [comment]
@smnandre tried it, now it returns 422, but does not re-render the form with the error. According to [Symfony Docs](https://symfony.com/bundles/ux-turbo/current/index.html#3-form-response-code-changes): 

> This changes the response status code to 422 on validation error, which tells Turbo Drive that the form submit failed and it should re-render with the errors.

**Comment by smnandre** [comment]
Hey @sherwomeister could you create a small reproducer ? I’ll look at it after christmas

**Comment by ghost** [comment]
@smnandre, srry, by reproducer you mean just paste Controller's code here or create a repo with full project ? I don’t often ask questions on Github so I don’t know how it’s done.

**Comment by smnandre** [comment]
Yes sorry i should have be more precise: a minimal repo that anyone can install and use to check the issue with minimal time.

There is some documentation about how to create a reproducer on the symfony website if you want: https://symfony.com/doc/current/contributing/code/reproducer.html

By doing so, you gave your issue a lot more chance to be looked upon. 

I made one quick recently (well, i did not reproduce the bug there, but that would be the format if the page did not redirect correctly): https://github.com/smnandre/repro-live-redirection/

For your problem i guess creating a minimal reproducer would start with

```
symfony new --webapp repro-turb-form 
```

And iterate from there with the minimal amount of code to create the bug

(as Turbo should be installed and configured with the webapp standard install)

**Comment by sherwomeister** [comment]
[Reproducer](https://github.com/sherwomeister/repro-turbo-form/)

**Comment by ghost** [comment]
[Reproducer](https://github.com/sherwomeister/repro-turbo-form/)

**Comment by smnandre** [comment]
Ok i get now where the trouble is. As you add the error manually inside the condition

```
 if ($authForm->isSubmitted() && $authForm->isValid()) {

            $content = "Replaced!";
            $authForm->addError(new FormError('ERR'));

            if (TurboBundle::STREAM_FORMAT == $request->getPreferredFormat()) {
                $request->setRequestFormat(TurboBundle::STREAM_FORMAT);
                return $this->render('index/index.stream.html.twig',
                    [
                        'content' => $content,
                        'form' => $authForm
                    ]);
            }

        }
```
        
You always render "index.stream.html" there... and there is no mention of the form in it.

Try adding the error before this condition, and you'll see it works (re-renders the form with the added error).

**Comment by ghost** [comment]
But how to show an error after form submission? For example, after failed login?

**Comment by ghost** [comment]
What is the point of adding error before the condition? Isn't the whole point to add an error after form submission?

> and you'll see it works (re-renders the form with the added error).

I think it just shows the error that was already renderd

**Comment by smnandre** [comment]
If i understand correctly, what you want is : "if there is an error, render the form again"

What your code is doing is "if the form is submitted, add an error but do not render the form"

If you want to render the form again you must no render your result stream, so you can add a second condition

```diff
if ($authForm->isSubmitted() && $authForm->isValid()) {

            $content = "Replaced!";
            $authForm->addError(new FormError('ERR'));

-            if (TurboBundle::STREAM_FORMAT == $request->getPreferredFormat()) {
+            if ($authForm->isValid() && TurboBundle::STREAM_FORMAT == $request->getPreferredFormat()) {
                $request->setRequestFormat(TurboBundle::STREAM_FORMAT);
                return $this->render('index/index.stream.html.twig',
                    [
                        'content' => $content,
                        'form' => $authForm
                    ]);
            }

        }
   ```

**Comment by smnandre** [comment]
In your case as you add the error unconditionnaly, that's not easy to see the differences.. 

You may try adding the formError only when a condition is met

**Comment by ghost** [comment]
> If i understand correctly, what you want is : "if there is an error, render the form again"
> 
> What your code is doing is "if the form is submitted, add an error but do not render the form"
> 
> If you want to render the form again you must no render your result stream, so you can add a second condition
> 
> ```diff
> if ($authForm->isSubmitted() && $authForm->isValid()) {
> 
>             $content = "Replaced!";
>             $authForm->addError(new FormError('ERR'));
> 
> -            if (TurboBundle::STREAM_FORMAT == $request->getPreferredFormat()) {
> +            if ($authForm->isValid() && TurboBundle::STREAM_FORMAT == $request->getPreferredFormat()) {
>                 $request->setRequestFormat(TurboBundle::STREAM_FORMAT);
>                 return $this->render('index/index.stream.html.twig',
>                     [
>                         'content' => $content,
>                         'form' => $authForm
>                     ]);
>             }
> 
>         }
> ```

I think your example just avoids using Turbo on form error, it just reloads the page. Documentation clearly states that Turbo will re-render form with errors, if 422 code is returned.

[Symfony Docs:](https://symfony.com/bundles/ux-turbo/current/index.html#3-form-response-code-changes)
> Turbo Drive also converts form submissions to AJAX calls. To get it to work, you do need to adjust your code to return a 422 status code on a validation error (instead of a 200). 

[Symfony Docs](https://symfony.com/bundles/ux-turbo/current/index.html#3-form-response-code-changes)
> This changes the response status code to 422 on validation error, which tells Turbo Drive that the form submit failed and it should re-render with the errors. 

[Turbo Drive documentation](https://turbo.hotwired.dev/handbook/drive#redirecting-after-a-form-submission)
>  This allows form validation errors to be rendered by having the server respond with `422 Unprocessable Entity`

**Comment by ghost** [comment]
> In your case as you add the error unconditionnaly, that's not easy to see the differences..
> 
> You may try adding the formError only when a condition is met

Originally, I was adding an error when a condition was met, and it was not rendered

**Comment by smnandre** [comment]
I don't understand what is not working as you expect, i'm sorry.

With your reproducer, Symfony returns a 422 as stated in the numerous pages of the documentation you provided..

https://github.com/symfony/ux/assets/1359581/64fabadd-16c5-4720-9c5e-b90ca09f85bf

**Comment by ghost** [comment]
Sorry, maybe I'm asking stupid questions or I don't fully understand how it works, but that's the behavior I am expecting:
1. User submits the form
2. The form is processed
3. If there is an error during form processing, add an error to the form
4. render() function sees the error and returns HTTP 422
5. Turbo drive sees 422 response and re-renders form with errors without reloading the page

Maybe it's a false expectation, but it's an expectation I got after reading the documentation.

**Comment by smnandre** [comment]
I'm trying to explain. 

As you add your error in the bloc starting with `if ($authForm->isSubmitted()` and don't test after.... you always return a TurboStream containing only the content. 

You wrote what you're expecting, but what you're doing in your code is a bit different: 

1. User submits the form
2. The form is processed
3A. If there is NO error -> add an error ->  ALWAYS send a stream / replace the frame with content 

How would the errors be injected in your code ? How could it know wich template you uses, wich CSS classes, etc ? If you do not render the form, the form is not rendered. 

The examples you saw all works in the following way

1. User submits the form
2. The form is processed
3A. If there is NO error -> send a stream / replace the frame with new content
3B. If there is an error -> render again (that's where the Turbo magic will do its work) with the form and the initial template

**Comment by ghost** [comment]
Got it, thank you for your time
