### ISSUE TITLE
[LiveComponent] make AsLiveComponent non-final

### ISSUE THREAD

**Issue by jannes-io** [symfony/ux#1351]
Request to remove final from class declaration.

Use-case:
Re-usable components that all use the same template, but have a different name.

Example
```php
abstract class Table
{
    // declare re-usable live props/actions/...
}
```

As-Is:
```php
#[AsLiveComponent('UserTable', 'components/table.html.twig')]
class UserTable extends Table
{
    // specific functions for this table
}
```

Desired:
```php
#[AsTable('UserTable')]
class UserTable extends Table
{
    // specific functions for this table
}

#[\Attribute(\Attribute::TARGET_CLASS)]
class AsTable extends AsLiveComponent
{
    public function __construct(
        string $name = null,
        string $template = 'components/table.html.twig',
    ) {
        parent::__construct($name, $template);
    }
```

https://github.com/symfony/ux-live-component/blob/d0897b7dea722ef9253bd9c07410d6fb80dd4f0a/src/Attribute/AsLiveComponent.php#L22

Are there any consequences to this? What is the reason for AsLiveComponent to be marked final?

**Comment by kbond** [comment]
> Are there any consequences to this? What is the reason for AsLiveComponent to be marked final?

I believe this has been answered in https://github.com/symfony/ux/pull/1352#issuecomment-1867823527 (at least until when/if `registerAttributeForAutoconfiguration()` supports attribute children).

**Comment by jannes-io** [comment]
> > Are there any consequences to this? What is the reason for AsLiveComponent to be marked final?
> 
> I believe this has been answered in [#1352 (comment)](https://github.com/symfony/ux/pull/1352#issuecomment-1867823527) (at least until when/if `registerAttributeForAutoconfiguration()` supports attribute children).

Yes, I've closed the PR, this should be the resolution:
> Ok gents, thanks for the quick responses! I’ll go a different route and register the custom attribute for auto wiring in my bundle the same way live component is auto registered. I thought perhaps because `AsLiveComponent` extends `AsTwigComponent` that this was the way to go but it’s not a big deal to register it manually.

Even though, rightfully so seeing how a lot of UX is still experimental, @smnandre recommended against it. I have a working version now which makes the API for users of my bundle a lot less complex, so I'm satisfied.
