### ISSUE TITLE
[StimulusBundle] Deprecation after "symfony new --webapp"

### ISSUE THREAD

**Issue by smnandre** [symfony/ux#1366]
When you do a fresh install ( `symfony new --webapp` ), the StimulusBundle is installed, and i guesss its recipes add the 

```twig
        {% block stylesheets %}
            {{ ux_controller_link_tags() }}
        {% endblock %}
```        

But that triggers a deprecation.

>  User Deprecated: Since symfony/ux-stimulus-bundle 2.13.0: Calling ux_controller_link_tags() is deprecated and does nothing with symfony/asset-mapper 6.4. The link tags are rendered automatically via the importmap() function. 

Is there something to do, or we "just" have to update the recipes and wait the next StimulusBundle release ? 

(cc @weaverryan )

**Comment by maxhelias** [comment]
I think updating recipes for 2.13.0 should be sufficient. No need to wait a next release

**Comment by smnandre** [comment]
Oops.. there was already one ready 😅 

https://github.com/symfony/recipes/pull/1262

**Comment by fabpot** [comment]
https://github.com/symfony/recipes/pull/1262 merged now

**Comment by smnandre** [comment]
Thank you @fabpot
