### ISSUE TITLE
[Stimulus] Update hotwired/stimulus to v3.0.0-beta.2

### ISSUE THREAD

**Issue by seb-jean** [symfony/ux#137]
Hi,
Stimulus is in version v3.0.0-beta.2. It would be great to have to update it in symfony/ux 😄.
https://github.com/hotwired/stimulus/releases/tag/v3.0.0-beta.2
Thanks :)

**Comment by nicolas-grekas** [comment]
Please send a PR then ;)

**Comment by weaverryan** [comment]
Thanks for the issue. This is actually not going to be so simple. Here is beta 1: https://github.com/hotwired/stimulus/releases/tag/v3.0.0-beta.1

I believe the only big thing is the package name change, which is significant - to ` @hotwired/stimulus`.

However, beta 2 is a bit more concerning, specifically this: https://github.com/hotwired/stimulus/pull/444 - that removes the Webpack support. We could include that in our package - but we should check to see what other approach Rails is doing to see if that's where we should go.

**Comment by seb-jean** [comment]
Stimulus 3 is release today! : https://world.hey.com/hotwired/stimulus-3-c438d432

https://github.com/hotwired/stimulus/pull/302

**Comment by fbourigault** [comment]
> However, beta 2 is a bit more concerning, specifically this: hotwired/stimulus#444 - that removes the Webpack support.

Webpack support seems to been released in a separate package: https://github.com/hotwired/stimulus-webpack-helpers.

> see what other approach Rails is doing to see if that's where we should go.

Rails 7 will default to import-maps (see https://world.hey.com/dhh/rails-7-will-have-three-great-answers-to-javascript-in-2021-8d68191b)

**Comment by weaverryan** [comment]
> Webpack support seems to been released in a separate package: https://github.com/hotwired/stimulus-webpack-helpers.

Yup - I had missed this originally. So the quick path that we should take is to use that new package from inside of stimulus-bridge: https://github.com/symfony/stimulus-bridge. Unless we're able to work some magic (which I'm not sure is possible), this will likely cause us to need to trigger a new major release in that package.
