### ISSUE TITLE
[UX] 503 error with opcache JIT enabled

### ISSUE THREAD

**Issue by tristan-lg** [symfony/ux#1386]
### Symfony version(s) affected
6.4.2

### Description
Using symfony UX on symfony 6.4.*, with opcache JIT enabled may case 503 errors.
I had no problem in 6.3.*

### How to reproduce
Configure opcache and set `opcache.jit=1235`
Create a form type with ux live component with at least one field.
Configure APP_ENV=prod
Refresh the page multiple times, until 503 error.
Then, all refresh of pages using Symfony UX components will cause 503 error.

### Possible Solution

Change opcache JIT configuration trigger to 5.
For example : `opcache.jit=1255`

I don't know if it is symfony-ux related, but i wanted to share the error with a solution.

Hope it will help.

**Comment by weaverryan** [comment]
Hey! 

Thanks for the report. But I can't think of how this could be related to Symfony UX, at least not without more info - like some sort of error log. If you can get that, it would make this actionable.

Cheers!

**Comment by smnandre** [comment]
Hi @tristan-lg !

Could you create a minimal reproducer so we can investigate ?
Or if you cant, share your PHP / opcache settings ? 

Does this happen with every UX packages or specifically with Twig/Live Components, Autocomplete, etc ?

**Comment by tristan-lg** [comment]
Here is the opcache settings that cause the issue (due to `opcache.jit` config) : 
```ini
opcache.enable=1
opcache.enable_cli=1
opcache.interned_strings_buffer=8
opcache.max_accelerated_files=20000
opcache.memory_consumption=256
opcache.validate_timestamps=0
opcache.revalidate_freq=0
opcache.preload_user=1010
opcache.preload=/var/www/html/config/preload.php

opcache.jit=1235
opcache.jit_buffer_size=500000000

realpath_cache_size = 4096K
realpath_cache_ttl = 600
```

Sorry, i don't have a reproducer.

I only tested it with live component, using a form inside live component.
I don't know if it is only related to symfony ux, maybe with a lot of pages i will have the same result.

EDIT : 
When i reduce the buffer size (/10), i no longer have the issue.
```ini
opcache.jit=1235
opcache.jit_buffer_size=50000000
```

**Comment by lyrixx** [comment]
Without a reproducer, we won't be able to do anything... sorry!

**Comment by tristan-lg** [comment]
I understand, i will close the issue.
Maybe it will help someone encoutering the same problem/
