### ISSUE TITLE
[TwigComponent] props reflexion

### ISSUE THREAD

**Issue by WebMamba** [symfony/ux#1387]
Hey! I want your though before to start working on something.
Today if you have a TwigComponent 
```php
#[AsTwigComponent]
class Button
{
...
}
```
```twig
{% props label %}

<button>
{{  label }}
</button>
```

The props label defined in the template will not be taken in to account because the Button component is not an anonymous component.
What do you think about letting the ability to merge props defined into the template with props defined in the class.
If a conflict happen raise an error.
WDYT?

**Comment by smnandre** [comment]
What would be the "rules" ?

**Comment by WebMamba** [comment]
If you have:

```php
#[AsTwigComponent]
class UserCard
{
      public string $user = null;
      
     public string $language = 'fr';
}
```

```twig
    {% props size = 'md' %}
  
    // content here

  //Then you can access {{  size }} {{  language }} {{ user }}
```

Do you see what I mean?

**Comment by weaverryan** [comment]
I thought it already worked this way? I thought that, even if your component is NOT anonymous, if you have `{% props %}`, it would covert anything listed there from an attribute into a prop. Are you sure that's not already the case? Or tell me if I'm misunderstanding the issue also :)

**Comment by WebMamba** [comment]
This is not the case, and you actually had this issue during your live coding at the SymfonyCon 😁

**Comment by smnandre** [comment]
In your example can you mount your component with size ? I imagine yes ? 

`<twig:UserCard size="foo" />  `

right ? 

How would you handle it PHP-side in your mount methods ? DOes it appear in the component Metadata ? In the Events then ? 
How would it work with LiveComponents ?

Maybe those answers are really simple... but if "not", i fear this add much complexity to a limited gain. I mean, declaring properties in two different places in not the most frequent thing we see right ? 

Do you have maybe a full example where that addition feel like a immediate DX improvment ? 

(side note: I still think we should have a more distinct usage / interface between pure static components and php ones :))

**Comment by smnandre** [comment]
Wait.... @weaverryan is right :) 


I just added the "foo" as props in the template

<img width="759" alt="Capture d’écran 2024-01-11 à 22 51 24" src="https://github.com/symfony/ux/assets/1359581/bd830c22-6d94-436a-a765-7d6d95ba3135">


<img width="894" alt="Capture d’écran 2024-01-11 à 22 51 35" src="https://github.com/symfony/ux/assets/1359581/7174532a-5d72-48e9-8382-e125dc07ca5b">

**Comment by smnandre** [comment]
Is there something i missed there guys ? @weaverryan  @WebMamba
