### ISSUE TITLE
Documentation could be improved by being clear about incompatibility with AssetMapper

### ISSUE THREAD

**Issue by vcopleutre** [symfony/ux#1391]
Hi, 

On a fresh install (Symfony 6 and 7) after following the doc for installing symfony/ux-react (with webpack-encore-bundle). I get this when running `yarn watch` (or `npm run watch`)

`Module build failed: Module not found:
"./assets/app.js" contains a reference to the file "@symfony/ux-react".`
(same for stimulus-bundle)

The reason is that it's not compatible with asset-mapper.

I found the solution here : https://stackoverflow.com/a/77720816/5251749

I think it would be great to write in the doc that symfony ux components are not compatible with asset-mapper (installed by default for webapp).

Thank you 😃

**Comment by smnandre** [comment]
I’m not sure to understand « what » is not compatible with AssetMapper, but there is no « yarn watch » with AssetMapper. 

And AssetMapper is the default asset component now. 

Maybe what you mean is that WebPack doc should mention it does not work with AssetMapper ?

**Comment by vcopleutre** [comment]
Hi @smnandre ,

Thank you for your answer. Well you are right, what I mean is that WebPack does not work with AssetMapper and so when using npm install to download symfony ux components (after composer require), only webpack was downloaded in node_modules.

It's just that I struggled on this problem and couldn't find any solution on the web, so I think it could help some people to raise this issue.

Thanks

**Comment by weaverryan** [comment]
Hi!

We have this at the top of the ux-react docs: 

> This package works best with WebpackEncore. To use it with AssetMapper, see [Using with AssetMapper](https://symfony.com/bundles/ux-react/current/index.html#using-with-asset-mapper).

Maybe the warning isn't obvious enough?

**Comment by smnandre** [comment]
I believe the problem is that AssetMapper "take the lead" when both are installed... and there is where we may improve the DX

**Comment by vcopleutre** [comment]
> Maybe the warning isn't obvious enough?

It wasn't for me but It may be enough. I agree with your previous comment.

**Comment by weaverryan** [comment]
I'm going to close for now. We can see if anyone else has issues. And if so, think about some changes then.

Thanks!
