### ISSUE TITLE
[Twig] avoid need for `{{ }}` around spread operator when using html-syntax

### ISSUE THREAD

**Issue by kbond** [symfony/ux#1407]
Instead of:

```html
<!-- current -->
<twig:Alert {{ ...myAttributes }} />

<!-- new -->
<twig:Alert ...myAttributes />
```

@smnandre thinks it's possible.

**Comment by smnandre** [comment]
I mean... yeah it is possible 😅 

<img width="277" alt="Capture d’écran 2024-01-19 à 00 03 34" src="https://github.com/symfony/ux/assets/1359581/1dcc8e59-87fd-4762-bd8c-e6a301890747">
<img width="445" alt="Capture d’écran 2024-01-19 à 00 03 38" src="https://github.com/symfony/ux/assets/1359581/a6e9a30d-4698-4c7c-bf30-737722354c85">

**Comment by smnandre** [comment]
We have this code in the PreLexer

```php
            if ($this->check('{{...') || $this->check('{{ ...')) {
                $this->consume('{{...');
                $this->consume('{{ ...');
                $attributes[] = '...'.trim($this->consumeUntil('}}'));
                $this->consume('}}');

                continue;
            }
```


Just added a second case 

```php

            if ($this->check('...')) {
                $this->consume('...');
                $attributes[] = '...'.trim($this->consumeUntil(' '));
                $this->consume(' ');

                continue;
            }
```


Of course, this will need a lot of tests / edge cases / ... 

But we know it's here :)

**Comment by norkunas** [comment]
Imho less readable and not so "twig" :) thats why I've implemented like this and everybody agreed at that time

**Comment by kbond** [comment]
Forgot about that discussion 😁. Ok, let's leave as is.
