### ISSUE TITLE
[LiveComponent] Deferring loading components and the paradox of twig component exposeInTemplate eager loading

### ISSUE THREAD

**Issue by fGuix** [symfony/ux#1424]
Hello,
I'm using live components in multiple projects and I'm facing an issue that I don't really understand and that is IMO contradictory in the behavior (and the documentation) of twig/live components.

### The problem : **having (not using !)** heavy exposeInTemplates methods in live-components.
I have a component (list of products) that have multiple methods exposed and some of them are really heavy on call. The thing is, they are not necessarily called during my component rendering because of some condition on render (sometimes the filters are render, other times not). But as the [documentation](https://symfony.com/bundles/ux-twig-component/current/index.html#exposeintemplate-attribute) of twig component mentioned, the exposed methods are eagerly fetched resulting on them being called during initialization **and** render.

I see multiple issues related to that : 
1. The exposed methods are always called at least once during component initialization, even if not called in render.
-> Is it possible to avoid that initialization call ?
2. The exposed methods are called x number of time during render (depending on the number of call in template). Using "computed.myMethod" does not change the behavior of being called at least twice (init + render).
3. I tried to defer the render of my component with the [defer option](https://symfony.com/bundles/ux-live-component/current/index.html#deferring-lazy-loading-components), but it's irrelevant because of the methods being called during initialization, even if I dont call it on render. I mention this because it is written:
> Behind the scenes, your component is created & mounted during the initial page load, but it isn't rendered. **So keep your heavy work to methods in your component (e.g. getProducts()) that are only called when rendering**.

which is IMO contradictory to the eager fetch.

For now I set up a workaround to avoid calling the heavy processes by checking a condition inside my component. But is that not a major issue to execute exposed code that might not be used in template ? Did I miss something big ?

Side-note: I could not use the "loading-template" option while deferring the component loading, also the documentation have some syntax error (after "Or override the loadingContent block:"), is it still WIP ?

**Comment by smnandre** [comment]
Do you need to expose them ? 

Any public method is accessible from the template if you need them, without this attribute (that indeed pre-compute the resultes to expose it in the context)

See the Alert component for exemple: https://ux.symfony.com/twig-component

**Comment by smnandre** [comment]
Concerning the syntax error, could you suggest a correction ? (You can open a PR directly from the documentation page (top of the page just under the title)

**Comment by fGuix** [comment]
> Do you need to expose them ?
> 
> Any public method is accessible from the template if you need them, without this attribute (that indeed pre-compute the resultes to expose it in the context)
> 
> See the Alert component for exemple: https://ux.symfony.com/twig-component

ok. so that's what I didn't get. thanks for the precision.

> Concerning the syntax error, could you suggest a correction ? (You can open a PR directly from the documentation page (top of the page just under the title)

Sorry but I couldn't figure how to set it up.

**Comment by smnandre** [comment]
> ok. so that's what I didn't get. thanks for the precision.

Happy to help :) 

> Sorry but I couldn't figure how to set it up.

I just created a PR to fix it, thank you!
