### ISSUE TITLE
[LiveComponent] Broken forms after #1218

### ISSUE THREAD

**Issue by akyoscommunication** [symfony/ux#1452]
Using form in LiveComponent throws Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException after https://github.com/symfony/ux/pull/1218

Throws error at LiveComponentSubscriber line 108:

if (!$request->isMethod('post')) {
      throw new MethodNotAllowedHttpException(['POST']);
}

No change in code since last composer update, forms worked perfectly before. Didn't found yet why each form field change is sent using GET and not POST.

![Capture d’écran 2024-02-02 à 14 43 16](https://github.com/symfony/ux/assets/50996280/f44ebdce-de47-4541-a2e2-3040e6c2ec9a)

![Capture d’écran 2024-02-02 à 14 44 38](https://github.com/symfony/ux/assets/50996280/0a2de247-3ddb-4696-82a3-84af666cfb67)

**Comment by weaverryan** [comment]
Hey! If you're using Encore, have you done a `yarn install --force` or `npm install --force`? It may just be that your JS is still using the previous version, which sends GET requests.

**Comment by akyoscommunication** [comment]
Oh yeah my bad, I didn't restart the watch process after install --force ... 
Sorry for the mistake, thanks !
