### ISSUE TITLE
[Live Component] HTTP 405 Method Not Allowed with data binding

### ISSUE THREAD

**Issue by Gulivertx** [symfony/ux#1458]
Hello,

I updated my project from Symphony 5.4 to Symfony 6.4.
Now all my Live Component give an 405 error when I use data binding from an input to a live props.

Simple exemple here.

Template twig
```html
<input
                                    autocomplete="off"
                                    name="search-field"
                                    id="search-field"
                                    class="h-full w-full rounded-sm bg-white border-neutralSecondary py-2 px-3 pl-10 pr-3 text-sm text-neutralPrimary placeholder-neutralSecondary focus:border-themePrimary focus:placeholder-gray-400 focus:outline-none focus:ring-0"
                                    placeholder="Nom, avs, date de naissance..."
                                    type="search"
                                    data-model="debounce(400)|keyword"
>
```

Component php
```php
#[LiveProp(writable: true)]
public string $keyword = '';
```

Then I got an error all the time I use the input. There is the get method from : 
```json
{
    "route": "ux_live_component",
    "route_parameters": {
        "_route": "ux_live_component",
        "_live_action": "get",
        "_live_component": "patients_list"
    },
    "request_uri": "http://gynemanager.localhost/_components/patients_list?props=%7B%22keyword%22%3A%22%22%2C%22%40attributes%22%3A%7B%22data-live-id%22%3A%22live-1464226707-0%22%7D%2C%22%40checksum%22%3A%22EHvuV523%2BcAsav9PzW4WuRlOQ9BKPxjlNSa7QF5dzok%3D%22%7D&updated=%7B%22keyword%22%3A%22bap%22%7D",
    "method": "GET"
}
```

Error is in LiveComponentSubscriber.php @ line 175
```php
if ($request->isMethod('get') && 'post' === $requestMethod) {
        throw new MethodNotAllowedHttpException([strtoupper($requestMethod)]);
}
```

My requestMethod here is a post but in the browser I see a get. Then I don't understand why I get now this error, before the upgrade I not had any problem.

Anyone to help ?

EDIT : 
when I check what I get as method in LiveComponentSubscriber.php I get a POST
`$this->container->get(ComponentFactory::class)->metadataFor($componentName)?->get('method')` this return me a post.

When I check the Symfony Ajax request I only send a GET :/ and in the browser network tool I only see the GET as well....

**Comment by Gulivertx** [comment]
Found the problem ! Need to rebuild my JS with webpack -_-

**Comment by tito10047** [comment]
Same problem for me. 
for me help install packages ```yarn install --force```
