### ISSUE TITLE
[LiveComponent] Setting custom live-id in template not working anymore (since 2.14)

### ISSUE THREAD

**Issue by tijnema** [symfony/ux#1472]
Hi,

We've been generating a custom live-id inside components for a while now, which fixes a lot of reloading issues (including #1470 ). Since release 2.14 however, this no longer works as expected.

I've created a reproducer project: https://github.com/tijnema/livebug2
Currently it is running with live components 2.13, pressing the button will reload the parent (render time will update), and childs are not being updated.
When upgrading the reproducer to 2.14, clicking the rerender button will reload all 100 child components (see the 102 network request in debug bar).

We set the live-id in the template like this:
```twig
<div {{ attributes.without('data-live-id').defaults({'data-live-id': this.liveId}) }}>
```
I haven't found a better way to set the live-id inside a component (docs mention only setting it as argument when creating the component).
Maybe live components can have a method for generating a live id?

**Comment by smnandre** [comment]
Same thing here...  i see no problem here after installing your reproducer (or upgrading to 2.14.2)

https://github.com/symfony/ux/assets/1359581/b6bd9262-0573-4257-a0f3-08e42d298b19

**Comment by tijnema** [comment]
[Screencast_20240207_214931-1.webm](https://github.com/symfony/ux/assets/45099994/4e368345-ffe2-4034-958f-cfb3fa5a4b71)

**Comment by smnandre** [comment]
Maybe it's related to other packages ? Did you upgrade all ux packages ?

**Comment by tijnema** [comment]
I tried upgrading ux-live-component only, and with composer -W option, which updated ux-twig-component too, but it makes no difference. 

I've installed the reproducer on a dev server here: http://livebug2.tijnema.com/

All I've done is: 
```
git clone https://github.com/tijnema/livebug2
cd livebug2
composer require symfony/ux-live-component="v2.14.2" -W
```

**Comment by smnandre** [comment]
I upgraded all, that could be a solution

**Comment by tijnema** [comment]
What other packages are you talking about? I ran `composer update` once more, and that doesn't update anything. 

Just to be sure it's not browser related, can you see the issue on the link I provided?

**Comment by smnandre** [comment]
I did and i saw the bug you described

**Comment by smnandre** [comment]
Could you update symfony/ux-twig-component and symfony/stimulus-bundle to 2.14.2 just to see if that can be related ? 

(the only thing i see that seems to be different between my working test and yours )

**Comment by tijnema** [comment]
They are at version 2.14.2 right now, doesn't make any difference.

**Comment by smnandre** [comment]
I have now the bug locally oO ... will investigate from there.

**Comment by smnandre** [comment]
The following code would do what you expect i think 

(working on my machine, but as we just saw.... it's not something we can base anything on haha)

```twig
{# child.html.twig #}
<div {{ attributes.defaults({'key': this.liveId})  }}>
    <strong>Hello, I'm {{ this.number }}</strong><br>
</div>
```

**Comment by tijnema** [comment]
This works on my machine too, because it does not actually update the live-id used. 

It's actually the same as:
```twig
{# child.html.twig #}
<div {{ attributes  }}>
    <strong>Hello, I'm {{ this.number }}</strong><br>
</div>
```

But for me to fix other issues, like #1470 , I need to be able to set the live-id .

**Comment by davidhoelzel** [comment]
Version: 2.17.0

I'm having the same problem: I need to set a custom ID due to the example for [infinite-scrolling](https://ux.symfony.com/demos/live-component/infinite-scroll) not working with embedded components. The same live-ids will be generated again for all appended items and thus embedded components will not be rendered at all. There is just an empty div with the generated live-id like this:

```
<div id="live-3048092986-0"></div>
 ```

The item which was rendered on the first load has the same id and is rendered correctly.

Seems like either the example code by using the "data-live-ignore" attribute is just too simple or I'm missing something.

**Comment by davidhoelzel** [comment]
Seems like setting a custom id works this way:
`{{ attributes.without('id').defaults({id: 'some-unique-id'}) }}`

Then, the embedded components will be rendered correctly :-)

**Comment by tomazartack** [comment]
I have a similar issue like [davidhoelzel](https://github.com/davidhoelzel). Not sure yet but I'm investigating what is happening.

**Comment by tomazartack** [comment]
Yes, well the solution from @davidhoelzel worked for me in 90% of the cases, which suggests me that there is definitely something wrong with generation of live id attribute. For some reason I have about 10 live components of <twig:SomeComponent /> rendered in a loop on my page and some keep receiving the same id from some render before, although they should not have the same id. I want the id always to be new. I'd say this is a bug in live components and should be investigated. What makes it really annoying is, that this bug happens randomly, so like 9/10 components will work, and then randomly 1 will not work so I cannot reproduce it 2 times when I'm debugging my code. This has to be reopened, and checked by the symfony team.

**Comment by tomazartack** [comment]
For me the solution was something like this:
                                <twig:SomeComponent id="modal_interest_edit_form_{{ row['id'] }}_{{ random(100000, 999999) }}" />
So basically, adding a randomly generated id to the component forces it each time to be rendered, and 100% of the time I don't end up with empty div tags like a few comments above anymore
