### ISSUE TITLE
[TwigComponent] Value of "this" inside a nested component and accessing a method of the parent component?

### ISSUE THREAD

**Issue by gremo** [symfony/ux#1482]
`WeatherWidget` has a `location` public property and `getHasError()` public method.

My `WeatherWidget` component re-use `WidgetCard` for styling. Inside this nested component, variable `location` is visibile, but value of `this` refers to the nested component, not to the parent one. I think this is by design.

So how can I access `this.hasError` in the nested component?

```twig
{# components/WeatherWidget.html.twig #}
<div {{ attributes }}>
    <twig:WidgetCard>
        Current location is: {{ location }} {# variable is visible #}
        {% if this.hasError %} {# not working, value of this is WidgetCard #}
            An error occurred.
        {% endif %}
    <twig:WidgetCard>
</div>
```

One solution could be making `hasError` a public property, but I don't want to: this values is computed and depends on external API call (it should be not passed as input).

**EDIT**: another solution, seems counter-intuitive too:

```twig
{# components/WeatherWidget.html.twig #}
<div {{ attributes }}>
    {% set parent = this %}
    <twig:WidgetCard>
        {% if parent.hasError %}
            An error occurred.
        {% endif %}
    <twig:WidgetCard>
</div>
```

**Comment by norkunas** [comment]
maybe `outerScope.this.hasError` works?

**Comment by gremo** [comment]
> maybe `outerScope.this.hasError` works?

Almost, it has some caveats.

```twig
<div {{ attributes }}>
    <twig:WidgetCard>
        <twig:block name="title">
            <twig:WidgetTitle>
                {{ outerScope.this.title }} {# refer to WidgetCard, not WeatherWidgets #}
            <twig:WidgetTitle>
        </twig:block>
    <twig:WidgetCard>
</div>
```

**Comment by norkunas** [comment]
Do a `{{ dump() }}` and see what's available to use then

**Comment by gremo** [comment]
> Do a `{{ dump() }}` and see what's available to use then

Sure, outerScope.outerScope.this.title works. But is this the right way? Is documented?

**Comment by norkunas** [comment]
Yes in https://symfony.com/bundles/ux-twig-component/current/index.html#context-variables-inside-of-blocks section a little bit lower

**Comment by gremo** [comment]
Oh, sorry than. I was using outerBlocks all the time, not looking at outerScope. Thanks.
