### ISSUE TITLE
[LiveComponent] Getting "Cannot find a template matching "a67ec1ad40dd8f6b6934cb852ed6d2f9". Cache may be corrupt."... all the time

### ISSUE THREAD

**Issue by gremo** [symfony/ux#1493]
I've created a dashboard with a few live components, some of them configured with the [polling option](https://symfony.com/bundles/ux-live-component/current/index.html#polling).  The dashboard is running on a tablet, in Kiosk mode, so it can't be refreshed easly (at least, it will be refreshed at some time interval, i.e. 30 minutes).

The error happens in dev mode but, most important, in production mode. It goes away as soon as I refresh the page (in both modes).

Every time I deploy a new version of my app I get the following error: 

> Cannot find a template matching "a67ec1ad40dd8f6b6934cb852ed6d2f9". Cache may be corrupt. at /var/www/html/vendor/symfony/ux-live-component/src/Twig/TemplateMap.php:33

Source of exception is [TemplateMap.php](https://github.com/symfony/ux-live-component/blob/2.x/src/Twig/TemplateMap.php#L33) and details is:

```json
{
    "class": "RuntimeException",
    "message": "Cannot find a template matching \"e04c41ae1f6221d0e0371055ff8d5cb2\". Cache may be corrupt.",
    "code": 0,
    "file": "/var/www/vhosts/my-project/httpdocs/releases/41/vendor/symfony/ux-live-component/src/Twig/TemplateMap.php:33",
    "trace": [
        "/var/www/vhosts/my-project/httpdocs/releases/41/vendor/symfony/ux-live-component/src/EventListener/AddLiveAttributesSubscriber.php:72",
        "/var/www/vhosts/my-project/httpdocs/releases/41/vendor/symfony/event-dispatcher/EventDispatcher.php:246",
        "/var/www/vhosts/my-project/httpdocs/releases/41/vendor/symfony/event-dispatcher/EventDispatcher.php:206",
        "/var/www/vhosts/my-project/httpdocs/releases/41/vendor/symfony/event-dispatcher/EventDispatcher.php:56",
        "/var/www/vhosts/my-project/httpdocs/releases/41/vendor/symfony/ux-twig-component/src/ComponentRenderer.php:145",
        "/var/www/vhosts/my-project/httpdocs/releases/41/vendor/symfony/ux-twig-component/src/ComponentRenderer.php:65",
        "/var/www/vhosts/my-project/httpdocs/releases/41/vendor/symfony/ux-live-component/src/EventListener/LiveComponentSubscriber.php:342",
        "/var/www/vhosts/my-project/httpdocs/releases/41/vendor/symfony/ux-live-component/src/EventListener/LiveComponentSubscriber.php:270",
        "/var/www/vhosts/my-project/httpdocs/releases/41/vendor/symfony/event-dispatcher/EventDispatcher.php:246",
        "/var/www/vhosts/my-project/httpdocs/releases/41/vendor/symfony/event-dispatcher/EventDispatcher.php:206",
        "/var/www/vhosts/my-project/httpdocs/releases/41/vendor/symfony/event-dispatcher/EventDispatcher.php:56",
        "/var/www/vhosts/my-project/httpdocs/releases/41/vendor/symfony/http-kernel/HttpKernel.php:183",
        "/var/www/vhosts/my-project/httpdocs/releases/41/vendor/symfony/http-kernel/HttpKernel.php:76",
        "/var/www/vhosts/my-project/httpdocs/releases/41/vendor/symfony/http-kernel/Kernel.php:185",
        "/var/www/vhosts/my-project/httpdocs/releases/41/vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php:35",
        "/var/www/vhosts/my-project/httpdocs/releases/41/vendor/autoload_runtime.php:29",
        "/var/www/vhosts/my-project/httpdocs/releases/41/public/index.php:5"
    ]
}
```

I think it's something related to components configured with polling. Any help is really important here. Thanks.

This is a photo of the error, shown in a popup, with the standard Symfony error page template:

![PXL_20240213_114644787](https://github.com/symfony/ux/assets/1532616/51d76a09-c4dc-4e04-9532-3ad3364350f4)

**Comment by smnandre** [comment]
Hello @gremo ! You can try the PR i made if you want, that should fix your problem (it will probably be released at the end of the month)

**Comment by gremo** [comment]
@smnandre I'm so so happy this is a bug and you find out the solution! Thanks! I'll try your PR as soon as possible!

**Comment by smnandre** [comment]
You beeing that happy makes me even happier :)
