### ISSUE TITLE
Get data from <twig:block> in class

### ISSUE THREAD

**Issue by dirkjf** [symfony/ux#1508]
With a component "Tooltip", which has a block called "trigger" using it like this:

```
<twig:Tooltip hasArrow="{{ false }}">
    <twig:block name="trigger">
       <a href="/edit">edit</a>
    </twig:block>
    Edit page
</twig:Tooltip>
```

It would be nice to get the content from `<twig:block name="trigger">` in the **Tooltip.php** class, so calculated attributes could be set on it. 

My class looks like this:

```
#[AsTwigComponent]
class Tooltip
{
    public string $id = '';

    public string $position = 'top';

    public bool $hasArrow = true;

    // add random id if not set
    public function mount(): void
    {
        if (!$this->id) {
            $this->id = uniqid('tooltip_');
        }
    }
}
```

And I would want to put that `id` on `<a href="/edit">edit</a>`, instead of having to wrap it inside another element:

```
{# I would want this attribute "data-floating-tooltip-reference" with the id created in the class passed in the first element of block "trigger" instead #}
<div data-floating-tooltip-reference="{{ id }}">
    {% block trigger %}
        <button>Default trigger content</button>
    {% endblock %}
</div>

<div id="{{ id }}" class="floating-tooltip" data-floating-position="{{ position }}" role="tooltip" data-floating-arrow="{{ hasArrow ? 'true' : 'false' }}">
    {% block content %}
        Default content
    {% endblock %}
</div>
```

I don´t think there currently is any way to do this without the wrapper element or calling `parent()` inside the anchor element and putting the attributes inside the {% block %} as default content. Preferable, the data passed into the block can be accessed by the class.

**Comment by smnandre** [comment]
Maybe there ? https://symfony.com/bundles/ux-twig-component/current/index.html#inheritance-forwarding-outer-blocks

**Comment by dirkjf** [comment]
What you suggested did not work, for it would render the block where it was defined. But it did give me the idea to put the values inside a variable to call inside the block, which does work. Like this:

**Component**
```
{% set trigger_attributes %}data-floating-tooltip-reference="{{ id }}"{% endset %}

{% block trigger %}
    <button>Default trigger content</button>
{% endblock %}

<div id="{{ id }}" class="floating-tooltip" data-floating-position="{{ position }}" role="tooltip" data-floating-arrow="{{ hasArrow ? 'true' : 'false' }}">
    {% block content %}
        Default content
    {% endblock %}
</div>
```

**Usage**
```
<twig:Tooltip hasArrow="{{ false }}">
    <twig:block name="trigger">
       <a {{ trigger_attributes }} href="/edit">edit</a>
    </twig:block>
    Edit page
</twig:Tooltip>
```

Thanks for your suggestion. I will close this for it solves my issue.
