### ISSUE TITLE
Line missing in `bundles.php` after installing `symfony-ux-twig-component`

### ISSUE THREAD

**Issue by johanv** [symfony/ux#151]
I was triggered by Ryan Weavers talk at SymfonyWorld Online last summer to try out twig components; I think this looks very promising.

But when I added the `symfony-ux-twig-component` package to my project, and I tried to use a component on my twig page, I got this 'syntax error' message:

```
Unknown "component" function.
```

It turned out that symfony flex did not add the line

```
    Symfony\UX\TwigComponent\TwigComponentBundle::class => ['all' => true],
```

to my `bundles.php` file. I'm not completely sure if this is an issue with the twig-components-package or with my local setup. Maybe that file was read-only during the installation of the package (I have a docker setup with some permission issues), but I didn't get an error message when installing the package using composer.

Anyway, I thought to post this issue, in case someone else is hit by this problem. 

Thank you for all the work you put into symfony-ux, I really like it!

**Comment by weaverryan** [comment]
Hey @johanv!

Sorry for the slow reply :). I occasionally hear an issue like this - across many bundles. My guess is that, for some reason, Flex didn't complete its recipe install - but I don't know why :/. I think it's not an issue - but if someone else hits it, hopefully they can find your issue.

Cheers!
