### ISSUE TITLE
[Site] Using raw data attributes

### ISSUE THREAD

**Issue by seb-jean** [symfony/ux#1514]
raw data attributes is a preferred way. The `stimulus_*` functions will then have to be replaced on https://ux.symfony.com/.

Reference: https://github.com/symfony/ux/pull/1336

What do you think ?

**Comment by smnandre** [comment]
I'll do it if you want. But not this week please :)

I'm gonna make some changes on those files and i'd like to avoid handling conflicts on switch/rebase 😅

**Comment by seb-jean** [comment]
Yes @smnandre , no problem :)
