### ISSUE TITLE
The option "extra_options" does not exist.

### ISSUE THREAD

**Issue by adalbertus** [symfony/ux#1541]
Hi
I'm now upgrading my Symfony 6.3 application to 6.4 and I've also updated `symfony/ux-autocomplete` to the 2.15.0 version.

Now each time I'm trying to use my autocomplete field I'm getting error:
`
An error has occurred resolving the options of the form "App\Form\Autocomplete\MemberSingleAutocompleteField": The option "extra_options" does not exist. Defined options are: "action", "allow_extra_fields", ....
`
I've noticed that this extra_options was introduced in https://github.com/symfony/ux/pull/1322.

Should I stick to 2.14 version in order to use it with 6.4 Symfony?

**Comment by smnandre** [comment]
The extra_options exists in 2.15.0, but it is available for form types extending from:

```php
        return [
            ChoiceType::class,
            TextType::class,
        ];
```

What does your `MemberSingleAutocompleteField` _descend_ from ?

**Comment by thorstenlbk** [comment]
I am getting the error, too.

`An error has occurred resolving the options of the form "App\Form\KundendatenAutocompleteField": The option "extra_options" does not exist. Defined options are: "action",`

The relevant parts of KundendatenAutocompleteField:

~~~
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
...
class KundendatenAutocompleteField extends ChoiceType
...
~~~

Using `Symfony\Component\Form\AbstractType` or `Symfony\Component\Form\Extension\Core\Type\TextType` results in the same error.

**Comment by bdujon** [comment]
For autocomplete since 2.13 you need
`public function getParent(): string
{
    return BaseEntityAutocompleteType::class;
}`

instead of
`public function getParent(): string
{
    return ParentEntityAutocompleteType::class;
}`

https://symfony.com/bundles/ux-autocomplete/current/index.html#usage-in-a-form-with-ajax
at least that was my issue

**Comment by adalbertus** [comment]
@bdujon - brilliant! 😄 It is working now. Thank you!

I wonder that maybe it would be worth to add it as a comment in `symfony console make:autocomplete-field`?
Autogenerated class uses `ParentEntityAutocompleteType::class;` which is fine when you are not using Ajax but is not otherwise. Error message was missleading here (at least for me).

For example:
```
Customize your new field class, then add it to a form:
 
     $builder
         // ...
         ->add('user', Foo::class)
     ;

```
Add somethig like: Change getParent() acordingly if using with Ajax.
