### ISSUE TITLE
Explicit re-render of a field when clicking a button

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/ux#1569]
I have a complex component with many form elements (it's not a Symfony form).

When I change `<select>` and `<input>` elements, the page re-renders as expected. But then, I have this other element:

![image](https://github.com/symfony/ux/assets/73419/25c4e87c-d495-4deb-b744-ce00aa2ad8a6)

The input text is a live prop and I only want the page to re-render when the user clicks on the related button.

I can't do that. I read the docs and followed this: https://symfony.com/bundles/ux-live-component/current/index.html#lazy-updating-on-change-of-a-field

So, I applied the `<input data-model="on(change)|coupon">` syntax. It almost works:

* When you type the coupon code, the page doesn't re-render
* When you click on the button, the page re-renders
* BUT ... there's an edge-case: you change the contents of the coupon input and don't click on the button ... you change other input and then the coupon is applied to that re-render. It's strange because two different things are changing at the same time

I'd need something like this:

`<input data-model="on(click=couponButton)|coupon">`

Thanks!

**Comment by weaverryan** [comment]
Hey Javier!

What about:

```html
<input data-model="norender|coupon">
<button
    data-action="live#$render"
>Apply</button>
```

I think this will work. And if it does, yay! Then the question will be: how can we update the docs to make this more obvious.

**Comment by javiereguiluz** [comment]
Ryan, you are a genius 🙇  Your suggestion worked beautifully.

Yes, I'd love to see this "magic action" mentioned somewhere in the docs. Thanks!

**Comment by weaverryan** [comment]
Cool :) #1574
