### ISSUE TITLE
[LiveComponent] Using ComponentWithFormTrait and switching forms doesn't keep form values.

### ISSUE THREAD

**Issue by pierredup** [symfony/ux#1573]
I am implementing a settings page, where I have different forms for different setting categories. When a user switches the menu to a different category, the form changes to a different form to match the category.

When using the `ComponentWithFormTrait` trait and the `instantiateForm` method to create the different forms, the values gets lost between re-render. The form switches fine, but the values for the new form is not added correctly.

E.G this is the `instantiateForm` method:

```php
protected function instantiateForm(): FormInterface
{
    $settings = $this->getAppSettings();
    return $this->createForm(SettingsType::class, $settings[$this->section]);
}
```

Where `$this->section` is a LiveProp that switched between the different setting categories.

Here is a video showing the current behaviour:

https://github.com/symfony/ux/assets/144858/c0a3838b-2191-4e77-ace6-5970859fdfa5

If I remove the `ComponentWithFormTrait` and change the method to the following to manually create the form, then it works perfectly:

```php
#[ExposeInTemplate]
public function getForm(): FormView
{
    $settings = $this->getAppSettings();    
    return $this->createForm(SettingsType::class, $settings[$this->section])->createView();
}
```

https://github.com/symfony/ux/assets/144858/a0eecab8-3a06-49b6-9138-fb5d25b141dc

(In the first video, the form is rendered fine when switching between categories but loosing existing values. In the second video the form is rendered correctly and existing values is kept in the form).

While using the custom `getForm` method works fine, it loses a lot of the built-in functionality (automatic validation, resetting the form, simplified form saving, etc)

**Comment by weaverryan** [comment]
Hey @pierredup!

Hmm. Yea, this switching the form data is a bit odd (not that it's wrong, but it's obviously tripping the system up). I think what's happening is this (and perhaps you can verify) when you click to change sections

A) The `instantiateForm()` method is called. At this point, `$this->section` DOES have the new value, so we ARE passing the correct data into the form.

B) Internally, the old form values are submitted into the form https://github.com/symfony/ux/blob/2.x/src/LiveComponent/src/ComponentWithFormTrait.php#L108-L113 - I think this is causing the previous forms values to be submitted into the form. The fields are totally different, so you end up with, basically, a form where all of the original values have been replaced by nothing.

If I'm correct, the moment the `section` changes, the next re-render should avoid submitting the form. I'd try this:

```php
#[LiveProp(writable: true, onUpdated: 'onSectionChange')]
public string $section;

public function onSectionChange(): void
{
    $this->resetForm();
}
```

Let me know how it goes and what you discover. There is likely *at least* a documentation improvement we can make here.

**Comment by pierredup** [comment]
> If I'm correct, the moment the section changes, the next re-render should avoid submitting the form. I'd try this:

This works perfectly. Thanks @weaverryan!

> Let me know how it goes and what you discover. There is likely at least a documentation improvement we can make here.

I'll create a PR with some doc improvements next week.

**Comment by weaverryan** [comment]
Well that was fast :D. 

> I'll create a PR with some doc improvements next week

Please do - you rock!
