### ISSUE TITLE
[TwigComponent] Allow passing array in attribute defaults system

### ISSUE THREAD

**Issue by seb-jean** [symfony/ux#1604]
Currently, we can set defaults attributes with a string:

```twig
<div {{ attributes.defaults({
    class: 'row mb-5 align-items-center position-relative'
}) }}>
    <div class="col-12 col-md-6 code-description {{ not reversed ? 'order-md-2' }}">
        {% apply markdown_to_html %}
            {% block content %}{% endblock %}
        {% endapply %}
    </div>
    <div class="col-12 col-md-6" {{ not reversed ? 'order-md-1' }}>
        <twig:CodeBlock :filename="filename" />
    </div>
</div>
```
It would be interesting to be able to also do this with an array. It's a bit of a continuation of https://github.com/symfony/ux/issues/1586:
```twig
<div {{ attributes.defaults({
    class: [
        'row',
        'mb-5',
        'align-items-center',
        'position-relative'
    ]
}) }}>
    <div class="col-12 col-md-6 code-description {{ not reversed ? 'order-md-2' }}">
        {% apply markdown_to_html %}
            {% block content %}{% endblock %}
        {% endapply %}
    </div>
    <div class="col-12 col-md-6" {{ not reversed ? 'order-md-1' }}>
        <twig:CodeBlock :filename="filename" />
    </div>
</div>
```

What do you think ?

**Comment by kbond** [comment]
I do like this idea but, and I can't think of an example, it's not guaranteed that every attribute uses a space as a separator.

https://github.com/twigphp/Twig/pull/3970#issuecomment-1906492444

I think I'm ok adding as you probably want a space separator 90% of the time.

**Comment by smnandre** [comment]
I'm not sure i like this, because you could expect a form of serialization for some attributes (data-* ?), this make no sense for all that do not accept spaces (id, for, ..) etc.

You can do the following here in the meanwhile

```twig
<div {{ attributes.defaults({
    class: [
        'row',
        'mb-5',
        'align-items-center',
        'position-relative'
    ]|join(' ')
}) }}>
```

**Comment by smnandre** [comment]
And i'm pretty sure this will bring frustrations with people asking how to add/remove "one" of the classes.

**Comment by smnandre** [comment]
Or you can leverage [html_classes](https://twig.symfony.com/doc/3.x/functions/html_classes.html) for syntaxic sugar 

```twig
<div {{ attributes.defaults({
    class: html_classes(
        'row',
        'mb-5',
        'align-items-center',
        'position-relative',
    )
}) }}>
```

which will allow you more things like


```twig
<div {{ attributes.defaults({
    class: html_classes(
        'row',
        { 'mb-5': this.hasMargin }
        'align-items-center',
        'position-relative',
       { 'color-user': app.user is not null }
    )
}) }}>
```

**Comment by kbond** [comment]
I think I'm leaning towards @smnandre's suggestions.

**Comment by seb-jean** [comment]
Thank you friends for your suggestions!
