### ISSUE TITLE
Roadmap for Symfony 6 & Stimulus 3 support

### ISSUE THREAD

**Issue by weaverryan** [symfony/ux#161]
Hi!

Stimulus 3 has been released (if you're unaware, it's a few nice feature, but mostly, the library was renamed from `stimulus` to `@hotwired/stimulus`) and Symfony 6 is around the corner. Here is what I think we should do:

~~A) Make one last 1.x release of symfony/ux with Symfony 6 support #160~~ (we decided to skip this - if you're using Symfony 6, you'll use 2.0 of the symfony/ux libraries)
~~B) Create 1.x and 2.x branches on symfony/ux~~ (skipped this also - keep `main` branch only for now)
C) Make a 2.0 release of symfony/ux, stimulus-bridge, stimulus-testing
    - Merge Stimulus 3 PR (#141, https://github.com/symfony/stimulus-testing/pull/4, https://github.com/symfony/stimulus-bridge/pull/48)
    - new build system / typescript (#156)
    - Chartjs upgrade (#126)
    - bump PHP min version to 8.0

Blockers for the 2.0 release:

* [x] #141
* [x] #156
* [ ] #126 (not a block but would be great to have)
* [ ] PR to update the recipe for WebpackEncoreBundle to install `@hotwired/stimulus` v3

**Comment by norkunas** [comment]
This can be closed I think
