### ISSUE TITLE
[LiveComponent] Unable to use a collection of DTOs as LiveProp: Unable to dehydrate value of type "array".

### ISSUE THREAD

**Issue by gremo** [symfony/ux#1611]
I'm afraid this could be a regression as I'm pretty sure it worked before 2.16. I'm following the [official docs:](https://symfony.com/bundles/ux-live-component/current/index.html#using-dto-s-on-a-liveprop)

> To work with a collection of DTOs, specify the collection type inside PHPDoc:

Here is the DTO:

```php
<?php

namespace App\Model;

class AddressDto
{
    public ?string $name = null;
}
```

And the simple component that use a collection of `AddressDto`:

```php
<?php

namespace App\Twig\Components;

use Symfony\UX\LiveComponent\Attribute\AsLiveComponent;
use Symfony\UX\LiveComponent\Attribute\LiveAction;
use Symfony\UX\LiveComponent\Attribute\LiveProp;
use Symfony\UX\LiveComponent\DefaultActionTrait;
use App\Model\AddressDto;

#[AsLiveComponent]
class Test
{
    use DefaultActionTrait;

    /**
     * @var AddressDto[]
     */
    #[LiveProp()]
    public array $results = [];

    #[LiveAction]
    public function update(): void
    {
        $address = new AddressDto();
        $this->results[] = $address;
    }
}
```

... and the Twig:

```twig
<div {{ attributes }}>
    {% for result in results %}
        {{ dump(result) }}
    {% endfor %}

    <button
        data-action="live#action"
        data-live-action-param="update"
    >update</button>
</div>
```

As soon as you click the updated button (and the result array is populated) I get the following:

> Unable to dehydrate value of type "array" for property "results" on component "App\Twig\Components\Test". Change this to a simpler type of an object that can be dehydrated. Or set the hydrateWith/dehydrateWith options in LiveProp or set "useSerializerForHydration: true" on the LiveProp to use the serializer.

Are you able to get this to work?

**Comment by gremo** [comment]
I've found the issue. My root composer.json is missing `phpdocumentor/reflection-docblock` which seems required to work with PHPDoc anotations and live components.

**Why this isn't mentioned in the documentation?**

**Comment by smnandre** [comment]
I believe it's simply a matter of something being omitted, or because it never happened before, as the `phpdocumentor/reflection-docblock` is automatically included when you use the `symfony new --webapp` command.

Pull Requests are welcome! :)

**Comment by gremo** [comment]
@smnandre Yes, of course. `phpdocumentor/reflection-docblock` is installed using the `serializer-pack` if I recall correctly, and it's listed in [the pack](https://github.com/symfony/webapp-pack/blob/main/composer.json). 

But not all people install the whole webapp package, right? 

For example, if you try to use the serializer as hydrator in a live component, symfony will warn you: https://github.com/symfony/ux/blob/2562a6c3c7542dd85a59e6d84201dd44d0e6e759/src/LiveComponent/src/LiveComponentHydrator.php#L250

But this is not happening if you miss `phpdocumentor/reflection-docblock` and you try to hydrate collections (arrays).

At least, **this should be documented IMHO**. Or we can close this issue and continue with our lives, of course. 😄

**Comment by smnandre** [comment]
It should 100% be documented,

I just tried to explain you why it is not documented right now :) 

(the serializer was required for LiveComponent until recently)

That's why i said "PR are welcome": if you want to add a sentence about it in the documentation, it will be usefull for others!

**Comment by gremo** [comment]
@smnandre Done, not sure if this will get approved (my first PR here, didn't have found the way to generate the docs and preview changes).

**Comment by smnandre** [comment]
@gremo  And it has been 👏  Thank you again
