### ISSUE TITLE
[LiveComponent] Wrong LiveAction called when adding a Stimulus controller, even an empty one

### ISSUE THREAD

**Issue by gremo** [symfony/ux#1612]
**EDIT**: minimal reproducible repo: https://github.com/gremo/ux-issue-1612

Imagine this component tree, pretty simple:

```twig
<twig:AppContext>
    {% if not address %}
        <twig:Foo />

        <button data-action="live#action" data-live-action-param="setAddress">
            call setAddress()
        </button>
    {% else %}
        <twig:Bar />

        <button data-action="live#action" data-live-action-param="unsetAddress">
            call unsetAddress()
        </button>
    {% endif %}
</twig:AppContext>
```

Where you have a root component `AppContext` which render `Foo` or `Bar` based on the value of `address`:

```php
#[AsLiveComponent]
class AppContext
{
    use DefaultActionTrait;

    public ?AddressDto $address = null;

    #[LiveAction]
    public function setAddress(): void
    {
        $this->address = new AddressDto();
    }

    #[LiveAction]
    public function unsetAddress(): void
    {
        $this->address = null;
    }
}
```

1. Click `call foo()` and value "foo" is shown
2. Click `call setAddress()`
3. Component Bar is shown
4. Click `call bar()` and value "bar" is shown
5. Click `call unsetAddress()`
6. Click `call foo()` and value "foo" is shown again

```php
#[AsLiveComponent]
class Foo
{
    use DefaultActionTrait;

    #[LiveAction]
    public function foo(): void
    {
        dd("foo");
    }
}
```

```twig
{# components/Foo.html.twig #}
<div {{ attributes }}>
    <button data-action="live#action" data-live-action-param="foo">
        call foo()
    </button>
</div>
```

```php
#[AsLiveComponent]
class Bar
{
    use DefaultActionTrait;

    #[LiveAction]
    public function bar(): void
    {
        dd("bar");
    }
}
```

```twig
{# components/Bar.html.twig #}
<div {{ attributes }}>
    <button data-action="live#action" data-live-action-param="bar">
        call bar()
    </button>
</div>
```

## This is working good and without problems action are routed correctly

![working](https://github.com/symfony/ux/assets/1532616/c8bc73ea-f2a5-4e55-9712-c7f490ed15f0)

## Now just add an empty Stimulus controller to `Foo` to make action routing not working anymore

```js
// assets/controllers/foo-controller.js
import { Controller } from '@hotwired/stimulus';

export default class extends Controller {}
```

A little change to `Foo` template:

```twig
{# components/Foo.html.twig #}
<div {{ attributes.defaults(stimulus_controller('foo')) }}>
    <button data-action="live#action" data-live-action-param="foo">
        call foo()
    </button>
</div>

```

![notworking](https://github.com/symfony/ux/assets/1532616/5a94f878-4597-4b61-8b7a-79702280a769)

As you can see:

1. Click `call foo()` and value "foo" is shown
2. Click `call setAddress()`
3. Component Bar is shown
4. Click `call bar()` and an excaption is thrown

Clicking `call bar()` just invoked the wrong action on component `Foo`, while it should call `Bar` instead:

![Screenshot 2024-03-12 131114](https://github.com/symfony/ux/assets/1532616/a5603439-0d86-4319-8fb8-d7117caf24e0)

**Comment by smnandre** [comment]
Does adding an id "foo" or "bar" on your component help ?

If not could you make a small reproducer with this case, it would help to install locally and understand what's happing (or not) there ?

**Comment by gremo** [comment]
@smnandre i can make a minimal repo showing the issue yes... give me some time!

**Comment by smnandre** [comment]
Adding id's on your root elements (in both "foo" and "bar") did not work ?

**Comment by gremo** [comment]
@smnandre It didn't. Just finished the repo, wait a few minutes I can put a README

**Comment by gremo** [comment]
@smnandre here we are: https://github.com/gremo/ux-issue-1612

Let me know if it's working for you, or if you have any kind of trouble setting up the project. And thanks for investigating...

**Comment by smnandre** [comment]
There is a JS error on the second click (setAddress / unsetAddress).

Not sure if related, but i used the more standard way of adding a controller from inside the template.

```twig
<div {{ attributes.defaults(stimulus_controller('foo')) }}>
    <button data-action="live#action" data-live-action-param="foo">
        call foo()
    </button>
</div>
```


And then this fixed --i think-- the problem


```twig
<twig:AppContext>
    {% if not address %}
        <div id="with-foo">
            <twig:Foo  />

            <button data-action="live#action" data-live-action-param="setAddress">
                call setAddress()
            </button>
        </div>
    {% else %}
        <div id="with-no-foo">
            <twig:Bar />

            <button data-action="live#action" data-live-action-param="unsetAddress">
                call unsetAddress()
            </button>
        </div>
    {% endif %}
</twig:AppContext>
```

**Comment by gremo** [comment]
> There is a JS error on the second click (setAddress / unsetAddress).

In the console you mean? Yes, but I it's not an error caused "by me", it's just Stimulus not finding the node.

About adding the `id`... oh yes, it fixes the problem!!! Can you explain better... why? It's documented? I didn't added the `id` to the wrapper element, only to `Foo` and `Bar` componets - sorry.

**Comment by smnandre** [comment]
I think the morphing lib think in one case your component is the same as the precedent, and so Stimulus does not realize it's a new action.. 

Using "ids" helps a lot identifying what's identical from a request to another, forcing the creation of a new node/component instead of just modifying the existing once

**Comment by gremo** [comment]
I guess there is nothing documented about this behaviour. Coming from a bit of React I can imagine how it works, but still it's "obscure".

Thank you for helping me figure it out. Closing!
