### ISSUE TITLE
Can't get $options in autocomplete, and can't override query_builder in base class

### ISSUE THREAD

**Issue by robert-hoffmann** [symfony/ux#1613]
I need to access a variable i passed in in the component

I add the variable here
![image](https://github.com/symfony/ux/assets/5472296/a53ec595-73a2-4f21-9d48-d88c86419f57)

Then i pass it on here
![image](https://github.com/symfony/ux/assets/5472296/da7a922f-1419-4f8b-a8ad-05e86af70075)

And pass it along again here
![image](https://github.com/symfony/ux/assets/5472296/75597e21-bae5-4073-8722-3b798d7ff98c)

But no matter what i do, i can't seem to access $options here inside the query_builder
And i need to to customize the query_builder code to filter stuff based on that variable
![image](https://github.com/symfony/ux/assets/5472296/11555be2-7935-45dc-af2a-902adb7332a0)

Also i can't override query_builder here in the base class (it's just ignored), or i would have done it here
(yet you "can" override other settings) 
![image](https://github.com/symfony/ux/assets/5472296/3c605b35-6263-4108-9134-60e3ecccea1a)

Any ideas ?

**Comment by smnandre** [comment]
In the documentation, there is a note [just before this](https://symfony.com/bundles/ux-autocomplete/current/index.html#styling-tom-select) 

> Avoid passing any options to the 3rd argument of the ->add() method as these won't be used during the Ajax call to fetch results. Instead, include all options inside the custom class (FoodAutocompleteField).

If i understand it right, you fall in this case. But there is a new way to pass options to query, look https://github.com/symfony/ux/pull/1322

**Comment by robert-hoffmann** [comment]
Interesting 👍

But i still don't see how i can extract extra_options inside
![image](https://github.com/symfony/ux/assets/5472296/971b7a91-db29-4417-8421-985f497aafe1)


I need to access it inside query_builder

**Comment by robert-hoffmann** [comment]
Ok i got it like this ..probably a better way to do it though
(ignore the query ..it's bugged still ^^)

![image](https://github.com/symfony/ux/assets/5472296/c1794a57-9a5a-4439-b737-b8d710580006)

Thanks 🙏

**Comment by robert-hoffmann** [comment]
Assez moche la solution, mais ca marche
![image](https://github.com/symfony/ux/assets/5472296/f1cac599-0835-497e-a00b-ed28594e0f0c)

**Comment by jkgroupe** [comment]
I was trying to find out where come from the class `Options` because it is not explained in doc and I found it in test cases here   https://github.com/symfony/ux/blob/2b2d180fb14b40ac933bfd0fb36f2b6cea88ab85/src/Autocomplete/tests/Fixtures/Form/IngredientAutocompleteType.php
