### ISSUE TITLE
Display Problem UX Autocomplete / TomSelect

### ISSUE THREAD

**Issue by simonsolutions** [symfony/ux#1616]
I have the problem with the newest version, that on grouped Autocomplete/TomSelect, the selected item gets duplicated to the end of the list, or sometimes the grouping completely disappears.
Like in this example:
Before selecting a different item:
![image](https://github.com/symfony/ux/assets/20499623/84d932cd-5952-4fa3-b3be-fad29cb9735c)
After selecting the other item:
![image](https://github.com/symfony/ux/assets/20499623/e9faf77f-9d4b-4b10-8650-53316cf335ef)

With other UX Autocompletes the items are additionally added to the bottom of the list as new items. 

Tested on safari and firefox. 
symfony/ux-autocomplete	2.16.0
tom-select	2.3.1

Does anyone have these effects too?

**Comment by smnandre** [comment]
Do you use LiveComponent or is this with Autocomplete "only" ?

**Comment by simonsolutions** [comment]
It is only the autocomplete without the live component.

**Comment by smnandre** [comment]
When you say "newest version" do you know if you used Autocomplete 2.14 or 2.15 previously ? 

Could create a minimal reproducer ? That would be a great help to start the investigation / bug fix :)

**Comment by simonsolutions** [comment]
I just recognised the behaviour yesterday with 2.16, and also tried 2.14 and 2.15 now, that happens also with these versions.

Here is a minimal project (blank Symfony project) that reproduces the behaviour:
https://github.com/simonsolutions/symfony_ux_auto_problem

**Comment by smnandre** [comment]
Thank you for the reproducer

So it seems to me TomSelect move the option outside the original group, but i'm not sure how to fix / compensate this :| 


<img width="1056" alt="Capture d’écran 2024-03-13 à 23 34 36" src="https://github.com/symfony/ux/assets/1359581/38ce4675-b921-4033-9dd4-6927e8f0bea4">

**Comment by simonsolutions** [comment]
That explains the behaviour, but not why it occurs. 

They released last time in Oct 2023: https://github.com/orchidjs/tom-select/releases

I'm not sure if it already happens since then. But does it make sense to downgrade the tom select below 2.3?

**Comment by smnandre** [comment]
Can you remove the groups temporarely ?

**Comment by simonsolutions** [comment]
In the reproducer I added one UX Autocomplete/Tom select without the groups. That works fine, but for my project the groups are necessary.

**Comment by smnandre** [comment]
And does it work without UxAutocomplete ?

**Comment by simonsolutions** [comment]
I tried it on the reproducer with tom select 2.3.1, 2.3.0 and 2.2.2 and the problem occurs on all versions. I'm not really sure if its a problem on tom select or Symfony ux component?!

**Comment by smnandre** [comment]
Even with just TomSelect and no UXAutocomplete ?

**Comment by simonsolutions** [comment]
It was with UX Autocomplete. 
I now tried also the tomselect only. Here is a simple HTML file with just a tomselect. It works just fine for me - the problem does not occur:
https://github.com/simonsolutions/symfony_ux_auto_problem/blob/main/test.html

**Comment by smnandre** [comment]
So they do have the same problem, as the real `<select>` HTML code is messed with

<img width="400" src="https://github.com/symfony/ux/assets/1359581/cde6d168-8a78-472b-9c05-e10ea024aa25" />

<img width="400" src="https://github.com/symfony/ux/assets/1359581/a9823595-ea67-46e1-84bf-7df702694d5a" />

**Comment by simonsolutions** [comment]
For me the simple HTML tomselect sample worked, now I am confused. that the test.html not work for you or is the code just wrong but displayed correctly?

**Comment by smnandre** [comment]
Just saw this in the documentation, maybe you could try with the options as shown here ? 

https://symfony.com/bundles/ux-autocomplete/current/index.html#manually-using-the-stimulus-controller

Not sure if that can/should be in the JS options to TomSelect, or in the form... but this is something you should investigate, as TomSelect has some documentation on it: https://tom-select.js.org/plugins/optgroup-columns/ 

```json
{
    "results": {
        "options": [
            { "value": "1", "text": "Pizza", "group_by": ["food"] },
            { "value": "2", "text": "Banana", "group_by": ["food"] }
        ],
        "optgroups": [{ "value": "food", "label": "food" }]
    }
}
```

**Comment by simonsolutions** [comment]
I think that is needed if the tomselect is bound the a free (not entity bound) Ajax source. in this case there is no Ajax loading for the tom select, the input options and groups are just sent when generating the (tom) select.
