### ISSUE TITLE
UX Toggle Password used for RepeatedType?

### ISSUE THREAD

**Issue by simonsolutions** [symfony/ux#1623]
I've started using the UX Toggle Password component. Using it on the Symfony PasswordType fields is no problem. But I didn't find any option to use it with the RepeatedType (new password and repeating password). Is there anything I didn't see or is an implementation planned?

**Comment by jmsche** [comment]
I think it should work if you pass the option in `first_options` & `second_options`.

See https://symfony.com/doc/current/reference/forms/types/repeated.html

**Comment by simonsolutions** [comment]
Awesome thank you for your fast reply. That was exactly what I was looking for and missed.
