### ISSUE TITLE
[LiveComponent] pass optional validation groups to ValidatableComponentTrait

### ISSUE THREAD

**Issue by Craeckerffm** [symfony/ux#1626]
I want to validate a property in my LiveComponent using the `ValidatableComponentTrait`
I need to pass it a validation group. As far as i understand there is no such option yet. 
I am about to create a patch for my project where i modify the `ComponentValidatorInterface` like so:

  `  public function validate(object $component, ?array $groups): array;`

   ` public function validateField(object $component, string $propertyName, ?array $groups): array;`

and implement the changes into the `ComponentValidator`

I will also patch the `ValidatableComponentTrait` to be able to pass the  optional ` $groups` parameter down from my component.

Is there an easier solution i did miss? Otherwise, if from interest, i am happy to create a PR for this as well.

**Comment by smnandre** [comment]
There is an almost-finished PR about this here: https://github.com/symfony/ux/pull/1270#pullrequestreview-1778012849
