### ISSUE TITLE
[Icons] Add a way to access icons via PHP code

### ISSUE THREAD

**Issue by gubler** [symfony/ux#1656]
It would be helpful to have a way to access icons from PHP code (for example, to send SVG data in a payload to be loaded by JS).

This could possibly be by loading the icon registry as a service and then fetching an icon (using the same identifier as I would use in the Twig `ux-icon('icon-name')` function.

**Comment by kbond** [comment]
I'd like to stabilize the API a bit before adding this but for sure, we should enable this. I'm thinking to make `IconRegistryInterface` auto-wireable (removing the `@internal` flag from it and `Icon`).

**Comment by smnandre** [comment]
Agree with @kbond ! Yes to the idea, but let’s take some time before exposing anything, as the next week could require some changes in the implementation.

**Comment by smnandre** [comment]
Hi @gubler .. it's been a while, but if you missed it, you now can inject / autowire the Renderer where you need to use it :) 

--> Symfony\UX\Icons\IconRendererInterface

**Comment by gubler** [comment]
Thanks! I really appreciate it :)
