### ISSUE TITLE
[Icons] `<twig:UX:icon .../>` casing issue

### ISSUE THREAD

**Issue by kbond** [symfony/ux#1657]
ux.symfony.com/icons shows <twig:ux:icon .../> (lowercase `UX`). Considering the way we hijack rendering the component via an event, can we make case insensitive? I admit, uppercasing `UX` is a bit of a pain when writing manually.

**Comment by smnandre** [comment]
We can! ... 

Lowercase would just be "supported" or we make it the "official" case ? 

We should use the same as much as possible, as i'm not sure of the implications in term of caching, opcode, etc.. :|

**Comment by kbond** [comment]
Yes, we should definitely be consistent in docs/code, and of course, projects should be consistent in their usage.

I'm not sure on the official case... I think I'm leaning towards `<twig:ux:icon .../>` (lowercase).
