### ISSUE TITLE
[LazyImage] - Issue between ux-lazy-image and intervention/image (ImageManager::__construct(), 0 passed)

### ISSUE THREAD

**Issue by a-lebailly** [symfony/ux#1670]
Hello, I have a problem when I try to use `UX Lazy Image` with `BlurHash`.  

When I try to execute this code in one of my templates ([according to symfony example ux](https://ux.symfony.com/lazy-image)) :
```html
<img
    src="{{ data_uri_thumbnail('build/images/logo.png', 40, 30) }}"
    data-controller="symfony--ux-lazy-image--lazy-image"
    data-symfony--ux-lazy-image--lazy-image-src-value="{{ asset('build/images/logo.png') }}"
    alt="A blurhash image that is replaced by the real image on load"
    width="578"
    height="275"
    style="border-radius: 5px;"
>
```

I get the following error message :
> An exception has been thrown during the rendering of a template ("To use the Blurhash feature, install intervention/image.").

So I install `intervention/image` according to the message with `composer require intervention/image` (version `3.5`).  
But I get another error message :
> Too few arguments to function Intervention\Image\ImageManager::__construct(), 0 passed in /Users/.../symfony-app/var/cache/dev/ContainerGHlcxB8/App_KernelDevDebugContainer.php on line 1525 and exactly 1 expected

After looking through the `App_KernelDevDebugContainer` file, I found this line :
```php
$instance->addExtension(new \Symfony\UX\LazyImage\Twig\BlurHashExtension(new \Symfony\UX\LazyImage\BlurHash\BlurHash(new \Intervention\Image\ImageManager())));
``` 

`ImageManager` is instantiated without any parameter, but requires one :
```php
public function __construct(string|DriverInterface $driver)
{
    $this->driver = $this->resolveDriver($driver);
}
```
[https://github.com/Intervention/image/blob/3.5.0/src/ImageManager.php](https://github.com/Intervention/image/blob/3.5.0/src/ImageManager.php)

If anyone has any ideas on how to solve this problem, I'd love to hear from you.
I'll investigate for more details.

**Comment by kbond** [comment]
Can you try using intervention v2? V3 is not yet supported (https://github.com/symfony/ux/issues/1465).

**Comment by a-lebailly** [comment]
> Can you try using intervention v2? V3 is not yet supported (#1465).

@kbond Sorry, I hadn't seen this issue.
I went back to the latest v2 (`2.7.2`) and it works fine.

Thank's for your help ! 👍
