### ISSUE TITLE
[Icons] Cannot install from composer

### ISSUE THREAD

**Issue by xVinniVx** [symfony/ux#1671]
Using command from docs: _composer require symfony/ux-icons_ i get error: **Could not find a version of package symfony/ux-icons matching your minimum-stability (stable). Require it with an explicit version constraint allowing its desired stability.**

How can I install UX Icons in Symfony 7?

**Comment by fracsi** [comment]
Stable ux-icons is not released yet.
You can install the dev version: `composer req symfony/ux-icons:^2.x-dev`

**Comment by javiereguiluz** [comment]
@fracsi's solution is the good one ... and you don't even have to change your `minimum-requirement` option in `composer.json`. Run that command and only that `ux-icons` dependency will be unstable; the rest of dependencies won't change.

Closing here as "fixed" ... although the real fix will be the stable release of `ux-icons` in a few days. Thanks!
