### ISSUE TITLE
[LiveComponent] Accessing the original request when a component route is called

### ISSUE THREAD

**Issue by gremo** [symfony/ux#1675]
My application consist in some routes accessibile using a special parameter called `_profile` (behave like `_locale` special parameter):

- `60b276df-290f-4479-9ffc-ec7ca39dc297/page1`
  - Component1
  - Component2
- `60b276df-290f-4479-9ffc-ec7ca39dc297/page2`
  - Component3

Under both pages, my live components "live". These components need the `profile` object (I'm actually passing the `profile` to each component). Live component action will call some service, which in turn will use the provided `profile`:

`LiveComponent -> Action -> Service (use the profile)`

**Do you have an idea on how to access the original request from the service, when a Live Component action is called? The `RequestStack` can't help here.**

<details>
  <summary>Additional notes: I also have a <code>ProfileListener</code></summary>

Additional notes: I also have a `ProfileListener` which, on every request, check if we are under the "profile zone" and:

- Add a Twig global variable named `profile` (so I can access the `profile` object in my Twig)
- Add a router context parameter named `_profile` (so I don't need to specify `_profile` when generating urls)

```php
<?php

namespace App\EventListener;

use App\Entity\Profile;
use App\Repository\ProfileRepository;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\HttpKernel\Event\RequestEvent;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\HttpKernel\KernelEvents;
use Symfony\Component\Routing\RequestContextAwareInterface;
use Twig\Environment;

class ProfileListener implements EventSubscriberInterface
{
    public function __construct(
        private ProfileRepository $repository,
        private Environment $twig,
        private ?RequestContextAwareInterface $router = null
    ) {
    }

    public function onKernelRequest(RequestEvent $event): void
    {
        $request = $event->getRequest();
        if (!$event->isMainRequest()) {
            return;
        }

        $profileUuid = $request->attributes->get('_profile');
        if (!$profileUuid) {
            return;
        }

        $profile = $this->repository->find($profileUuid);
        if (!$profile) {
            throw new NotFoundHttpException(
                sprintf('"%s" object not found by "%s".', Profile::class, self::class)
            );
        }

        $this->twig->addGlobal('profile', $profile);
        $this->router?->getContext()->setParameter('_profile', $profileUuid);
    }

    public static function getSubscribedEvents(): array
    {
        return [
            KernelEvents::REQUEST => 'onKernelRequest',
        ];
    }
}
```

</details>

**Comment by smnandre** [comment]
There is currently no way to access the original request. 

If your components need this "profile" information, it doesn't feel illogical to me that you pass it and make it a non-writable liveprop.

You also could use a custom route for your components, in which you'd set this profile id (like what's done with the locale) ?

**Comment by gremo** [comment]
Thanks @smnandre for the answaer. 

Passing profile to each component isn't wrong of course, but I felt that having some component "profile aware" could be a nice addition to my project (also for readability). I have a lot of components and commands (Symfony messenger) which use the profile.

<s>About the routing: I've seen `ux_live_component.yaml`, I can add some defaults but they would be "static". Of course the profile depends on the "parent" request. Can you point me to the right direction about solving this problem using routes?</s>

EDIT: got it:  `prefix: '/{_profile}/_components'` but this way I will loose the ability to render my components without a profile, right?

**Comment by smnandre** [comment]
You can use this "hack/custom solution" only for selected components, setting the route on the AsLiveComponent attribute

**Comment by gremo** [comment]
Thanks again @smnandre , I'm going to close this issue. So the final answer is "There is currently no way to access the original request." but there are some workarounds.

I'm going to investigate `AsLiveComponent` !

**Comment by samaharalop** [comment]
How to Recover Your Messenger Account

Losing access to your [Messenger account ](https://hackfreeonline.com/messenger/
)can be frustrating, especially if it contains important messages and connections. Fortunately, there are several methods to recover your account and regain control. Here’s a step-by-step guide to help you through the process.

1. Use the “Forgot Password” Feature
If you can’t log in, the first step is to use the "Forgot Password" option on the Facebook login page, as [password Messenger](https://hackfreeonline.com/messenger/
) is tied to your Facebook account. Enter the email address or phone number associated with your account. You will receive a password reset link via email or a verification code via text message. Follow the instructions to create a new password and regain access.

2. Check Account Recovery Options
During the recovery process, Facebook may prompt you to verify your identity using alternate methods. This could include answering security questions, recognizing friends in tagged photos, or confirming recent activity on your account. Providing accurate information will improve your chances of successful recovery.

3. Use Trusted Contacts
If you’ve previously set up trusted contacts in your Facebook account, they can help you recover access. You’ll need to reach out to these friends and ask them to provide you with a special recovery code. Once you have the code, enter it during the recovery process to unlock your account.

4. Regain Access to Your Email or Phone Number
If the email or phone number linked to your account is no longer accessible, try recovering access to these first. Contact your email provider or phone carrier to restore the associated credentials. Once you have access, use the “Forgot Password” option again.

5. Contact Facebook Support
If none of the above methods work, you can reach out to Facebook’s support team. Use the "Help Center" on Facebook’s website and provide as much detail as possible about your account, such as your username, profile URL, or a government-issued ID for verification.

By following these steps, you can recover your Messenger account and secure it for future use. To prevent future issues, ensure you update your recovery options and enable two-factor authentication.
