### ISSUE TITLE
[Icons] HTML different between iconify.design and other websites

### ISSUE THREAD

**Issue by seb-jean** [symfony/ux#1677]
Hi,

Why is SVG on https://icon-sets.iconify.design/lucide/activity-square/ different from https://lucide.dev/icons/square-activity ?

https://icon-sets.iconify.design/lucide/activity-square/:
```html
<svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24"><g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"><rect width="18" height="18" x="3" y="3" rx="2"/><path d="M17 12h-2l-2 5l-2-10l-2 5H7"/></g></svg>
```

https://lucide.dev/icons/square-activity:
```html
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-square-activity"><rect width="18" height="18" x="3" y="3" rx="2"/><path d="M17 12h-2l-2 5-2-10-2 5H7"/></svg>
```

There is the `<g>` tag which is added on https://icon-sets.iconify.design/

**Comment by smnandre** [comment]
Iconify normalize icons, allowing anyone to use icons from different icons sets as if they were from one. 

This group thing did not please me at first, to be honest. But i must admit the possibilities of changing, trying, switching icons from differents sets is worth that normalization step.

And, as usual, if you want / need to use "raw" Lucide icons (as i do on many projects), you just have to download them yourself in the assets/icons directory and everything will work as you expect :)

**Comment by seb-jean** [comment]
Ok thanks ☺️

**Comment by seb-jean** [comment]
Should I close the issue?

**Comment by smnandre** [comment]
@seb-jean only if you got the answers you wanted :)
