### ISSUE TITLE
[Icons] Main documentation : documentation and screencasts links redirect to 404

### ISSUE THREAD

**Issue by MTindev** [symfony/ux#1680]
Hello,

On [UX Icons documentation main page](https://ux.symfony.com/icons), the links _Documentation_ and _Screencasts_ are broken, the both redirect to 404 HTTP code.

### Documentation 

Current link : https://symfony.com/doc/ux.html/.html.html

I guess the expected link should be : https://symfony.com/bundles/ux-icons/current/index.html 

### Screencasts

Current link : https://symfonycasts.com/screencast/symfony-ux

Expected link : is there currently one ?

**Comment by javiereguiluz** [comment]
Thanks for reporting this issue. We're trying to fix this in #1672 and #1673.

**Comment by smnandre** [comment]
Thank you @MTindev  it's now fixed

**Comment by javiereguiluz** [comment]
Closing as fixed. Thanks.

**Comment by MTindev** [comment]
Thanks to both of you
