### ISSUE TITLE
[TwigComponent] PreMount VS required props

### ISSUE THREAD

**Issue by cavasinf** [symfony/ux#1686]
First time using TwigComponent, but works like a charm good job 👍 
I've stumbled upon a case that I can't accomplish without feeling like "it's too much code".

Simple case:
- Required props `title`.
- Pass **Entity** to the props which is `Stringable`.
- Component used like this:
   ```twig
   <twig:DropdownHeaderItem title="{{ app.user }}"/>
   ```

Here's the Component:
```php
// src/Twig/Components/DropdownHeaderItem.php

#[AsTwigComponent]
final class DropdownHeaderItem extends DropdownItem
{
    public string $title;
}
```

And his twig:
```twig
{# templates/components/DropdownHeaderItem.html.twig #}

<h6
        {{ attributes }}
        class="dropdown-header {{ this.extraClass }}" {{ macros.attr_to_html(this.attr) }}
>
    {{ this.title }}
</h6>
```

Sadly, this is not enough to make the `title` option required AND with an explicit error message.
If you call the component with no parameters:
```twig
<twig:DropdownHeaderItem/>
```

This is the error that is displayed:
![image](https://github.com/symfony/ux/assets/25293190/abdb1915-9df3-475b-9c1b-46e51c89cce3)

Two problems:
1. It show the error INSIDE his component template and not where it is used.
2. The stack trace (as usual with twig) doesn't show where the error occured in twig (only controller with `->render()...`)

Looking [at the doc](https://symfony.com/bundles/ux-twig-component/current/index.html#premount-hook), we should use PreMount hook with the OptionsResolver like this:
```php
#[AsTwigComponent]
final class DropdownHeaderItem extends DropdownItem
{
    public string $title;

    #[PreMount]
    public function preMount(array $data): array
    {
        $resolver = new OptionsResolver();
        $resolver->setRequired('title');
        $resolver->setAllowedTypes('title', ['string', \Stringable::class]);

        return $resolver->resolve($data);
    }
}
```

I'm not a fan of that because:
1. Nowadays we can do a lot with only PHP8 (declarations/types/attributes) for simple cases.
    PHP auto `__toString()` call if property typed to `string` when class implements the method.
3. The string reference `'title'` to the property `$title` (maintainability).
4. You need to declare ALL other properties, otherwise you'll get `The option "xxxx" does not exist`
5. All the default value from the PHP declaration, need to be redefined IN the OptionsResolver.
6. +9 lines of code just for a required.

Is there any limitation, to not be able to print required error without the OptionResolver?

**Comment by smnandre** [comment]
Your property is typed string, so even if you allow stringable in the option, it wont be set during mount without some code i think.

What surprises me is that the error is not thrown earlier.

What happens if : 
* you give explicitly a string to the component
* you cast your title during mount 

```php
public function mount(string|\Stringable $title): void
{
      $this->title = (string) $title;
}
```

**Comment by cavasinf** [comment]
> What surprises me is that the error is not thrown earlier.

All of the code above (from my example), doesn't trigger any error though.

An error is thrown if the `title` argument is missing, 
but with a message that is not explicit at all if there is no OptionsResolver

**Comment by smnandre** [comment]
So you suggest to improve the error message, right ?  Or is the "stringable" thing more your point there ? 
i'm asking to be certain to understand the main issue :) 

What would do you suggest the message 'say' ?

**Comment by cavasinf** [comment]
Yes, it's more of a question/improvement than a bug (I should have been more/less specific, sorry).

The main question is:
**Is there any limitation to not be able to define component usage without the OptionResolver (preMount)?**

Can't we define the component configuration from the component property itself? 
Like entity bound to Symfony Form:
- Required (nullable or not)
- Type
- Default value
- Allowed values (perhaps from an enum)
- Visible/Settable (public or private + `Symfony\UX\TwigComponent\Attribute\ExposeInTemplate`)

**Comment by cavasinf** [comment]
For example, what the OptionsResolver tells "more" than the property definition:
```php
#[AsTwigComponent]
final class Alert
{
    public string $message;

    #[PreMount]
    public function preMount(array $data): array
    {
        $resolver = new OptionsResolver();
        $resolver->setIgnoreUndefined();

        $resolver->setRequired('message');
        $resolver->setAllowedTypes('message', 'string');

        return $resolver->resolve($data);
    }
}
```

- Required: because string not nullable and NO default value
- Type: string as defined by the type
- Default value: as defined directly in the PHP property
   ```php
    #[AsTwigComponent]
    final class Alert
    {
        public string $type = 'success';
    
        #[PreMount]
        public function preMount(array $data): array
        {
            $resolver = new OptionsResolver();
            $resolver->setIgnoreUndefined();
    
            $resolver->setDefaults(['type' => 'success']);
    
            return $resolver->resolve($data);
        }
    }
    ```
- Allowed values can be defined through an Enum:
    ```php
    enum ColorEnum: string
    {
        case Primary        = 'primary';
        case Secondary      = 'secondary';
    
        case Success      = 'success';
        case Warning      = 'warning';
        case Danger       = 'danger';
        case Info         = 'info';
    }
    ```
    
    ```php
    #[AsTwigComponent]
    final class Alert
    {
        public ColorEnum $color;
    
        #[PreMount]
        public function preMount(array $data): array
        {
            $resolver = new OptionsResolver();
            $resolver->setIgnoreUndefined();
    
            $resolver->setRequired('color');
            $resolver->setAllowedValues('color', [
                'primary',
                'secondary',
                'success',
                'warning',
                'danger',
            ]);
    
            return $resolver->resolve($data);
        }
    }
    ```

**Comment by smnandre** [comment]
LiveComponent uses validator and constraints ... could we find a way to use it there ? 

What make me doubts regarding the OptionsResolver is that it will not work with LiveComponent and i would like to avoid users needing to have two parralel validation systems ..

**Comment by WebMamba** [comment]
I agree here! With an anonymous component when you set a variable without a default variable, you get an error telling you that this prop is required to use this component. But with a standard class component, you can't make your props mandatory just by not setting a default variable. I think it could be a nice improvement but this is a huge BC break! What we can do in a PR is add an option `strictProps`if this option is set to true we throw an error if a component is used without giving a props with no default value. WDYT?

**Comment by smnandre** [comment]
What if..... we introduce a "Prop" argument ... that could be some "LiveProp" but for TwigComponent ?

That would allow us to add type, constraints, hydration, ...

**Comment by WebMamba** [comment]
Do we really need this argument? What about public props but not with the Prop argument? What do you mean by type?

**Comment by smnandre** [comment]
Just thinking out loud / suggesting something to handle the BC :)

**Comment by cavasinf** [comment]
I haven't tested the LiveComponent, so I don't measure the impact of these changes (but I understand the BC break).

As @WebMamba said, coming from the anonymous component, I was "chocked" by all the changes that I have to do to convert it to a TwigComponent BUT when converting it to a LiveComponent will be maybe easier? 🤔 

The complexity of the TwigComponent is maybe due to the fact that it was made from/for the LiveComponent (with validator, constraints and other).

-----
To handle the BC break:
- `strictProps` is nice and simple, but it means EVERY public property follows these rules without exception.
- The `Prop` argument is more tedious and harder to deprecate, but more "configurable".

If I have to choose, I'll go with `strictProps`. 
Today it will be defaulted to `false`, and in the next major release it will be defaulted to `true`.
We can already deprecate the `strictProps` when using the default value by saying you should explicitly define it to be `false`. 

@WebMamba Have you considered of the impact/conflict with `Symfony\UX\TwigComponent\Attribute\ExposeInTemplate`. Is there any?

**Comment by smnandre** [comment]
Hmm.. really not sure about this.

The prop argument has two advantages:
* beeing easy to migrate into LiveProp one 
* explicitly tag the prop as beeing ... a prop

And that would allow some Validation trait (as in Live component) .. and use real constraint attribute tags (instead or this config resolve that i _personaly_ do not find user friendly at all 

>  coming from the anonymous component, I was "chocked" by all the changes that I have to do to convert it to a TwigComponent 

I would love to have more insights about this !

**Comment by cavasinf** [comment]
As the doc says about LiveProp:
> Most properties will be LiveProps

So in our case, most properties should be Prop?

Why not do the opposite, everything is prop except when you add an attribute or just a `private` declaration?
That is why I liked the `strictProps` proposal, you can set everything with ONE boolean, and handle the BC break + deprecation from one boolean too.

I understand the pain as a bundle developer 😄, but I also see the improvement for developers using Symfony 💨.

As an example of a HUGE improvement in the quality of life for developers, is the mapping ORM for entity.
We've come from:
```php
  #[ManyToOne(targetEntity: Address::class)]
  #[JoinColumn(name: 'address_id', referencedColumnName: 'id')]
  private Address|null $address = null;
```

to:
```php
  #[ManyToOne]
  private ?Address $address = null;
```

**Comment by smnandre** [comment]
Yes... with an attribute 👼

**Comment by smnandre** [comment]
To have a required prop (with no default value) in a component PHP class you can also declare it in the mount() method.

I think i understand what you would like, but i also have to think to all the user / developpers that don't need it, and i don't want to penalize / force them to change their code :)

**Comment by cavasinf** [comment]
> Yes... with an attribute 👼

To define it as "a Prop" or "not a Prop"? 😄 

> can also declare it in the mount() method

Good point, but does that mean you have three "ways" of declaring the default value?

```php
#[AsTwigComponent]
final class Alert
{
    public string $type = 'success'; // <-- Here

    #[PreMount]
    public function preMount(array $data): array
    {
        // ...
        $resolver->setDefaults(['type' => 'danger']); // <-- Here (but shouldn't as you recommended)
        // ...
    }

    public function mount(
       bool $isSuccess, // <-- What about him.
       string $type = 'warning', // <-- Here
     ): void
    {
        $this->type = $isSuccess ? 'success' : 'danger'; // Where $type should be put?
    }
}
```

**Comment by smnandre** [comment]
For me it's pretty clear: if you have a default value, you just need the typed class property.

If you want to throw when missing, the mount method works, but this is where the DX can be improved i agree

We also could just, as i suggest, handle validation attributes, with an optional trait / interface, and that would lead to this

```php
#[AsTwigComponent]
final class Alert  // maybe implement ValidatorInterface or something
{
    // use ValidationTrait;

   #[Assert\Choice(['success', 'danger'])]
    public string $type = 'success'; // <-- Here
    
    #[Assert\NotBlank]
    public bool $enabled;
}
```


But saying "all public props are to be required" is a massive massive break, and again i'd like to keep the path easy between Twig and Live component :)

**Comment by cavasinf** [comment]
> But saying "all public props are to be required" is a massive massive break, and again i'd like to keep the path easy between Twig and Live component :)

Agreed

> i don't want to penalize / force them to change their code :)

I don't think `change code` is the right word but `simplify code` is the "goal".

> what you would like

(no offense ❤️) I think I would like what Symfony "taught me" about how to magically use Symfony.
Example, 70% of our Symfony projects are `Entity` <=> `Form`, and it is so easy to create a Form bounded to an entity just through an entity declaration thanks to the [Form Guessing](https://symfony.com/doc/current/forms.html#form-type-guessing). I think it is the most "magical" part of Symfony (after the DI 😄).

```php
class Task
{
    public string $task;

    public ?\DateTimeInterface $dueDate;
}
```

```php
class TaskType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('task')
            ->add('dueDate')
            // OR
            ->add('dueDate', null, ['required' => false])
        ;
    }
}
```

In the end, I "would like" the TwigComponent to be as magical (simple 😉) as the Form entity.
And it is already the case with anonymous component 👍

**Comment by smnandre** [comment]
I understand, and i'm trying to find some idea to fullfill your needs, but again, they are not "everyone's need" so i'm trying to find some balance here :)

On your form example you explicitely add 'dueDate' for instance, it's not magical :) That is why i think the equivalent here would be an attribute !

```php
class TaskComponent
{
     #[Prop]
     public string $task;
}
```

or 

```php
class TaskComponent
{
     public function mount(string $task) // ... 
}
```

Regarding public props, there is something we could do as "exposePublicProps" is true per default already... so maybe after all the mounts and just before rendering, there could be a check to see if they are defined and throw some Runtime exception if they are not.

**Comment by cavasinf** [comment]
Okay, I get it, and I am starting to like it!

> instead or this config resolve that i personaly do not find user friendly at all

Couldn't agree more 😭

Something like this is good for you?
```php
#[AsTwigComponent]
class Alert
{
    #[Prop]
    public string $title = "Uh oh, something went wrong";

    #[Prop]
    public string $message; // <-- This trigger required error? or should it be in the mount() function?

    #[Prop]
    #[ExposeInTemplate('alert_type')]
    public string $type = 'danger'; 

    #[Prop] // <-- I don't think it is a good idea to be able to do that on a private
    #[ExposeInTemplate(name: 'ico', getter: 'fetchIcon')]
    private string $icon = 'ico-warning';

    private ProductRepository $productRepository;

    public function __construct(ProductRepository $productRepository)
    {
        $this->productRepository = $productRepository;
    }

    public function mount(
       // string $message, // Depend on above question
       bool $isSuccess = false,
    ): void
    {
        $this->type = $isSuccess ? 'success' : $this->type;
    }

    /**
     * Required to access $this->icon
     */
    public function fetchIcon(): string
    {
        return $this->icon;
    }

    public function getProducts(): array
    {
        return $this->productRepository->findFeatured();
    }
}
```

I am just wondering what would be the outcome of such a thing:
```php
#[AsTwigComponent]
class Alert
{
    #[Prop]
    public string $message = "default message";

    public function mount(
       string $message = "mount default message",
    ): void
    {
    }
}
```

**Comment by smnandre** [comment]
> I am just wondering what would be the outcome of such a thing

Not sure to understand, if you do not set $message, it will keep its default value. Would you expect anything else ?

**Comment by smnandre** [comment]
```
    #[Prop]
    public string $title = "Uh oh, something went wrong";

    #[Prop]
    public string $message; // <-- This trigger required error? or should it be in the mount() function?

    #[Prop]
    #[ExposeInTemplate('alert_type')]
    public string $type = 'danger'; 

    #[Prop] // <-- I don't think it is a good idea to be able to do that on a private
    #[ExposeInTemplate(name: 'ico', getter: 'fetchIcon')]
    private string $icon = 'ico-warning';
 ```
 
On this example, the only "problem" is with the uninitialized typed property (that won't be passed to the front-end ... because it has no value).
 
I'm really not sure this is a problem _per se_, but there is something we could do easily on the DX (as long as "exposePublicProps" is true)

When we extract those values to pass them to the template (via _get_object_vars_ we could simply compare the keys to get_class_vars)

```php
<?php

class Foo {
    
    public string $foo = 'title';
    
    public string $bar;
    
}

$foo = new Foo();

var_dump($objectVars = get_object_vars($foo));

var_dump($classVars = get_class_vars($foo::class));

var_dump(array_diff_key($classVars, $objectVars));
```
https://3v4l.org/YBbdW

And then trigger a deprecation / exception ? 

That could be done with no BC break and solve the "unitialized" problem, with no need to change anything to anyone, and keep the usage simple and clean.

WDYT ?

**Comment by cavasinf** [comment]
Why are you still up at 3AM 😭 

-----------

> Not sure to understand, if you do not set $message, it will keep its default value. Would you expect anything else ?

From the doc mount:
> If a prop name (e.g. isSuccess) matches an argument name in mount(), the prop will be passed as that argument and the component system will not try to set it directly on a property or use it for the component attributes.

So, having two times `$message`, the prop will be passed to the `mount` by priority, 
but if there's no `message` prop like so `<twig:Alert />`, what will happen?

1. If mount has default value (like the example) will the $message property will be set with the mount default value.
    ```php
    #[AsTwigComponent]
    class Alert
    {
        #[Prop]
        public string $message = "default message";
    
        public function mount(
           string $message = "mount default message", // <-- This will be the real default value?
        ): void
        {
            // ...
        }
    }
    ```
2. How will this handle the required prop?
   i. 
   ```php
    #[AsTwigComponent]
    class Alert
    {
        #[Prop]
        public string $message; // <- No default value = Required
    
        public function mount(
           string $message = "default mount message", // <-- Has default value = Not Required anymore?
        ): void
        {
           $this->message = $message; // <- Mount default value
        }
    }
    ```
   ii. 
   ```php
    #[AsTwigComponent]
    class Alert
    {
        #[Prop]
        public string $message = "default message";
    
        public function mount(
           string $message,  // <- No default value = Required? Error?
        ): void
        {
        }
    }
    ```
-----------

> That could be done with no BC break and solve the "unitialized" problem, with no need to change anything to anyone, and keep the usage simple and clean.
> 
> WDYT ?

That sounds like a good solution to me!  :+1:

**Comment by WebMamba** [comment]
I think if we go with the #[Prop] attribute, we should deprecate the #[ExposeInTemplate] attribute.
The #[Prop] attribute gonna have the same behaviors than the #[ExposeInTemplate] and the validation process. Why? Because I think in regard to what we did with with anonymous component an exposed property is a props. And we should not separate those two notions.

Regarding your 3 examples, I think the validation that the props with no default value are not empty should be done before the mount method. So the error is triggered even before the component is mounted. WDYT ?

**Comment by cavasinf** [comment]
> The #[Prop] attribute gonna have the same behaviors than the #[ExposeInTemplate]

Is `ExposeInTemplate` available in LiveComponent? The doc says nothing about it.
If not, OK 👍 

> So the error is triggered even before the component is mounted.

I'm OK with that, BUT `PreMount` should ignore this validation since they can add or remove props from there.

**Comment by WebMamba** [comment]
> Is ExposeInTemplate available in LiveComponent? The doc says nothing about it.
If not, OK 👍

Yes, everything that is available in TwigComponent is available in LiveComponent.

> I'm OK with that, BUT PreMount should ignore this validation since they can add or remove props from there.

Sound good to me!

**Comment by kbond** [comment]
I'd prefer not to replace `ExposeInTemplate` with `Prop` unless it's going to be doing more than exposing the property in the template.

**Comment by smnandre** [comment]
So

```php

#[AsTwigComponent('FooBar')]
class FooBar
{
    public string $message;
}
```

would throw

> Error rendering "FooBar" component: Cannot expose uninitialized property "$message" from "App\Twig\Components\FooBar".

and 

```php

#[AsTwigComponent('FooBar')]
class FooBar
{
    public string $message;

    public function mount(string $message = 'toto')
    {
        $this->message = $message;
    }
}
```

is all good.


Everyone ok ? Should it be a deprecation or an exception ? I'm tempted to say exception because well... you cannot expose uninitialized properties. 



We'd just need those lines in ComponentRenderer.php

```php
    private function exposedVariables(object $component, bool $exposePublicProps): \Iterator
    {
        if ($exposePublicProps) {
            $publicProps = get_object_vars($component);
            if ($uninitializedProps = array_diff_key(get_class_vars($component::class), $publicProps)) {
                throw new \LogicException(sprintf('Cannot expose uninitialized property "$%s" from "%s".', array_keys($uninitializedProps)[0], $component::class));
            }
            yield from $publicProps;
        }
```

**Comment by cavasinf** [comment]
What would happen if:
```php
#[AsTwigComponent('FooBar')]
class FooBar
{
    public string $message;

    public function mount(string $message) // <- No default value
    {
        $this->message = $message;
    }
}
```

And used like this: `<twig:FooBar />`

**Comment by smnandre** [comment]
That would throw an Exception no ?

**Comment by cavasinf** [comment]
I'm afraid that will throw an exception FROM the component and not WHERE the component is **wrongly** used (as the screenshot on the first issue message).
It is a dev/user error, or it will look like a "component error".

**Comment by smnandre** [comment]
It won't be the same exception as you showed, because $message is not initialized so the new exception will be thrown
