### ISSUE TITLE
[ChartJS] Possibility to make Gauge with ChartJS

### ISSUE THREAD

**Issue by Erwanou77** [symfony/ux#1697]
Hello everyone, how are you?
Tell me, is it possible to make a gauge with a needle in ChartJS?
If so, can someone give me an example please?
And of course with ux-chartjs !
Thanks in advance friends !

**Comment by smnandre** [comment]
There seem to be all you need in the Chart.js doc 
* https://www.chartjs.org/docs/latest/charts/doughnut.html

If then you have a specific issue with UX Chartjs, feel free to reopen this issue :) 

Happy coding!

**Comment by ag-erwan** [comment]
Yes, I had seen this documentation, but I can make the gauge graph, but I cannot make the needle.

```
$chart->setData([
    'labels' => ['1', '2'],
    'datasets' => [
        [
            'data' => [75,25],
            'backgroundColor' => [
                '#36A2EB',
                '#DDDDDD'
            ],
            'circumference' => 180,
            'rotation' => 270,
            'cutoutPercentage' => 85,
        ],
    ],
]);
```

**Comment by ag-erwan** [comment]
![image](https://github.com/symfony/ux/assets/147044961/05b109d7-87b9-498d-bc8b-df57c2255c2d)

@smnandre I would like where there is the red square and the red arrow, a needle instead

**Comment by smnandre** [comment]
I think you'll get more answers asking this on the ChartJS repository : https://github.com/chartjs ;)
