### ISSUE TITLE
Request for renovatebot Support for @symfony/ux-* Packages

### ISSUE THREAD

**Issue by Lappihuan** [symfony/ux#1712]
I've encountered an issue with the package.json configuration in the @symfony/ux-vue package, affecting integration with renovatebot. The devDependency setup for @symfony/ux-vue uses a local file path reference to the vendor directory which is outside the scope of npm:

`"@symfony/ux-vue": "file:../vendor/symfony/ux-vue/assets"`

This configuration is incompatible with renovatebot's operational model, as it does not conceptualize performing a composer install before npm install. The local file path reference prevents renovatebot from updating dependencies in a straightforward manner, which is crucial for projects that rely on automated dependency management.

Suggested Solution

Adjusting the package distribution to be more compatible with dependency management bots like renovatebot could alleviate this issue. For example, publishing the package to npm or referencing a versioned package in package.json could make the Symfony UX components more accessible and manageable for projects utilizing renovatebot.

**Comment by smnandre** [comment]
Hi @Lappihuan !

This file system is at the heart of SymfonyUX, when used with webpack : https://symfony.com/bundles/StimulusBundle/current/index.html#how-are-the-stimulus-controllers-loaded

New projects tend to use AssetMapper, where no packages.json is even necessary.

So i don't think we can change this way of referencing packages.. but if you find something that could be implemented we'd be happy to include it in the codebase (maybe with npm settings concerning the scope or renovate tuning ?)

**Comment by Kocal** [comment]
Hey! Someone just send me this issue, but since some weeks, assets are now available on npm -> https://www.npmjs.com/search?q=%40symfony%2Fux-

It's for the moment an "hidden feature", we are waiting the 2.24 to announce it, but packages are downloadable (for power-users only) :)
