### ISSUE TITLE
[Icons] Icons with 2 (alias) names are not found

### ISSUE THREAD

**Issue by alexz707** [symfony/ux#1721]
I have searched via https://ux.symfony.com/icons?query=x&set=flowbite and found the "X" Icon.

According to the site it should be named:  `flowbite:x-outline`

`<twig:ux:icon name="flowbite:x-outline" />`

If it is used in twig it will throw an error that the icon is not found.

The reason behind it is that it expects the Iconify response to include that name in the array:

Iconify.php L64
```PHP
if (!isset($data['icons'][$name]['body']))
```

In my case it finds the right icon but the name included in the array is `close-outline` and not `x-outline`.

So it complains: `Error rendering "UX:Icon" component: Icon "flowbite:x-outline" not found.`

﻿﻿﻿regards Alex

**Comment by kbond** [comment]
Thanks for reporting this Alex!

For reference: https://api.iconify.design/flowbite.json?icons=x-outline

Looks like we need to check the `aliases` before throwing the exception. I'll work on a fix shortly. Or @alexz707, up for a PR?
