### ISSUE TITLE
Unused images

### ISSUE THREAD

**Issue by seb-jean** [symfony/ux#1733]
The images below were added in the PR https://github.com/symfony/ux/pull/1707 but do not appear to be used:

- https://github.com/symfony/ux/blob/2.x/ux.symfony.com/assets/images/symfony-ux.svg
- https://github.com/symfony/ux/blob/2.x/ux.symfony.com/assets/images/symfony-ux.webp

**Comment by smnandre** [comment]
Hi @seb-jean ! This is a bad habit i have to push things a bit before i use them ... and something @kbond must be really tired of telling me haha 

But on this one, i'd ask for an exception. I really will use them really soon, and as i made the 3 images at once I admit I take a shortcut and pushed them at once ..... 

... could we close our eyes on this for once  ? 🐱 👼 

(no problem to remove it if you think it's better / not making exceptions, i could 100% get this)

**Comment by seb-jean** [comment]
I make an exception!!! 😄

**Comment by seb-jean** [comment]
Do you want me to close the ticket or should I keep it for now? :)

**Comment by smnandre** [comment]
We can close it then ;)
