### ISSUE TITLE
Assets that do not use AssetMapper

### ISSUE THREAD

**Issue by seb-jean** [symfony/ux#1736]
The assets below do not use the [AssetMapper component](https://symfony.com/doc/current/frontend/asset_mapper.html). Do you think it should be done?

- https://github.com/symfony/ux/blob/2.x/ux.symfony.com/public/android-chrome-192x192.png
- https://github.com/symfony/ux/blob/2.x/ux.symfony.com/public/android-chrome-512x512.png
- https://github.com/symfony/ux/blob/2.x/ux.symfony.com/public/apple-touch-icon.png
- https://github.com/symfony/ux/blob/2.x/ux.symfony.com/public/favicon.ico
- https://github.com/symfony/ux/blob/2.x/ux.symfony.com/public/favicon.svg
- https://github.com/symfony/ux/blob/2.x/ux.symfony.com/public/site.webmanifest

**Comment by smnandre** [comment]
Nope, as we want to keep those exact file names, and AssetMapper hash suffixes cannot be disabled

**Comment by seb-jean** [comment]
Thanks Simon!
