### ISSUE TITLE
[Site] Infinite Scroll - Remove wrapper

### ISSUE THREAD

**Issue by seb-jean** [symfony/ux#1748]
Hi,
I would like to know if there is a possibility to avoid having the element having the `ProductGrid_page` wrapper class for each page on demo https://ux.symfony.com/demos/live-component/infinite-scroll?

Currently it is like this:
![Capture](https://github.com/symfony/ux/assets/12116264/2961211a-3fde-4f71-8d1f-0fb338bfaa76)

The idea would be to have this:

![Capture1](https://github.com/symfony/ux/assets/12116264/72e162b0-b099-48d9-85da-e348553c5b1e)

Would it be possible to have the `<articles>` directly?

Thanks :)

**Comment by smnandre** [comment]
It can be done, but only with some DOM manipulation.

That was my first attempt earlier this year... 

Let's say you're rendreding "page 2" 

```
<div # results>
</div>
<div #page1></div>
<div #page2 class="current">
    {% for ... in results %} .... {% endfor } %}
</div>
```

In JS just before the render you can select all items from the current page (so, just before page2 it's still page1 in the DOm) and move them to the #result div.

But i wanted something that would require no "manipulation" for maximal browser performance / no CLS. 

All this obviously only based on what i tried... there are probably a lot of other solutions (and i'd be really interested to ear about them and update the demo :) )

**Comment by seb-jean** [comment]
There is this video made with Laravel Livewire:
https://www.youtube.com/watch?app=desktop&v=B6TtWdA7uS0

There is also this article: https://apexcode.dev/blog/infinite-scroll-with-laravel-and-livewire, with a demo: https://play.apexcode.dev/blog

If that helps :)

**Comment by smnandre** [comment]
Do you want to try a PR ?

**Comment by seb-jean** [comment]
I have no idea how I could improve this.

**Comment by smnandre** [comment]
I found something!  I'll use/show it for the part 2/2  :)

**Comment by seb-jean** [comment]
Super-Simon 🦸‍♂️ !

**Comment by smnandre** [comment]
Thanks @seb-jean, this one is for you  ;) https://github.com/symfony/ux/pull/1887

**Comment by seb-jean** [comment]
Thanks @smnandre, this emoji is for you: :ok_hand:
