### ISSUE TITLE
[TwigComponent] Translation domain not passed to component content when defined in template

### ISSUE THREAD

**Issue by ker0x** [symfony/ux#1749]
It seems that when the translation domain is defined at the template level using the `{% trans_default_domain domain %}` tag, the domain is not passed to the `trans` filter when the translation string is passed as component content

Example:

```twig
{% trans_default_domain 'emails' %}

{% block body %}
    <twig:Email:Paragraph>{{ 'customer.welcome.body.p_1'|trans }}</twig:Email:Paragraph>
    <twig:Email:Paragraph>{{ 'customer.welcome.body.p_2'|trans }}</twig:Email:Paragraph>
{% endblock %}
```

Output:

```html
    <p>customer.welcome.body.p_1</p>
    <p>customer.welcome.body.p_2</p>
```

Expected:

```html
    <p>Customer welcome paragraph 1</p>
    <p>Customer welcome paragraph 2</p>
```

For now, to fix the bug, I have to specify the domain directly in the `trans` filter:

```twig
{% block body %}
    <twig:Email:Paragraph>{{ 'customer.welcome.body.p_1'|trans({}, 'emails') }}</twig:Email:Paragraph>
    <twig:Email:Paragraph>{{ 'customer.welcome.body.p_2'|trans({}, 'emails') }}</twig:Email:Paragraph>
{% endblock %}
```

Also, adding `{% trans_default_domain domain %}` directly inside the component template doesn't work!

**Comment by smnandre** [comment]
Internally, embeded content in Twig Component are similar to the embed tag : they work as isolated block. So you should define the trans_default_domain in the content you set to make it work (i think)

**Comment by smnandre** [comment]
I can confirm it's working as expected.. (or let's say as [documented](https://symfony.com/doc/current/translation.html#using-twig-filters))

> Note that this only influences the current template, not any "included" template (in order to avoid side effects).

TwigComponent are some sort of include/embed so we're in that case.

So you have indeed two choices for your example: 
* using `|trans({}, 'emails')`
* adding a trans_default_domain in the component content block, but for one sentence there is probably no added value

**Comment by ker0x** [comment]
Thank you @smnandre for looking into it!

I'm closing the issue as it is the expected behavior!
