### ISSUE TITLE
Cannot use attributes.

### ISSUE THREAD

**Issue by seb-jean** [symfony/ux#1758]
Hi,

I wanted to use the `CurrentUser` attribute but for a function which is used to return a result. I have the error below:

`An exception has been thrown during the rendering of a template ("Too few arguments to function App\Twig\Components\PostList::getPosts(), 0 passed in ...\vendor\twig\twig\src\Extension\CoreExtension.php on line 1635 and exactly 1 expected").`

In the file below, it was used for a function and it works.

https://github.com/symfony/ux/blob/2.x/src/LiveComponent/tests/Fixtures/Component/WithSecurity.php#L33

Here is my component:

```php
<?php

namespace App\Twig\Components;

use App\Entity\User;
use App\Repository\PostRepository;
use Symfony\UX\LiveComponent\Attribute\AsLiveComponent;
use Symfony\UX\LiveComponent\Attribute\LiveAction;
use Symfony\UX\LiveComponent\Attribute\LiveProp;
use Symfony\UX\LiveComponent\ComponentToolsTrait;
use Symfony\UX\LiveComponent\DefaultActionTrait;
use Symfony\Component\Security\Http\Attribute\CurrentUser;

#[AsLiveComponent]
final class PostList
{
    use ComponentToolsTrait;
    use DefaultActionTrait;

    public function __construct(
        private readonly PostRepository $postRepository
    ) {
    }

    public function getPosts(#[CurrentUser] User $user): array
    {
        return $this->postRepository->findLatestByUser($user);
    }
}
```

```twig
<div>
  {% for post in this.posts %}
      <div>
      
      </div>
  {% endfor %}
</div>
```

**Comment by Erwanou77** [comment]
Hi @seb-jean ,

So, I just saw your problem, from what I see, you forgot to add the {{ attributes }} attribute in your div.

Moreover, to pass the logged in user, you need to extend the AbstractController class.

Finally, to avoid using the 'this' keyword in twig, you can use #[ExposeInTemplate]

Here is an example of code that I think meets your request:

```php
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\UX\TwigComponent\Attribute\ExposeInTemplate;

#[AsLiveComponent]
final class PostList extends AbstractController
{
    use DefaultActionTrait;

    public function __construct(
        private readonly PostRepository $postRepository
    ) {
    }

    #[ExposeInTemplate]
    public function getPosts(): array
    {
        return $this->postRepository->findLatestByUser($this->getUser());
    }
}
```

```twig
<div{{ attributes }}>
  {% for post in posts %}
      <div>
      
      </div>
  {% endfor %}
</div>
```

I hope this answered your question, I wish you an excellent evening, happy coding ;)

**Comment by smnandre** [comment]
> Hi,
> 
> I wanted to use the `CurrentUser` attribute but for a function which is used to return a result. I have the error below:
> 
> `An exception has been thrown during the rendering of a template ("Too few arguments to function App\Twig\Components\PostList::getPosts(), 0 passed in ...\vendor\twig\twig\src\Extension\CoreExtension.php on line 1635 and exactly 1 expected").`
> 
> In the file below, it was used for a function and it works.
> 
> https://github.com/symfony/ux/blob/2.x/src/LiveComponent/tests/Fixtures/Component/WithSecurity.php#L33
> 
> Here is my component:
> 
> ```
> <?php
> 
> namespace App\Twig\Components;
> 
> use App\Entity\User;
> use App\Repository\PostRepository;
> use Symfony\UX\LiveComponent\Attribute\AsLiveComponent;
> use Symfony\UX\LiveComponent\Attribute\LiveAction;
> use Symfony\UX\LiveComponent\Attribute\LiveProp;
> use Symfony\UX\LiveComponent\ComponentToolsTrait;
> use Symfony\UX\LiveComponent\DefaultActionTrait;
> use Symfony\Component\Security\Http\Attribute\CurrentUser;
> 
> #[AsLiveComponent]
> final class PostList
> {
>     use ComponentToolsTrait;
>     use DefaultActionTrait;
> 
>     public function __construct(
>         private readonly PostRepository $postRepository
>     ) {
>     }
> 
>     public function getPosts(#[CurrentUser] User $user): array
>     {
>         return $this->postRepository->findLatestByUser($user);
>     }
> }
> ```
> 
> ```
> <div>
>   {% for post in this.posts %}
>       <div>
>       
>       </div>
>   {% endfor %}
> </div>
> ```

You cannot use CurrentUser ValueResolver if you don't set your method as LiveAction or Controller method

**Comment by seb-jean** [comment]
@smnandre I imagine it's the same for `MapEntity?`

**Comment by Erwanou77** [comment]
> use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
> use Symfony\UX\TwigComponent\Attribute\ExposeInTemplate;
> 
> #[AsLiveComponent]
> final class PostList extends AbstractController
> {
>     use DefaultActionTrait;
> 
>     public function __construct(
>         private readonly PostRepository $postRepository
>     ) {
>     }
> 
>     #[ExposeInTemplate]
>     public function getPosts(): array
>     {
>         return $this->postRepository->findLatestByUser($this->getUser());
>     }
> }

With this code, isn't that what you're looking for @seb-jean ?

**Comment by seb-jean** [comment]
Yes, but it would be interesting to take advantages of PHP attributes.

**Comment by smnandre** [comment]
@seb-jean We are not doing more (or less) that standard Symfony controllers here :) 

In a LiveAction, attributes are used for argument dependency injection, but your getPosts() method is "just" a standard method, so there is no way to intercept any call made by .. anyone there :) 

In your specific case, i think you should inject your user in the constructor (the Security helper to be precise)

--

Pure curiosity, why/how is your component Live ? You don't have any live prop / action there, is there a reason to not use TwigComponent ?

**Comment by seb-jean** [comment]
> Pure curiosity, why/how is your component Live ? You don't have any live prop / action there, is there a reason to not use TwigComponent ?

@smnandre I haven't put the whole PHP file but I'm going to use the Infinite Scroll (https://ux.symfony.com/demos/live-component/infinite-scroll) dynamically with repositories.

**Comment by smnandre** [comment]
You could also pass the user ID from the calling template i guess ?

**Comment by seb-jean** [comment]
Sorry I do not understand what you mean.

**Comment by smnandre** [comment]
Let's say you have a page "dashboard" where a User can see its last Posts.

On the dashboard.html.twig

**Comment by smnandre** [comment]
```twig
<twig:LastPosts userId={{ app.user.id }} />
```

Then you use userId as a prop of your component (it will be mounted with the current user id) and you can display its posts

**Comment by seb-jean** [comment]
Yes, it's interesting :)
