### ISSUE TITLE
[TwigComponent] composer install fails in combination with twig/twig:3.9.X

### ISSUE THREAD

**Issue by beephotography** [symfony/ux#1764]
Hi,

renovate just wanted to update the version of `twig/twig` package but this caused an error with `ux-twig-component`:

`Problem 1
    - Root composer.json requires symfony/ux-twig-component 2.16.0 -> satisfiable by symfony/ux-twig-component[v2.16.0].
    - symfony/ux-twig-component v2.16.0 requires twig/twig ~3.8.0 -> found twig/twig[v3.8.0] but it conflicts with your root composer.json require (3.9.3).
`

Can anybody tell me when the next release will be out so that we are able to upgrade the twig-package?

**Comment by smnandre** [comment]
You can expect a release later this week ! 

And if you want to try / beta-test it, the 2.x-dev supports Twig 3.9 

* https://github.com/symfony/ux/pull/1753
* https://github.com/symfony/ux/pull/1487
* https://github.com/symfony/ux/pull/1397

**Comment by beephotography** [comment]
@smnandre thank you for rocket-fast answer, mate 👍
