### ISSUE TITLE
[Icons] Alias for icons

### ISSUE THREAD

**Issue by Xbirdfr** [symfony/ux#1767]
Hi !

I love the icon initiative, a very great ressource !

i'm comming with an idea, a thing that actually I use a lot in my custom projects: 

an alias system for icons
Ex: 

```
# config/packages/ux_icons.yaml
ux_icons:
    alias:
      - "home": "material-symbols:home"
```

```
# templates/base.html.twig
...
<a href="#">{{ ux_icon('home') }} Homepage </a>
...
```
this will ensure consistency of the icon throughout the project, and to be able to easily change / update it in one go

Or maybe a way to create a custom twig extension extending ux_icons already exist ?

**Comment by kbond** [comment]
Hey @Xbirdfr, thanks for the idea! This is a bit similar to https://github.com/symfony/ux/pull/1596 where we've been discussing multiple icon registries and aliasing. That issue is more about including multiple directories of icons.

What you're thinking is using `ux_icon('home')` would lazy load (on-demand) `material-symbols:home`?

**Comment by Xbirdfr** [comment]
Hi @kbond ,

not necessarily this particular icon, but rather an alias:icon format

like today I want my alias "home" to refer to "material-symbols:home",
but tomorrow, I think the "solar:home-outline" will better fit my app, so I juste change the alias from :
```
# config/packages/ux_icons.yaml
ux_icons:
    alias:
      - "home": "material-symbols:home"
```

to

```
# config/packages/ux_icons.yaml
ux_icons:
    alias:
      - "home": "solar:home-outlinee"
```

refresh the cache and voila

**Comment by Kocal** [comment]
What about using symbolic links instead? `assets/icons/home.svg` can refers to `assets/icons/solar/home-outline.svg`

**Comment by kbond** [comment]
> What about using symbolinks instead?

That could work today for sure.

**Comment by Xbirdfr** [comment]
> What about using symbolinks instead? `assets/icons/home.svg` can refers to `assets/icons/solar/home-outline.svg`

Yes, nice solution 👌

But I think a file based / config based way will ne more stable

**Comment by smnandre** [comment]
> But I think a file based / config based way will ne more stable

We will add several configuration parameters and "namespace aliases" are one of my top priorities, as all icon sets are not equal currently on a DX perspective (typing `bi:heart` VS `material-icon-foo-bar:heart` is not _fair_)

We've been very busy with support / minor bugs / documentation recently but we're going to work on Icon very very soon :)

**Comment by kbond** [comment]
I think having aliases in config is valid. From a technical standpoint, we can decorate the current icon registry service with an `AliasIconRegistry` (that read the config).

As Simon said, we are going to be doing some work multiple icon sets/namespaces so let's keep this issue open as something to add after that.

**Comment by Xbirdfr** [comment]
I will keep an eye on that, and if I can propose a pr, I will 👌

**Comment by smnandre** [comment]
> . From a technical standpoint, we can decorate the current icon registry service with an `AliasIconRegistry` (that read the config).

I'm not sure this will be necessary... i think we can resolve in the renderer 

(and this is precisely why i'd like to add "name" and "set/namespace" in the Icon object..)

**Comment by Xbirdfr** [comment]
While the next version of ux/icons is not published, I wrote this gist which nearly do what I intend :

https://gist.github.com/Xbirdfr/973640403b71b6abff61796c9238c266

**Comment by Xbirdfr** [comment]
I created a  [bundle](https://github.com/Xbirdfr/ux-icons-alias-bundle) that corresponds to what I want, thanks to release 2.19. 

I am closing this issue because this release responded to the request. Thanks to all of you !
