### ISSUE TITLE
[LazyImage] Usage of `file_get_contents` for external images

### ISSUE THREAD

**Issue by Kocal** [symfony/ux#1773]
Hi everyone,

This is more of an RFC/question regarding LazyImage and file_get_contents.

I haven't yet attempted to use `data_uri_thumbnail('https://...')` with an external image (let's say https://symfony.com/doc/6.2fr//the-fast-track/_images/infrastructure.png), but I assume it should work, leveraging [file_get_contents](https://github.com/symfony/ux/blob/83f3e2f/src/LazyImage/src/BlurHash/BlurHash.php#L96).

However, here lies the issue: I'm not particularly fond of using`file_get_contents` for downloading resources over HTTP. Even if we can use it, we're limited in configuring any options (e.g., proxy, authentication, timeout...).

I have two suggestions at the moment:

1. Add support for PSR-7 and PSR-18. Inject a `Psr\Http\Client\ClientInterface` instance, and if we detect that $filename starts with https?://, we utilize the client to download the file.
2. Alternatively, create an abstraction over `file_get_contents`, with an interface and a default implementation using`file_get_contents`. End-users can then use their own implementation, making it easier for us to implement and maintain on our side.

WDYT? Thanks!

**Comment by Kocal** [comment]
Note that it can fixes #174 and #342

**Comment by kbond** [comment]
> Alternatively, create an abstraction over file_get_contents

This feels like the best approach for now. I can imagine someone wanting to use flysystem too.

**Comment by nicolas-grekas** [comment]
just a closure would be fine

**Comment by Kocal** [comment]
Closures again... :eyes:

Joke aside, you're right, closure would be enough, but is this easily do-able with Symfony 5.4? https://github.com/symfony/ux/blob/2.x/src/LazyImage/composer.json#L34

EDIT: got it https://github.com/symfony/symfony/pull/45878
