### ISSUE TITLE
UX Icons > carbon:area-custom > Undefined array key "url"

### ISSUE THREAD

**Issue by BigBenJr** [symfony/ux#1785]
When I do

`symfony console ux:icons:import carbon:area-custom`

I get

```
  [ErrorException]                    
  Warning: Undefined array key "url" 
```

It's not really a big problem as the svg is correctly downloaded in my /assets/icons/ folder, but I prefer notice this error here.

**Comment by smnandre** [comment]
Thank you for the report, i'll fix this as soon as i find some time :) 

Probably something like that to add, but as this URL is used as different place, i really start to think we should have an object there @kbond (IconSet)

```diff
// ... ImportIconCommand.php

$license = $this->iconify->metadataFor($prefix)['license'];
+ if (isset($license['spdx'])) {
+   $license['url'] ??= sprintf('https://spdx.org/licenses/%s.html', $license['spdx']);
+ }
```
