### ISSUE TITLE
[LiveComponent] change other values via `onUpdated` hook

### ISSUE THREAD

**Issue by norkunas** [symfony/ux#1788]
I have a search component with this definition:

```
    #[LiveProp(writable: true, url: true)]
    public string $query = '';

    /**
     * @var int<1, max>
     */
    #[LiveProp(writable: true, url: true)]
    public int $page = 1;
```

The problem is if you are on other page than 1, changed query could result in pagination showing non-existing page.
I tried to add `onUpdated: 'onQueryChange'` to `$query #[LiveProp]` to reset to page 1, but it still stays on the previous page..

**Comment by smnandre** [comment]
I've used the postHydrate for this on several occasions

**Comment by norkunas** [comment]
How do you know in postHydrate when a specific model has changed?

**Comment by smnandre** [comment]
The "onUpdated"' is called after the hydration, that's why.. you need to listen to mount or hydrate hooks

**Comment by norkunas** [comment]
You mean something like:
```php
    #[LiveProp(writable: true, url: true, hydrateWith: 'hydrateQuery')]
    public string $query = '';

    public function hydrateQuery($value)
    {
        $this->page = 1;
        return $query;
    }
```
?

**Comment by smnandre** [comment]
I've done this but my props were not writable indeed. 

I'm trying to do something with the demo i'm working on, i'll answer tonight.

In all manner, we do need to improve this DX. I need to get a better vision off all the use cases (and i'm open to suggestions on this)

**Comment by smnandre** [comment]
It is really interesting, as some behaviour are working or not depending on other attributes, and that should not be the case (in DX side i mean).

**Comment by norkunas** [comment]
Would be good to have a hook, that we could modify component state based on the some prop value..

**Comment by smnandre** [comment]
```php
#[LiveProp(writable: true, url: true)]
    public string $query = '';

/**
 * @var int<1, max>
 */
#[LiveProp(writable: true, url: true)]
public int $page = 1;
```

is this really your original usage (for this issue i mean) ? If "yes" you probably could use an action instead of an event and trigger there your changes

**Comment by norkunas** [comment]
Yes, this is an original usage excerpt. there is also an additional `$type` prop as determinator which api endpoint to call and in UI you can change them via live action.

> you probably could use an action instead of an event and trigger there your changes

you mean setting `data-action="live#action"` on the `$query` input to call custom action?

**Comment by smnandre** [comment]
That may be enough no ?

**Comment by norkunas** [comment]
ok, this solves the problem for me, thanks :)

**Comment by smnandre** [comment]
The hook idea is really to consider .. don't know when i have the time, but seens the number of people wanting the same thing.... ;)
