### ISSUE TITLE
[LiveComponent] Module not found: "./assets/bootstrap.js" contains a reference to the file "@symfony/ux-live-component".

### ISSUE THREAD

**Issue by johanv** [symfony/ux#179]
Today I updated my app to Symfony 5.3.11, and I also updated symfony/ux-live-compoment (currently at revision e382fc0). Doing this triggered this error in my [ci/cd pipeline](https://gitlab.com/rva-vzw/dikdikdik/-/jobs/1834275431) when running `yarn encore dev`:
```
Module build failed: Module not found:
"./assets/bootstrap.js" contains a reference to the file "@symfony/ux-live-component".
This file can not be found, please check it for typos or update it if the file got moved.
```

I am not very good at frontend technology, but I managed to work around this problem by [changing the line](https://gitlab.com/rva-vzw/dikdikdik/-/merge_requests/180/diffs?commit_id=dbd86f0ca2b1ec2179d06629be533d9eb9aca224)
```
import LiveController from '@symfony/ux-live-component';
```
in `assets/bootstrap.js` by
```
import LiveController from '@symfony/ux-live-component/dist/live_controller';
```

I doubt this is a correct solution. But I'm not sure either if I found a bug, or if something is wrong in my webpack-configuration.

Anyway, I've reported the problem, maybe it's of some use :-)

Thanks for providing this cool technology; keep up the good work!

**Comment by weaverryan** [comment]
Hey @johanv!

Thanks for the report - and for testing the bleeding edge :). We've just reworked our build system - I bet this is a bug related to that. I'll check into it.

Cheers!

**Comment by weaverryan** [comment]
All fixed now :)
