### ISSUE TITLE
[ux-icons] title attribute to handle differently

### ISSUE THREAD

**Issue by Nayte91** [symfony/ux#1807]
Hello all,

Let's consider a random icon with a title attribute:

```twig
<twig:UX:Icon name="foo" title="Hello!" />
```
It will render with a correct title attribute, but nothing will happen on your browser.

The reason is that using a title attribute seems to be [discouraged by W3C](https://html.spec.whatwg.org/multipage/dom.html#the-title-attribute), for SVGs but also any other HTML elements.

On the SVG side, the best practice is to use a [title tag](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/title) at the beginning of the svg tag content. That's for example what font awesome do, here's a random icon rendering when I put a title="whatever" in the i tag:

 ```twig
<svg class="svg-inline--fa fa-star" data-replay-favorite-target="icon" aria-labelledby="svg-inline--fa-title-GKRKa00WHbm5" data-prefix="fas" data-icon="star" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512" data-fa-i2svg=""><title id="svg-inline--fa-title-GKRKa00WHbm5">Whatever</title><path fill="currentColor" d="M316.9 svg stuff"></path></svg>
<!-- <i class="fa-solid fa-star" title="Whatever" data-replay-favorite-target="icon"></i> Font Awesome fontawesome.com -->
```
And this title is correctly displayed on browser.

So it seems that the iconRenderer should process the title attribute a bit differently than the other ones, by [prepending](https://www.w3.org/TR/SVG/struct.html#DescriptionAndTitleElements) a `<title>$value</title>` element inside the rendered SVGs, otherwise it will not work/shoot in the foot of accessibility.

**Comment by smnandre** [comment]
For now we only touch the attributes and not the content of the SVG.

In term of accessibility, depending on your usage of icons, aria-hidden / aria-label are both great solutions too.

**Comment by smnandre** [comment]
If we start to handle title, we then will handle paths, or styles, or comments... and that will slow down terribly the performances for everyone.

**Comment by smnandre** [comment]
(sorry if i answer too quickly, i have a lot to do 😅 )

**Comment by kbond** [comment]
I was not aware of the `<title>` tag. Is it handled the same as the `aria-label` attribute? If so, I would prefer this over adding content for the perf reasons Simon mentioned.

> The reason is that using a title attribute seems to be [discouraged by W3C](https://html.spec.whatwg.org/multipage/dom.html#the-title-attribute), for SVGs but also any other HTML elements.

@smnandre, I thought we convert `title` to `aria-label`?

**Comment by Nayte91** [comment]
I checked on the documentation, and there is no mention of title attribute; So I feel like you are right, and the library should not alter how any random attribute should or should not be used.

There is a mention of the title attribute in [here](https://github.com/symfony/ux/blob/db886843ed04e7f7ccf88602339c0010598090be/src/Icons/src/IconRenderer.php#L64): why for?

I feel like it's a non issue here. If this mention is coherent, then we can close this one.

**Comment by kbond** [comment]
> and the library should not alter how any random attribute should or should not be used.

Good point.

> I thought we convert title to aria-label?

And probably why we didn't do this.

> There is a mention of the title attribute in [here](https://github.com/symfony/ux/blob/db886843ed04e7f7ccf88602339c0010598090be/src/Icons/src/IconRenderer.php#L64): why for?

I think if someone was using the title attribute, we don't want to render aria-hidden.

**Comment by smnandre** [comment]
Yep !

**Comment by kbond** [comment]
@Nayte91, if you don't feel this issue is sufficiently resolved, ping me and I'll reopen.

**Comment by smnandre** [comment]
> @smnandre, I thought we convert `title` to `aria-label`?

Nope in the end we said "don't switch attributes from the user" ... we can add one or set a value, but as soon as we switch some, this will be a mess :)
