### ISSUE TITLE
[LiveComponent] Morph error trying to apply invalid classes

### ISSUE THREAD

**Issue by aleho** [symfony/ux#1819]
When live components try to apply changes to elements for some reason the different classes are picked up with whitespaces or even empty strings. Browser console then throws `Uncaught (in promise) DOMException: DOMTokenList.remove: The empty string is not a valid token.`.

This happened here when an element was morphed that probably shouldn't have been in the first place (and `data-skip-morph` doesn't solve the problem).

---

For example when an inline menu (with ID and `data-skip-morph`) is displayed after clicking an element only the class "hidden" changes. Then after updating the live component the element and its menu are still there (but the menu should be invisible, as backend renders context menus hidden of course):

The changes that are picked up:
- `addedClasses: Set [ "w-full" ]`.
- `removedClasses: Set(3) [ "", "hidden\n", "w-full\n" ]`

---

In my case, simply filtering class changes at least prevents the error and didn't have any side effects here:

```JS
className = className.trim();

if (className === '') {
    return;
}
```

https://github.com/symfony/ux/blob/80b36bcbeb2902a55495db2afd544f738c73148f/src/LiveComponent/assets/src/Rendering/ElementChanges.ts#L13-L23

Am I doing something wrong?

**Comment by smnandre** [comment]
Where and how is the `w-full ` set ? In template or JS ?

**Comment by aleho** [comment]
`w-full` is always on the Element. The only class that actually changes is `hidden`.

**Comment by smnandre** [comment]
Could you create a minimal reproducer ? It would be easier to investigate, thank you :)

**Comment by WebMamba** [comment]
Hey I tried to reproduce your issue on the UX website but couldn't! What I did was take a live component where the class changes and add space at the beginning of the class attribute on this component: https://github.com/symfony/ux/blob/396258284b39f1d0b4056daed1e9722daefae74f/ux.symfony.com/templates/components/InlineEditFood.html.twig#L17 
There may maybe something I don't understand about your issue, could you try to reproduce your issue on this component ?

**Comment by aleho** [comment]
After investigating further I finally found the root of the problem:

`handleClassAttributeMutation` doesn't consider the spec correctly.

According to the HTML standard the class attribute can contain "[a set of space-separated tokens](https://html.spec.whatwg.org/#space-separated-tokens)". Splitting on spaces only will tokenize newlines too resulting in an array containing newlines and empty spaces.

https://github.com/symfony/ux/blob/396258284b39f1d0b4056daed1e9722daefae74f/src/LiveComponent/assets/src/Rendering/ExternalMutationTracker.ts#L193-L201


You can easily reproduce this with a simple markup for a live component:

```html
<div {{ attributes }}>
    <p
        class="
            a
            b
            c
        "
    >
        <button type="button" data-action="live#$render" onclick="this.parentElement.classList.remove('a')">
            Remove class and render
        </button>
    </p>
</div>
```

**Comment by smnandre** [comment]
~~But i think your markup is not valid.. class should not contain new lines~~

Ok i'm pretty sure we already had a problem with that but great if you have a fix :)

**Comment by MsLady45** [comment]
What class
