### ISSUE TITLE
[Twig Components] anonymous components in a vendor bundle ??

### ISSUE THREAD

**Issue by barberob** [symfony/ux#1869]
Hello 🙂
I'd like to know if it's possible to load **anonymous** components from a bundle ? ( i'm trying to share components between multiple apps ) 
i can't find a way to make it work...
Also, is it possible to have multiple anonymous template directories so we can load components from bundle and within the app ?

**Comment by smnandre** [comment]
It will be possible soon, but we lack time here a bit :)

**Comment by barberob** [comment]
Cool! Can't wait to use it, such a great feature !
