### ISSUE TITLE
[StimulusBundle] twig_escape_filter notice fixed, please make a new release

### ISSUE THREAD

**Issue by twisted1919** [symfony/ux#1871]
Hello,

My logs are full of errors like:
```
{"message":"User Deprecated: Since twig/twig 3.9: Using the internal \"twig_escape_filter\" function is deprecated.","context":{"exception":{"class":"ErrorException","message":"User Deprecated: Since twig/twig 3.9: Using the internal \"twig_escape_filter\" function is deprecated.","code":0,"file":"/app/vendor/twig/twig/src/Resources/escaper.php:36"}},"level":200,"level_name":"INFO","channel":"deprecation","datetime":"2024-05-28T18:47:28.131267+00:00","extra":{}}
```  

Doing some research, I see that this has been addressed in https://github.com/symfony/stimulus-bundle/commit/e24a12ce43dee6ae27c5d6e6a1d09548e3848dc8 but no release has been made.

Thanks.

**Comment by pfpro** [comment]
Thanks, the logs should be empty again!

https://github.com/symfony/stimulus-bundle/commit/e24a12ce43dee6ae27c5d6e6a1d09548e3848dc8

**Comment by smnandre** [comment]
A new version will be released probably monday !

**Comment by pfpro** [comment]
I think the problem seems to have been resolved today - my logs look good again.
