### ISSUE TITLE
Icons - command is not defined

### ISSUE THREAD

**Issue by jgwiazdowski** [symfony/ux#1881]
Hey,

so according to the docs 
https://symfony.com/bundles/ux-icons/current/index.html#installation

after I ran
`composer require symfony/ux-icons`

I should be able to run 
`bin/console ux:icons:search tabler`
right?

but instead, I am getting command not defined
![image](https://github.com/symfony/ux/assets/457223/a2fe7b11-e508-4017-8b1d-fa4e39121820)

 that's all I from ux commands
![image](https://github.com/symfony/ux/assets/457223/0bb5a446-90ca-4b98-8899-55f24690b406)

am I missing something? (yup i tried cc, restart web server etc)

**Comment by Kocal** [comment]
Which version are you using?

**Comment by jgwiazdowski** [comment]
2.17

![image](https://github.com/symfony/ux/assets/457223/be933aab-882f-4942-9e55-b0b51613c60b)

**Comment by jmsche** [comment]
I had the same issue on some projects; running `composer req http-client` should fix your issue

**Comment by jgwiazdowski** [comment]
@jmsche 
right! worked, thanks
