### ISSUE TITLE
[LazyImage] Support images from Symfony Asset

### ISSUE THREAD

**Issue by Kocal** [symfony/ux#1884]
Hi,

I've started to implementing LazyImage on our application, and I quickly run into an issue with images coming from [`asset()`](https://symfony.com/doc/current/templates.html#linking-to-css-javascript-and-image-assets).

A very simplified example:
```twig
{% set illustration = article.hasMainPicture 
    ? { url: asset('build/images/article/default-illustration.jpg', 'local_assets') }
    : { url: 'https://...' } %}

<img 
    src="{{ data_uri_thumbnail(illustration.url, 20, 10) }}"
    data-controller="symfony--ux-lazy-image--lazy-image"
    data-symfony--ux-lazy-image--lazy-image-src-value="{{ illustration.url }}"
    // other attributes ...
/>
```

If my article has no picture, the output of `asset('build/images/article/default-illustration.jpg', 'local_assets')` will be passed to `file_get_contents()`, resulting into the following error:

> An exception has been thrown during the rendering of a template ("Warning: file_get_contents(/build/images/article/default-illustration.jpg?v=3007fee4): Failed to open stream: No such file or directory").

Which makes sense... but it's totally not user friendly! For the moment I dont use BlurHash when the URL starts with `/build`, but this is not ideal IMO.

In my case, we can resolve this issue by implementing the opposite logic of [`framework.assets.json_manifest_path`](https://symfony.com/doc/current/reference/configuration/framework.html#reference-assets-json-manifest-path) and find which file corresponds to `/build/images/article/default-illustration.jpg?v=3007fee4`: 
```json
{
  "//": "...",
  "build/images/article/default-illustration.jpg": "/build/images/article/default-illustration.jpg?v=3007fee4",
  "//": "..."
}
```

In a more generic way, maybe we can implement the opposite method of [`Symfony\Component\Asset\Package::getUrl`](https://github.com/symfony/symfony/blob/7.2/src/Symfony/Component/Asset/Package.php#L40-L47), something like `getReversedPath`, but this may be too much specific to the [`JsonManifestVersionStrategy`](https://github.com/symfony/symfony/blob/b3508ee76e982474b4a16c546c2e1a92825ec61b/src/Symfony/Component/Asset/VersionStrategy/JsonManifestVersionStrategy.php)...

... WDYT?

**Comment by smnandre** [comment]
Is it not possible for you to pass the "path" instead of an URL (and fallback on the URL if needed) ? 

To illustrate what i mean, in the documentation, the example uses the local filesystem assets path

```twig
<img
    src="{{ data_uri_thumbnail('public/image/large.png', 100, 75) }}"
    {{ stimulus_controller('symfony/ux-lazy-image/lazy-image', {
        src: asset('image/large.png')
    }) }}

    {# Using BlurHash, the size is required #}
    width="200"
    height="150"
/>
```

So for you (even if i'm pretty sure your real case is a bit more complex 😅 than that) ... that could give something like that:

```twig
{% set illustration = article.hasMainPicture 
    ? { 
        url: asset('public/images/article/default-illustration.jpg', 'local_assets'), 
        path: 'assets/images/article/default-illustration.jpg' ,
    }
    : { url: 'https://...' } %}

<img 
    src="{{ data_uri_thumbnail(illustration.path ?? illustration.url, 20, 10) }}"
    data-controller="symfony--ux-lazy-image--lazy-image"
    data-symfony--ux-lazy-image--lazy-image-src-value="{{ illustration.url }}"
    // other attributes ...
/>
```

**Comment by Kocal** [comment]
Ah... Developers love complexity and I fall for it, I've totally forgot about the examples from documentation and demo 🥲 

Yeah I'm gonna try this today, I'm not 100% a big fan, but that's a lot better than reversing the `manifest.json` entries.

Thanks :)

**EDIT:**
> So for you (even if i'm pretty sure your real case is a bit more complex 😅 than that) ... that could give something like that:

Yes totally, the `<img>` rendering is done in a Twig component, that could accept an external URL or a local path: 
```twig
<twig:Image src="https://..."/>
<twig:Image :src="asset('build/images/article/default-illustration.jpg', 'local_assets') />
```

I don't want to introduce a new property, but I guess I don't have the choice

**Comment by Kocal** [comment]
Nevermind, I really don't want to _pollute_ my component with another prop, so I went with a quick and dirty solution to get the reversed asset: 
- in my `Image` component, PHP: 
```php
// ...

    public function isLocalAsset(): bool
    {
        return str_starts_with($this->src, '/build/');
    }

    public function getAssetLocalPath(): string
    {
        if (!$this->isLocalAsset()) {
            throw new \LogicException('The image is not a local asset.');
        }

        // Because our pattern in Webpack Encore is "'images/[path][name].[ext]?v=[contenthash:8]'"
        return s($this->src)->before('?v=')->toString();
    }
// ...
```
- in my `Image` component, Twig:
```twig
<img {{ attributes.defaults({
    ...(this.useBlurHash() ? {
        src: data_uri_thumbnail(
            preload(this.isLocalAsset() ? this.getAssetLocalPath() : src , { as: 'image', fetchpriority: 'high' }),
            20,
            10
        ),
        'data-controller': 'symfony--ux-lazy-image--lazy-image',
        'data-symfony--ux-lazy-image--lazy-image-src-value': src,
    } : { src }),
	{# ... #}
}) />
```
- in my custom `FetchImageContent`: 
```php
final class FetchImageContent
{
    public function __construct(
        private readonly HttpClientInterface $httpClient,
        #[Autowire(param: 'kernel.public_dir')]
        private readonly string $publicDir
    ) {
    }

    public function __invoke(string $filename): string
    {
        // Remote files
        if (str_starts_with($filename, 'http')) {
            $response = $this->httpClient->request('GET', $filename);

            return $response->getContent();
        }

        // We assume that the file is in the public directory, it should be built by Webpack Encore
        if (str_starts_with($filename, '/build')) {
            return file_get_contents($this->publicDir .$filename);
        }

        // Fallback to the initial implementation
        if (file_exists($filename)) {
            return file_get_contents($filename);
        }

        throw new \RuntimeException(sprintf('Unable to fetch image "%s".', $filename));
    }
}
```

With 2/3 integrations tests, that an acceptable solution for me, especially for the DX it gaves me.

**Comment by smnandre** [comment]
We can close here ? :)

**Comment by Kocal** [comment]
Yup!
