### ISSUE TITLE
[TwigComponent]  Tag a new release ?

### ISSUE THREAD

**Issue by allan-simon** [symfony/ux#1886]
Hello 

Is it possible to tag a new release for ux-twig-component ? We're currently having a lot of log generated due to the deprecation of `EscaperExtension::addSafeClass`  , which has been fixed in the master branch https://github.com/symfony/ux-twig-component/commit/c186c43c269aef0500910d5768f94c1ef798b167 , but the last release is from April. 

Thanks a lot for your help :)

**Comment by smnandre** [comment]
II believe we will release one before the end of next week 

(cannot be more precise for now sorry :) )

**Comment by allan-simon** [comment]
Ok no problem then :)

**Comment by smnandre** [comment]
Released has been tagged already .. but we will only "announce" it monday i guess.

As you guys were in a hurry, i wanted to let you know... you can update now ;)

**Comment by smnandre** [comment]
(and thanks Kevin  for this ^^ - sorry @kbond ;) )

**Comment by allan-simon** [comment]
Thanks a lot for the heads up 🙂 it will make this weekend duty call  much easier with less logs in our kibana ^^

________________________________
