### ISSUE TITLE
React Integration not working

### ISSUE THREAD

**Issue by folivora97** [symfony/ux#1892]
Hi there,

I configured Symfony UX React like in the documentation (https://symfony.com/bundles/ux-react/current/index.html#installation)
I did `composer require symfony/ux-react` and `npm install -D @babel/preset-react --force`. When I run `npm run watch` I get the following error:

```
Running webpack ...

 ERROR  Failed to compile with 2 errors                                                                                                                                                                 22:38:30

Module build failed: Module not found:
"./assets/app.js" contains a reference to the file "@symfony/ux-react".
This file can not be found, please check it for typos or update it if the file got moved.

"./assets/react/controllers/Hello.jsx" contains a reference to the file "react".
This file can not be found, please check it for typos or update it if the file got moved.
```

Am I missing something here? StimulusBundle is configured.

Thanks in advance.

**Comment by folivora97** [comment]
Okay I think I got it resolved with this: https://stackoverflow.com/questions/77684268/bootstrap-cannot-find-symfony-stimulus-bundle/77720816#77720816

Assetmapper was working because the default creation with webapp is enabling it and it is not that clear if you are new to symfony that this is working :/ 
Maybe a hint in the documentation that asset mapper is enabled by default would help here.

**Comment by smnandre** [comment]
Would you be up for a PR ?
