### ISSUE TITLE
[Live-Component] Composer cannot upgrade to 2.x of Twig and Live components

### ISSUE THREAD

**Issue by benr77** [symfony/ux#190]
I've just upgraded my app to Symfony 5.4. Immediately I can across an error:

```
Call to undefined method Symfony\UX\LiveComponent\Attribute\AsLiveComponent::attributeMethodsFor()
```

I then looked at the versions for `symfony/ux-twig-component` and `symfony/ux-live-component`. 

Previously my composer version constraints were:

```
"symfony/ux-live-component": "@dev",
"symfony/ux-twig-component": "@dev",
```

I have then changes these to be:

```
"symfony/ux-live-component": "2.*-dev",
"symfony/ux-twig-component": "2.*-dev",
```

The version `2.x` of the Twig component is needed to fix the error I encountered (the missing `attributeMethodsFor()`). However, composer cannot install these due to the live component 2.x branch still requiring twig-component 1.4  :

```
  Problem 1
    - Root composer.json requires symfony/ux-live-component 2.*-dev -> satisfiable by symfony/ux-live-component[2.x-dev].
    - symfony/ux-live-component 2.x-dev requires symfony/ux-twig-component ^1.4 -> found symfony/ux-twig-component[dev-main, 1.4.x-dev (alias of dev-main)] but it conflicts with your root composer.json require (2.*-dev).
```

Is it just that the minimum version of the Twig component needs to be bumped to 2.x ?

**Comment by kbond** [comment]
Thanks for catching @benr77, lots of changes related to branches recently and this was missed.

> Is it just that the minimum version of the Twig component needs to be bumped to 2.x ?

Yes, it doesn't exist in 1.x anymore. Fixed in #191.

**Comment by benr77** [comment]
Nice one - thanks for the super-fast response. Can the PR be merged quickly? This will effect everybody that use `ux-live-component` that upgrades to 5.4 or 6.0 won't it? Cheers!

**Comment by kbond** [comment]
Merged, can you ensure this works now?

**Comment by benr77** [comment]
Confirmed - this now works as expected. Thanks again!
