### ISSUE TITLE
[LiveComponent][Bug] Header not recognize if chartset is added

### ISSUE THREAD

**Issue by BeyerJC** [symfony/ux#1902]
Hey !

We deploy our UI as a lambda on AWS and use API Gateway in front of. The APIG adds a charset to the content-type which afaik can not be disabled.

Instead of `application/vnd.live-component+html` the content-type returned is `application/vnd.live-component+html; charset=UTF-8`

I think the problem is here https://github.com/symfony/ux-live-component/blob/4c975aa9787c8ce1e2438dc53158abfa3623734f/assets/src/Component/index.ts#L299

**Comment by WebMamba** [comment]
@BeyerJC could you try my PR and see if it solves your issue? Thanks for your report, and for searching how to solve it 🧡

**Comment by jc-beyer-tqgg** [comment]
Hey @WebMamba  ! Thanks for the super fast reply and the PR 🎉 

Its not easy to test because my local api gateway does not add the charset. I did some hacks and i think i was able to simulate it and can confirm that it works with your fix !
