### ISSUE TITLE
Twig Component with Stimulus Attributes

### ISSUE THREAD

**Issue by TomoyaHamasaki** [symfony/ux#1905]
How does one use stimulus when using a component?

`<twig:Component {{ stimulus_controller('example') }} />`

I can't do this as I can with a typical element. Is the only way to achieve this goal is by doing this?

`<twig:Component data-controller="example" />`

**Comment by WebMamba** [comment]
~~Yes the HTML syntax allows you to only add attribute to your component and can't parse twig directly like that~~

**Comment by smnandre** [comment]
> `<twig:Component {{ stimulus_controller('example') }} />`

@TomoyaHamasaki  here you can use the `...` syntax 

```twig
<twig:Component {{ ...stimulus_controller('example') }} />
```

:)

**Comment by TomoyaHamasaki** [comment]
+

> > `<twig:Component {{ stimulus_controller('example') }} />`
> 
> @TomoyaHamasaki here you can use the `...` syntax
> 
> ```
> <twig:Component {{ ...stimulus_controller('example') }} />
> ```
> 
> :)

I love you, but why does that work? lol what is `...`?

**Comment by norkunas** [comment]
It's a spread operator (destructuring) borrowed from JavaScript
