### ISSUE TITLE
[LiveComponent] automatically refresh component

### ISSUE THREAD

**Issue by tito10047** [symfony/ux#1914]
Hi,
It is possible to set timer for reload live component? I want component that is autmaticaly feetch new data from server every minute. 

Has live component this feature or i need add custom controller for that.

**Comment by smnandre** [comment]
The "data-poll" attribute is what you're looking for :) 

https://symfony.com/bundles/ux-live-component/current/index.html#polling

```html
<div
    {{ attributes }}
    data-poll="delay(500)|$render"
>
```
