### ISSUE TITLE
[TwigComponent] Passing components as Props

### ISSUE THREAD

**Issue by seb-jean** [symfony/ux#1942]
Hello,

I would like to know if it is possible to pass Components as Props. Example with [Headless UI](https://headlessui.com/react/menu#rendering-as-different-elements):

`<MenuButton as={MyCustomButton}>My account</MenuButton>`

**Comment by smnandre** [comment]
Nope as you call MenuButton, so this is the component name/class.

I guess for children you could pass component name and call it with the twig function ?

**Comment by seb-jean** [comment]
Yes, that's what I was telling myself to pass component name and call it with the twig function.

**Comment by smnandre** [comment]
Can i close ? :)

**Comment by seb-jean** [comment]
It's linked to https://github.com/symfony/ux/issues/1922 so :)
