### ISSUE TITLE
[Live Component] Typed property must not be accessed before initialization

### ISSUE THREAD

**Issue by kempha** [symfony/ux#1952]
There is this live component:
```php
#[AsLiveComponent]
final class TestComponent
{
    use DefaultActionTrait;

    #[LiveProp(writable: true, onUpdated: 'onNameUpdated')]
    public string $name;

    #[LiveProp(writable: true)]
    public string $phone;

    #[PostMount]
    public function postMount(): void
    {
        $this->name = 'kempha';
        $this->phone = '1234567890';
    }

    public function onNameUpdated(): void
    {
        $phone = $this->phone; // Error: Typed property must not be accessed before initialization.
    }
}
```

I can't access the phone inside the `onNameUpdated()` handler because it hasn't been initialized yet. This happens because the handler is called as soon as the variable to which the handler refers is initialized. But other class variables have not yet been initialized during hydration.

I believe that all handlers should be called after all class variables have been initialized during component hydration. The problem is here: `Symfony\UX\LiveComponent\LiveComponentHydrator::hydrate()` line 218. The `onUpdated` handler is called directly inside the iteration when the variable associated with it has been initialized. All handlers should be called outside the `foreach()`, after all variables have been initialized.

**Comment by smnandre** [comment]
Hey @kempha !

That's an intersting idea... would you be ok to start some PR / digging on this ? :)

**Comment by kempha** [comment]
> would you be ok to start some PR / digging on this ? :)

I can make a pull request. It will become clear how I see it)

**Comment by smnandre** [comment]
That'd be nice! Thank you :)
