### ISSUE TITLE
[LiveComponent] Openning component in component ?

### ISSUE THREAD

**Issue by xorgxx** [symfony/ux#1968]
Hi, I would like to know if it is possible to open a component from another component that displays on the parent component? Essentially, a window that replaces the other one as SAP.

![sf-compo](https://github.com/symfony/ux/assets/7679725/c0249465-d0ce-457b-85e4-918ec80a26f8)

**Comment by smnandre** [comment]
You can emit an event from `component 1`  that `component base` listen too.. and then react by rendering `component 2 `instead of `component 1 `. 

(performances could vary depending on your `component base` implementation / template)
