### ISSUE TITLE
[TwigComponent] Empty `props` throw incomprehensible Exception

### ISSUE THREAD

**Issue by smnandre** [symfony/ux#1971]
Create an anonymous component template, and let props empty

```twig
{% props %}
```

You will get some incomprehensible exception

> An exception has been thrown during the compilation of a template ("Warning: Undefined variable $name").

![emprty-props](https://github.com/symfony/ux/assets/1359581/fe783b8d-aa59-4aab-bdb2-e379a5e979d4)

**Comment by WebMamba** [comment]
I can't reproduce it what is inside your component ? Are your sure you don't have a {{ name }} somewhere ?

**Comment by smnandre** [comment]
https://github.com/smnandre/repro-empty-props

composer install 
symfony server:start
php bin/console open:local
