### ISSUE TITLE
`loading` attribute without Live Component

### ISSUE THREAD

**Issue by seb-jean** [symfony/ux#1975]
Hi,

I would like to use the `loading` attribute on my Twig Component but it adds `data-action="live:appear->live#$render"` which I do not want to have. How to avoid this? 

Thanks.

**Comment by smnandre** [comment]
It is not a LiveComponent you are sure ? If yes, it's a bug indeed

**Comment by seb-jean** [comment]
Yes, it is an anonymous component.

**Comment by smnandre** [comment]
Well it was indeed a bug, should be fixed by the linked PR. Thanks @seb-jean !
