### ISSUE TITLE
Wrong dependency on `symfony/ux-turbo-mercure`

### ISSUE THREAD

**Issue by Lustmored** [symfony/ux#198]
When following upgrade guide I stumbled upon dependency conflict within `ux-turbo-mercure`:

```
Problem 1
    - Root composer.json requires symfony/ux-turbo-mercure ^2.0 -> satisfiable by symfony/ux-turbo-mercure[v2.0.0].
    - symfony/ux-turbo-mercure v2.0.0 requires symfony/ux-turbo ^1.3 -> found symfony/ux-turbo[v1.3.0] but it conflicts with your root composer.json require (^2.0).
```

Looks like `ux-turbo-mercure` needs dep bump on `ux-turbo` to `^2.0` that was missed.

**Comment by tgalopin** [comment]
Fix in https://github.com/symfony/ux/pull/199

**Comment by virtualize** [comment]
Thanks for the fix. @tgalopin. Can we please have minor release for ux-turbo-mercure that includes this fix?

**Comment by tgalopin** [comment]
Should be the case now, 2.0.1

**Comment by Lustmored** [comment]
Yep, I can confirm upgrade went well this time. Thanks a lot!
