### ISSUE TITLE
[Icons][Twig-Component] Update documentation for installation ux icons

### ISSUE THREAD

**Issue by Erwanou77** [symfony/ux#1993]
Hi everyone,

I just initialized a new symfony project, and I wanted to first install the ux icons library but it doesn't work until twig components is installed.

You should add at the beginning of the ux icons documentation that you must first install ux twig component then ux icons

**Comment by WebMamba** [comment]
There is a note in the doc: https://symfony.com/bundles/ux-icons/current/index.html#html-syntax-1. We agree to say that the HTML syntax is not working for you, but if you use the twig function, does it work?

**Comment by Erwanou77** [comment]
I did it with the html syntax and it didn't work. But I haven't tried the twig function

**Comment by smnandre** [comment]
The component does not require TwigComponent, as it works with the Twig function  `{{ ux_icon(...) }}`

The two times we show HTML syntax, there is a note explaining `symfony/ux-twig-component` must be installed.

![Capture d’écran 2024-07-17 à 21 17 54 - Grande](https://github.com/user-attachments/assets/bcb4aac3-67bb-426b-891b-c0ab351b2ad3)
https://symfony.com/bundles/ux-icons/current/index.html#html-syntax

![Capture d’écran 2024-07-17 à 21 18 14 - Grande](https://github.com/user-attachments/assets/ae86c012-7cd3-49f4-827e-1b11fdcee8d9)
https://symfony.com/bundles/ux-icons/current/index.html#html-syntax-1

And we don't want to force / push anyone to install Twig component if they don't need it.

So i'm not sure how we could do it better there: do you maybe have a suggestion @Erwanou77 ?

**Comment by Erwanou77** [comment]
Ah yes indeed, I had not seen the ux twig component.
My bad, I will close this issue

**Comment by Erwanou77** [comment]
Maybe putting it in red could be a good idea, because in fact I haven't seen this note

**Comment by smnandre** [comment]
Red is reserved to "danger" / "caution", but a "tip" could render like this: 

<img width="969" alt="Capture d’écran 2024-07-17 à 21 29 14" src="https://github.com/user-attachments/assets/1d6d5839-4770-4612-8a03-45509df7cb09">

**Comment by Erwanou77** [comment]
Yes it's already a little better, but maybe put it at the beginning of the documentation.
After that it's maybe because I'm used to using the html syntax that's why ux twig component.
