### ISSUE TITLE
ux_icon triggers an exception when icon doesn't exists

### ISSUE THREAD

**Issue by Seb33300** [symfony/ux#2008]
### Description

The twig `ux_icon` function always triggers an exception when the icon name doesn't exists.

In my opinion, since icons are usually not a critical feature (most of the time only for design purpose), this should trigger an exception only in `dev` mode by default and the exception should be catched with an error message in logs in `prod` mode.

Maybe by adding an option to the UX Icons component to configure this?

### Example

I have a feature in my app where the admin can add icons to display in the app.
One icon has been added with a typo and this put few pages of our site down.

**Comment by smnandre** [comment]
Really sorry to hear that. 

Unfortunately, many users expect an exception in this specific case, so i don't think we would silent them here.

However.... we recently merged [#1889](https://github.com/symfony/ux/pull/1889), which exposes an interface for the IconRenderer and will be available in the next release (in the coming weeks).

You could then decorate the IconRenderer to catch potential exceptions?

**Comment by Kocal** [comment]
> Unfortunately, many users expect an exception in this specific case, so i don't think we would silent them here.

I don't really agree here, you don't want you app to crash if an icon is not able to be rendered. I understand the benefit in thrownig an error, but **in development only**.

Before Symfony UX Icon, we used things like `'<i class="fa-solid fa-'~ iconName ~'"></i>'` and it didn't crash the whole app.

Something like a strict mode, like Twig and variables. Depending of the configuration (by default `%kernel.debug%` if I remember well), it may throw an exception or not.

**Comment by smnandre** [comment]
>  if an icon is not able to be rendered

That's very debatable :) 

So yeah, a configuration option could please everyone.

And what about a "default" icon ?

**Comment by smnandre** [comment]
Hi @Seb33300 : i tried something with a config option... in #2023  If by chance you had time to check and see if everything works for you that'd be very nice :)

**Comment by Seb33300** [comment]
> Hi @Seb33300 : i tried something with a config option... in #2023 If by chance you had time to check and see if everything works for you that'd be very nice :)

Thank you for that PR!
Just tested it and it seems to work.
My only concern is to add errors to logs so we can still have a way to find and fix them.
