### ISSUE TITLE
[LiveComponent] LiveCollection component attributes error with form

### ISSUE THREAD

**Issue by cve** [symfony/ux#2010]
I have component which is:

```php
<?php

namespace App\Twig\Components\Panel;

use App\Dish\Domain\Model\Dish;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\FormInterface;
use Symfony\UX\LiveComponent\Attribute\AsLiveComponent;
use Symfony\UX\LiveComponent\Attribute\LiveProp;
use Symfony\UX\LiveComponent\DefaultActionTrait;
use Symfony\UX\LiveComponent\LiveCollectionTrait;

#[AsLiveComponent]
class DishForm extends AbstractController
{
    use DefaultActionTrait;
    use LiveCollectionTrait;

    #[LiveProp(fieldName: 'formData')]
    public ?Dish $dish;

    protected function instantiateForm(): FormInterface
    {
        return $this->createForm(
            \App\App\Resource\Form\DishForm::class,
            $this->dish
        );
    }
}
```

the template is:

```twig
<div{{ attributes }}>
    {{ form_start(form) }}
    {{ form_row(form.name) }}
    {{ form_row(form.quantity) }}
    {{ form_row(form.unit) }}
    {{ form_row(form.allocation) }}
    {{ form_row(form.menuPosition) }}
    {{ form_row(form.category) }}
    {{ form_row(form.quantityStep) }}
    {{ form_row(form.sumStep) }}
    {{ form_row(form.priceForEvent) }}
    {{ form_row(form.priceForCatering) }}
    {{ form_row(form.priceQuantity) }}
    {{ form_row(form.workerPrice) }}
    {{ form_row(form.workers) }}

    <table class="table table-borderless form-no-mb">
        <thead>
        <tr>
            <td>Product</td>
            <td>Dish</td>
        </tr>
        </thead>
        <tbody>
        {% for item_form in form.dishProducts %}
            <tr>
                <td>
                    {{ form_row(item_form.product) }}
                </td>
                <td>
                    {{ form_row(item_form.dish) }}
                </td>
                <td>
                    {{ form_row(item_form.vars.button_delete, {label: 'X', attr: {class: 'btn btn-outline-danger'}}) }}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    {{ form_widget(form.dishProducts.vars.button_add, {label: '+ Add Item', attr: {class: 'btn btn-outline-primary'}}) }}

    <button type="submit" class="btn btn-success" formnovalidate>Save</button>
    {{ form_end(form) }}
</div>
```

this is the usage (and form variable has a form instance):
```
<twig:Panel:DishForm :dish="entity" :form="form" />
```

and I have that error:

![image](https://github.com/user-attachments/assets/681bd5ac-ad7c-44db-84ca-699459cb4c3d)

what's wrong?, I took similar code from official demo of LiveCollection from ux website. I checked few versions of `symfony/ux-twig-component` and `symfony/ux-live-component` and I have the same result. Could you guys help me with that?

**Comment by smnandre** [comment]
I think you forgot the ComponentWithFormTrait

**Comment by cve** [comment]
thanks for your reply, but `LiveCollectionTrait` includes `ComponentWithFormTrait` 
![image](https://github.com/user-attachments/assets/f9efde8e-90ce-4d1c-b1d2-ac13d252c694)

**Comment by cve** [comment]
I created brand new symfony project next to this problematic project, installed live components, created some form types and it works. I don't have idea why it does not work in previous project. I updated Symfony from 6.3.* to 6.4.*, and still the same problem...

**Comment by cve** [comment]
I have the same versions of twig (3.10.3) and live/twig components 2.18.1 in both projects

**Comment by smnandre** [comment]
The problematic project is on symfony 6. ? 

It could be related to ->render method from controller that transform form into form view ?

**Comment by cve** [comment]
both projects are on symfony 6. Yeah it makes sense, but how can I change that behaviour?

**Comment by cve** [comment]
Ok, I changed the render behaviour for form and now there is very similar error but about Form, not FormView
![image](https://github.com/user-attachments/assets/9481744c-5100-4f34-9299-93ea3d700dc8)

**Comment by smnandre** [comment]
Can you do 

```
php bin/console debug:twig-component Panel:DishForm
```

This could be your component not recognized and `attributes` trying indeed to use "form" as an attribute.

**Comment by cve** [comment]
This is the output:

![image](https://github.com/user-attachments/assets/31d2cfb5-8277-48a9-9029-5fdf2c9bc73a)

weird, it looks like annonymous component, but should not, I will debug further

**Comment by cve** [comment]
this is the output from `DishForm` without Panel prefix

![image](https://github.com/user-attachments/assets/5a294b98-9bf9-4ff4-93b9-e404bc22e0a0)

**Comment by cve** [comment]
Yes! It works, I should add aliast like that `#[AsLiveComponent('DishForm')]` thank you guys for your support

**Comment by smnandre** [comment]
Happy to help! 

As you "should" not need to declare the name, can you tell me what's in your `config/packages/twig_component.yaml`

**Comment by cve** [comment]
I don't have this config file at all :-/

**Comment by smnandre** [comment]
This is the default content added by the [flex recipe](https://github.com/symfony/recipes/blob/main/symfony/ux-twig-component/2.13/config/packages/twig_component.yaml) (i guess you're not using flex :) )

```
twig_component:
    anonymous_template_directory: 'components/'
    defaults:
        # Namespace & directory for components
        App\Twig\Components\: 'components/'
```

I think maybe with some config you could avoid using hard coded names in your class 

(see the UX Twig Component documentation for the details on this config / how it works)
