### ISSUE TITLE
The other args are lost if i use  loading="defer"

### ISSUE THREAD

**Issue by AlDaFlux** [symfony/ux#2012]
I've a component who take an argument 

php: 
`    #[LiveProp(writable: true)]
    public ? Projet $projet= null;`

template : 
`
<twig:Web:MatomoChartProjet  :projet="projet"  /> `

It's work perfectly. But if use loading="defer" ....      the var $projet is now null....  

for information; loading="defer" on my other components with no args....

**Comment by WebMamba** [comment]
Hey @AlDaFlux thanks for your reports! I can't reproduce your issue could you create a small reproducer to show your issue! Thanks!

**Comment by AlDaFlux** [comment]
Hi @WebMamba 

I make a small project : 
[2024-DeferCaseSmall.zip](https://github.com/user-attachments/files/16438343/2024-DeferCaseSmall.zip)

It's ok for you or you need more projects file ?

**Comment by AlDaFlux** [comment]
Detail : 

 - php component : 

```
namespace App\Twig\Components;

use Symfony\UX\LiveComponent\Attribute\AsLiveComponent;
use Symfony\UX\LiveComponent\DefaultActionTrait;

#[AsLiveComponent]
final class Arg
{
    use DefaultActionTrait;
    
    #[LiveProp(writable: true)]
    public ? String $message = "Empty";
    
}
```

- template component

```
<div{{ attributes }}  class='col alert {% if  this.message %}{% if  this.message =='Empty' %}alert-warning{% else %}alert-success{% endif %}{% else %}alert-danger{% endif %}'>
    {{ this.message }}
</div>
```
- template 

```
     <div class='row'>
        <twig:Arg message="Arg OK" />
        <twig:Arg message="Arg OK" loading="defer" />
    </div>
```
Result : 

![defer](https://github.com/user-attachments/assets/3fbde341-9427-43a8-afc3-ffcd736e2ed1)

**Comment by smnandre** [comment]
I believe your JS is not executed / compiled ... probably because of the .scss file.

Also, you did not import the namespace for the LiveProp attribute 

```php
use Symfony\UX\LiveComponent\Attribute\LiveProp;
```

I could not install your package.json so i tried your code with AssetMapper instead, and got no problem (defer was working i mean).

Can you check your webpack / assets configuration ?

**Comment by AlDaFlux** [comment]
Damned !  It was just that....  I've forgot the use Liveprop..... thanks for the help !
