### ISSUE TITLE
[Stimulus] Input type "date" and "datetime-local" do not display initial value

### ISSUE THREAD

**Issue by Mauriceu** [symfony/ux#2029]
Hello UX-Team,

I also posted this in the stimulus repo [here](https://github.com/hotwired/stimulus/issues/781), however for the sake of making sure this reaches the right people, I am adding the issue here too.

Reproducer: [https://github.com/Mauriceu/symfony-issues/tree/turbo-datepicker-issue](https://github.com/Mauriceu/symfony-issues/tree/turbo-datepicker-issue)

I came across an issue regarding <input> elements with type "date" and "datetime-local", but not "datetime". 
Consider the following HTML:

```html
    <input
        type="date"
        value="2024-07-30"
        data-model="debounce(700)|from"
    />
```

The "value" attribute is not rendered correctly, the <input> element just displays the expected format, in my case "tt.mm.yyyy", not "2024-07-30". Inspecting the DOM shows that the "value" attribute is set correctly, so I assume a stimulus hook is responsible for this?

The value is displayed correctly in one of these cases:
 - the "data-model" attribute is removed from the input-element
 - the user inputs a value with the datepicker
 - the user inputs a value with a keyboard

**Comment by Mauriceu** [comment]
Okay, I tracked the problem down to the serializer. The "data-live-props-value" property contains a datetime string not in line with the format passed to the LiveProp::format property - most likely because the serializer ignores it.

**Comment by smnandre** [comment]
Exactly. The 'format' options is for the default hydrator. When you use the serializer you need to configure your properties as you would do outside Live component

**Comment by Mauriceu** [comment]
Ah okay, well if this is intended behavior then lets just close this. Thank you for the answer
