### ISSUE TITLE
[Doc] Little error on form-collection-type demo

### ISSUE THREAD

**Issue by Nek-** [symfony/ux#2033]
From what I understand, the following instantiateForm is useless:

https://github.com/symfony/ux/blob/e122096cead156c2e1608976a6a69a887fd3b1a0/ux.symfony.com/src/Twig/TodoListForm.php#L32-L38

The form is actually instantiated here:

https://github.com/symfony/ux/blob/e122096cead156c2e1608976a6a69a887fd3b1a0/ux.symfony.com/src/Controller/Demo/LiveComponentDemoController.php#L50

It's pretty disturbing while reading the doc 😅

**Comment by norkunas** [comment]
But the controller is not reached at all when the component rerenders, so it needs to know which form to instantiate

**Comment by smnandre** [comment]
That's why this method must be implemented (it's an abstract method of the ComponentWithFormTrait, used in the LiveCollectionTrait)

See here: https://github.com/symfony/ux/blob/21595a73e74c0ef1a3a14f8697b48580e6b07488/src/LiveComponent/src/ComponentWithFormTrait.php#L68

**Comment by Nek-** [comment]
The form is passed here:

https://github.com/symfony/ux/blob/e122096cead156c2e1608976a6a69a887fd3b1a0/ux.symfony.com/templates/demos/live_component/form_collection_type.html.twig#L12

_[And it's not in the doc besides it seems required](https://ux.symfony.com/demos/live-component/form-collection-type)._

**Comment by smnandre** [comment]
I'm not sure to understand.. the documentation states the following in the "ComponentWithFormTrait" section 

> The trait forces you to create an instantiateForm() method, which is used each time the component is rendered via AJAX. To recreate the same form as the original, we pass in the initialFormData property and set it as a LiveProp.

https://symfony.com/bundles/ux-live-component/current/index.html#rendering-an-entire-form-in-a-component

How would you improve things ? :)
