### ISSUE TITLE
[Assetmapper] "importmap:require" downloads a minified version of the base package - sub directories are not included

### ISSUE THREAD

**Issue by Mauriceu** [symfony/ux#2034]
When running 

``` bin/console importmap:require date-fns ```

the resulting file in the "assets/vendor/date-fns" directory is only the base package. When running "npm i date-fns" the resulting "node_module/date-fns" directory contains multiple sub directories, such as "lib" and "locale" - the latter is used to set locales as needed, however these definitions do not exist when requiring this package with the importmap command.

I guess a workaround would be downloading the relevant files/directories manually and providing your own pathing in the importmap.php, though that would feel pretty dirty.

I think it would be nicer if the full package would be downloaded - pretty much 1:1 as with the npm command. And when running "asset-map:compile" minified versions are created. But if that is not possible, maybe someone can point me in the right direction on how to provide these missing definitions?

**Comment by smnandre** [comment]
> I guess a workaround would be downloading the relevant files/directories manually and providing your own pathing in the importmap.php, though that would feel pretty dirty

Pretty dirty, but.... in the date-fns [documentation](https://date-fns.org/v3.6.0/docs/CDN) 😅 

I made a really quick test, but following the [i18n section](https://date-fns.org/v3.6.0/docs/I18n) of the doc, it seems you can do:

```
symfony console i:req date-fns
symfony console i:req date-fns/locale
```


I did not digg that much, but it seems you can also directly import specific locales (cf the "[locale](https://date-fns.org/v3.6.0/docs/CDN#locales)" section of the CDN page)

```
symfony console i:req date-fns/locale/fr
```

--- 

PS: @kbond / @javiereguiluz / anyone who can move this issue, i think it should probably be in the symfony/symfony repository :)

**Comment by Mauriceu** [comment]
oh wow, the command

`symfony console i:req date-fns/locale`

works.

I thought I already tried this and ran into an error, though everything now hints towards the opposite ^^
Thank you very much!

**Comment by smnandre** [comment]
Happy if things are working for you :)
