### ISSUE TITLE
Add the Map component to the UX website

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/ux#2042]
Symfony UX has a new Map component: https://github.com/symfony/ux/pull/1937

Hugo (@Kocal) is still tweaking and polishing some of its features, but when the component stabilizes, we need to add it to:

* The list of packages: https://ux.symfony.com/packages
* Create a demo for it in: https://ux.symfony.com/demos

Thanks!

**Comment by Kocal** [comment]
cc @smnandre 👀

**Comment by 94noni** [comment]
idea :) a map of all symfony events happened or to be happening ;) with a link to their page https://live.symfony.com

**Comment by javiereguiluz** [comment]
Just mentioning that we already have that feature here: https://symfony.com/events/

In the list of issues of the symfony.com repo I created a new one to migrate this custom-made map to use the Map component from UX.

**Comment by Kocal** [comment]
A bit related, but can we have a GitHub label `Map`?

**Comment by smnandre** [comment]
I'm on it @javiereguiluz ;) (already started)

**Comment by smnandre** [comment]
> In the list of issues of the symfony.com repo I created a new one to migrate this custom-made map to use the Map component from UX.

Oh that's so cool @javiereguiluz! 

By the way, i have a couple of ideas i'd be happy to share with you about this page/component if you have 5mn one of these days ;)

**Comment by smnandre** [comment]
@94noni On the SymfonyUX website, the package "main page/demo" will feature a standard usage example, likely centered around "Lyon" 👼 (poke @Kocal).

I have two demos coming up next: one focused on customization with Leaflet, and the other functioning as a "locator" (which I assume will be one of the most common uses for this component).

The locator demo will likely evolve into a two- or three-part series, as it's ideal for demonstrating events, filters, list/map synchronization, and more.

Teasers that may **_or may not_** be related to the aforementioned demos.
| . | . |
| - | - |
| ![map-demo-tease2](https://github.com/user-attachments/assets/23d61ad4-8518-4c76-bd70-4cc706d2c891) | ![map-demo-tease1](https://github.com/user-attachments/assets/c1bc82db-72c0-4aca-bf62-3d082ccd9b2d) |
