### ISSUE TITLE
[AutoComplete] the `openOnFocus` option works only on the second focus?

### ISSUE THREAD

**Issue by alexislefebvre** [symfony/ux#2050]
With this code:

```
                'tom_select_options' => [
                    'openOnFocus' => false,
                ],
```

The dropdown appears on the first click to focus the field, but not on the second click. So it looks like there's an issue when initializing the component?

It should work like in this example (results appear only if a character -other than a space- is typed): https://codepen.io/Raven0us/pen/GRLKNGX (source: https://github.com/orchidjs/tom-select/issues/701 )

I don't have any reproductible example, but please try it if you already have a project with `symfony/ux-autocomplete`.

**Comment by smnandre** [comment]
I'm not sure to fully understand.. could you explain the scenario you would like to see ? And what change you think should be done ?

**Comment by alexislefebvre** [comment]
> I'm not sure to fully understand.. could you explain the scenario you would like to see ? And what change you think should be done ?

With the `openOnFocus` option set to `false`, the dropdown with the results should not appear as soon as the field has the focus, but only after some text is typed, like in this example: https://codepen.io/Raven0us/pen/GRLKNGX

When I use this option with the AutoComplete component, it doesn't work: the first focus on the field trigger the display of the dropdown with the results. But if I click again in the field, then the dropdown doesn't appear, it only shows if some text is typed.

So it looks like this option partially work with this component.

**Comment by smnandre** [comment]
Is this something related to the way options are loaded ?

**Comment by alexislefebvre** [comment]
I'm trying to create a reproducer.

Meanwhile, it looks like we may circumvent this issue by changing the JS code instead of the form itself: https://symfony.com/bundles/ux-autocomplete/current/index.html#extending-tom-select

**Comment by alexislefebvre** [comment]
Here is the reproducer: https://github.com/alexislefebvre/symfony-ux-openOnFocus-2050

There is one problem: it works! But it's a field without AJAX or `#[AsEntityAutocompleteField]`, so I'll have to add these in order to test in conditions close to what we observed.

**Comment by alexislefebvre** [comment]
Well, it's working on our project now. It looks like the issue was that we had to run `bin/console asset-map:compile` to apply the `openOnFocus` option. Thanks for your help.
