### ISSUE TITLE
Unable to load the "Symfony\UX\Icons\IconRenderer" runtime. after update symfony/ux-icons v2.18.1 to v2.19.0

### ISSUE THREAD

**Issue by cedric-r-mycelium** [symfony/ux#2054]
Unable to load the "Symfony\UX\Icons\IconRenderer" runtime. after update symfony/ux-icons v2.18.1 to v2.19.0

**Comment by smnandre** [comment]
Could it be a cache problem ?

**Comment by cedric-r-mycelium** [comment]
i think but it's strange 
it's never happend before

**Comment by smnandre** [comment]
Let's close if this works for now, and we'll see if this occurs again ? My guess is something related to twig/symfony cache mix and match, but let's keep an eye on it
