### ISSUE TITLE
[TwigComponent] 3rd party anon. components breaks `debug:twig-component`

### ISSUE THREAD

**Issue by kbond** [symfony/ux#2087]
Ref: https://github.com/symfony/ux/pull/2019#issuecomment-2297713537

> From here, you can organize your components into subdirectories if desired. For example, a component like twig:Acme:Table:Header will be located in /templates/components/Table/Header.html.twig.

> Just a heads up, if there is a subfolder inside /templates/components, it breaks the TwigComponentDebugCommand

> In ComponentFactory.php line 256:
Unknown component "Cards:Card". And no matching anonymous component template was found.
Even tough, twig correctly renders the component using the :Folder:ComponentName described in the original post.

**Comment by yceruto** [comment]
it should be fixed in https://github.com/symfony/ux/pull/2088

**Comment by rrenteria-dev** [comment]
Thank you @kbond @yceruto 🙌

**Comment by smnandre** [comment]
Thank you @yceruto
