### ISSUE TITLE
[UX Map] Rename a variable

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/ux#2111]
When using UX Map and Leaflet bridge to customize a marker, you have to do this:

```js
const { definition, leaflet } = event.detail;
// ...
```

As suggested by @Kocal, the `leaflet` variable should probably be named `L` because Leaflet uses `L` in all its docs. Now that the bridge is so new (and experimental), we could even rename the variable wihout considering BC, etc.

Thanks

**Comment by Kocal** [comment]
I can work on it tomorrow at noon
