### ISSUE TITLE
[Website] Missing icon for twig component success alert

### ISSUE THREAD

**Issue by mttsch** [symfony/ux#2115]
On https://ux.symfony.com/twig-component, the success message example does not show the icon:

![Screenshot 2024-08-31 at 19 43 25](https://github.com/user-attachments/assets/5b629dc7-ba9a-4ace-a47a-3293a8833aa3)

It appears that `viewBox` should be `0 0 512 512`.

**Comment by smnandre** [comment]
Thanks @mttsch for letting us know!
