### ISSUE TITLE
[LiveComponent] Stimulus controller inside a Live Component does not rerender

### ISSUE THREAD

**Issue by Nek-** [symfony/ux#2126]
Re-opening #2048 in a new issue.

TL;DR: If you have a stimulus controller inside a live component, after the live component reloads, you will experience weird issues (dom in an unexpected state) because of dom morphing feature of turbo/live components.

Examples I have:
- A component that calculates a price with VAT "on the fly" while typing in an input
- A component that starts QuillJS! related to #1  btw

For those interested, I summarized #2048 solutions in this article: https://wiki.swag.industries/en/symfony/ux/controller-state-after-live-update

**Comment by smnandre** [comment]
Can you create a small reproducer so we can look at a concrete case of this problem and see what can be done ? :)
