### ISSUE TITLE
[Autocomplete] Placeholder not longer displayed when converting field to autocomplete

### ISSUE THREAD

**Issue by bretrzaun** [symfony/ux#2131]
I added the 'autocomplete' option to an existing form field:

```
            ->add(
                'cost',
                ChoiceType::class,
                [
                    'required' => true,
                    'placeholder' => '-- please select --',
                    'multiple' => true,
                    'choices' => [...]
                    'autocomplete' => true,
                    'constraints' => [
                        new Assert\NotBlank()
                    ]
                ]
            )
```

While the autocomplete functionally works perfectly, the placeholder is no longer displayed.

I had to use the following workaround to make the placeholders appear again:
```
                    'tom_select_options' => [
                        'placeholder' => '-- please select --',
                        'hidePlaceholder' => true,
                    ],
```

The TomSelect documentation says (in https://tom-select.js.org/docs/#general-configuration):
> The placeholder of the control. Defaults to input element's placeholder, unless this one is specified. 

So my workaround should not be necessary.

**Comment by andersonsilva87** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by smnandre** [comment]
> This option determines whether or not a special "empty" option (e.g. "Choose an option") will appear at the top of a select widget. This option only applies if the multiple option is set to false.

https://symfony.com/doc/current/reference/forms/types/choice.html#placeholder

So _maybe_ this workaround is in fact not necessary.. but you had no placeholder in the HTML at first ? 

Did you try like this ? 

```php
'choices' => ... ,
'multiple' => true,
'attr' => [
    'placeholder' => '-- please select --',
],
```

**Comment by bretrzaun** [comment]
@smnandre Right, I see the point.
However - I had the placeholder option set with the original ChoiceType. I understand this has a different meaning than adding an HTML attribute.

For DX it would be nice if the UX Autocomplete would add the placeholder to the HTML. Otherwise converting to a ChoiceType to an autocomplete will loose the placeholder unless the option is migrated as well.

**Comment by smnandre** [comment]
So, let's make a quick test

## Test  1 - `multiple = true`

### Form code

```php
        $form = $this->createForm(FormType::class)
            ->add('n1', ChoiceType::class, [
                    'required' => true,
                    'placeholder' => '-- please select --', // placeholder defined here ?
                    'multiple' => true,
                    'choices' => [
                        'foo' => 'foo',
                        'bar' => 'bar',
                    ],
                ]
            )
            ->add('n2', ChoiceType::class, [
                    'required' => true,
                    'placeholder' => '-- please select --',
                    'multiple' => true,
                    'choices' => [
                        'foo' => 'foo',
                        'bar' => 'bar',
                    ],
                    'autocomplete' => true, // same as "n1" but with autocomplete
                ]
            )
            ->add('n3', ChoiceType::class, [
                    'required' => true,
                    'placeholder' => '-- please select --',
                    'multiple' => true,
                    'choices' => [
                        'foo' => 'foo',
                        'bar' => 'bar',
                    ],
                    'autocomplete' => true,
                    'attr' => [
                        'placeholder' => 'Foo Bar', // now with attr placeholder
                    ],
                ]
            );
```

### Results

<img width="996" alt="Capture d’écran 2024-09-06 à 19 53 21" src="https://github.com/user-attachments/assets/7ceaaf84-f36b-42cf-aaa4-1fbedcfb201b">


## Test 2 - `multiple = false`


### Form code 

```php
            ->add('n1', ChoiceType::class, [
                    'required' => true,
                    'placeholder' => '-- please select --',
                    'multiple' => false, // visible placeholder
                    'choices' => [
                        'foo' => 'foo',
                        'bar' => 'bar',
                    ],
                ]
            )
            ->add('n2', ChoiceType::class, [
                    'required' => true,
                    'placeholder' => '-- please select --',
                    'multiple' => false,
                    'choices' => [
                        'foo' => 'foo',
                        'bar' => 'bar',
                    ],
                    'autocomplete' => true, // same as "n1" but with autocomplete
                ]
            )
            ->add('n3', ChoiceType::class, [
                    'required' => true,
                    'placeholder' => '-- please select --',
                    'multiple' => false,
                    'choices' => [
                        'foo' => 'foo',
                        'bar' => 'bar',
                    ],
                    'autocomplete' => true,
                    'attr' => [
                        'placeholder' => 'Foo Bar', // now with attr placeholder
                    ],
                ]
            )
```


### Results

<img width="1004" alt="Capture d’écran 2024-09-06 à 19 55 12" src="https://github.com/user-attachments/assets/fdb8a287-7fb3-4b7c-970a-f4a4fbf04dc9">

**Comment by bretrzaun** [comment]
@smnandre It proves my point in test 1 - N2: The configured placeholder is ignored...

**Comment by smnandre** [comment]
Again, i copy you here the related paragraph from the documentation

> [!TIP]
> This option **only applies if the _multiple_ option is set to _false_**.

Now i'll try to answer once more :) 

> It proves my point in test 1 - N2: The configured placeholder is ignored...

Of course it is. Because it is not a valid option ChoiceType in this case (remember, the "placeholder" option only applies if the multiple option is set to false).  So Autocomplete does nothing different.

> However - I had the placeholder option set with the original ChoiceType. 

You had the option set, and it was not used in the HTML nor rendererd in any way. Because this option does not apply if the multiple option is set to true.

> Otherwise converting to a ChoiceType to an autocomplete will loose the placeholder unless the option is migrated as well.

You kept this option, and with no surprise it is not used by Autocomplete nor rendered in any way. Because this option applies only when the 'multiple' option is set to false.

Now, if you accept to follow the documentation of both ChoiceType and Autocomplete, and use the `attr  => ['placeholder' => ...`,  you will get the result you expect. 

😃

**Comment by bretrzaun** [comment]
Ok thanks.
