### ISSUE TITLE
[TogglePassword] Should called block from form theme be hardcoded?

### ISSUE THREAD

**Issue by reyostallenberg** [symfony/ux#2140]
[Here](https://github.com/symfony/ux/blob/5c17b26876e1ac544903d0a99837b6aa1cda0934/src/TogglePassword/templates/form_theme.html.twig#L2C69-L2C84) the block 'password' is called, but when a developer also do the trick with adjusting the block_prefixes like in here [TogglePasswordTypeExtension](https://github.com/symfony/ux/blob/5c17b26876e1ac544903d0a99837b6aa1cda0934/src/TogglePassword/src/Form/TogglePasswordTypeExtension.php#L76) and the priority of both extensions is in a way that TogglePasswordTypeExtension is loaded later, then the block of the developer is not called.

It could be something like this instead:
```twig
{% set blockname = 'password' %}
{% for block_prefix in block_prefixes %}
    {% if block_prefix == 'ux_toggle_password' %}
        {% set blockname = (block_prefixes[loop.index0 - 1] ~ '_widget') %}
    {% endif %}
{% endfor %}
{{ block(blockname) }}
```

What do you think?

**Comment by smnandre** [comment]
I think the idea here really was to offer a _plug-n-play_ theme for developpers using the default ones.

The documentation mention various options to use another form theme, or even not use the provided one.

If you are this _developer doing the trick with adjusting the block prefixes_, maybe you could directly add the css classes for the ux_password block ? 

```twig
{# somewhere on **your** theme, something like #}

{% block password_widget %}
    <div class="{{ toggle_container_classes|join(' ') }}">
       {# call parent or block depending on your theme #} 
    </div>
{% endblock %}
```

**Comment by reyostallenberg** [comment]
Okay, it's fine with me
