### ISSUE TITLE
[TwigComponent][Icons] Inconsistency between allowed attributes

### ISSUE THREAD

**Issue by norkunas** [symfony/ux#2148]
Twig components allows to provide an integer as attibute values and casts it, while `UX:Icon` doesn't allow it.

Valid example:
```twig
<twig:Test a="1" b="{{ 2 }}">
  test
</twig:Test>
```
Currently invalid:
```twig
<twig:UX:Icon a="1" b="{{ 2 }}" />
```

**Comment by smnandre** [comment]
I'm curious to know the real problem behind this (factual) observation ? 

What did you want to do here you could not  ?

**Comment by norkunas** [comment]
I was switching from custom icon component. In one twig component I had a loop where icon's are rendered and then binding `{{ loop.index0 }}` via data attribute and this is where the problem appear. Had to do `{{ '' ~ loop.index0 }}`.

So this was an expectation error, where you can write numbers to attributes via twig component and so `<twig:UX:Icon />` looks like a twig component with some exceptions :)

**Comment by smnandre** [comment]
Let's add this :)

**Comment by smnandre** [comment]
Does this fix from @Kocal solve all your use cases ?

#2149

**Comment by norkunas** [comment]
Yup
