### ISSUE TITLE
[StimulusBundle] `StimulusAttributes::addAction()` method miss encoding of the controller name in the `$eventName` parameter

### ISSUE THREAD

**Issue by 7-zete-7** [symfony/ux#2151]
Executing of the following code
```php
$attributes->addAction('@foo/controller_1', 'someAction', '@bar/controller_2:someEvent');
```

will produce `data-action` attribute
```html
<div ... data-action="@bar/controller-2:someEvent->foo--controller-1#someAction" ...>
```

The controller name of event is not normalized.

Now, in order for the `data-action` attribute to be generated correctly, need to write the already normalized name of the controller.

```php
$attributes->addAction('@foo/controller_1', 'someAction', 'bar--controller-2:someEvent');
```

This behavior also happens for Twig.

**Comment by smnandre** [comment]
As far as i know the even name can have a lot of forms, so i'm not entirely sure here what we can do without breaking things for others... 

Are you up for a PR ?

**Comment by 7-zete-7** [comment]
@smnandre, I have several ideas on how to do this without breaking the current functionality.

I can make a PR a little later.
