### ISSUE TITLE
[TwigComponent] Error in `debug:twig-component` with anonymous components in a bundle directory

### ISSUE THREAD

**Issue by tacman** [symfony/ux#2171]
Anonymous components within a bundle work as expected:

```bash
bin/console debug:twig-component

| SurvosBootstrap:accordion            |                                                              | @SurvosBootstrap/components/accordion.html.twig            | Anon |
| SurvosBootstrap:dropdown             |                                                              | @SurvosBootstrap/components/dropdown.html.twig             | Anon |
| SurvosBootstrap:tabs                 |                                                              | @SurvosBootstrap/components/tabs.html.twig                 | Anon |
```

However, if I create a component in a directory, it fails:

```bash
# in the bundle's templates/components directory
mkdir tabler && touch tabler/history-widget.html.twig
```

back to the app
```bash
bin/console debug:twig-component
```

```
In ComponentFactory.php line 254:
                                                                                                      
  Unknown component "tabler:history-widget". And no matching anonymous component template was found.  
                                                                                                      

debug:twig-component [<name>]
```

**Comment by smnandre** [comment]
What if you test with `SurbosBootstrap:tabler:history-widget` ?

**Comment by tacman** [comment]
I believe the problem is with the debugger, as indeed a component in a subdirectory works as expected, it's just the debugger that fails.

![image](https://github.com/user-attachments/assets/e1976189-e13d-4d14-aa1b-f2357c1e1025)

![image](https://github.com/user-attachments/assets/bd41e20b-0428-4a68-b6ee-7bf0fb1170f9)

**Comment by smnandre** [comment]
Oh sorry ...  it has been fixed by #2088 and will be released soon (next week probably) 

(i need to stop using the 2.x-dev when reproducing issues 🤦‍♂️ )

**Comment by tacman** [comment]
Funny, I just switched from using 2.x-dev because everything _seemed_ to be working with the release version!

**Comment by tacman** [comment]
fixed by https://github.com/symfony/ux/pull/2088
