### ISSUE TITLE
[Turbo] Progress bar CSP violation in production

### ISSUE THREAD

**Issue by DavidPetrasek** [symfony/ux#2175]
See: https://github.com/hotwired/turbo/issues/704#issuecomment-2352218461

Am I the only one experiencing this?

**Comment by smnandre** [comment]
Not sure if that can be related, but locally i had to "double-quote" the nonce in the config .. 

```yaml
# config/packages/nelmio_security.yaml

  # ... 

      style-src:
          - 'self'
          - 'https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/'
          - "'sha256-WAyOw4V+FqDc35lQPyRADLBWbuNK8ahvYEaQIYF1+Ps='"      

```

Without the `"'` Firefox considered the nonce invalid

**Comment by DavidPetrasek** [comment]
> "'sha256-WAyOw4V+FqDc35lQPyRADLBWbuNK8ahvYEaQIYF1+Ps='"    

I was also using this solution. (BTW that is not a nonce but a hash.)
Anyway, I solved it by using the right (style) nonce . It didn't work because I was using the wrong (script) nonce:
`<meta name="csp-nonce" content="{{ csp_nonce('script') }}">`
... which needed to change to:
`<meta name="csp-nonce" content="{{ csp_nonce('style') }}">`
... after that I removed the hash from NelmioSecurity config

**Comment by smnandre** [comment]
Ok i'll try. I will have some time on launch break i'll update and send you my test repo for Turbo. I think i have understood why the last error occurs.
