### ISSUE TITLE
[Live Component][Dependent Form Fields] reference lost during submit cause unwanted insertion instead of update

### ISSUE THREAD

**Issue by fGuix** [symfony/ux#2176]
Hello,
I'm using the dependent form fields in a project and I noticed I guess a bug.

In my form type, I have this code:
``` php
$builder
...
  ->addDependent('shippingAddress', 'shippingSameAsBillingAddress', function (DependentField $field, ?bool $billingSameAsShippingAddress) use ($options) {
      if (false === $billingSameAsShippingAddress) {
          $field->add(UserAddressType::class, [
              'mapped' => false,
              ...
          ]
          );
      }
  });
```
Notice this is an unmapped field.
During the POST_SET_DATA event, I populate the field with setData() and an entity of class UserAddress. Everything works well.

The problem comes with the submit operation. Doctrine tries to insert a new entity instead of updating the existing.
**A.** I checked the state of my form data, and in the form PRE_SUBMIT event, the id is still here:
<img width="524" alt="image" src="https://github.com/user-attachments/assets/00900ba2-208d-4d13-813e-92f0d0931355">
Then I checked in the form SUBMIT event, and the id is lost at this point:
<img width="369" alt="image" src="https://github.com/user-attachments/assets/efe5a34b-b7f8-4ba5-b39b-2afd39cf1a2b">
Thus, it tries to create a new userAdress.

**B.** I tried replacing the dependent field with a classic one, and it works as expected (updating the entity instead of trying to create a new one).

**C.** might be related to [this issue](https://github.com/symfony/ux/issues/2100) as I didn't get the problem when creating a new one. Only when editing an existing.

**Comment by smnandre** [comment]
The dependant form field is not an UX package, so i'll do what i can :) Do you think you could create a minimal reproducer that show the bug, so we can have a look ?

**Comment by fGuix** [comment]
> The dependant form field is not an UX package, so i'll do what i can :) Do you think you could create a minimal reproducer that show the bug, so we can have a look ?

Ho! sorry, I didn't notice it was a different repo. Moving to https://github.com/SymfonyCasts/dynamic-forms/issues/34
