### ISSUE TITLE
[LiveComponent] Testing forms causes exeption "There is currently no session available."

### ISSUE THREAD

**Issue by daFish** [symfony/ux#2177]
I'm trying to test my live component which contains a form. The following code raises an exception of type `Symfony\Component\HttpFoundation\Exception\SessionNotFoundException`.

My sample testcode:
```
$formComponent = $this->createLiveComponent(
        name: ProductionForm::class,
)->actingAs($testUser);

$formComponent->set('form_name.title', 'Loreum Ipsum');
```

The user and the field exist. What else is needed to get the test working?

**Comment by daFish** [comment]
Forgot to add: I‘m using the latest versions of Symfony and the UX components.

**Comment by smnandre** [comment]
Hi @daFish !

I'd need a bit more information to help you I think, as I dont see right now what could be the problem. Could you maybe share some code from your test and/or your component? 

Or, even better, if you could create a minimal bug reproducer ?

**Comment by daFish** [comment]
Hi @smnandre,

I have created a reproducer. The commit with all relevant changes is https://github.com/daFish/symfony-ux-issue-2177/commit/12cc45ff1984b1bdfb3977382a0aa4961e38cbd5

The project has been created from the Symfony demo application. Running the tests with `vendor/bin/phpunit tests/Components/ReportComponentTest.php` fails with the above exception.

**Comment by smnandre** [comment]
@daFish thank you for creating this ideal reproducer 😃 

I'll look at it tonight!

**Comment by smnandre** [comment]
It seems to occur when the CSRF token is generated, but i'm not too sure why right now.

**Comment by daFish** [comment]
No change with the latest releases of Symfony UX packages.

**Comment by daFish** [comment]
Ok, after some digging and with the help of Fracsi in Slack I got to the point where the exception is no longer thrown:
```
$request = new Request();
$request->setSession($this->createMock(SessionInterface::class));
self::getContainer()->get(RequestStack::class)->push($request);
```

Adding this boilerplate code before creating the live component in the test solved it. However, I was under the impression that something like this isn't needed at all.

**Comment by mkrauser** [comment]
I have this issue as well. This occurs only in Components using the ComponentWithFormsTrait. 

In ComponentsWithFormsTrait::initializeForm (which is called PostMount), the FormView is generated, which in turn creates a CSRF-Token. 

When running Tests, there is no Request on the RequestStack. That's why the Session-Object cannot be fetched from the RequestStack.

There is already a PR for this: https://github.com/symfony/ux/pull/2254
