### ISSUE TITLE
[Live component] data-model triggers 'Invalid model name' error when array key does not exists

### ISSUE THREAD

**Issue by fransweerts** [symfony/ux#2195]
Hello,

I have a collection form, and I am using the data-model attribute for saving the input value. 
It's an array because the form can contain multiple rows.
```php 
#[LiveProp(writable: true)]
public array $travelDistances = [];
```  

The input field has the data-model attribute with the array key.
```Twig 
 {{ form_row(itemForm.travelDistance, { 'attr' : {'data-model' : 'travelDistances.'~(loop.index-1), 'data-action' : 'live#action', 'data-live-action-param': 'calcDistanceTravelCosts'} }) }}
```  

After changing the input value, I see this javascript error in the console:
``
Error: Invalid model name "travelDistances.0".
``

The error is triggerd because the array is initialised empty. When I initialise the array the issue is solved. Its fine as temporary fix, but I dont think this a correct long term solution.  
```php 
#[LiveProp(writable: true)]
public array $travelDistances = [0 = ""];
```

Maybe it something to do with this merge:  https://github.com/symfony/ux/pull/1216/files ?

**Comment by smnandre** [comment]
Pure curiosity, do you mound the travelDistances into the LiveComponent ? 

Also (if not done already), you may need to install phpdocumentor (cf: https://symfony.com/bundles/ux-live-component/current/index.html#liveprop-for-entities-more-complex-data)

Unrelated question, maybe naive as i don't know the rest of your component: do you need both data-model and the live action ? The data-model would already trigger a re-render once the prop is updated.

You may look at [this recent PR](https://github.com/symfony/ux/pull/1990) and see if that solves your problem (if you're using the latest version of Live Component) 

If not, maybe you can create a small reproducer ?

**Comment by fransweerts** [comment]
> Pure curiosity, do you mound the travelDistances into the LiveComponent ?

No, I did not. You have pointed me in the right direction. I've added a PostMount hook which loops the collection rows and initialize the array foreach index key with empty value. This fixes my issue. 

Thank you!
