### ISSUE TITLE
[Autocomplete] Allow autocomplete for FormTypes that extend ChoiceType

### ISSUE THREAD

**Issue by Chris53897** [symfony/ux#2197]
https://symfony.com/bundles/ux-autocomplete/current/index.html#form-options-reference

We can add this to ChoiceType to get HTML-Choices.
`'autocomplete' => true,
 'options_as_html' => true,`
 
 It would be great if this could work for Types that extend ChoiceType. I guess the best solution would be with a interface.
 
 Or maybe there is already a solution for this?

**Comment by smnandre** [comment]
The form type extensions work with the "parent" system (described in the docs page "[how to create a custom type](https://symfony.com/doc/current/form/create_custom_field_type.html#creating-form-types-based-on-symfony-built-in-types)" ) 

So if you have a class that _extends_ ChoiceType, i'm not sure if this can work.
However, if you're using `getParent`, this probably should work as expected. 

Could you give us more details on how you're using it and what is not working as expected ?

**Comment by Chris53897** [comment]
Thanks @smnandre 

My error was that i extend from ChoiceType, and not from AbstractType.
Extending from ChoiceType with getParent leads to this error.
`An exception has been thrown during the rendering of a template ("Unable to render the form because the block names array contains duplicates: "_list_listing_form_xxx_help", "choice_help", "choice_help", "form_help".") in "bootstrap_5_horizontal_layout.html.twig".`


This code works. I will close this Issue.

`final class BoolChoiceType extends AbstractType
{
    public function configureOptions(OptionsResolver $resolver): void
    {
        parent::configureOptions($resolver);

        $resolver
            ->setDefault('choices', static function (Options $options): array
            {
                return [
                    '<span class="badge bg-success">Yes</span>' => true,
                    '<span class="badge bg-danger">NO</span>' => false
                ];
            })
            ->setDefault('autocomplete', true)
            ->setDefault('options_as_html', true)
        ;
    }

    public function getParent(): string
    {
        return ChoiceType::class;
    }
}`

**Comment by smnandre** [comment]
Perfect! Thanks for the update :)
