### ISSUE TITLE
[Documentation] [Live Component] LiveAction does not redirect after submitting form

### ISSUE THREAD

**Issue by matthieumastadenis** [symfony/ux#2205]
Hello, I have a suggestion about the [Redirecting](https://symfony.com/bundles/ux-live-component/current/index.html#actions-redirecting-and-abstractcontroller) part of Live Components documentation.

I spent some time figuring out why my component wasn't triggering a redirection despite I correctly followed the docs by:

1. Extending AbstractController
2. Returning a RedirectResponse from my LiveAction method

The issue was because I was calling my LiveAction from `__invoke()` (without returning its result) rather than calling it directly.

As an example, **this will not work**:

```php

    public function __invoke(): static
    {
        $this->create();
        return $this;
    }

    #[LiveAction]
    public function create(): RedirectResponse|static
    {
        $this->submitForm();

        $form = $this->getForm();

        if ($form->isSubmitted() && $form->isValid()) {
            // handle form result...

            return $this->redirectToRoute('other_route');
        }

        return $this;
    }
```

The fix is very easy: by simply returning the result of the create method from `__invoke()`, **the redirection will work as expected**:

```php

    public function __invoke(): RedirectResponse|static
    {
        return $this->create();
    }
```

I think this could be mentioned in the Redirecting part of the docs to avoid other people to be stuck on the same issue.

**Comment by smnandre** [comment]
Thanks for sharing! 

Documentation says a LiveAction should return a RedirectResponse 
(cf: https://symfony.com/bundles/ux-live-component/current/index.html#actions-redirecting-and-abstractcontroller)

In your first example, you return "$this" (the component instance).

I'm closing here, but feel free to open a PR if you have documentation improvements to suggest!
