### ISSUE TITLE
[UX][Autocomplete] - QueryBuilder doesn't return results but dd(...) return

### ISSUE THREAD

**Issue by HugoSEIGLE** [symfony/ux#2208]
Hi all, 

I have a problem with the autocomplete field (AJAX).
I'm writing this issue cause I haven't found anything similar in existing issues (open and closed).

Presently, I have this `query_builder` in the definition of my autocomplete field :
```php
<?php

// ...

'query_builder' => function (ArticleRepository $articleRepository) {
    $query = $articleRepository->createQueryBuilder('article')
        ->join('article.product', 'product')
        ->...
    ;

    return $query;
},

// ...
```

When I put some text in my Autocomplete Select, I didn't have any result :
```json
{
      "results": [ ],
      "next_page": null
}
```

But if I didn't return the `$query` variable and put a dump and die of `$query->getQuery()->getResult()`, my DQL request gives me a result.

So I don't understand what the differences are that can cause this.
I don't do anything else in the form that calls this Autocomplete Field.

Thank's in advance for your help

**Comment by WebMamba** [comment]
I think you just have a syntax issue:

```php
'query_builder' => function (Options $options) {
                return function (EntityRepository $er) use ($options) {
                    $qb = $er->createQueryBuilder('o');

                    $excludedFoods = $options['extra_options']['excluded_foods'] ?? [];
                    if ([] !== $excludedFoods) {
                        $qb->andWhere($qb->expr()->notIn('o.id', $excludedFoods));
                    }

                    return $qb;
                };
            }
```

the query_builder expects a callback that returns a callback, here is the example from the doc. Tell me if it helps

**Comment by HugoSEIGLE** [comment]
@WebMamba Thanks for your answer, but the result is still the same. It returns nothing in the autocomplete, but when I use $query->getQuery()->getResult(), I get the result I want.

**Comment by WebMamba** [comment]
Hum, so we have a typo in the doc?
It should be ?
```php
'query_builder' => function (Options $options) {
                return function (EntityRepository $er) use ($options) {
                    $qb = $er->createQueryBuilder('o');

                    $excludedFoods = $options['extra_options']['excluded_foods'] ?? [];
                    if ([] !== $excludedFoods) {
                        $qb->andWhere($qb->expr()->notIn('o.id', $excludedFoods));
                    }

                    return $qb->getQuery()->getResult();
                };
            }
```
