### ISSUE TITLE
[LiveComponent] Make a LC read url parameters at mounting time

### ISSUE THREAD

**Issue by Nayte91** [symfony/ux#2215]
Hello,

Part of the discussion about [faceted search menu and results page combo](https://github.com/symfony/ux/discussions/2212) (challenge point 1), I would like to report a behavior of LCs that disallow some cool tricks.

Currently, imagine you have an ArticleResults page, populated from your db with various filters, that user brings to you with url parameters. For now, you have your regular Symfony controller, that will process the parameters, send them as filters to your ORM, that will give you back a Pagination or an array of articles (called $articlesPage for example), that you will send to view.

Let's assume that you want to upgrade this with an ArticleResults LC, and for independency and simplicity purposes, you want not to pass the $articlesPage from your controler to the LC, but rather let the LC do its logic when rendering.

For some scenarii, doing an independant LC that will do logic at rendering is OK; but in our case, we currently can't, LC and subsequently Twig and SF will throw an error because $articlesPage doesn't exist yet.

My understanding of the current behavior is that when you reach mount() in LC to do logic and hydrate the `public Pagination $articlesPage`, your actual url-mapped-properties ($page, $name, $date, ...) aren't yet populated from the Request parameters.

Allowing to control the flow of this url params mapping should allow to do logic based on it during mounting, improving drastically simplicity of the system (no need to handle the filters twice, in controler and LC), and independency/reusability/shareability of a LOT of LCs based on logic at Request.

**Comment by WebMamba** [comment]
Hum sorry could you share your controller, template and LiveComponent. I think I missing something

**Comment by smnandre** [comment]
@Nayte91 i think there is something that miss-guided you here (components initialize state on "mount", not with "construct"

But the behaviour you're looking for is exactly what we did for the [icon page](https://ux.symfony.com/icons?query=aa&set=) of the website

No search in the controller: 
https://github.com/symfony/ux/blob/2.x/ux.symfony.com/src/Controller/Icons/IconsController.php

No parameter given to the live component:
https://github.com/symfony/ux/blob/bc3d442ba5a4ca75e72c6c3468b77fbd44b1028b/ux.symfony.com/templates/icons/index.html.twig#L44

LiveComponent SearchIcon with LiveProps binded to the query string
https://github.com/symfony/ux/blob/bc3d442ba5a4ca75e72c6c3468b77fbd44b1028b/ux.symfony.com/src/Twig/Components/Icon/IconSearch.php#L30-L34

;)

**Comment by Nayte91** [comment]
Hello, thank you for your answers,

You're right I typed my issue away from my project, and I mixed "construct" and "mount" concepts; it's all about mounting timings, I remember trying #[Mount], #[PreMount], etc.

I'll give a shot of your proposition ASAP! ❤️

**Comment by Nayte91** [comment]
Hello @smnandre,

I tried this and you're right, I can make this works without passing an object from the regular controller.

Thank you very much for your answer and sorry for the missunderstanding!

I have one little question if I may: Is there any tricky point of the #[PostMount] empty function [here](https://github.com/symfony/ux/blob/bc3d442ba5a4ca75e72c6c3468b77fbd44b1028b/ux.symfony.com/src/Twig/Components/Icon/IconSearch.php#L44)?

**Comment by smnandre** [comment]
> I have one little question if I may: Is there any tricky point of the #[PostMount] empty function [here](https://github.com/symfony/ux/blob/bc3d442ba5a4ca75e72c6c3468b77fbd44b1028b/ux.symfony.com/src/Twig/Components/Icon/IconSearch.php#L44)?

Let's see :) #2244
