### ISSUE TITLE
[LiveComponent] Inheritance in live components

### ISSUE THREAD

**Issue by tito10047** [symfony/ux#2217]
It would be nice if you could inherit live component from normal component.

```twig
{# templates/components/Alert.html.twig #}
<div {{ attributes.defaults({class: 'alert alert-'~type}) }}">
    {% block content %}{% endblock %}
</div>
```
```twig
{# templates/components/SuccessAlertLiveComponent.html.twig #}
{% component Alert with attributes.defaults({class:"foo"}) %}
    {{ block(outerBlocks.content) }}
{% endcomponent %}

```

Is something like this possible?

**Comment by smnandre** [comment]
LiveComponent have no knowledge of their "outerblocks" so it would not work during re-render

**Comment by tito10047** [comment]
Yes, of course. Stupid example copied from docs.
I have problem only with this "with attributes.defaults({class:"foo"})" . With this I get parse error

**Comment by smnandre** [comment]
Can you maybe show the code that triggers this error?

**Comment by smnandre** [comment]
Oh i'm sorry i did not pay enough attention.. 

You cannot pass "attributes" like this, as it is not a mapping/array but a special object, and it is required to be renderered in its template :/ 

Let's say you want do the same for Twig Components... then you could use `with {attributes: attributes.defaults( ...) }` or `with attributes.defaults(...).toArray()`

**Comment by tito10047** [comment]
Yes, that is what I means. Thanks :)
