### ISSUE TITLE
Backport `twig_to_array` fix for twig-ux-component to version 2.9 or add conflict to 

### ISSUE THREAD

**Issue by leroy0211** [symfony/ux#2247]
We're in the middle of updating a legacy application. And we stumble upon the following. 

```
An exception has been thrown during the rendering of a template ("Call to undefined function twig_to_array()").
```

I think I've pinned it down to the combination of:

* `symfony/ux-twig-component@2.9.1`   (php 8.0 restriction)
* `twig/twig@3.14.0` 

This is a valid combination, however we are yet pinned to an old version of php. 

Could you either backport the fix, or add a conflict to it?  Thanks!

**Comment by smnandre** [comment]
Just to be sure to understand.. you are using twig 3.14 and ux-twig-component 2.9.1, right ?

**Comment by leroy0211** [comment]
Sorry, I was a bit in a rush when I created the issue. 

Yes, those are the versions I have installed at the moment, and they are giving an issue.  The `twig_to_array` was fixed in https://github.com/symfony/ux-twig-component/commit/27f4e752d260938f8d4d636556106a9c7bd4a2bf.  

But it's not Backwards compatible with the limitation of php 8.0.   I know it's EOL, but we are in the middle of an upgrade, and this is now blocking without having to lock these packages to older versions.

**Comment by smnandre** [comment]
I mean it's not a "fix", it was to adapt to ... Twig :) Do you need to use the [last](https://github.com/twigphp/Twig/blob/5ac03a440cb1a3b3b8b1e08f692e42443e62a382/CHANGELOG#L28) Twig version ?

**Comment by leroy0211** [comment]
I know. We are using the latest twig version.  But symfony/ux-twig-component version 2.9.1 (without the adaption) is the last one compatible with php8.0.
  
I know that php8.0 is EOL. But could you create a 2.9.2 version that has the adoption added? 

Otherwise we need to pin twig to an old version, create a temporary fork of twig-ux-component or replace the `ComponentNode` somehow with a custom one.  While I guess, adding BC to version 2.9 would be more useful for anyone else having the same situation. Although probably not many will have this issue.

**Comment by nicolas-grekas** [comment]
We just tagged v2.9.2 with the patch
Please upgrade to PHP 8.1 ASAP also ;)

**Comment by leroy0211** [comment]
Thanks a lot for the patch. I hope this will help us speeding up the update.
