### ISSUE TITLE
[AutoComplete] Weak dependency on symfony/form

### ISSUE THREAD

**Issue by alexislefebvre** [symfony/ux#2252]
I followed these steps to create a bug reproducer:

1. https://symfony.com/doc/5.x/contributing/code/reproducer.html#reproducing-complex-bugs
2. https://symfony.com/bundles/StimulusBundle/current/index.html
3. https://symfony.com/bundles/ux-autocomplete/current/index.html

And I got blocked when adding `class AnyForm extends AbstractType`: without `symfony/form` installed, `AbstractType` is not available.

So I had to install `symfony/form`, and this may not be obvious for newcomers.

Possible solutions:

- add `composer require symfony/form` in the documentation of `ux-autocomplete`
- declare that `symfony/ux-autocomplete` depends on `symfony/form` in https://github.com/symfony/ux/blob/2.x/src/Autocomplete/composer.json`

**Comment by MrYamous** [comment]
As this component can be used outside of a Symfony project, adding `symfony/form` to composer requirements doesn't seem to me to be a good solution.
I'm going to make a PR to add this precision to the documentation, it's a good point.
