### ISSUE TITLE
[TwigComponent] Test if component exists (guard?)

### ISSUE THREAD

**Issue by tacman** [symfony/ux#2255]
The new {% guard %} tag merged today is will very helpful for testing if a filter/function/test exists.

Is there a way to test if a component exists?

```twig
{% guard component badge %}
   <twig:badge color="red">Badge!</twig>
{% else %}
   <span class="badge">no component</span>
{% endguard %}
```

**Comment by Kocal** [comment]
Hi Tac, 

for the moment there is no way to test if a Twig component exists.

**Comment by tacman** [comment]
I wonder if the ux component could "hook into" the guard tag.

Two situations: 
* the ux component isn't installed
* ux component is installed by there's no component of a particular name.

The issue is mostly with bundles.  I find myself using components in other bundles, which creates a dependency that should be optional.  

Not exactly related to components, but I'd like a backup for ux_icon() as well, or at least a way to ignore it, since usually icons are a bonus.  I love ux_icons, I got rid of including all of fontawesome and bootstrap-icons and my attempts to normalize them.

BUT before I could do <span class='fas fa-some-icon'></span> and it would gracefully fail.  Now it throws an error.

**Comment by smnandre** [comment]
We won't use the guard tag as it is really destined to rare cases (see original issue) where a bundle may need two options for certain filters / functions depending on the parent app choices.

Regarding the component existence, we cannot and won't do it in 2.x. But this is absolutely something i'd like to have in 3.x.
