### ISSUE TITLE
Document how to install in China (JsDelivr is not accessible reliably)

### ISSUE THREAD

**Issue by SimonVanacco** [symfony/ux#2256]
Hi,

In China the JsDelivr CDN is not accessible in a reliable manner. 

This is a bummer as anybody following a Symfony tutorial will do a `composer require webapp` and be greeted with this : 

![image](https://github.com/user-attachments/assets/0dfdfac4-5f9d-4854-8cf6-2047aae6454c)

or this : 

![image](https://github.com/user-attachments/assets/e064ffb5-5981-4685-9afe-83c6483d1aec)

Ideally there should be some documentation so that these users are not road-blocked on their Symfony install. What would you recommend ? 

Right now I'm installing everything in the webapp-pack except for Symfony UX packages, but I will want them at some point.

Thanks!

**Comment by Kocal** [comment]
Hi Simon, unfortunately I don't know this subject at all.

AFAIK JsDelivr should even be accessible in China, see https://www.jsdelivr.com/network and https://status.jsdelivr.com/. I think the best you can do is to contact them directly :/

**Comment by smnandre** [comment]
This issue should be posted on the symfony/symfony repository i suppose, as it's more about AssetMapper 

@kbond ?

**Comment by kbond** [comment]
Definitely looks like there's issues in China: https://github.com/jsdelivr/jsdelivr/issues/18407

Looks like unpkg can be used in China without issue.

Agree this should be on `symfony/symfony` or `symfony/symfony-docs`.

**Comment by SimonVanacco** [comment]
OK i'm closing this ticket and opening again on `symfony/symfony` thank you for your insight !
