### ISSUE TITLE
[Twig Component]Update from 2.19.2 to 2.20.0 > undefined ComponentExtension::render()

### ISSUE THREAD

**Issue by Gulivertx** [symfony/ux#2271]
Hello,

When I update my project with last Twig Component bundle I get an error : undefined ComponentExtension::render().

`An exception has been thrown during the rendering of a template ("Call to undefined method Symfony\UX\TwigComponent\Twig\ComponentExtension::render()").`

Did I miss something necessary to used this last update ?

Thank's for any help.

**Comment by Kocal** [comment]
Hi, did you try to clear your Symfony cache?

**Comment by Gulivertx** [comment]
Thanks for your answer. Yes for sure, I didn't mention because it's a natural task after each update. 
I also deleted all cache directory because clearing the cache was not working. 

Edit : by the way I run Symfony 6.4 and php 8.3.

**Comment by Kocal** [comment]
Note that some people got the same issue than you on Symfony Dev slack, and they solved it by removing `var/cache` and clearing the cache (through `bin/console`) again: https://symfony-devs.slack.com/archives/C01FN4EQNLX/p1728386542673789

**Comment by Gulivertx** [comment]
Aerf cannot understand.
I try again with **rm -Rf var/cache/dev && dev cac:c && dev cac:w** and now it works !!!

First I tried this
dev cac:c (doesn't work)
rm -Rf var/cache/dev (doesn't work)


Thank you for your help and recommandation.
