### ISSUE TITLE
Improve the link to docs on each package

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/ux#2273]
In the current web design, the `Documentation` link is displayed at the bottom of the page. For most folks, this is way below the visible contents when loading the page:

![](https://github.com/user-attachments/assets/3cda6ba9-7272-48b2-baf0-cf0fa563d2c2)

I propose to display a link to the docs right next to the command shown to install the package:

![](https://github.com/user-attachments/assets/9af7e19c-0010-414a-bb91-f70e0d6cf0af)

Don't mind the text and the "design" of my mockup. It's just a quick mockup to give you an idea of the exact location where I'd like this link to be.

**Comment by Kocal** [comment]
That would be a great improvment :)

**Comment by smnandre** [comment]
Sub menus for every package pages is a work in progress... i really hope to release all this before vienna :)

**Comment by Kocal** [comment]
Closing, since #2309 has been merged
