### ISSUE TITLE
[LiveComponent] Response 400 after application idle for long time

### ISSUE THREAD

**Issue by tito10047** [symfony/ux#2278]
Hi, 
I have Aplication with live component which is opened in background for long time (one day).
When I wake up mornig, and do interaction with application with live component, I get Status code from server "400 Bad Request" . This is happening every morning.
Actualy is is error "Invalid CSRF token." but its show 400 and popup big screen error.

How I can suppress or catch this error and reload page?

Thanks

**Comment by smnandre** [comment]
Naive question, but do you need crsf protection ?

**Comment by tito10047** [comment]
Yes, in current project I can disable crsf. But this will be happening in all my projects.
So, question is still justified. How I can catch error page and show my own error? like "your session is expired, please reload page"

**Comment by smnandre** [comment]
There is an event you can hook yourself on: 

> response:error args (backendResponse: BackendResponse, controls: { displayError: boolean })

https://symfony.com/bundles/ux-live-component/current/index.html#javascript-component-hooks

There is also [a PR in progress](https://github.com/symfony/ux/pull/1916) to improve this modal and display custom attribute / content if you want to have a look

**Comment by tito10047** [comment]
Thanks
