### ISSUE TITLE
[TwigComponent] Roadmap to first stable release

### ISSUE THREAD

**Issue by polarbirke** [symfony/ux#228]
Is there a plan to release a stable version in the near future? The current tag is `v2.0.1` (which sounds like this is already out of beta?) but the README warns 

>EXPERIMENTAL This component is currently experimental and is likely to change, or even change drastically.

I would _very much_ like to use TwigComponent and possibly LiveComponent in client projects, but drastic changes would be a no-go, sadly.

Thanks for this initiative in any case! Super hyped to use this eventually. 👍

**Comment by kbond** [comment]
Hey! You can check #102 for a rough LiveComponent roadmap.

For the [experimental](https://symfony.com/doc/current/contributing/code/experimental.html) status, we left it this way to give us some wiggle room to see how it's used and how users want to use it. Based on feedback, we are free to add features/adjust code and not be tightly tied to Symfony's BC policy. That being said, I don't expect major BC breaks/drastic changes. Any that do happen will be well documented.

**Comment by polarbirke** [comment]
Sounds fair. I'll try it out then :)
