### ISSUE TITLE
[TwigComponent]  change `cva`  to `html_cva`

### ISSUE THREAD

**Issue by seb-jean** [symfony/ux#2291]
`cva` twig function is deprecated. Is it worth changing the documentation to use the `html_cva` function?

**Comment by smnandre** [comment]
There is already a note about it, do you think we should make it more visible ? 
<img width="850" alt="Capture d’écran 2024-10-23 à 08 54 33" src="https://github.com/user-attachments/assets/62975351-a0cf-43b9-a782-22c6bf8d2864">


Renaming: i'm not sure, as keeping the current naming will be more usefull for people searching in search engine, using previous Twig Component versions, etc... at least until version 3.0  :) 

Then... i doubt we maintain the documentation here as it is now a official Twig package and has it's own documentation 🤷‍♂️

**Comment by seb-jean** [comment]
Yes, it doesn't make sense to change the documentation indeed.
