### ISSUE TITLE
[Dropzone] - Problems after #2154 ?

### ISSUE THREAD

**Issue by Chris53897** [symfony/ux#2311]
We noticed problems with Dropzone after the lastest update from 2.20.0 => 2.21.0

Most of the times Adding (not replaceing) works correct.
But sometimes (tested on Safari and Chrome) on/after the drop, the following errors occurs.

In our case it happens with .pdf-Files

![error-safari-2024-10-24 um 13 51 58](https://github.com/user-attachments/assets/c5923062-60cd-422e-a20e-c8740dec5437)

After a new load of the page. The area inside the dotted line is empty. But the "x" button ont the right side is visible.
![empty](https://github.com/user-attachments/assets/bcae449b-e505-4ee9-92b9-8760b6ec2f87)

Error repeats now.

I assume related to.
@rrr63 Maybe you can have a look?
https://github.com/symfony/ux/pull/2154

I will provide more info if i find a way to reproduce it.

**Comment by smnandre** [comment]
@Chris53897, 

I'm very sorry if this is related to recent changes.

If you could provide me some minimal reproducer (even textual / step by step one), i will investigate to provide a quick fix

**Comment by Chris53897** [comment]
I could not replicate it yet. But maybe this video helps. Is is not the same error.
https://github.com/user-attachments/assets/4ae1df33-d1c2-4394-9bd0-1c959d49c23e

**Comment by smnandre** [comment]
At the beginning of your video, the preview block is enabled but with no previous upload... maybe you did send it, and did not restore initial state of the component ?

**Comment by Chris53897** [comment]
Yes. You can see a bit more in this video. The empty preview block needs to be manual cleared by clicking on the `x`
https://github.com/user-attachments/assets/31e40fd6-1fb4-46b2-91c3-1c8027e5c332

**Comment by rrr63** [comment]
@Chris53897 , @smnandre 

Sorry if this is related my last PR, i can't reproduce it, waiting for a minimal repro

**Comment by smnandre** [comment]
Don't worry @Chris53897!  Changes sometimes impact this gray zone of non-documented behaviour, zone that existing project may be counting on. We will react and fix what we can as soon we can reproduce ;) 

And thank you again for your PR ;)

**Comment by Chris53897** [comment]
I have downgraded to 2.20 and check if the error still occurs. Just to be sure, that 2.21 is the reason for the problem.

**Comment by smnandre** [comment]
I really tried hard and could not reproduce your problem. I'm seeing the expected behaviour on this [dropzone demo](https://ux.symfony.com/dropzone) (running the [2.21 version](https://ux.symfony.com/assets/@symfony/ux-dropzone/controller-qXyjKzb.js)) on Symfony UX website.

Fact is: the PR from @rrr63 did not change a thing on how the component should render on page load. It only deals with dragenter/dragleave.

On your video, the "close preview button" should not be visible in the first place. Maybe you do have some custom CSS with special rules or some JS code that interact with the component on render ?

**Comment by rrr63** [comment]
I also tried to reproduce this bug, unsuccessful. As @smnandre said, I think it could happen by some 'custom' JS/CSS files
I can't find any [incompatibility with other browsers](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/dragenter_event) either

**Comment by Arnaudgouel** [comment]
I had the same problem, to reproduce the issue, i have a DropzoneType inside a LiveComponent, i think the LiveComponent rerender the field and destroy the preview name, when i'm not inside a LiveComponent it works well. To overcome this issue i added 
`data-model="norender"` to the form_row
