### ISSUE TITLE
[Site] Code blocks display incorrect paths

### ISSUE THREAD

**Issue by hellomedia** [symfony/ux#2333]
```
src/Twig/FoodVote.php
```

![image](https://github.com/user-attachments/assets/14373ab9-0749-4116-b429-520fa32a848e)

The default file structure is

```
src/Twig/Components/FoodVote.php
```

as shown in more recent examples

![image](https://github.com/user-attachments/assets/d2827e9c-91b6-45d1-a371-d9dc77955075)

```
twig_component:
    defaults:
        # Namespace & directory for components
        App\Twig\Components\: 'components/'
```

**Comment by smnandre** [comment]
Thank you  @hellomedia !

I'll fix it later in the week (i need to release something first)

**Comment by smnandre** [comment]
Good, thank you @hellomedia
