### ISSUE TITLE
500 Error when deploying

### ISSUE THREAD

**Issue by TomoyaHamasaki** [symfony/ux#2341]
When I deploy my project, I frequently encounter 500 errors, which appear related to auto-wiring issues. The only solution I’ve found so far is to undo recent changes to Twig components, clear the cache, and then redeploy. Anyone else experienced something similar?

**Comment by Kocal** [comment]
Hi, by any chance do you have some logs to share with us? It would help us to understand what is happening and to solve it.

Thanks!

**Comment by TomoyaHamasaki** [comment]
`Uncaught Error: Too few arguments to function App\\Service\\AssetService::__construct(), 3 passed in /app/var/cache/prod/Container3JqsrB1/getAssetServiceService.php on line 21 and exactly 4 expected`

Running `symfony console cache:clear` doesn't fix it. Using latest version of Symfony 7.x

`git revert --no-commit 87158cb6d3fc7e6d4d09a4346687d39706f83278..9844bfe9199049e986d5a18469df540b9e15d471 -m 1`

The first id is the one we're reverting to, the second is the most recent, idk what the -m 1 means really.

**Comment by Kocal** [comment]
What is that class `App\Service\AssetService`? I don't see it in UX repository

**Comment by TomoyaHamasaki** [comment]
AssetService is a service class that we made that handles assets (images).

**Comment by TomoyaHamasaki** [comment]
This happens when trying to rename a class. We try to find that class, but it obviously doesn't exist. Somehow that data is in the cache or something. The same issue happens more commonly when creating Twig components.

`{"message":"Uncaught PHP Exception RuntimeException: \"Unable to create the cache directory (/app/var/cache/prod/twig/10).\" at FilesystemCache.php line 53","context":{"exception":{"class":"RuntimeException","message":"Unable to create the cache directory (/app/var/cache/prod/twig/10).","code":0,"file":"/app/vendor/twig/twig/src/Cache/FilesystemCache.php:53","previous":{"class":"Symfony\\Component\\ErrorHandler\\Error\\ClassNotFoundError","message":"Attempted to load class \"ConstantNamesExtension\" from namespace \"App\\Twig\".\nDid you forget a \"use\" statement for another namespace?","code":0,"file":"/app/var/cache/prod/ContainerUCiJbKI/getTwigService.php:50"}}},"level":500,"level_name":"CRITICAL","channel":"request","datetime":"2024-11-05T20:09:32.211297+00:00","extra":{}}`

**Comment by smnandre** [comment]
> This happens when trying to rename a class.

In prod did you re-do a composer install after? Did you clear the full app cache too (`bin/console cache:pool:clear --all`) ? 

As this error seems to be triggered at the container level, i'm not sure how this is related to Symfony UX here 🤷

**Comment by TomoyaHamasaki** [comment]
We don’t directly do the composer install, the platform.sh build script does that during every deploy. Tried clearing the cache in several different ways including rm -rf var/cache/prod and it has no effect.

> As this error seems to be triggered at the container level, i'm not sure how this is related to Symfony UX here 🤷

After install Twig components, I started having this issue. Sorry, if this isn't the place for it, I understand. You can close it.

**Comment by TomoyaHamasaki** [comment]
`{“message”:“Uncaught PHP Exception Twig\\Error\\RuntimeError: \“An exception has been thrown during the rendering of a template (\“Symfony\\Component\\Form\\FormRenderer::renderBlock(): Argument #1 ($view) must be of type Symfony\\Component\\Form\\FormView, null given, called in /app/var/cache/prod/twig/bc/bc472653b3731b19615fa1f57ed3c509.php on line 893\“).\” at list.html.twig line 128",“context”:{“exception”:{“class”:“Twig\\Error\\RuntimeError”,“message”:“An exception has been thrown during the rendering of a template (\“Symfony\\Component\\Form\\FormRenderer::renderBlock(): Argument #1 ($view) must be of type Symfony\\Component\\Form\\FormView, null given, called in /app/var/cache/prod/twig/bc/bc472653b3731b19615fa1f57ed3c509.php on line 893\“).“,”code”:0,“file”:“/app/templates/recipient/list.html.twig:128",“previous”:{“class”:“TypeError”,“message”:“Symfony\\Component\\Form\\FormRenderer::renderBlock(): Argument #1 ($view) must be of type Symfony\\Component\\Form\\FormView, null given, called in /app/var/
cache/prod/twig/bc/bc472653b3731b19615fa1f57ed3c509.php on line 893”,“code”:0,“file”:“/app/vendor/symfony/form/FormRenderer.php:57"}}},“level”:500,“level_name”:“CRITICAL”,“channel”:“request”,“datetime”:“2024-11-06T16:28:10.405928+00:00”,“extra”:{}}`

Here's what happened after deploying, just now, after making changes to Twig templates.

So I go in, comment out some stuff near the lines it’s complaining about, deploy it, then uncomment it and deploy again.

**Comment by smnandre** [comment]
This kinda looks to me more related to Form/Twig cache  than to TwigComponent.

Can you show us what'is this script maybe ? Or the versions of Twig and TwigComponent.

I'd like to help but for now i don't see anything related to TwigComponent :|

**Comment by TomoyaHamasaki** [comment]
I moved a FormType file and its related controller logic from the Controller and FormType class over to a Twig component. Maybe I did jump the gun in assuming it to be a Twig component issue. Where should I report this?

Thank you for trying, I really appreciate it.

**Comment by smnandre** [comment]
I'd really need to see some part of your code to help you :|
