### ISSUE TITLE
[Translator] No translations if detected via HTML lang attribute

### ISSUE THREAD

**Issue by aleho** [symfony/ux#2378]
Symfony locales are specified with an underscore to split country code from language code, e.g. `de_AT`.

When using UX Translator it correctly detects the current locale if set [via the HTML attribute](https://symfony.com/bundles/ux-translator/current/index.html#configuring-the-default-locale):

```twig
<html lang="{{ app.request.locale }}">
{# <html lang="de_AT"> #}
```

Unfortunately, [according to W3](https://www.w3.org/TR/html401/struct/dirlang.html#h-8.1.1), this format is invalid, as the "subcode" has to be separated by a hyphen.

Using

```twig
<html lang="{{ app.request.locale | replace({'_': '-'}) }}">
{# <html lang="de-AT"> #}
```

doesn't work, because this format is not detected by Translator, resulting in no translations at all (only the string constants are returned).

**Comment by smnandre** [comment]
You can use the data attribute as shown in the section of the documentation you link ?

**Comment by aleho** [comment]
Yes, there are other ways of configuring the locale. I'm just saying that Translator has a feature to read `html lang=""` but that feature requires an invalid value for `lang` to be fully compatible with Symfony i18n.

In my opinion either the feature should be removed or fixed. As the fix would be trivial (as far as I can see right now), I'd rather see a fix. As it stands now it doesn't break with `en` but would break with `en_US`, which was unexpected, at least for me.

**Comment by smnandre** [comment]
If you want to use the lang attribute of the html tag, and if your locale region and langage code differ, you're right it would currently requires a value not following the w3 spec. 

What i understand here is the feature is working for users:
* using simple lang code (fr, en, es, ...) 
* using symfony-formatted locale (fr_BE) in the lang attribute
* using any of the other methods suggested

So i doubt it will be "removed" 

But it does not "convert" en-US to en_US indeed. So.. would you have some time to open a PR? 😃 

(Only constraint: any change should keep previous behaviour working, to not break existing apps)

**Comment by aleho** [comment]
@smnandre Done!

**Comment by smnandre** [comment]
Thank you very much @aleho :)
