### ISSUE TITLE
[TwigComponent] Unknown component "Stream\After" in debug command

### ISSUE THREAD

**Issue by xDeSwa** [symfony/ux#2389]
Hi, 

` php bin/console debug:twig-component `

when use giving error

`
  Unknown component "Stream\After". And no matching anonymous component template was found.  `

this works when i created new project copied old project files to new one.

but i copied config files to new one this wont work

Where and how could I have made a mistake?

**Comment by smnandre** [comment]
Are you on windows ? 

Last version on symfony/ux-twig-component ?

Maybe you could try with the unreleased 2.22 version that [may have fixed](https://github.com/symfony/ux/pull/2342) this problem ?
 (you can try it using "2.x-dev" in your composer json)

**Comment by xDeSwa** [comment]
yep, i using windows 10

https://github.com/symfony/ux/pull/2342

this fixed the error


![aa](https://github.com/user-attachments/assets/62235954-5ea1-4f24-bc85-ee90d8bb7fdd)
