### ISSUE TITLE
[Turbo] symfony/ux-turbo doesn't install correctly when using --webapp

### ISSUE THREAD

**Issue by tacman** [symfony/ux#2391]
This fails, I reported it at https://github.com/symfony/symfony/issues/58926 but probably belongs in this repo.

```bash
symfony new TurboBug  --webapp && cd TurboBug
bin/console make:controller AppController
symfony server:start -d
symfony open:local --path=/app
```

![image](https://github.com/user-attachments/assets/d26e773f-3ae3-47d8-a409-ba567f435a49)

But if I remove ux-turbo, it works:

```bash
symfony new NewApp  --webapp && cd NewApp
composer remove symfony/ux-turbo
bin/console make:controller AppController
symfony server:start -d
symfony open:local --path=/app
```

**Comment by nicolas-grekas** [comment]
Let's figure this out. Did you run assets:install et al commands? They should be in the composer.json script's entry already.
Turbo is part of the core DX we want to promote out of the box so we should make it work.

**Comment by tacman** [comment]
No change:

```bash
symfony new NewApp  --webapp && cd NewApp
bin/console assets:install
bin/console make:controller AppController
symfony server:start -d
symfony open:local --path=/app
```

Unless my composer has some global to block scripts, this has always worked for me, so I think it's something in ux-turbo.

**Comment by WebMamba** [comment]
I had the same issue after running a `symfony new --webapp`. Huuuum not sure what's happen here... I am digging in to it

**Comment by smnandre** [comment]
So... it appears Turbo is not present in the bundle.php file after install 

Had to manually add it (and then everything worked as expected)

```diff
<?php

return [
    Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
    Doctrine\Bundle\DoctrineBundle\DoctrineBundle::class => ['all' => true],
    Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle::class => ['all' => true],
    Symfony\Bundle\DebugBundle\DebugBundle::class => ['dev' => true],
    Symfony\Bundle\TwigBundle\TwigBundle::class => ['all' => true],
    Symfony\Bundle\WebProfilerBundle\WebProfilerBundle::class => ['dev' => true, 'test' => true],
    Symfony\UX\StimulusBundle\StimulusBundle::class => ['all' => true],
+    Symfony\UX\Turbo\TurboBundle::class => ['all' => true],
    Twig\Extra\TwigExtraBundle\TwigExtraBundle::class => ['all' => true],
    Symfony\Bundle\SecurityBundle\SecurityBundle::class => ['all' => true],
    Symfony\Bundle\MonologBundle\MonologBundle::class => ['all' => true],
    Symfony\Bundle\MakerBundle\MakerBundle::class => ['dev' => true],
];

```

**Comment by smnandre** [comment]
I guess the "bundle" lines are missing from the recipes ...  we did not have one before so the registration was automatic, but now we have one, i think we need to add these lines in https://github.com/symfony/recipes/blob/main/symfony/ux-turbo/2.20/manifest.json

```json
    "bundles": {
        "Symfony\\UX\\Turbo\\TurboBundle": ["all"]
    },
```
    
See https://github.com/symfony/recipes/blob/main/symfony/stimulus-bundle/2.20/manifest.json for comparaison

**Comment by smnandre** [comment]
Posted a [PR to fix this](https://github.com/symfony/recipes/pull/1357).... would love a second eye (@nicolas-grekas  ?)

**Comment by smnandre** [comment]
Confirmed here (if i read it correctly): we do need at least _one_ working recipe https://github.com/symfony/flex/pull/865

**Comment by smnandre** [comment]
Not sure if this works (only once for me ... maybe)

... could you try @tacman with the instructions provider in the PR ?

**Comment by smnandre** [comment]
https://github.com/symfony/recipes/pull/1357

**Comment by tacman** [comment]
Yep, works as expected!

```bash
export SYMFONY_ENDPOINT=https://raw.githubusercontent.com/symfony/recipes/flex/pull-1357/index.json
symfony new TurboTest  --webapp && cd TurboTest
bin/console make:controller AppController
symfony server:start -d
symfony open:local --path=/app
```
