### ISSUE TITLE
Issue with nested attributes in Twig components

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/ux#2404]
I'm trying to render an icon with UX Icons inside a (class-based) Twig Component and I need its CSS class to be configurable via a nested attribute.

**Syntax 1**:

```twig
<twig:ux:icon attributes.nested('title_icon').defaults({name: 'tabler:calendar-plus', height: '18px', width: '18px', class: 'mr-1'}) />
```

error: `Expected attribute name when parsing the "<twig:ux:icon" syntax.`

-----

**Syntax 2**:

```twig
<twig:ux:icon name="tabler:calendar-plus" attributes.nested('title_icon').defaults({height: '18px', width: '18px', class: 'mr-1'}) />
```

error: `Expected attribute name when parsing the "<twig:ux:icon" syntax.`

-----

**Syntax 3**:

```twig
{{ ux_icon('tabler:calendar-plus', attributes.nested('title_icon').defaults({height: '18px', width: '18px', class: 'mr-1'})) }}
```

error:

```
An exception has been thrown during the rendering of a template ("Symfony\UX\Icons\Twig\UXIconRuntime::renderIcon():
Argument #2 ($attributes) must be of type array, Symfony\UX\TwigComponent\ComponentAttributes given.
```

-----

**Syntax 4**:

```twig
{{ ux_icon('tabler:calendar-plus', attributes.nested('title_icon').defaults({height: '18px', width: '18px', class: 'mr-1'}).all()) }}
```

**It works!**

-----

I think that **Syntax 1** should work. If it's not possible, could we at least make **Syntax 3** work? But maybe I'm missing things and the current behavior is the best one 🙏  Thanks!

**Comment by norkunas** [comment]
```twig
<twig:ux:icon{{ ...attributes.nested('title_icon').defaults({name: 'tabler:calendar-plus', height: '18px', width: '18px', class: 'mr-1'}) }} />
```
should work

**Comment by smnandre** [comment]
Syntax 3 miss an ending "all" ou "toArray" (not sure), or a spread syntax as @norkunas pointed out.

Update: just saw the end of your S4 😅 


So no bug here, you cannot "echo" things into twig component

**Comment by javiereguiluz** [comment]
Thanks for reviewing this. I'm closing because, as you said, the spread operator is already explained in the HTML syntax section: https://symfony.com/bundles/ux-twig-component/current/index.html#component-html-syntax

Thanks!
