### ISSUE TITLE
[Icons] Console error after update

### ISSUE THREAD

**Issue by trsteel88** [symfony/ux#2415]
After updating to Symfony 7.2 along with deps, seeing the error `You have requested a non-existent service ".ux_icons.command.lock".`.

Still digging into why but is anyone else seeing this?

This shows even when running `bin/console`

**Comment by smnandre** [comment]
You have iconify disabled i suppose? 

I just opened a PR to fix this mistake (_my_ mistake..)

**Comment by trsteel88** [comment]
Yes, that is correct. Thanks @smnandre
