### ISSUE TITLE
[LiveComponent] Emit events targeting not only a component's name but also specific keys

### ISSUE THREAD

**Issue by kilianklein** [symfony/ux#2422]
Hi guys, thanks again for the awesome bundle

I have recently started using LiveEvents more, and as I was doing so, I thought of 2 improvements that would be helpful (please let me know if those already exist and I just missed them):

1. Would love to use the live component's backend class's FQCN instead of a simple string when emitting an event to target only a specific type of components only
2. **[More importantly]** Could we please add the capacity to emit an event with a component name target BUT also with an array of component keys

Example: 
Imagine you have a `Calendar` component showing an entire month with 30 days, and each day box is a `Day` component. If you want to update a specific Day component from another component via an event, there will be 30 ajax requests and only within the LiveListener's function can the discrimination logic to target the specific day be coded.

This is 29 ajax requests that are not needed, and it is also not great for the UX if, for example, we have a loading state linked to receiving this event.

Proposition of a new feature:
Since we already have the capacity to give a key to a specific component, could we add the capacity to add an array of component keys when targetting a specific component while emitting an event.

The key attribute is particularly suiting since it is especially important to set on pages that include lists of repeating similar components, and those cases are when the excessive number of ajax requests happen.

I guess the php-side would look something like this:
```
$this->emit(
       'refreshEvent",
       componentName: 'Calendar:Day',
       componentKeys: ['day-13', 'day-29']
);
```

**Comment by smnandre** [comment]
The emitUp method only targets the ascendants of the emitting component.. so not sure to get your example.. How a component could have both a day-13 and a day-29 parent ?

**Comment by kilianklein** [comment]
Thank you for your answer, you are correct, I took a snippet of my code for the example and forgot to change emitUp to emit, I rectified it in my original post.

The point I wanted to make was that it would be useful to single out some of the components that have a certain name and not all of those.

Now that I think of it, I suppose it is achievable via a stimulus controller to target only a specific component and launch a live action from there instead of using events. I just think it'd be simpler having that option.

**Comment by smnandre** [comment]
I'd rather stay close to event standard usage "name + payload" and have listeners / subscribers ... 

What you ask for here is a way to call methods by id ... very different thing than an event.

We do have this parameter right now, and i do not have the context/history on this.

But i personnaly dont think we don't want to mix too much event and message patterns.

So finding a way to adress/find components i don't know... but using events for this feels very odd to me 🤷 

Let's wait for other opinions ?

**Comment by kilianklein** [comment]
You are right, I figured out a more efficient way to do this.

I was basically using events to do something that would be much more efficient targeting directly a live action in another component, just never figured out how to do so until now.

If anyone else is in the same situation here is how I would do it:

1. Add a custom stimulus controller to the Calendar component
2. add a data-calendar-target='calendar-day' to each Day LiveComponent within the calendar
3. add a unique id to each of those
4. Whenever doing something in a Day component that needs to update specific other day components, don't trigger the LiveAction directly from the twig, but call the live action through the new custom controller using getComponent
5. Recover the other Day targets via their ID, and apply loading state if necessary
6. Use getComponent on them too to trigger some kind of LiveAction that will re-render them with "await"
7. Remove loading state if applied

Using this way we get instant loading state and removal, we target only the components we want and we don't use events at all which are not suited for this situation.

Thank you for your answers, closing this!

Have a nice day
