### ISSUE TITLE
[Twig Component] [Developer experience enhancement] Add interfece to Component Renderer and type hint this class by it's interface

### ISSUE THREAD

**Issue by sabat24** [symfony/ux#243]
I tried to decorate [ComponentRenderer](https://github.com/symfony/ux-twig-component/blob/2.x/src/ComponentRenderer.php) class to change a bit it's behaviour. However it can't be done because `ComponentRuntime` class requires directly the `ComponentRenderer`. If you add an interface to `ComponentRenderer` class and then type hints it in `ComponentRuntime` it allows to decorate your class.

Is it possible?

**Comment by weaverryan** [comment]
Hey!

Im open to this, but what’s your use-case? What are you trying to accomplish?

cheers!

**Comment by kbond** [comment]
@sabat24, @weaverryan and I have been talking about a `PreRender` event to be called here that includes: the component, the template and all variables that would be sent to the `$twig->render()`. Listeners could manipulate this data. Could something like this help you?

**Comment by sabat24** [comment]
I needed to get direct access from twig file to public properties in php component class (without `this`).

However meanwhile @kbond made [that change](https://github.com/symfony/ux-twig-component/commit/37edf970c7073006d03ae0b20dd31eb00abbb9bc) few days ago. He added `array_merge(['this' => $component], get_object_vars($component))` which was exactly what I wanted to do :)

Regarding the `PreRender` event. Right now your change solves my problem and I didn't have any other situations where I wanted to change the behaviour of that method.

**Comment by kbond** [comment]
Perfect, I'm glad it that change solved your issue! Closing for now but feel free to reopen if a situation arises.
