### ISSUE TITLE
Links in Resources are broken

### ISSUE THREAD

**Issue by guillaumebriday** [symfony/ux#246]
Links in https://github.com/symfony/ux#resources are dead.

But I'm not sure what page you want to show now so I don't open a PR, sorry for that.

**Comment by kbond** [comment]
Thanks for reporting. @javiereguiluz, do you know the new home for these pages?

**Comment by javiereguiluz** [comment]
The "List of UX Packages" link could point to https://symfony.com/bundles because we now publish the UX bundles there.

The other link ("Install Symfony UX") I'm not sure. Maybe @weaverryan could help us here. Thanks!

**Comment by wouterj** [comment]
All these links will be available when https://github.com/symfony/symfony-docs/pull/16404 is merged, but that PR is still in "WIP" status.

**Comment by weaverryan** [comment]
Oh, crap - I let that PR get lost! My bad, I'll get on it now

**Comment by weaverryan** [comment]
All better now :)
