### ISSUE TITLE
[Live Component] RedirectResponse causes JS error on v2.1

### ISSUE THREAD

**Issue by benr77** [symfony/ux#260]
When returning a `RedirectResponse` from a form submit method, in `2.0.1` this works correctly.

However, as soon as I upgrade to `2.1` then the redirect does not work and I get a JS error `Uncaught (in promise) SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data` and then the redirect fails.

**Comment by weaverryan** [comment]
Hey @benr77!

I can't repeat this locally. BUT, if you updated before this PR - https://github.com/symfony/ux/pull/256 - then you would have gotten out-of-date JavaScript (we've added a check to our CI to prevent that).

Let me know. If you ARE still getting the error, I would love to see what line number the error is coming from in JavaScript. 

Cheers!

**Comment by benr77** [comment]
Hi Ryan. Thanks for getting back to me.

I only installed this component yesterday so that must have been after #256 so I don't think that was the issue.

It seems it was to do with upgrading from version 2.0.1 to 2.1 and my JS was not expecting HTML back but JSON as previously. 

I seem to have fixed it by force updating my Javascript build

```
yarn install --force
yarn encore dev
```

This, followed by a hard-refresh in the browser, seems to have done the trick.

I realise this is all still experimental but is there anything we can do to ease this kind of issue when upgrading? Or am I just missing something?

Thanks

**Comment by Lustmored** [comment]
@benr77 AFAIK all UX upgrades require at least `yarn install --force` after any upgrade simply because update frontend assets need to be updated on yarn side too. I don't think there is a simple workaround (or any workaround in fact)

Also - composer should have warned you about requirement to run `yarn install --force` after install/upgrade command.

**Comment by benr77** [comment]
@Lustmored thank you and yes, composer did warn me as usual, but it's just outside of the normal workflow when updating composer packages and I just forgot to deal with Yarn afterwards. Totally my own fault.

In this case, the error became obvious quickly, as the old JS was expecting JSON and receiving HTML so it complained about this immediately.

However, I imagine some JS upgrades are going to be much less obvious and cause users a lot of headaches.
