### ISSUE TITLE
[LiveComponent] data-live-ignore and nested elements

### ISSUE THREAD

**Issue by norkunas** [symfony/ux#270]
Currently when using `data-live-ignore` on an element, it will be ignored from re-render and also it's all child elements also will be ignored.

I have an use case with a modal, where I have a live action which triggers re-render and I would like to keep the modal open, but that the form in the modal would be re-rendered.

**Comment by weaverryan** [comment]
I was wondering if someone would ask for this :). Yes, this seems reasonable - Livewire also has something like this.

**Comment by weaverryan** [comment]
See #519 for the proposal. For a modal, you would use `<div data-rerender="children">`. This would mean that the parent component is "ignored", but then children re-render via the normal mode of "diffing" the old and new elements via morphdom.
