### ISSUE TITLE
Component attributes - way to pass html attributes to component more directly

### ISSUE THREAD

**Issue by sabat24** [symfony/ux#275]
You lately added a concept of [component attributes](https://symfony.com/bundles/ux-twig-component/current/index.html#component-attributes). The concept per se is a good direction to help managing attributes in TWIG files. However I've got a problem with the way how you pass that HTML attributes to TWIG component. As I understand the main idea behind this concept is to render everything passed to component as HTML attribute, unless it has own property declared in PHP class. Except some auto-magic involved I discovered some issues with such approach when I tried to implement this approach to my project:

1. ~~I use the `preMount` method to validate attributes passed from TWIG into PHP component (more information why I need such validation can be found in issue [#142](https://github.com/symfony/ux/issues/142)):~~
```php
#[PreMount]
    public function configureProperties(array $data): array
    {
        $resolver = new OptionsResolver();
        $resolver->setRequired(["text", "url", "action", "icon", "icon_2", "class", "text_transform", "color"]);
        $resolver->setAllowedValues('icon', ["ico_add_card_white", "button_search_loupe", "ico_plus", "arrow_grey_right", "arrow_mob_right_orange", "arrow_mob_left_orange", "arrow_mob_right_white", "arrow_mob_left_white", "arrow_mob_right_green", "arrow_mob_left_green"]);
        $resolver->setAllowedValues('icon_2', ["ico_add_card_white", "button_search_loupe", "ico_plus", "arrow_grey_right", "arrow_mob_right_orange", "arrow_mob_left_orange", "arrow_mob_right_white", "arrow_mob_left_white", "arrow_mob_right_green", "arrow_mob_left_green"]);
        $resolver->setAllowedValues('text_transform', ["capitalize", "lowercase", "uppercase"]);
        $resolver->setAllowedValues('color', ["default", "green"]);
        return $resolver->resolve($data);
    }
```

~~Right now I can't pass any HTML attributes, because there is no direct way to do it and my validation will block any unmapped keys.~~

2. ~~In my PHP component I use `action` and `class` properties. I won't be able to pass the same HTML attributes into TWIG component, because my properties will have priority and values with these keys will be assigned to them. So in general there is no way to pass for example `action` property into form if that name is already taken by PHP component. I can of course change my names, but in general such approach may lead to unexpected behaviour.~~ 

~~For me it would be better to provide more direct way to pass such HTML attributes other then using unmapped keys. Then components can be more strict and much easier validatable against disallowed properties. I don't know if it would be possible to introduce third argument to pass other options and do not mix them with variables. Something like:~~

```twig
{{ component('alert', {properties: values}, {htmlAttributes: attributes}) }}
```

~~If it's not possible maybe special property named: `_htmlAttributes`~~

```twig
{{ component('alert', {key_1: value_1, _htmlAttributes: {class: 'red', type: 'button'}}) }}
```

3. Right now I use attributes [Twig Extension](https://api.druphelp.com/api/drupal/core%21lib%21Drupal%21Core%21Template%21TwigExtension.php/class/TwigExtension/9) created by Drupal team. 

```php
final class AttributesExtension extends AbstractExtension implements GlobalsInterface
{
    /**
     * @return mixed[]
     */
    public function getGlobals(): array
    {
        return [
            'attributes' => new Attributes(),
        ];
    }
}
```

However your implementation conflicts with my globals with following error

```
Neither the property "setAttribute" nor one of the methods "setAttribute()", "getsetAttribute()"/"issetAttribute()"/"hassetAttribute()" or "__call()" exist and have public access in class "Symfony\UX\TwigComponent\ComponentAttributes
```

I wonder if is possible to avoid such conflicts by prefixing by you things added to Twig? It's not a problem for me to change name from `attributes` to something else. However I think more about any other conflicts that may arise in future. 

**EDIT** I saw in code that you already use special property like `attributes` to pass them directly, so the first two points make no sense any more.

**Comment by kbond** [comment]
Hey @sabat24. In addition to `attributes`, we also add all public properties as variables in the twig template. These could also cause conflicts. I'm wondering about come config options for `AsTwigComponent`:

```php
#[AsTwigComponent(attributesVar: '_attributes', exposePublicProps: false)]
class MyComponent {}
```

**Comment by sabat24** [comment]
As I understand with such configuration I will be able to use `{{ _attributes }}` variable in twig file
```twig
{# templates/components/my_component.html.twig #}
<input{{ _attributes}}/> 
```
defined for example here 
```twig
{# render component #}
{{ component('my_component', { type: 'text', value: '', autofocus: null }) }}
```
as well as my custom `attributes` twig extension at the same time? If yes such config would be great and solves all my problems with conflicts.

**Comment by kbond** [comment]
Yes, for your premount hook to work, I guess you can pass attributes like:

```twig
{# render component #}
{{ component('my_component', { _attributes: { type: 'text', value: '', autofocus: null } }) }}
```

Then add `_attributes` to your `OptionsResolver`?

**Comment by sabat24** [comment]
My PreMount hook will work fine even now when I add `attributes` to `OptionsResolver`. That's ok.

I was thinking rather about my point 3 and the error from `Symfony\UX\TwigComponent\ComponentAttributes` which conflicts with my registered twig extension under the `attributes` name because of [line 52 from ComponentRenderer](https://github.com/symfony/ux/blob/c27fa1968ad66ff9d0f7041974303ff47ad3e982/src/TwigComponent/src/ComponentRenderer.php#L52)

I just wanted to confirm if your idea is to change that line from
```php
['attributes' => $mounted->getAttributes()],
```
into something like that
```php
// where $attributeVar is set to _attributes defined as AsTwigComponent attrubute's option
$attributeVar = $this->factory->metadataFor($mounted->getName())->getAttributeVar();

$variables = array_merge(
...,
[$attributeVar => $mounted->getAttributes()],
...,
```

**Comment by kbond** [comment]
Sorry @sabat24, didn't realize you were working on a PR

**Comment by sabat24** [comment]
I started today to test this approach in our team. I planned to send you a ready solution, but you were faster with your implementation :)

To be honest I wanted only link my PR with this issue to get all things organized in one place. Auto-closing this thread wasn't expected.
