### ISSUE TITLE
[LiveComponent] Cannot use array as model

### ISSUE THREAD

**Issue by RikudouSage** [symfony/ux#288]
I cannot figure a way to use an array as a model.

On my component I have this:

```php
    #[LiveProp(writable: true)]
    public array $values = [];
```

Then in my `mount()` method I have this to initialize the empty array keys:

```php
        foreach ($fields as $field) {
            $this->values[$field->getName()] ??= null;
        }
```

In my html I have this (`boolean` is the name of the field):

```html
<input class="toggle-checkbox" type="checkbox" checked="" data-action="live#update" data-model="values[boolean]">
```

The error I get is `Input value "values" contains a non-scalar value.` which is triggered in `LiveComponentSubscriber` by this line:

```php
parse_str($request->query->get('values'), $values);
```

The `get()` doesn't work with arrays. Is there any possible workaround for now?

Edit: As I was writing this I realized what the problem is, still a better exception message would be welcome, something like "values is a reserved name and cannot be used as a live property".

**Comment by kbond** [comment]
Hey @RikudouSage, things were changed quite a bit for 2.1 (not released yet). I think this may no longer be an issue but I'm not positive.

**Comment by RikudouSage** [comment]
Eagerly awaiting it! It was a little confusing since the documentation on symfony.com is already for 2.1 and I couldn't find any info on how to use `init_live_component()`.
