### ISSUE TITLE
What about using the syntax of react in twig ?

### ISSUE THREAD

**Issue by jgroc-de** [symfony/ux#290]
Hi,
About the part https://github.com/symfony/ux-twig-component, i was wondering if it was possible (and desirable) to have some kind of syntax more closer to what react do (or vue maybe). I mean, coding with custom html tag instead of using functions ?

My point is just that its usually much much more easy to work with html tag than with twig functions.

I think that even if we have to use brackets, it s still better to have:
```
{{ <alert /> }}
```
than
```
{{ component('alert') }}
```

What's your thoughts about this?

**Comment by kbond** [comment]
Hello! This is on my radar, see https://github.com/giorgiopogliani/twig-components#html-syntax for my inspiration.

Thinking there could be an optional _html-like-lexer_ that can be enabled in your config.

**Comment by jgroc-de** [comment]
ah nice, yes, it's totally that ! Hope you will be able to achieve this !
