### ISSUE TITLE
Use ComponentAttributes everywhere in project

### ISSUE THREAD

**Issue by seb-jean** [symfony/ux#304]
Hi,

It would be great to be able to use `ComponentAttributes` everywhere in project but `ComponentAttributes` is marked as `@internal`

For instance:

```php
<?php

namespace App\Twig;

use Symfony\UX\TwigComponent\ComponentAttributes;
use Twig\Extension\AbstractExtension;
use Twig\TwigFunction;

class AriaExtension extends AbstractExtension
{
    public function getFunctions(): array
    {
        return [
            new TwigFunction('aria_dialog', [$this, 'ariaDialog']),
        ];
    }

    public function ariaDialog()
    {
        $attributes = [
            'data-controller' => 'dialog',
            'role' => 'dialog',
            'aria-modal' => 'true',
        ];

        return new ComponentAttributes($attributes);
    }
}

```

**Comment by kbond** [comment]
If there is an _external_ use-case for something marked as internal, I'm fine with removing `@internal`.

**Comment by seb-jean** [comment]
An example use case is generating HTML attributes like the Twig extension, above.
But it is not a component.

**Comment by kbond** [comment]
Yep, looks legit to me!

**Comment by seb-jean** [comment]
Maybe we could rename `ComponentAttributes` to `HtmlAttributes`?

**Comment by kbond** [comment]
I'd be fine with this as well. @weaverryan, any objections?

**Comment by seb-jean** [comment]
Hi @weaverryan,
Do you have any objections?

**Comment by wouterj** [comment]
It's often better to start a PR if the change is scoped like this one. Easier to judge the impact, and PRs often get more attention than issues :)

**Comment by weaverryan** [comment]
Yes, PR please! No objections from me, including the name change.
