### ISSUE TITLE
Symfony 5.4 Stimulus3 not working 

### ISSUE THREAD

**Issue by behrus** [symfony/ux#306]
Hi, i am now several hours trying to running Stimulus but it seems that installation was not correct. I dont know.

**Here the package.json:**

> "devDependencies": {
>         "@hotwired/stimulus": "^3.0.0",
>         "@symfony/stimulus-bridge": "^3.0.0",
>         "@symfony/webpack-encore": "^1.8.1",
>         "core-js": "^3.0.0",
>         "greet": "^1.0.0",
>         "jquery": "^3.6.0",
>         "regenerator-runtime": "^0.13.2",
>         "sass": "^1.49.0",
>         "sass-loader": "^12.0.0",My base.html.twig has javascript block **with:**
>         "webpack-notifier": "^1.6.0"
>     },
>     "license": "UNLICENSED",
>     "private": true,
>     "scripts": {
>         "dev-server": "encore dev-server",
>         "dev": "encore dev",
>         "watch": "encore dev --watch",
>         "build": "encore production --progress"
>     },
>     "dependencies": {
>         "vue": "^2.6.14",
>         "vue-loader": "^15.9.8",
>         "vue-template-compiler": "^2.6.14"
>     }
> }
> 

```js
assets/app.js:
`/*
 * Welcome to your app's main JavaScript file!
 *
 * We recommend including the built version of this JavaScript file
 * (and its CSS file) in your base layout (base.html.twig).
 */

// any CSS you import will output into a single css file (app.css in this case)
/* import './scss/app.scss'; */
import './scss/project.scss';

// start the Stimulus application
import './bootstrap';

import jQuery from 'jquery';

jQuery(document).ready(function() {
});


import Vue from 'vue';

new Vue({
    delimiters: ['[[', ']]'],
    el: '#vue-content',
    data: {
        message: 'Hello!'
    }
})


new Vue({
    el: 'tr.jklhks-user',
    data: {
        user: null,
        shortname: ''
    },
    methods: {
        displayShortname: function(event) {
            this.user = JSON.parse(this.$el.attributes['data-user'].value);
            this.shortname = this.user.shortname;

            alert('Edit ' + this.shortname);

            new Vue({
                delimiters: ['[[', ']]'],
                el: '#selected-kjlgkl-user',
                data: {
                    shortname: this.shortname
                }
            })
        }
    }
})


export default {
    data() {
        return {
            hover: false,
        };
    }
}
```

**assets/bootstrap.js:**
```js
import { startStimulusApp } from '@symfony/stimulus-bridge';

// Registers Stimulus controllers from controllers.json and in the controllers/ directory
export const app = startStimulusApp(require.context(
    '@symfony/stimulus-bridge/lazy-controller-loader!./controllers',
    true,
    /\.(j|t)sx?$/
));

// register any custom, 3rd party controllers here
 //app.register('counter_controller', counter_controller);
```

Than there is the counter_controller.js in assets/controllers:
```js
import { Controller } from '@hotwired/stimulus';

//import { Controller } from 'stimulus';
export default class extends Controller {
    connect() {
        this.element.innerHTML = 'You have clicked me 0 times ?';
        console.log("Hello, Stimulus!", this.element)
    }
}
```

**My base.html.twig has javascript block with:**
{{ encore_entry_script_tags('app') }}

**There is also a div in one twig template:**
`<div data-controller="counter"></div>`

But the message doesnt appear in the div. There is also no error in frontend or backend.
yarn encore dev --watch  is running in background

Building scss and images works only javascript nor.

Thank for your help

**Comment by franciscosantamaria** [comment]
Hi @behrus what's your file name inside your **assets/controllers** directory?

I've tested a clean Symfony 5.4 application and stimulus works perfectly on it.

Check it [here](https://github.com/franciscosantamaria/symfony-5.4-stimulus)

Regards,
kiko

**Comment by weaverryan** [comment]
Also, if you run a `yarn upgrade` or `npm update` to get the latest version of `@symfony/stimulus-bridge`, you should now see debugging messages from Stimulus in your console. You'll see messages about Stimulus starting and any other controllers starting (and if you don't see a message about your `counter` controller starting, then you at least know that, for some reason, Stimulus doesn't see it).

Cheers!
