### ISSUE TITLE
[Live Component] CKEditor disappeared after update

### ISSUE THREAD

**Issue by Faulk13** [symfony/ux#314]
Hello,
I try to use CKEditor to replace textarea on my component form like this :
```
        $form
            ->add('additionalInformations', CKEditorType::class, [
                'required' => false,
                'label' => 'prepare_payslip.label.additional_informations',
            ]);
```

I have a template for my component with a change live#update like this :
`<div {{ attributes }} data-action="change->live#update">`

and I have a component : 
```
[...]
    #[LiveProp(fieldName: 'data')]
    public ?PreparePayslip $preparePayslip = null;

    protected function instantiateForm(): FormInterface
    {
        return $this->createForm(PreparePayslipType::class, $this->preparePayslip);
    }
[...]
```

When I type some text on CKEditor, if I pass to another field, I don't have ajax request launched by my change.
And If I type anything on other fields, I have a request ajax launched but my CKEditor disappeared with his text and I have a old textarea.

Do you have any clue to solve this issue ? :slightly_smiling_face: 

Thanks

**Comment by WebMamba** [comment]
Hey @Faulk13 ! That's fun to see you here 😁 ! I can't reproduce your issue, maybe you can share a small project, and I would be happy to help you debug !

**Comment by Faulk13** [comment]
Hey @WebMamba ! Big surprise to see you here ! I hope you are fine. I can't share project to show you my issue but I think it's not blocking for now
