### ISSUE TITLE
Unable to resolve path to module '@symfony/autoimport' with eslint

### ISSUE THREAD

**Issue by rzeczkowskip** [symfony/ux#32]
I have Webpack Encore configured with ESLint and I have the `Unable to resolve path to module @symfony/autoimport` error both from eslint and my IDE. The "only" issue is ESLint error and red underline in IDE. And with ESLint error, compilation fails.

I've noticed the issue while using web-server inside docker (with the whole project mounted inside the container) and when I dump the assets to the public/build dir. Looking at this I don't think it should matter.

As a dirty fix I used `// eslint-disable-line import/no-unresolved`. Controllers work fine, no errors in console etc.

After a short discussion on Slack with @tgalopin I know that autoimport is created on compilation by Webpack Encore. I think that dirty fix might be the only fix in that case. I'm not sure if it's possible to ignore a single specified module from `.eslintrc`.

package.json versions:
```
        "@symfony/stimulus-bridge": "^1.0.0",
        "@symfony/webpack-encore": "^0.32.0",
```

composer.json versions:
```
        "symfony/webpack-encore-bundle": "^1.8",
```

Symfony 5.2

**Comment by tgalopin** [comment]
I don't think that's an issue of Symfony UX though, it's more of a problem that ESLint doesn't know about Virtual Modules. Perhaps is there a ESLint extension you could use to discover Virtual Modules?

**Comment by Kocal** [comment]
You can configure ESLint to use your Webpack config, thanks to [`eslint-plugin-resolver`](https://www.npmjs.com/package/eslint-plugin-import) and [`eslint-plugin-resolver-webpack`](https://github.com/benmosher/eslint-plugin-import/tree/master/resolvers/webpack).

However I don't know if virtual modules are supported.

**Comment by tgalopin** [comment]
I'm closing this issue as it's unrelated to UX but feel free to discuss ideas here if you wish :) .
