### ISSUE TITLE
[LiveComponent] Add a way to disable csrf

### ISSUE THREAD

**Issue by norkunas** [symfony/ux#320]
Currently if the project has `symfony/security-csrf` package, csrf is automatically enabled for LiveComponent, but I don't see a way how to disable it for the component?

**Comment by weaverryan** [comment]
What's your use-case @norkunas? It's definitely something we could look into making configurable.

**Comment by norkunas** [comment]
Sometimes randomly I get invalid csrf token, so I thought that I don't need that csrf at all in my component :)

**Comment by weaverryan** [comment]
Lol. Well, I'd rather track down WHY/HOW that is happening vs disabling it. But, I am not against making it configurable... probably on the "component level", in the same way that you can disable CSRF tokens on a form-by-form basis with Symfony's form component, but I don't think you can disable it globally.

**Comment by norkunas** [comment]
Yes, I thought about that it should behave same like forms :) If you agree I could try to make  a PR for this on monday.

**Comment by weaverryan** [comment]
👍
