### ISSUE TITLE
Add getter for data property in Chart.js

### ISSUE THREAD

**Issue by bastien70** [symfony/ux#34]
It would be interesting to add the getter for the "data" property in the model of the Chart object, in the Chart.js component

For my part I need to access it from my Twig view for something.

For example I need to take all the sum of all the values ​​in data [] to display the total above the graph, like this :

```twig
<div class="reports-stats-item card text-white bg-success mb-3">
            <div class="card-body">
              <h2 align="center" class="card-title"> <i class="fas fa-coins"></i>
                {% set total_amount = fullReports.invoices.data.datasets|sumMultiArrays("data") %}
                {{ total_amount }} € générés
              </h2>
            </div>
          </div>
```

![image](https://user-images.githubusercontent.com/53140475/101789991-3b8cf900-3b02-11eb-9b84-dbf0f0f9d091.png)

**Comment by tgalopin** [comment]
Hi! That's a good idea, I'd be down to add `getType`, `getData` and `getOptions` methods on the Chart model. If you wish to open a PR, go for it :) !

**Comment by bastien70** [comment]
> Hi! That's a good idea, I'd be down to add `getType`, `getData` and `getOptions` methods on the Chart model. If you wish to open a PR, go for it :) !

Thanks for your reply ! I'm not familiar with PR yet, so I'll leave it to you to do that :)
