### ISSUE TITLE
Generate code on the console

### ISSUE THREAD

**Issue by WebMamba** [symfony/ux#36]
For lots of applications, the js is separate from the PHP, so I think, it could be interesting to generate code on the console and then pass it to the js app. As Read Admin does with their guesser component. For example, a command can generate a form with dynamic validation in the console, and you just need to pass the result in your js.

**Comment by tgalopin** [comment]
Hi! I'm not sure to understand what you aim for. Wouldn't that be better as a UX package instead of a command line to generate code?

**Comment by WebMamba** [comment]
Yes is it, but I looking for a solution to not be stuck in twig

**Comment by tgalopin** [comment]
I'm closing this for now but if you have a question feel free to reach us on Symfony Slack: https://symfony.com/slack
