### ISSUE TITLE
[UxSite] Scroll indicator horizontal scroll incorrect when you have horizontal and vertical scrolling

### ISSUE THREAD

**Issue by ghost** [symfony/ux#361]
When you have a scroll bar for both horizontal and vertical scrolling like on https://ux.symfony.com/notify for block `src/Controller/NotifierController.php` the horizontal scroll balk is shown on the bottom of the block, so you first need to scroll all the way down before your can scroll horizontally.

Can only confirm that this is the case on desktop.

**Comment by ghost** [comment]
Confirmed the problem still exits

**Comment by weaverryan** [comment]
I'm not sure what controls that - but I'll ping someone smarter than me to look into it :)
