### ISSUE TITLE
[Symfony UX React] Component without props

### ISSUE THREAD

**Issue by milankaranovic** [symfony/ux#364]
Hey Symfony team! Thanks for all the amazing work you did so far! 🙏🏻 

`"symfony/ux-react": "^2.2"`

I've noticed an issue when I tried to render react component without props using the `react_component` twig function.

When I try to render react component like this:
```twig
<div {{ react_component('MyComponent') }}></div>
```
I get the following console error:
![image](https://user-images.githubusercontent.com/28490562/175050582-39df0f90-2a65-47f8-b36a-899b7c6e9af6.png)

As you can see from the image, it renders props as an array instead an object

It works this way (without props data attribute)
```html
<div data-controller="symfony--ux-react--react" data-symfony--ux-react--react-component-value="MyComponent"></div>
```

I think that props should be optional.

Thanks!

**Comment by weaverryan** [comment]
Excellent catch - that definitely looks like a bug! 

Probably we should default the `$props` argument to `null` here - https://github.com/symfony/ux/blob/2.x/src/React/Twig/ReactComponentExtension.php#L41-L47

That might be enough to get it working. If it's not, then we would just also modify the call to `renderStimulusController()` to ONLY pass the `props` key if `props` is *not* null.

PR welcome - it would be great if someone could try fixing this :)
