### ISSUE TITLE
[UxSite] When using the back button, images aren't rendered properly

### ISSUE THREAD

**Issue by evertharmeling** [symfony/ux#381]
Steps to reproduce:
- **Vist** https://ux.symfony.com/live-component
- **Click on** one of the 'Live component demo' blocks (at the bottom of the page)
- Then click on the **back button** of your browser (I used Chrome Version 103.0.5060.114 (Official Build) (x86_64))

![Screenshot 2022-07-05 at 10 42 17](https://user-images.githubusercontent.com/308513/177287843-305c2d9b-bd90-4c61-81d9-5722bc31e442.jpg)

![Screenshot 2022-07-05 at 10 42 35](https://user-images.githubusercontent.com/308513/177287882-3be1aee7-360c-4319-ad0d-8e24c9632dd9.jpg)

**Comment by evertharmeling** [comment]
Could be related to https://github.com/symfony/ux/issues/362?

**Comment by weaverryan** [comment]
Got it in #386 - thanks!
