### ISSUE TITLE
Provide a test/playground app to facilitate development and contributing

### ISSUE THREAD

**Issue by Kocal** [symfony/ux#40]
Hi,

For working on https://github.com/symfony/ux/issues/33#issuecomment-745879205, I had to:
- create a new Symfony app
- configure Composer repositories for using local Symfony UX packages (`src/Dropzone`)
- install and setup webpack encore
- create a new page for rendering a dropzone

I think this would be really nice to provide a test/playground app for contributors. This way we saves times and energy before really starting to work on Symfony UX.
 
It would be a fully working Symfony app with:
- all Symfony UX packages are installed locally
- webpack Encore is installed
- test/demo pages for every Symfony UX packages

With this app, everything we have to do is to run the following commands to get ready for working on Symfony UX:
```shell
composer install
yarn
yarn dev
symfony serve
```

WDYT?

**Comment by tgalopin** [comment]
That's something I wanted to do indeed... but I wouldn't do an app but an equivalent of the link script in symfony/symfony (https://github.com/symfony/symfony/blob/5.x/link).

If you want to have a look that would be super useful!

**Comment by Kocal** [comment]
I'm not super familiar with the `link` script, but tell me if I'm wrong:
- this script should be ran inside a Symfony app (e.g.: `cd my-symfony-app; ../my-fork-of-symfony-ux/link`)
- this script will link each Symfony UX packages (`../my-fork-of-symfony-ux/src/*`) to `my-symfony-app/vendor/symfony/ux-<package name>`

Right?

Why not, but there is always the problem of:
- setup webpack encore
- creating dedicated pages for the Symfony UX packages

IMO a test/playground app would be more useful for everyone. WDYT?

**Comment by tgalopin** [comment]
Yes, the link script create symbolic links from a Symfony UX/Symfony fork to a Symfony app, in order to get the framework experience to develop more easily.

My reasoning behind adding this script is that the symfony/ux repository will probably be merge with symfony/symfony at some point, so using the same development technique makes sense.

If you would like to create in a personal repository a playground app, that could be indeed very useful but I'm not in favor of putting it under the symfony namespace.

**Comment by Kocal** [comment]
> My reasoning behind adding this script is that the symfony/ux repository will probably be merge with symfony/symfony at some point, so using the same development technique makes sense.

Oh! Alright, I didn't know about this, that makes sens then.

I will try to work on it this weekend I think.

**Comment by disjfa** [comment]
I have never found a way where it is explained how you could get the symfony base setup in a development environment. And have always been curious about that. Will keep this one in mind.

If these bundles will be incorporated in the symfony main repo is should be a good idea to setup the directories as they have. I don't think the main repo will change anytime soon, so it would be easier to have it set up to be merged already. Than the link script can be copied here. Twice the work is once too many.
