### ISSUE TITLE
How to add options to Swup?

### ISSUE THREAD

**Issue by bettinz** [symfony/ux#41]
Hello, I'm trying to add the slide theme in swup and other plugins like https://swup.js.org/plugins/scripts-plugin

What I've done so far is
`npm install @swup/scripts-plugin`
`npm install @swup/slide-theme`

Now how can I enable that options?

Thanks

**Comment by tgalopin** [comment]
Hi!

You should extend the default behavior (https://github.com/symfony/ux/tree/main/src/Swup#extend-the-default-behavior) and use the Swup instance to add the plugin:

```
event.detail.swup.use(new MyPlugin());
```

**Comment by bettinz** [comment]
Thank you very much 😎
