### ISSUE TITLE
[Autocomplete] How can I pass the `class` option of an EntityType through to an AutocompleteField?

### ISSUE THREAD

**Issue by jerrac** [symfony/ux#434]
This is the need that gave me the idea for #433 . That would resolve this issue perfectly. 

I have a bunch of entity types that reference each other. So I have a lot of EntityType fields on my forms. Autocomplete works fine when the entities already exist, but when I let the user add a new entity via a modal (thank you SymfonyCasts stimulus/turbo course) on the referencing entities form, that new entity is not available for selection.

Ajaxifying the form seems like the obvious solution to me. So I tried to create a generic EntityAutocompleteField. I figured the `class` option would get passed through and replace whatever default I set in the `$resolver->setDefaults()` call. That didn't work.

When I searched for similar issues I found #420 . Does the `class` option on an EntityType count as a custom option? If so, am I stuck creating a separate field type for every entity type I create? Or is there another way?

Or should the `class` option really pass through and override what's in the EntityAutocompleteField? 

Thanks in advance!

**Comment by weaverryan** [comment]
Hey @jerrac!

See my reply on #433 that explains why `class` can't be passed and the possible way that we *could* support this, if someone contributes it :).

Cheers!

cheers!
