### ISSUE TITLE
[Autocomplete] Turning off javascript causes no options to be rendered in custom AutocompleteField

### ISSUE THREAD

**Issue by jerrac** [symfony/ux#437]
I created a custom autocomplete field type to enable ajax loading and some filtering. Unfortunately, when I got around to testing without javascript turned on, the field rendered no options.

A non-custom autocomplete field works just fine without javascript. 

So, this works:
```php
$builder->add('Phone', EntityType::class, [
          'autocomplete' => true,
          'class' => Phone::class,
          'required' => false,
          'choice_label' => 'list_as',
          'help' => "Optional. Select the phone number of this contact.",
          'multiple' => true,
          'row_attr' => [
            'class' => 'mjh-entity-ref-row w-100 d-inline-flex justify-content-between align-middle',
            'data-controller' => 'modal-insert',
            'data-modal-insert-entity-type-value' => 'Phone',
            'data-modal-insert-modal-title-value' => 'Add Phone Number',
            'data-modal-insert-modal-frame-id-value' => 'mjh-modal-entity-new-Phone',
            'data-modal-insert-modal-frame-src-value' => '/basics/phone/new',
          ],
          'attr' => ['id' => 'mjh-phones-field', 'class' => 'mjh-multiple-entity-field mjh-optional-field'],
        ]);
```
![image](https://user-images.githubusercontent.com/910764/185773383-7d58de96-abef-4f3e-95a5-401809f2389a.png)

This does not work:
```php
        $builder->add('Phone', PhoneAutocompleteField::class, [
          'required' => false,
          'help' => "Optional. Select the phone number of this contact.",
          'multiple' => true,
          'row_attr' => [
            'class' => 'mjh-entity-ref-row w-100 d-inline-flex justify-content-between align-middle',
            'data-controller' => 'modal-insert',
            'data-modal-insert-entity-type-value' => 'Phone',
            'data-modal-insert-modal-title-value' => 'Add Phone Number',
            'data-modal-insert-modal-frame-id-value' => 'mjh-modal-entity-new-Phone',
            'data-modal-insert-modal-frame-src-value' => '/basics/phone/new',
          ],
          'attr' => ['id' => 'mjh-phones-field', 'class' => 'mjh-multiple-entity-field mjh-optional-field'],
        ]);
```

All I get is an empty multiselect box:

![image](https://user-images.githubusercontent.com/910764/185773251-9252ac71-a1c1-40ca-b47a-a5c01eea7ac7.png)

I did try stripping out all my custom filtering in the custom field type, (to the point it looks almost exactly like the one in the [docs](https://symfony.com/bundles/ux-autocomplete/current/index.html#usage-in-a-form-with-ajax)) but it didn't help.

```php
<?php

namespace App\Form\Basics;

use App\Entity\Basics\Phone;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\UX\Autocomplete\Form\AsEntityAutocompleteField;
use Symfony\UX\Autocomplete\Form\ParentEntityAutocompleteType;

#[AsEntityAutocompleteField]
class PhoneAutocompleteField extends AbstractType
{

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
          'class' => Phone::class,
          'placeholder' => 'Choose a Phone Number',
        ]);
    }

    public function getParent(): string
    {
        return ParentEntityAutocompleteType::class;
    }

}
```

Any ideas on how to fix this?

Thanks!

**Comment by 1ed** [comment]
I think that's how it should work. When using the autocomplete with ajax it should render an empty field on the server. If you want graceful degradation and being usable without js you should use the entity type.

If you want to write automated tests for it, you should run the tests in a browser e.g. using [panther](https://github.com/symfony/panther). If you really want to test it without js e.g. with Symfony's WebTestCase just add the data when posting the form, something like this:

```php
// create a phone entity, or just use an existing id
$phone = PhoneFactory::createOne(['name' => 'Test Number']);

// get the form
$form = $crawler->filter('button[type="submit"][value="saveAndReturn"]')->form([], 'POST');

// without js autocomplete selects are empty, so we need to disable validation
$form['ParentFormName[Phone][autocomplete]']->disableValidation();
self::$client->submit($form, [
    'ParentFormName[Phone][autocomplete][]' => $phone->getId(),
]);
```

**Comment by weaverryan** [comment]
I agree. When you’re using the ajax powered version, the select box must render empty (or it can render with your selected options, but it cannot render ALL the options). If it rendered all the options, that’d kill the page if you have many, many options, which is part of the point of the ajax-powered autocomplete.

I definitely want the component to degrade as gracefully as possible, but I’m not sure what real options we have to do better.

**Comment by jerrac** [comment]
I see your point... In my case, I'm after the fact that newly added entities can be found via the ajax call without reloading the form. As in the user adds a new entity via a modal on the form of another entity, then they can immediately find that new entity to add it as a reference. So the issues with loading lots of entities didn't occur to me.

I kinda want to be able to do it anyway, though. How many entities would it take to actually cause a problem? Either server or client side? How many sites would hit that mark?

Anyway, I'll keep thinking about my specific use and see if I can figure out a better way.

Thanks for the replies!

**Comment by weaverryan** [comment]
> I kinda want to be able to do it anyway, though. How many entities would it take to actually cause a problem? Either server or client side? How many sites would hit that mark?

Maybe 50-100 entities and you'd notice your page slowing down. It happens all the time. I mean, in some cases (e.g. category dropdown on a "product form") it is maybe no problem. In other cases (e.g. user drop down... when you have 100k users) will cause your page to completely break :).

Cheers!
