### ISSUE TITLE
[TwigComponents] Access a component via a custom twig function

### ISSUE THREAD

**Issue by tacman** [symfony/ux#438]
I love the twig components. They rock.

I'm refactoring a badge TwigFunction as a component, and realized that calling the component was longer than the twig call.

```twig
       {# with options array #}
        {{ badge({color:color, message:message}) }}

        {# positional arguments #}
        {{ badge(color, message) }}

        {# named arguments #}
        {{ badge(color=color, message=message) }}

        {# as component #}
        {{ component('badge', {color: color, message: message:message}) }}
```

This got me thinking, could I wrap the component in twig function?

```php
// TwigExtension.php

    public function __construct(
                                private ComponentRenderer $componentRenderer,
...


    public function getFunctions(): array
    {
        return [
            new TwigFunction('badge', [$this, 'badge']),
        ];
    }
 
    public function badge(array $props=[])
    {
        return $this->render('badge', $props);
    }

    public function render(string $name, array $props = []): string
    {
        return $this->componentRenderer->createAndRender($name, $props);
    }
```

This didn't work, it was copied from the TwigExtension in the Component class, the renderer is marked as ~~final~~ internal so this is certainly not the right approach.    Better would be if it were implemented in the component itself, something like 

```php
#[AsTwigComponent('badge', template: 'components/badge.html.twig', twigFunction: 'badge')]
class BadgeComponent
```

And if named arguments were implemented in Twig as proposed in https://github.com/twigphp/Twig/issues/3475, the transition would be seamless:

```
        {{ component('badge', {color: color, message: message:message}) }}
        {{ badge(color: color, message: message:message) }}

       OR without names:
        {{ badge(color, message}) }}

```

One advantage to this approach (besides fewer characters to read/type) is autocomplete and type-hinting.

Thoughts?  What do you think, especially @kbond and @weaverryan ?

**Comment by kbond** [comment]
Hey @tacman, I'm glad you're digging twig components!

> This didn't work, it was copied from the TwigExtension in the Component class, the renderer is marked as final so this is certainly not the right approach. 

I'm curious why this didn't work. `ComponentRenderer` can't be autowired, is that the problem?

If on 6.1, you can do:

```php
#[Autowire(service: 'ux.twig_component.component_renderer')]
private ComponentRenderer $componentRenderer,
```

Now this class is `@internal` so really shouldn't be used directly but just want to see if you can get this working.

Another thought that came to mind as a possible solution is [_dynamic functions_](https://twig.symfony.com/doc/3.x/advanced.html#dynamic-filters) (docs are for filters but I believe the same can be applied to functions).

```php
public function getFunctions(): array
{
    return [new TwigFunction('*_component', [$this, 'render'])];
}

public function render(string $name, array $props = [])
{
    return $this->componentRenderer->createAndRender($name, $props);
}
```

Now `badge_component()`, `another_component()` would be available.

Sounds like `badge_component()` might be a bit verbose for you. What about `badge_c()` or `c_badge()`? I'm not sure if you can have a fully dynamic function name like `new TwigFunction('*', [$this, 'render'])` but give it a try!

As for including in this library.. I'm not totally onboard. My main purpose in creating twig components was to reduce the number of these random twig functions all over my app. I'd like to at least wait for additional users to request this.

That being said, I totally think we can get this working in your app(s).

**Comment by tacman** [comment]
Thanks, @kbond , indeed autowiring was the problem!

I'll post a working example soon, which a collection of bootstrap components.

**Comment by WebMamba** [comment]
Hello, I am facing the same issue as @tacman. I use a twig function to genera a twig component. Thanks @kbond your little autowiring tricks work great! But I definitively think the component renderer should not be internal. Generate dynamically twig component can be useful in many way 😁

**Comment by kbond** [comment]
Sure, did you want to make a PR to remove internal? Let's make the constructor internal though. You can also make it autowireable too if you'd like.

**Comment by WebMamba** [comment]
@kbond https://github.com/symfony/ux/pull/513 here we are 😁
