### ISSUE TITLE
[LiveComponent] Page refresh does not submit dependent form field implementation

### ISSUE THREAD

**Issue by gnito-org** [symfony/ux#448]
Please refer to https://ux.symfony.com/live-component/demos/dependent-form-fields where one can see the problem in action.

Steps:

1. Select "Second Breakfast".
2. Select "Kiwi".
3. Refresh the page.

"Second Breakfast" is still selected but the Kiwi selection is forgotten.

At first glance it appears that the form is not submitted on page refresh.

**Comment by weaverryan** [comment]
Hey!

I’m not sure I understand. When I select both fields and refresh the page, both fields are “reset” back to their non selected value, which is what I would expect. When you refresh a page, you’re not resubmitting the form (in this case, the form doesn’t have a submit at all). Can you explain the problem a bit more?

**Comment by gnito-org** [comment]
Hi Ryan!

Perhaps this is just a browser-specific issue. It displays the behavior I described in Firefox on Linux, but not in Chrome on Linux. Also not in iOS at all.

Closing this issue with a big nothing-burger high-five!
