### ISSUE TITLE
[ChartJS]  How to customize tooltip title and label/body !?

### ISSUE THREAD

**Issue by hhoussou** [symfony/ux#450]
My chart is done and now I want to customize the tooltip title and label(or body).
I did like that :

```
$chart->setOptions([
        'tooltips' => [
            'callbacks' => [
                    // new title ...
                'title' =>  function($tooltipItem, $data) {
                    return $data['labels'][$tooltipItem[0]['index']];
                },
                    // new label/body ...
                'label' =>  function($tooltipItem, $data) {
                    ...
                }
            ],
            'backgroundColor' => '#fff',
            'bodyFontColor' => '#000',
            'bodyFontSize' => 11,
        ],
    ]);
```

For tooltips `backgroundColor,bodyFontColor,bodyFontSize works` but `not the title and label in callbacks`.
Anyone has already solved this problem ?

**Comment by weaverryan** [comment]
Hi there!

unfortunately, it can’t work like this :/. The callbacks need to be javascript callbacks. So, you can set all the other options this way. But for the options that require callbacks, you need to create a stimulus controller and listen to the pre-connect event, as shown here - https://symfony.com/bundles/ux-chartjs/current/index.html#extend-the-default-behavior - then you can modify the options that will be passed to chartjs and include your callback options. I wish this part could be done in php, but it’s not possible.

Cheers!
