### ISSUE TITLE
[LiveComponent] Support loading states on an action-by-action basis

### ISSUE THREAD

**Issue by FrancoisPog** [symfony/ux#462]
For now, the `data-loading` is added during all actions of the component (see [docs](https://symfony.com/bundles/ux-live-component/current/index.html#loading-states)), but it could be useful to know which action is triggering the loading.

Related to this [message](https://symfony-devs.slack.com/archives/C01FN4EQNLX/p1660246333556999?thread_ts=1660079481.593009&cid=C01FN4EQNLX).

Thanks !

**Comment by weaverryan** [comment]
I'm working on this right now - the syntax will be `data-loading="action(foo)|addClass(foo-loading)"`.

So, in this case, the `foo-loading` class will only be loaded if the `foo` action has been triggered :)
