### ISSUE TITLE
Directory structure consistency

### ISSUE THREAD

**Issue by BafS** [symfony/ux#463]
Some UX bundles are using the `src/` folder to have the php logic (eg. https://github.com/symfony/ux/tree/2.x/src/Autocomplete) and some are not (eg. https://github.com/symfony/ux/tree/2.x/src/Chartjs).

As discussed in https://github.com/symfony/symfony-docs/issues/15881 it would be great to be consistent, especially in the same repository.

The documentation got updated recently (https://symfony.com/doc/current/bundles.html#bundle-directory-structure and https://symfony.com/doc/current/bundles/best_practices.html#directory-structure) and the current best practice is to have the php logic under `src/`.

**Comment by weaverryan** [comment]
Yes, I think we should probably move things around to follow the convention of using `src/` as we've done in Autocomplete, and a few other packages. Consistency is super important in a mono-repo like this.

**Comment by kbond** [comment]
We've discussed moving `LiveComponent/src/Resources/*` to `LiveComponent/(root)` but I believe the routing config would be a BC break.
