### ISSUE TITLE
Dependent Form Field: Ajax is not trigger

### ISSUE THREAD

**Issue by Rem00756** [symfony/ux#464]
Hello,

I'm currently trying to reproduce this [demo](https://ux.symfony.com/live-component/demos/dependent-form-fields) but once I try to change the selected value : nothing append. I don't have any Ajax request.

I already try to add a basic `<input type="search">` in this component and it's trigger ajax call... 

⚠️ I already have other "input search" working well in this project.

reservation_planner.html.twig
![Capture d’écran 2022-09-16 à 15 02 46](https://user-images.githubusercontent.com/16013417/190645141-89988983-daf2-4e0d-828e-c4209c3240e8.png)

ReservationPlannerForm.php
![Capture d’écran 2022-09-16 à 15 06 54](https://user-images.githubusercontent.com/16013417/190645826-c7b3c796-2557-4da2-95e1-5a9b37461fb9.png)

ReservationPlannerComponent.php
![Capture d’écran 2022-09-16 à 15 07 38](https://user-images.githubusercontent.com/16013417/190645925-7e2a5dc9-35e2-4dbf-995e-dcb5a4e1132d.png)

Composer 
![Capture d’écran 2022-09-16 à 15 09 47](https://user-images.githubusercontent.com/16013417/190646336-f8005b0b-7ec3-42b6-b2f5-0c7cb015993b.png)

**Comment by weaverryan** [comment]
I believe that you @Rem00756 solved this by updating some dependencies? Please reopen if i'm incorrect

**Comment by Rem00756** [comment]
Yeah. To have a full idea, I made a new project with just this features and I check the packages from my "old" project and this new one. They were differents so I add missings packages to my project.
