### ISSUE TITLE
[Vue.js] How to access the app instance?

### ISSUE THREAD

**Issue by Kocal** [symfony/ux#479]
Hi everyone,

Currently it looks like it's not possible to access the result of `createApp()` in order to add some customisation, e.g. when you want to use a plugin: 
```js
const app = createApp();

app.use(MyPlugin);
app.use(MyPluginWithOptions, {
    // ...
});
```

When reading `render_controller.ts` code, I don't see/understand how we can access `this.app`, making plugins (like [Vue Router](https://router.vuejs.org/)) unusable. 

Thanks!

**Comment by weaverryan** [comment]
Hey @Kocal!

I think you need #444 - it's merged, just not tagged yet. All of these events need documentation.

**Comment by Kocal** [comment]
Oh thanks, I wasn't aware about that PR.

Then let's add some documentation :)

**EDIT:** well, I'm not sure to understand how those events work, even by reading the initial PR or the tests, 'guess I will pass my turn 😕
