### ISSUE TITLE
Library "Load More / Infinite Scroll"

### ISSUE THREAD

**Issue by seb-jean** [symfony/ux#48]
Hello :),
I think it would be nice to create a library "Load More / Infinite Scroll"
Thanks ;)

**Comment by seb-jean** [comment]
For instance load :
- comments with content, date and author
- only images
- posts with content, date, author, catégories and image
- etc

So, I wonder if 
- the data should be loaded in JSON and the template in JS (which seems complicated to me for the different possible cases)
- or if the data should be loaded with the template in a partial in HTML

**Comment by sebaherrera** [comment]
https://github.com/twigjs/twig.js merges the two options: data in JSON and template in Twig HTML, which is already known by Symfony developers and also reusable in server for the majority of use cases. Obviously, there is already a need for infinite scroll handling.

**Comment by seb-jean** [comment]
close in favor a nice video: https://symfonycasts.com/screencast/symfony-doctrine/forever-scroll 😃

**Comment by Ismail-Mouyahada** [comment]
> Hello :), I think it would be nice to create a library "Load More / Infinite Scroll" Thanks ;)

I created one for all Js frameworks : https://www.npmjs.com/package/lodscroljs
