### ISSUE TITLE
[ux-vue] Can't use Quasar Framework

### ISSUE THREAD

**Issue by ay-git** [symfony/ux#495]
I try add Quasar Framework to project.
Add library:
`npm add quasar`
`npm install`

In vue component add:
`import { useQuasar } from 'quasar'`

After this webpack-encore compile to js bundle Quasar lib

But i can't use Quasar components, browser error:
`[Vue warn]: Failed to resolve component: q-btn`

If I understand correctly, need to add Quasar to the vue app, something like this:
`app.use(useQuasar)`
But ux-vue does not give access to vue app

**Comment by weaverryan** [comment]
Hi there!

To be able to run `app.use(useQuasar)`,  you can listen to the `vue:before-mount` event, which was recently added (it's on the latest 2.x branch, but not released yet). 

The simplest way to do this would be to put this, for example, in `assets/app.js`:

```
import { useQuasar } from 'quasar';

document.addEventListener('vue:before-mount', (event) => {
    const app = event.detail.app;
    app.use(useQuasar);
});
```

You could also put this code inside a custom Stimulus controller that goes onto the same element as your "Vue" controller of a parent element (I would be the same code inside the `connect()` method of that controller and use `this.element.addEventListener()`.

Please let me know if this helps - we still need to document this, and I'd like to make it as easy as possible.

Cheers!

**Comment by ay-git** [comment]
Thanks @weaverryan !

Try use  `vue:before-mount` event

Implement this patch:
https://github.com/symfony/ux/pull/444/commits/86fa0c8423814fe72e47465882429602a537a020

Event `vue:before-mount` is work
Add to `assets/app.js`:
```
import { Quasar } from 'quasar';
document.addEventListener('vue:before-mount', (event) => {
  const app = event.detail.app;
  app.use(Quasar);
});
```

Quasar Framework is work!  But no styles.

Edit: correct comment, need `import { Quasar } from 'quasar';` instead of `import { useQuasar } from 'quasar';`
**Upd: See the post below "Final instruction to use Quasar Framework on ux-vue"**

**Comment by ay-git** [comment]
While styles added like UDM:
`<link href="https://cdn.jsdelivr.net/npm/quasar@2.9.1/dist/quasar.prod.css" rel="stylesheet" type="text/css">`
They work.

I have not yet figured out how to install them correctly through `webpack-encore`

**Upd: See the post below "Final instruction to use Quasar Framework on ux-vue"**

**Comment by ay-git** [comment]
**Final instruction to use Quasar Framework on ux-vue**
_**Disclaimer:** this instruction be work after this patch https://github.com/symfony/ux/commit/86fa0c8423814fe72e47465882429602a537a020 released, now not released yet!_

Add library:
```
npm add quasar
npm add @quasar/extras
```
_Module `@quasar/extras` need for add fonts with material-icons_

Add to assets/app.js:
```
import { Quasar } from 'quasar';
import 'quasar/dist/quasar.css'
import '@quasar/extras/material-icons/material-icons.css'

document.addEventListener('vue:before-mount', (event) => {
  const app = event.detail.app;
  app.use(Quasar);
});
```

**Everything is ready, you can use `Quasar` tags in your `vue` files**

If you using `dev-server` you can get CORS error on loading fonts, for resolve it add to file `webpack.config.js` in `.configureDevServerOptions(options => ({` this option:
```
      headers: {
        "Access-Control-Allow-Origin": "*",
      },
```


If you need not English language for Quasar component (French for example), add to assets/app.js:
```
import { Quasar } from 'quasar';
import quasarLang from 'quasar/lang/fr'
import 'quasar/dist/quasar.css'
import '@quasar/extras/material-icons/material-icons.css'

document.addEventListener('vue:before-mount', (event) => {
  const app = event.detail.app;
  app.use(Quasar, {
    plugins: {}, 
    lang: quasarLang,
  });
});
```

**Comment by ay-git** [comment]
The use of plugins in Quasar is also not standard, what is written in the Quasar documentation does not work.
Therefore, what I write here is an example of using plugins

**Work example of using plugin Notify for Quasar:**
assets/app.js:
```
import { Quasar } from 'quasar';
import { Notify } from 'quasar'
import 'quasar/dist/quasar.css'
import '@quasar/extras/material-icons/material-icons.css'

document.addEventListener('vue:before-mount', (event) => {
  const app = event.detail.app;
  app.use(Quasar, {
    plugins: {
      Notify
    },
    config: {
      notify: { /* look at QuasarConfOptions from the API card */ }
    },
  });
});
```

in test.vue file:
```
<template>
    <div>Test notification!</div>
    <q-btn
        color="primary"
        label="Show a notification"
        @click="showNotification"
    />
</template>

<script>
    import { Notify } from 'quasar'

    export default {
        data() {
          return {
          }
        },
        methods: {
            showNotification(){
                this.Notify.create({ type: 'positive', message: `Test Notify` });
            }
        }
    }
</script>

<script setup>
defineProps({
});
</script>
```

**Comment by weaverryan** [comment]
Thanks for posting your solution!
