### ISSUE TITLE
[Live] Add a variant to "data-live-ignore" limited to a single dom element and not its children 

### ISSUE THREAD

**Issue by jcrombez** [symfony/ux#509]
We currently have the `data-live-ignore` attribute to exclude a portion of our DOM from the live component render.

When a closed modal is part of a live component and the user opens it (client side), any later render would replace the modal by its initial dom, resulting in getting closed (usually). If the content of said modal is dynamic and needs to be updated by a render, adding the `data-live-ignore` attribute on the modal is not appliable.

What would be nice is to have a variant of this attribute to only exclude a given element and not its children : 

```html
<div id="modal" class="hidden" data-live-single-ignore>
    <h1>Dynamic title</h1>
</div>
```

Or maybe if what needs to be excluded/included is more complex, an inversed version of the attribute : 

```html
<div id="modal" class="hidden" data-live-ignore>
   <div id="something-else" class="hiden">hi</div>
   <div class="modal-body" data-live-notice>
        <h1>Dynamic title</h1>
   </div>
</div>
```

(I had no inspiration on the naming :p)

**Comment by norkunas** [comment]
Same as #270 I guess? 🙂

**Comment by jcrombez** [comment]
oh you're right it's the same !

so for the record, livewire calls it :

`wire:ignore.self`
> The "self" modifier restricts updates to the element itself, but allows modifications to its children.

**Comment by weaverryan** [comment]
I forgot about that issue too - thanks @norkunas 👍 . Very cool that you both had the same example - that validates the need for the feature for that use-case.
