### ISSUE TITLE
[TwigComponent] Component refs

### ISSUE THREAD

**Issue by norkunas** [symfony/ux#542]
Currently when you use `component` twig function, it immediatelly renders the component.
I'd like to have a possibility to get the component ref and modify it if needed before rendering.

For example rendering a table with custom components:
```php
class TableComponent {
    public string $align;
    public function mount(string|array $children) { $this->children = is_array($children) ? implode('', $children) : $children; }
}

class TableCellComponent {
    public string $align;
    public string $children;
}
```

When using it I need to pass the `align` prop down to the TableCell components:
```twig
{{ component('Table', {
  align: 'center',
  children: [
    component('TableCell', { align: 'center', children: 'Cell 1' }),
    component('TableCell', { align: 'center', children: 'Cell 2' }),
    component('TableCell', { align: 'center', children: 'Cell 3' }),
  ]
}}
```
What I'd like to have is:
```twig
Table.html.twig:
<table>
  {% for cellComponentRef in children %}
    {% do cellComponentRef.align = align %} {# set it from the table align prop #}
    {{ cellComponentRef.render() }}
  {% endfor %}
</table>
```

Is it feasible? Or there are better ways to manage child components from the parent? Or use some sort of contexts like in react?

**Comment by weaverryan** [comment]
Hey norkunas!

Interesting. I’ve never seen someone try to pass component objects into a component. I would have solved this by passing, as the children prop, an array of some sort of TableCell DTO, then called component() and used the data from that DTO to pass props to TableCell. However, I do see how having a TableCell component and then a TableCellDto with the same data seems a bit silly. And as components are just objects, I can’t immediately think of why it should be a bad idea to pass an array of them into another component. There could be complications in implementing this, but my gut thinking is that it wouldn’t be too hard. It would be done via something like a component_create() Twig function, I think.

WDYT @kbond? I want to avoid feature creep in favor of best practices on how to do things when possible.

**Comment by kbond** [comment]
Interesting indeed.

So we could add a `mount_component()` twig function that returns a `MountedComponent`. Then we could allow `component()` to accept `string|MountedComponent`. So the example above could look like:

```twig
{{ component('Table', {
  align: 'center',
  children: [
    mount_component('TableCell', { align: 'center', children: 'Cell 1' }),
    mount_component('TableCell', { align: 'center', children: 'Cell 2' }),
    mount_component('TableCell', { align: 'center', children: 'Cell 3' }),
  ])
}}

{# Table.html.twig #}

<table>
  {% for mounted in children %}
    {% do mounted.component.align = align %} {# set it from the table align prop #}
    {{ component(mounted) }}
  {% endfor %}
</table>
```

Some notes on this approach:
1. Would require removing `@internal` from `MountedComponent`
2. Would require adding `render()` to `ComponentRendererInterface`
3. The `PreCreateForRenderEvent` wouldn't be dispatched for components created this way
4. Parent component typehints would need to be for `MountedComponent`, not the wrapped component (ie `public MountedComponent[] $children`)

**Comment by norkunas** [comment]
> 3. The `PreCreateForRenderEvent` wouldn't be dispatched for components created this way

If MountedComponent would accept EventDispatcher then it could call :)

> 4. Parent component typehints would need to be for `MountedComponent`, not the wrapped component (ie `public MountedComponent[] $children`)

No problem, as it would be opt-in :)

Also maybe MountedComponent could also have a `ComponentRenderer` injected into it and have a `__toString()` method which would call the renderer? Then in templates it'd enough to use {{ child }} instead of {{ child.render() }} or something like that..

**Comment by kbond** [comment]
> Also maybe MountedComponent could also have a ComponentRenderer injected into it and have a __toString() method which would call the renderer? Then in templates it'd enough to use {{ child }} instead of {{ child.render() }} or something like that..

I was thinking this as well. We'd need to register `MountedComponent` with the escaper extension so the html isn't escaped. This would add quite a bit of complexity though.

> If MountedComponent would accept EventDispatcher then it could call :)

I don't think this event quite makes sense in this context. This event allows you to modify the rendered string before mounting the component.

**Comment by norkunas** [comment]
Should I try to come up with a PR?

**Comment by kbond** [comment]
I think I'm ok with the approach described here: https://github.com/symfony/ux/issues/542#issuecomment-1310414604

For now, I don't want to make the mounted component self-renderable.

**Comment by norkunas** [comment]
> I think I'm ok with the approach described here: [#542 (comment)](https://github.com/symfony/ux/issues/542#issuecomment-1310414604)
> 
> For now, I don't want to make the mounted component self-renderable.

But then I'd need in twig to do many additionals check for each part where `MountedComponent|string` is accepted to call the `component()` if not rendered, yes?

**Comment by norkunas** [comment]
https://github.com/symfony/ux/compare/2.x...norkunas:component-refs?expand=1

**Comment by norkunas** [comment]
https://github.com/symfony/ux/commit/c82abf5e45b1e73a5c95ea62dfd9994c1af05c65

**Comment by kbond** [comment]
I'm still a little hesitatant to add this feature but the change does seem pretty simple. Go ahead an open as a PR.
