### ISSUE TITLE
Extending Tom Select with a custom Stimulus controller

### ISSUE THREAD

**Issue by iampedropiedade** [symfony/ux#545]
I've followed documentation for extending TomSelect with a custom Stimulus controller.
https://symfony.com/bundles/ux-autocomplete/current/index.html#extending-tom-select

However, when I added the attr option:
```
public function configureOptions(OptionsResolver $resolver)
{
    $resolver->setDefaults([
        'class' => Food::class,
        'attr' => [
            'data-controller' => 'custom-autocomplete',
         ],
    ]);
}
```
the select element became a regular select instead of a TomSelect.

The only way I got it to work was by adding both my custom Stimulus controller and the default controller, like this:
```
public function configureOptions(OptionsResolver $resolver)
{
    $resolver->setDefaults([
        'class' => Food::class,
        'attr' => [
            'data-controller' => 'custom-autocomplete symfony--ux-autocomplete--autocomplete',
         ],
    ]);
}
```

I am unsure if the above is the correct way to use custom controllers and documentation is incorrect or if this is a bug?

**Comment by 1ed** [comment]
I think it's just a documentation issue, you should add `'autocomplete' => true,` to options.

**Comment by iampedropiedade** [comment]
> I think it's just a documentation issue, you should add `'autocomplete' => true,` to options.

I'm using a custom #[AsEntityAutocompleteField] field type though, not an EntityType.
That option doesn't exist.

**Comment by 1ed** [comment]
Oh, in that case `'autocomplete' => true` is added automatically.
Do you have a lazy controller? See https://github.com/symfony/ux/pull/550/commits/bfb7db737ecd19913c16aa721d17ab40e6a10464

**Comment by iampedropiedade** [comment]
I don't have that `stimulusFetch` option so I assume it's not lazy?

**Comment by 1ed** [comment]
It also can be managed by `assets/controllers.json`, but `"fetch": "eager"` is the default, there. I have no other idea and I can not reproduce your issue, please create a reproducer we can check. You can use mine as a starting point https://github.com/1ed/ux-autocomplete-extend
