### ISSUE TITLE
[Autocomplete] 500 when using multiple=true on a not required field

### ISSUE THREAD

**Issue by simondaigre** [symfony/ux#549]
Since https://github.com/symfony/ux/pull/494, Autocomplete fields doesnt work for not required inputs.
The error : `SELECT o FROM App\Entity\City o WHERE o.id IN ()`

**Comment by simondaigre** [comment]
@norkunas would you take a look at this issue ?

**Comment by norkunas** [comment]
I'll try. In which case it queries without a criteria?

**Comment by simondaigre** [comment]
Sorry my GH issue description was wrong. The issue happens when :
- the autocomplete field is not required
- nothing was selected in the autocomplete field
- the whole form is submitted

**Comment by norkunas** [comment]
Only with multiple case?

**Comment by norkunas** [comment]
I've opened a PR, maybe it will fix your case?

**Comment by simondaigre** [comment]
Yes it does, thank you !
