### ISSUE TITLE
Stimulus controllers are not loaded when navigating with turbo

### ISSUE THREAD

**Issue by 1ed** [symfony/ux#553]
Hi, using stimulus controllers with turbo should work out of the box, or am I missing something?

When I click a link and turbo loads the new page stimulus controllers are not run. When I reload the page it works.

There is a reproducer here: https://github.com/1ed/ux-autocomplete-extend

What am I missing?

**Comment by BahmanMehrdad** [comment]
@1ed I tested `https://github.com/1ed/ux-autocomplete-extend` and it ran without problems. It is better to clear the browser cache and Symfony cache. Also clear `public/build` path and rebuild the assets.

**Comment by 1ed** [comment]
Yeah, thanks! That was a caching issue.
