### ISSUE TITLE
Chart.js - Charts are no longer displayed

### ISSUE THREAD

**Issue by bastien70** [symfony/ux#56]
Hey! Since the last version of Symfony and therefore the update of Symfony UX, it seems that there is a problem to display charts with Chart.js

I haven't touched anything on my previous code. But when I return a chart, it no longer appears : 

```twig
<div id="reports_charts">
    <div class="chart-container chart">
        {{ render_chart(chartOne) }}
    </div>
    <div class="chart-container chart">
        {{ render_chart(chartTwo) }}
    </div>
</div>
```

![image](https://user-images.githubusercontent.com/53140475/106754337-2679a580-662d-11eb-8705-76d3a8349cf2.png)

I asked comrades, same problem for them

**Comment by tgalopin** [comment]
You may need to upgrade either Encore, stimulus-bridge or both. You should use Encore 1.0, stimulus-bridge 2.0 and the latest version of UX packages :) .

**Comment by bastien70** [comment]
The problem is that if we upgrade Webpack again to a version greater than or equal to v1, we get bugs that have not yet been officially fixed in the manifest.json file. The choice is therefore complicated ...

Either I update webpack-encore and its dependencies and I can use chart.js properly, but in this case I will have a big manifest.json bug, preventing me from doing some things

Either I leave webpack-still in version 0.32 but I will not be able to use chart.js from Symfony UX :'(

**Comment by Crayzo** [comment]
I got the same error ... the charts were displaying correctly on Symfony version 5.2.2, but since I updated to version 5.2.3 my charts are not showing anymore

**Comment by tgalopin** [comment]
Would you have an error to share here (in the development console of your browser for instance)? Also, could you share here what the generated HTML is for the charts?

**Comment by Crayzo** [comment]
> Would you have an error to share here (in the development console of your browser for instance)? Also, could you share here what the generated HTML is for the charts?

**Before update:**

```
"devDependencies": {
    "@symfony/stimulus-bridge": "^1.1.0",
    "@symfony/webpack-encore": "^0.32.0"
    ...
``` 
I have no errors, JavaScript is not loaded when I go to my charts page. 

But the html element is created:

<img width="1920" alt="Capture d’écran 2021-02-03 à 15 55 57" src="https://user-images.githubusercontent.com/48988062/106765077-b709b300-6638-11eb-9b2d-6f4856d560e4.png">

**After update:** 

If I upgrade webpack-encore to 1.0.4, stimulus-bridge to 2.0, and if I comment ```import '@symfony/autoimport';``` 
in assets/bootstrap.js **it work**. But I have lots of dependency warnings:

<img width="1396" alt="Capture d’écran 2021-02-03 à 16 02 25" src="https://user-images.githubusercontent.com/48988062/106765641-4f079c80-6639-11eb-90b5-1a5702404542.png">

And the compilation is extremely slow... and the names of my entry points are really strange:

```
vendors-node_modules_symfony_stimulus-bridge_dist_index_js-node_modules_bootstrap_dist_js_boo-395df3.css
```
```
 vendors-node_modules_symfony_stimulus-bridge_dist_index_js-node_modules_bootstrap_dist_js_boo-395df3.js
```

<img width="1873" alt="Capture d’écran 2021-02-03 à 16 11 33" src="https://user-images.githubusercontent.com/48988062/106766793-7e6ad900-663a-11eb-8408-998ee52e544a.png">

**Comment by tgalopin** [comment]
@weaverryan do you think there is a problem here?

**Comment by weaverryan** [comment]
> The problem is that if we upgrade Webpack-Encore to a version greater than or equal to v1, we get bugs that have not yet been officially fixed in the manifest.json file. The choice is therefore complicated ...

Hey @bastien70!

What problems are you having? Is it this issue? https://github.com/symfony/webpack-encore/issues/907

And hi @Crayzo!

> But I have lots of dependency warnings

The first one is nothing to worry about, but unfortunate. One of our dependencies doesn't advertise that it works on Webpack 5... even though it does.

About the other ones, do you have `postcss` installed? It looks like some of your packages are telling you that you're supposed to add it to your `package.json` file. That shouldn't have anything to do with Encore. If it didn't happen before, it's possible an upgrade to those packages made a difference. But none of those packages are things that Encore uses - so I'm not sure :).

> And the compilation is extremely slow

Just in case, make sure you're on at least version 1.0.3 - there was a performance regression on the "re"-build in watch and dev-server mode. Also, check out the new build cache - that might help - https://github.com/symfony/webpack-encore/blob/38f233dcb806e8aa4c8ddc5e80750f3419d403f8/index.js#L1008-L1037

> and the names of my entry points are really strange

Those are ok :). I think Webpack 5 did that to make debugging easier. If you build for production, these all become things like `139.js` and other random integer names.

If you have further questions or issues, please open them over on https://github.com/symfony/webpack-encore

Cheers!

**Comment by lordcysiek** [comment]
This is

> You may need to upgrade either Encore, stimulus-bridge or both. You should use Encore 1.0, stimulus-bridge 2.0 and the latest version of UX packages :) .

I started fresh symfony 5.3.3 project, followed instructions to install encore-webpack-bundle, symfony-ux and stimulus. It's broken.
Yarn throws node errors or deprecation warnings. Can't even make it works with 0.32 webpack and 1.1 bridge on 5.3.3 (no errors but no charts also).
On 5.2.2 everything works flawless and I'm afraid of doing composer update with my real application. I know its experimental feature, but i think we need more specific informations about supported yarn and node versions (is 1.22 yarn and 10.x node still supported anyway?).

**Comment by tgalopin** [comment]
Ah, your issue is linked to https://github.com/symfony/webpack-encore/pull/912
