### ISSUE TITLE
[Live] Error when emptying a LiveCollection because of PersistentCollection instead of array

### ISSUE THREAD

**Issue by jcrombez** [symfony/ux#568]
Hello, i'm having an issue with ComponentWithFormTrait  + LiveCollectionTrait.

I don't know what i could have done wrong but when removing all the element from a collection, when the last element is removed, the code fail because the field contains an empty PersistentCollection instead of the usual array. Before the collection is empty it's an array, it becomes a PeristentCollection when it's empty.
So the LiveFormUtility::removePathsNotInData used during ComponentWithFormTrait::submitForm fails when trying to call array_key_exists.

Any idea what could explain for the collection field to get filled with an empty PersistentCollection ?
Maybe the entity side can be of help to understand the problem : 

![image](https://user-images.githubusercontent.com/777666/204336975-f35430e9-d0c0-4f83-998e-cb9c68ac44a0.png)

**Comment by jcrombez** [comment]
I digged a little more on this issue and found out the moment the empty collection in the component data goes from an empty array to an empty PeristentCollection :

https://github.com/symfony/ux/blob/2.x/src/LiveComponent/src/ComponentWithFormTrait.php#L160
```php
$this->formValues = $this->extractFormValues($this->getForm());
```

Usually when the collection is not empty, this line recursively extractFormValues : 
https://github.com/symfony/ux/blob/2.x/src/LiveComponent/src/ComponentWithFormTrait.php#L239
Which ends up building an array representation of the collection, but when the collection is empty, it has no child form element so it goes to this line :
https://github.com/symfony/ux/blob/2.x/src/LiveComponent/src/ComponentWithFormTrait.php#L248
and the value is copied "as is" from the form, and since the value is always a PersistentCollection in the form, the component formValues goes from an array to a PersistentCollection.

**Comment by weaverryan** [comment]
Hi!

I can't repeat this locally, but maybe I don't have enough information yet. Can you post what your component looks like? And exactly what actions do you need to take to trigger the problem? Is the problem an error?

Also, you mentioned that:

> when removing all the element from a collection, when the last element is removed, the code fail because the field contains an empty PersistentCollection instead of the usual array. Before the collection is empty it's an array, it becomes a PeristentCollection when it's empty

When you say "the field contains an empty PersistentCollection", by "field" are you referring to the `lines` property of the entity that you posted in your screenshot? Or something else? If you're referring to the `lines` property in the entity, then it is *never* an array: it's either an `ArrayCollection` (because that's how you initialize it in the constructor) or `PersistentCollection` (because that's what Doctrine gives you when you query for it). So, I was confused about this part - but I'm wondering if you were referring to something else :).

Cheers!

**Comment by jcrombez** [comment]
> Can you post what your component looks like?

https://gist.github.com/jcrombez/9499c11f8f1abc35280b14c7195b4e5f


> And exactly what actions do you need to take to trigger the problem

I'm editing an existing entity. The collection is not empty, i fully empty it, and the problem occur when i remove the last element.


> Is the problem an error?

Yes, i get an exception when `array_key_exists` is called on the PersistentCollection (in removePathsNotInData).

![image](https://user-images.githubusercontent.com/777666/214084691-81e83973-6c87-49ce-ad7b-4d783075e189.png)


> When you say "the field contains an empty PersistentCollection", by "field" are you referring to the lines property of the entity

Yes it's what i'm referring to.

Maybe this information can help : for now i'm using an ugly workaround by using a custom trait (not included in the gist) to replace this line (in ComponentWithFormTrait::extractFormValues 247) : 

```php
                $values[$name] = $child->vars['value'];
```

by this line :

```php
                $values[$name] = $child->vars['allow_delete'] ?? false ? [] : $child->vars['value'];
```

To replace my empty PersistentCollection by an empty array.

**Comment by jcrombez** [comment]
A bit late to answer you but i can now confirm it fixes my issue. Great job !
