### ISSUE TITLE
[Autocomplete] - Not firing requests when using `autocomplete_url`

### ISSUE THREAD

**Issue by noook** [symfony/ux#576]
I'm trying to use the Symfony UX Autocomplete component within a form on the EasyAdmin bundle. I need to use a TextField which will call a custom controller to get results. The usecase is an address autocompleter thanks to Google Maps autocomplete service.

This is my current CrudView configuration:

```php
class LocationCrudController extends AbstractCrudController
{
    public static function getEntityFqcn(): string
    {
        return Location::class;
    }

    public function configureFields(string $pageName): iterable
    {
        if ($pageName === Crud::PAGE_INDEX) {
            return [/* ... */];
        } else if ($pageName === Crud::PAGE_NEW) {
            return [
                TextField::new('placeId')
                    ->setFormType(TextType::class)
                    ->setFormTypeOptions([
                        'autocomplete' => true,
                        // I tried with relative URL as well
                        'autocomplete_url' => 'http://localhost/api/place-autocomplete',
                    ]),
            ];
        }
    }
}
```

when rendering, all the atributes are present:
```html
<input type="text" id="Location_placeId" name="Location[placeId]" required="required"
  data-controller="symfony--ux-autocomplete--autocomplete"
  data-symfony--ux-autocomplete--autocomplete-url-value="http://localhost/api/place-autocomplete"
  data-symfony--ux-autocomplete--autocomplete-max-results-value="10"
  data-symfony--ux-autocomplete--autocomplete-min-characters-value="3"
  data-symfony--ux-autocomplete--autocomplete-no-results-found-text-value="No results found"
  data-symfony--ux-autocomplete--autocomplete-no-more-results-text-value="No more results"
  data-symfony--ux-autocomplete--autocomplete-preload-value="false" class="form-control">
```

But no requests are fired to the defined endpoint.

**Comment by daFish** [comment]
I think it works with the relative url. How many characters did you enter in the field? The default configuration is 3 characters minimum.

**Comment by noook** [comment]
Tried with relative URL, and min length, nothing is fired:

https://user-images.githubusercontent.com/19751938/204764688-72dbefdf-7b69-400e-8139-a200258b5b38.mov

**Comment by daFish** [comment]
Is the controller connected and shows its dev output in the console? Are all assets built?

**Comment by noook** [comment]
there is no controller at the moment, I'd expect the javascript to still fire requests and receive a 404, is there a server side check ?

The assets are built, I ran `npm run watch` after installing the assets

edit: what controller ? The RouteController (php) or javascript ?

**Comment by daFish** [comment]
The default stimulus controller should be bound due to `data-controller="symfony--ux-autocomplete--autocomplete"`.

![Bildschirmfoto 2022-11-30 um 11 16 44](https://user-images.githubusercontent.com/150416/204769858-5a257417-beb2-41b1-ab63-5fc09780b139.png)

One thing you could check is, if the assets are loaded in the template using `{{ encore_entry_script_tags('app') }}` (`app` may vary). This would make sure that the scripts from the bundle are loaded.

**Comment by daFish** [comment]
After a good conversation with @noook in Slack we came up with a solution:

To add the encore assets in EasyAdminBundle use the built-in methods as described in https://symfony.com/bundles/EasyAdminBundle/current/design.html#adding-custom-web-assets
