### ISSUE TITLE
Embed symfony/ux-turbo-mercure into symfony/ux-turbo

### ISSUE THREAD

**Issue by weaverryan** [symfony/ux#578]
Hi!

Since the repository reorganization in 2.6, I've discovered a problem #577.

Basically, when you install `symfony/ux-turbo` you ALSO get (and have always gotten) the code for the `symfony/ux-turbo-mercure` package. This is because that package lives as a subdirectory of `symfony/ux-turbo`: https://github.com/symfony/ux-turbo/tree/2.x/src/Bridge/Mercure. In 2.6, because autoloading rules were normalized, this becomes more obvious because Composer sees the classes 2 times.

Proposal: let's deprecate/remove the `symfony/ux-turbo-mercure` package and just include it (like we already are in 2.6) inside `symfony/ux-turbo`. Notes:

A) `symfony/ux-turbo-mercure` only includes 2 classes - it does not include a bundle, configuration or anything else.
B) When those 2 classes exist, there IS some magic in MercureBundle to wire them as services https://github.com/symfony/mercure-bundle/blob/fed303b571bbb58a411e02d52bebfe3b86d774ee/src/DependencyInjection/MercureExtension.php#L213-L230

However, I think this is "safe". If MercureBundle is not installed, then these services will not be registered and the user has 2 unused classes in `vendor/`. If MercureBundle IS installed, then it would instantly mean that Mercure could be used for listening to Turbo streams, without needing to install an extra package. 

What's the potential negative behavior change? It's very edge. If someone:

A) Has `symfony/ux-turbo` installed
AND
B) Has `symfony/mercure-bundle` installed
AND
C) Does NOT have `symfony/ux-turbo-mercure` installed
AND
D) Has registered their own custom broadcaster with `symfony/ux-turbo` so that they can publish/listen to messages using some other publisher.

If you have this situation, then you might now end up with 2 `default` broadcasters in `symfony/ux-turbo`, and one might win over the other. And IF we have this problem, we can think of some config to solve it.

**Comment by chalasr** [comment]
Makes sense to me.
