### ISSUE TITLE
Mail bundle

### ISSUE THREAD

**Issue by disjfa** [symfony/ux#6]
In the past i have dabbled with the symfony email setup. Tried to implement the foundation for emails and setup the css inliner for the emails. Some setups you can find in the [documentation](https://symfony.com/doc/current/mailer.html) as an example.

So this is not quite a question or issue or just a mention. But a sample for anyone that tries to implement the Mailer.

Forgot the link 🙈
https://github.com/disjfa/mail-bundle

**Comment by maxhelias** [comment]
I am not sure I understand what you are looking for. It's a issue ? A suggestion for improvement?

**Comment by dfridrich** [comment]
@disjfa  you're maybe looking for this: https://symfony.com/doc/current/mailer.html#twig-html-css
