### ISSUE TITLE
[ChartJs] Add support for chart.js:^4.0

### ISSUE THREAD

**Issue by evertharmeling** [symfony/ux#607]
Looks like it won't have a big effect on the ux-component? But probably best to leave that to the experts ;)

- https://www.chartjs.org/docs/latest/migration/v4-migration.html
- https://github.com/chartjs/Chart.js/releases

**Comment by weaverryan** [comment]
Yea, hopefully we can just change this: https://github.com/symfony/ux/blob/f270fe4cab069893aac5a25ebf62a399761325c0/src/Chartjs/assets/package.json#L18 to:

```
"chart.js": "^3.4.1 || 4.0"
```

PR welcome :)

**Comment by evertharmeling** [comment]
Thought so too, will take a look at it! ;)
