### ISSUE TITLE
[LiveComponent] parameter route doesn't exist

### ISSUE THREAD

**Issue by alexgaill** [symfony/ux#619]
On attribute AsLiveComponent, the 'route' parameter doesn't exist but documentation refers to it.
![Capture d’écran 2022-12-19 à 11 36 13](https://user-images.githubusercontent.com/47665701/208406624-9eae9f87-8f42-4809-b18d-0baf3e7a8faa.png)

**Comment by kbond** [comment]
This will also be added in 2.7. Don't have an ETA yet. Ryan's on vacation and there's a few things to finalize before a release.

**Comment by weaverryan** [comment]
I added the missing `versionadded` in sha: b6c86be345f6680ffed17332eadcbcd930a61404 

We're definitely due for a release soon :)
