### ISSUE TITLE
[Twig] Multiple actions with `stimulus_action`

### ISSUE THREAD

**Issue by Spomky** [symfony/ux#648]
Hi,

At the moment, when we use `stimulus_action` multiple times, only one action is visible.
But stimulus is designed for setting several actions on the same node (see https://www.dwightwatson.com/posts/using-multiple-actions-on-a-single-element-with-stimulus).

It would be great if, with the following Twig template,

```twig
<div
    {{ stimulus_action('my-controller', 'enableFeature', 'click') }}
    {{ stimulus_action('my-controller', 'updateFoo', 'other-controller:changed') }}
>
Foo, Bar
</div>
```

it converts it into

```html
<div
    data-action="click->my-controller#enableFeature other-controller:changed->my-controller#updateFoo"
>
Foo, Bar
</div>
```

**Comment by jmsche** [comment]
Hi, you can use the `stimulus_action` filter to have several actions: https://github.com/symfony/webpack-encore-bundle#stimulus_action

Also, this issue should be in Encore bundle, not ux :)

**Comment by Spomky** [comment]
Correct. I can confirm it works as expected.
Thanks for the hint.
