### ISSUE TITLE
[Autocomplete] max_results is ignored on first load without query

### ISSUE THREAD

**Issue by norkunas** [symfony/ux#654]
By default 10 rows are configured to be returned, but if I change to 25 or 50 and with min chars = 0 I expected to get also that number of rows

**Comment by weaverryan** [comment]
Is it possibly solved already by? https://github.com/symfony/ux/pull/626 Or is the problem that, when you change `max_results` to 25, you still see 10 on first load?

**Comment by norkunas** [comment]
Yes 10 on first load :)

**Comment by weaverryan** [comment]
Here's the problem: https://github.com/symfony/ux/blob/2.x/src/Autocomplete/src/Form/WrappedEntityTypeAutocompleter.php#L54-L59 - that max results should be above the if statement. Are you able to make a PR?

**Comment by norkunas** [comment]
Yeah I could on monday :)
