### ISSUE TITLE
[Dropzone] Cannot build, style.css missing

### ISSUE THREAD

**Issue by aleho** [symfony/ux#657]
Commit 807e0ea4cb4c1ead7c807826e5f84038498dfdaa removed the src directory containing `style.css` from the released sources but the `package.json` still refers to that file to include it in default builds:

https://github.com/symfony/ux/blob/57deb647010ba7f6de954ae74b6f35de4b82827c/src/Dropzone/assets/package.json#L15-L17

Did you intend to remove that CSS file completely? Or should it be copied to the dist folder instead?

**Comment by weaverryan** [comment]
Thanks for the report - fixed in #661 :)
