### ISSUE TITLE
[Dropzone] Impossible to install on SF4.4

### ISSUE THREAD

**Issue by Jibbarth** [symfony/ux#66]
On a fresh install of Symfony 4.4, when requiring ux-dropzone, the following error is raised 

![image](https://user-images.githubusercontent.com/3168281/109701028-dc83d100-7b92-11eb-8368-89a18bfc11a7.png)

The default recipes for twig-bundle in 4.4 use `%kernel.debug%` for `twig.debug` configuration.

May be related to https://github.com/symfony/symfony/issues/40198

**Comment by alexander-schranz** [comment]
FYI: my docs PR for resolving the paramters was merged so I think this is the correct way to handle this in the prepend extension: https://github.com/symfony/symfony-docs/pull/15048

**Comment by khaledBou** [comment]
Got the same error when using Symfony 5.2

  Invalid type for path "twig.debug". Expected "bool", but got "string".
