### ISSUE TITLE
Update the "about" link of this repository to https://ux.symfony.com

### ISSUE THREAD

**Issue by florentdestremau** [symfony/ux#664]
Currently it points to https://symfony.com/ux which leads to https://symfony.com/blog/new-in-symfony-the-ux-initiative-a-new-javascript-ecosystem-for-symfony. This link should probably be somewhere in the README to explain how this came to exist but the main interesting link is https://ux.symfony.com IMO :smiley:

**Comment by weaverryan** [comment]
Good call - done!
