### ISSUE TITLE
[LiveComponent] Password fields are not being send within form on model change

### ISSUE THREAD

**Issue by sabat24** [symfony/ux#677]
I created a component using `ComponentWithFormTrait`. In my form type there is an `input type="password"` field. If I modify value in that field directly everything works fine. Take a look at `plainPassword` attribute. 

![obraz](https://user-images.githubusercontent.com/6381661/216811494-6c2dbd99-3ea1-473e-ad2b-e60ec9573828.png)

However when I change another field the `plainPassword` attribute is empty in request.

![obraz](https://user-images.githubusercontent.com/6381661/216811625-d1144a67-b46f-4680-8e05-c0f3c2255dc7.png)

So I end up with validation error that password can not be empty. If I change that field from `type="password"` to `type="text"` everything works also fine.

**Comment by sabat24** [comment]
https://symfony.com/bundles/ux-live-component/current/index.html#form-rendering-problems -> `'always_empty' => false`

**Comment by weaverryan** [comment]
Hi!

Are you saying the `always_empty => false` fixed your issue?

**Comment by sabat24** [comment]
Yes. It wasn't an obvious case for me as I use `data-live-ignore` attribute, so the field was filled all the time on my screen, but internally it was empty.

**Comment by weaverryan** [comment]
Awesome - happy you found that! I wish there were some more automatic way for us to "fix" that, but probably not a good idea :).

Btw, what's your use-case for using `data-live-ignore` here? I always like to find out.

Cheers!

**Comment by sabat24** [comment]
> Awesome - happy you found that! I wish there were some more automatic way for us to "fix" that, but probably not a good idea :).

This is something you just need to know / remember that it works this way. For my projects I "fixed" it by extending core `PasswordType` with my `UxPasswordType`, which overrides `allow_empty` value. 
 
> Btw, what's your use-case for using `data-live-ignore` here? I always like to find out.

I use it to solve that case

User entered data in field A and pressed tab to move to field B. 
Moving to field B triggered an ajax request (onChange event).
In the meantime user started to type something in field B.
Then the request triggered in Field A has ended. As a result LiveComponent re-rerendered itself and emptied field B (because field B was empty in the time of making that request).
