### ISSUE TITLE
[ChartJs] Date Adapter?

### ISSUE THREAD

**Issue by temp** [symfony/ux#682]
I'm using chartsjs 3.x, and I'm trying to render a chart with a time scale, which doesn't work without a date adapter, since the bundled momentjs was removed in 3.x
What's the best way to include for example https://github.com/chartjs/chartjs-adapter-date-fns ?
I tried to import the adapter in app.js, but that did not work.
Any hints for this?

**Comment by weaverryan** [comment]
Hmm, I'm not sure. I would have done the same thing you did: add this to the top of my `assets/app.js`:

```
import { Chart } from 'chart.js';
import 'chartjs-adapter-date-fns';
```

It appears that this library works by "modifying" parts of `chart.js` itself. So, in theory, as long as the above code runs before your Chart.js Stimulus controller (which it DEFINITELY would, especially if you have this code above the `import './boostrap'` line), then it should work as expected: when the Stimulus controller imports `chart.js`, it will have already been modified by your imports in `app.js`.

**Comment by temp** [comment]
Thanks for your answer, Ryan! Nevermind, it was just webpack hassle - another chart.js plugin loaded version 4.x of chart.js, and this broke it. Upgrade to npm 9 solved the issue!
