### ISSUE TITLE
[Site] Change to use highlight.js directly

### ISSUE THREAD

**Issue by weaverryan** [symfony/ux#683]
Hi!

We currently use https://github.com/scrivo/highlight.php for code highlighting. Unfortunately, this has fallen behind the real package - https://github.com/highlightjs/highlight.js - and so we're lacking things like proper highlighting for attributes (PHP 8 attributes are currently seen as comments and aren't even selectable by users!)

We should remove highlight.php and, instead, just call out to highlight.js via JavaScript for it to add the highlighting classes.

**Comment by javiereguiluz** [comment]
I was going to create an issue about attributes not being selected:

![text-selection-comments](https://user-images.githubusercontent.com/73419/217461195-95a22002-0a69-4807-bb9a-cbe795f9d1f5.gif)

But I see that this will be fixed by switching to the JS highlighting library. Thanks!

**Comment by smnandre** [comment]
Still want to make the switch @weaverryan  ?

**Comment by kbond** [comment]
https://shiki.matsu.io/ is a nice option I've used before - has the same support as VS Code.

**Comment by weaverryan** [comment]
Yuuup, I still think we should switch. I mean, I don't really care: I just want the PHP attributes to look and work right :p

**Comment by smnandre** [comment]
I did not know this lib, thanks @kbond 

---

Let's say we want some "tech sobriety" and avoid using a JS library to transform code on every page render... 
(it's currently the case with the PHP library but we could add some cache in a couple of minutes)

... would it be possible to cache that result / pre-render it with a JS library ? How would we do that ? 

(not saying we should do it _now_)

**Comment by kbond** [comment]
I agree, pre-rendering the syntax highlighting is better. For shiki, this should do the trick: https://github.com/spatie/shiki-php. This would require a custom twig filter and probably use twig caching.
