### ISSUE TITLE
Using Stimulus controller with live-component

### ISSUE THREAD

**Issue by fajino17** [symfony/ux#687]
I've read discussion on this issue https://github.com/symfony/ux/issues/527, but I do not clearly understand what means 'put controller around root element'.
Something like this?
```
<div data-controller="custom-controller">
<div{{attributes}}></div> -- live component root
</div>
```
also
```
div {{ attributes.add(stimulus_controller('custom-controller', { someValue: 'foo' })) }}> -- live component root
```

#https://symfony.com/bundles/ux-live-component/current/index.html#working-with-the-component-in-javascript
I couldn't make none of these working.
Can somebody explain this for me. Thanks

**Comment by nicodemuz** [comment]
@fajino17 did you figure this out?

**Comment by IvoPereira** [comment]
If you have created a controller named `custom_controller`, you would only use `custom` when referencing it.

Basically, you create your component (let's say `NavBar`), and in its Twig definition you would have something in the lines of:
```twig
<div {{ attributes.defaults(stimulus_controller('custom')) }}>
    <!-- your component here -->
</div>
```
