### ISSUE TITLE
[LiveComponent] Accessing authenticated user

### ISSUE THREAD

**Issue by JSortGarcia** [symfony/ux#688]
I have the following case: when I render a twig live component for the first time, with the initial request, I can access the user by TokenStorageInterface (`Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface`) or the `Symfony\Bundle\SecurityBundle\Security`.

But when the same component is rerendered by a live action, the request is not authenticated or I cannot find a way to access the logged user.

In fact, I can make the ajax call made to rerender the page without being authenticated, it is simply returns the component html.

Shoudn't the request be only permited to a logged user? And in this case, how this user could be accessed?

I hope it is not a trivial question.

Thanks in advance!

**Comment by kbond** [comment]
My guess is the component route isn't behind your firewall? You can change this [globally](https://symfony.com/bundles/ux-live-component/current/index.html#installation) or on a [component-by-component](https://symfony.com/bundles/ux-live-component/current/index.html#define-another-route-for-your-component) basis.

Let me know if this doesn't work.

**Comment by JSortGarcia** [comment]
It works now! As components live behind the firewall I can access the user in their context

Thanks again for the quick response!

**Comment by kbond** [comment]
Closing but if you think the docs could be improved, feel free to open a PR!
