### ISSUE TITLE
[LiveComponent] Prevent refresh of some elements in the page

### ISSUE THREAD

**Issue by bastien70** [symfony/ux#689]
Hey! I would like to know if it is possible in a Twig file of a component, to target HTML elements that should not be refreshed?

For example, I have a form, and therefore I can ensure that all fields do not refresh by doing this for the selected fields:

```twig
{{ form_widget(form.mandatGestion, {'attr': {'data-model': 'on(change)|norender|' ~ form.mandatGestion.vars.full_name }}) }}
```

On the other hand, I have at the top of the page a bar with several tabs, some of which are grayed out (or not) thanks to a vote that is called.

Some of these tabs are grayed out depending on the values ​​in the form.

Except that when my form refreshes, it also refreshes this bar with the tabs above, and therefore it bases itself on the entity with its last values ​​even if they have not yet been flushed.

![image](https://user-images.githubusercontent.com/53140475/219697743-e4384df4-14b9-4051-9a7d-fdbbda925474.png)

So to make it simpler, if I have a div whose content I don't want to refresh, whatever it is, is that possible?

**Comment by weaverryan** [comment]
Hi!

You should be able to add `data-live-ignore` to that div, and it won't update at all when the component re-renders: https://symfony.com/bundles/ux-live-component/current/index.html#skipping-updating-certain-elements

It should work, though doing this usually means you're hacking around the system - something we'd like to avoid (and, when necessary, add features to help you not need to hack around it). I don't know your setup, but could you store the current "step" on some `LiveProp`. And then "advance" that value each time the user successfully finishes a step?

**Comment by bastien70** [comment]
It works pretty good! Thanks! :)
And the form is very very hard, this is the only solution I've currently ;)
