### ISSUE TITLE
[TwigComponent] Conditionally pass HTML attributes

### ISSUE THREAD

**Issue by AmProsius** [symfony/ux#709]
Sometimes I want to conditionally pass an HTML attribute to a Twig component, but that doesn't seem to work yet.

**Example**

```twig
<!-- components/button.html.twig -->

<button {{ attributes }}>
  {{ label }}
</button>
```

```twig
<!-- home/index.html.twig -->

{{ component('button', {
    label: 'Add feature',
    disabled: not feature.isEnabled,
}) }}
```

will always result in

```html
<!-- index.html -->

<button disabled>
  Add feature
</button>
```

No matter what value is passed (`''`, `false`, `null`), the `disabled` attribute will always be displayed.

My current workaround is this:

```twig
<!-- components/button.html.twig -->

<button {{ attributes ~ (isDisabled ? ' disabled') }}>
  {{ label }}
</button>
```

But this feels like a very dirty hack. I know that passing `null` will omit the value and just render the attribute, but I wish I was able to conditionally omit the whole attribute by passing `false` for example.

**Comment by kbond** [comment]
Interesting, I wonder if we should treat true/false (maybe null) differently when used as attributes. If the value is false/null, we remove the attribute. If you _truly_ wanted to pass `false` (to make the attribute `foo="false"`), you'd need to wrap in a string (`foo: 'false'`).

@weaverryan, wdyt?

**Comment by AmProsius** [comment]
> Interesting, I wonder if we should treat true/false (maybe null) differently when used as attributes. If the value is false/null, we remove the attribute.

Maybe it's worth a thought to pass `true` to an attribute to omit its value instead of `null` and omit the whole attribute on `false` or `null`.

Alternatively, to enable backwards compatibility, the `null` behaviour can be left unchanged (or be deprecated) and the `true`/`false` behaviour can be added.

That way, passing a boolean value will always result in a value-less attribute or no attribute at all (which is the equivalent of a boolean HTML attribute like `disabled`).

See [Boolean attributes](https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#boolean-attributes) in the HTML Specs:

> The presence of a boolean attribute on an element represents the true value, and the absence of the attribute represents the false value.

**Comment by kbond** [comment]
Yes, I think that makes sense, and follows the HTML Spec. For `null`, ~I guess the current behaviour of `disabled: null` would render as `disabled=""`?~ Current behaviour is actually `disabled: null` => `disabled`, which is weird.

**Comment by AmProsius** [comment]
> For `null`, I guess the current behaviour of `disabled: null` would render as `disabled=""`?

The current behaviour actually omits the value and renders as `disabled`.

https://github.com/symfony/ux-twig-component/blob/e6becc78e7d4618606ecb2af631366be73343592/src/ComponentAttributes.php#L32-L45

Proposed fix:
```php
    public function __toString(): string
    {
        return array_reduce(
            array_keys($this->attributes),
            function (string $carry, string $key) {
                if (false === $this->attributes[$key]) {
                    return $carry;
                }

                if (true === $this->attributes[$key] || null === $this->attributes[$key]) {
                    return "{$carry} {$key}";
                }


                return sprintf('%s %s="%s"', $carry, $key, $this->attributes[$key]);
            },
            ''
        );
    }
```
