### ISSUE TITLE
[LiveComponent] LiveCollectionType does not play well without block prefix

### ISSUE THREAD

**Issue by norkunas** [symfony/ux#715]
As soon as the form type returns an empty block prefix, `LiveCollectionType` fails to add or remove an item in the collection:
`Cannot read property "items" from an array. Maybe you intended to write the property path as "[items]" instead.`
That's because the property path for the action becomes `addCollectionItem(name=items)` instead of `addCollectionItem(name=todolist[items])`.

Should it be supported out of the box?

Reproducer: https://github.com/norkunas/sfux-tests/tree/live-form-dto-collection

**Comment by 1ed** [comment]
Thanks for the reproducer. Should be fixed by #717
