### ISSUE TITLE
[Live] Fix problems with CollectionType Demo & unpersisted TodoList

### ISSUE THREAD

**Issue by weaverryan** [symfony/ux#740]
In the unreleased 2.8 version, you are now allowed to have non-persisted entities on a LiveProp. We need to update https://ux.symfony.com/live-component/demos/form-collection-type to show this off, which means ALWAYS passing in the `todoList` to the component.

Doing this locally exposes a few problems:

1) When `TodoList` is dehydrated (via the serializer), it fails due to a circular reference (TodoList -> TodoItem -> TodoList)
2) When that's fixed, on the first Ajax call, the dehydrated data fails to set due to type problems. For example, `TodoList::setName()` accepts a `string` argument, but the object deserialized to `null` initially.
3) If we empty the `TodoList` (by default we put one item into it), we hit a checksum problem due to how the empty `ArrayCollection` is dehydrated.

Let's also check the case where the `ArrayCollection` is initialized to a few saved entities.

**Comment by chrisVdd** [comment]
Hey @weaverryan,

I'm trying to do the exact same thing as the TodoList example but can't make it work: when I click on the "add" button, it looks like it does... Nothing.
I'm currently in 2.7.1.

Do you advice me to wait for a newer version ?
The form collection always been a struggle with Symfony, for me so I was hoping UX could saved me lol.

Thanks !
