### ISSUE TITLE
Swup: reload Javascript

### ISSUE THREAD

**Issue by jaszfalvitamas** [symfony/ux#75]
Hi guys,

Swup works amazingly. It pulls every linked asset as required, but the javascript code is not executed.
The swup documentation suggests using
`swup.on('contentReplaced', init);`
but I can't get it to work.
Any help would be greatly appreciated!

**Comment by bastien70** [comment]
Have you solved the problem? I meet the same

**Comment by jaszfalvitamas** [comment]
Nah, I just used the vanilla swup instead.

**Comment by janwebdev** [comment]
`document.addEventListener('swup:contentReplaced', callback);`

where callback is your js initialization function
