### ISSUE TITLE
about ux react get logged user information

### ISSUE THREAD

**Issue by langziyang** [symfony/ux#758]
symfony+symfony/ux-react,
in any_file.html.twig
```
<div {{ react_component('EmployeeList') }}></div>
```

now i want kown how can i get logged user information on EmployeeList.jsx file?

like in any_file.html.twig use 
```
app.user
```

**Comment by ker0x** [comment]
You have a concrete example in the [ux-react documentation](https://symfony.com/bundles/ux-react/current/index.html#usage):

```twig
div {{ react_component('MyComponent', { 'fullName': app.user.fullName }) }}></div>
```

**Comment by langziyang** [comment]
@ker0x i know this way.but i want get full user informations.so.did have other best way?

**Comment by 94noni** [comment]
you can just serialize your use and pass it as json to your JS code
ref https://symfony.com/doc/current/frontend/encore/server-data.html (bottom of page)

**Comment by langziyang** [comment]
@94noni thank you,
