### ISSUE TITLE
[LiveComponent] Date field ajax request 3 times

### ISSUE THREAD

**Issue by bastien70** [symfony/ux#764]
Hello, when we have a date type field and we configure the `data-model="on(change)"`, it is executed when we modify the day, the month, and the year, instead of being executed when we have finished filling in everything : 

```twig
{{ form_row(form.birthdate, {'attr': {'data-model': 'on(change)|debounce(700)|' ~ form.birthdate.vars.full_name }}) }}
```

https://user-images.githubusercontent.com/53140475/228486448-0a39b2e8-99ea-4226-bfff-ecb207b120a7.mp4

In text fields, it works pretty good

**Comment by WebMamba** [comment]
I think this is the expected behaviour, html dispatch the onChange event on every change made to the field (day, month, year, and even minute and second). Maybe you can listen to the onBlur event or manually change the value.

**Comment by bastien70** [comment]
Hey! You mean, something like that?

```twig
    {{ form_row(form.birthdate, {'attr': {'data-model': 'on(blur)|debounce(700)|' ~ form.birthdate.vars.full_name }}) }}
```
Unfortunately, this no longer causes any events.

When you say "manually change the value", what do you mean?

**Comment by WebMamba** [comment]
Like here: https://symfony.com/bundles/ux-live-component/current/index.html#working-with-the-component-in-javascript

**Comment by bastien70** [comment]
Thank you!
