### ISSUE TITLE
[Autocomplete]  `next_page` URL is absolute

### ISSUE THREAD

**Issue by syl20b** [symfony/ux#772]
Hi, 

I encounter an error due to the fact that the URL generated to retrieve the next page of results is absolute. 

I know this is a special use case because the application I'm working on is under a proxy, and the hostname in the generated  URL is different from the main one. This leads to an error because the server is not directly reachable from the outside.

So, is there a reason to generate absolute URL? 

If not, I can provide a PR to change this behaviour.

Regards,

Sylvain

**Comment by norkunas** [comment]
But if your links are generated under a proxy hostname so that would be a problem in all places, like cli, emails?

**Comment by syl20b** [comment]
> But if your links are generated under a proxy hostname so that would be a problem in all places, like cli, emails?

@norkunas  Indeed, but that's use cases I can/have to handle due to the specificity of the project architecture...
