### ISSUE TITLE
[Autocomplete + Live] Tomselect multiselect 

### ISSUE THREAD

**Issue by kevinmade** [symfony/ux#785]
There is a problem with `Autocomplete` in combination with `Livecomponent` when creating a multiselect. It's reproducible by adding `multiple` to the meal field within `MealPlannerForm`.

[Screencast from 13-04-23 11:19:04.webm](https://user-images.githubusercontent.com/93974249/231716156-764b3b08-f99e-412b-b505-4a199ff1f0b5.webm)

**Comment by weaverryan** [comment]
Yup, the behavior IS very weird I can reproduce this - I'll check into it 👍
