### ISSUE TITLE
[Autocomplete] potential BC break in the upcoming 2.x release

### ISSUE THREAD

**Issue by 1ed** [symfony/ux#793]
There is an, I think accidental, BC break in the 2.8-dev branch. Adding a new `EntityAutocompleterInterface::getGroupBy` method by https://github.com/symfony/ux/pull/481.

**Comment by wouterj** [comment]
Good spot! We should instead do what was also commented on that PR: https://github.com/symfony/ux/pull/481#discussion_r1098888595
