### ISSUE TITLE
[TwigComponent] namespace double dot isn't parsed correctly

### ISSUE THREAD

**Issue by Jupi007** [symfony/ux#803]
First of all, thanks for this awesome component!

I noticed that create a twig component using a namespace wasn't working as expected using some syntaxes.

Let's assume a component named `foo:bar`.
Using quotes, it works as expected:

```twig
{% component 'foo:bar' %}
  {# ... #}
{% endcomponent %}
```

But if I try the same without quotes or using the html syntax:

```twig
{% component foo:bar %}
  {# ... #}
{% endcomponent %}

{# OR #}

<twig:foo:bar>
  {# ... #}
</twig:foo:bar>
```

This throw a `SyntaxError`:
```
An exception has been thrown during the compilation of a template ("Unknown component "foo". The registered components are: foo:bar").
```

As you can see, it is only taking in account the namespace as component name.

**Comment by weaverryan** [comment]
Looks legit - I’m sure we’ll find a few of these. @WebMamba would you mind taking a look?
