### ISSUE TITLE
[TwigComponent] Twig HTML syntax in attribute can't be mixed

### ISSUE THREAD

**Issue by weaverryan** [symfony/ux#812]
Hi!

Still finding edge cases in the new HTML twig syntax:

```
<twig:Something
    key="new-feature-{{ features|length }}"
/>
```

In this case, `key` will pass in as the literal string `new-feature-{{ features|length }}`. We're handling attributes that *start* with `{{`, but not strings with a `{{` later, or even multiple `{{`. Probably easy to fix - I think I remember introducing this shortcoming.

**Comment by WebMamba** [comment]
Not sure de follow you here. Do you want {{ features|length }} to be computed? Because in {% component Something key="new-feature-{{ features|length }}" %} {{ features|length }}" is not computed

**Comment by norkunas** [comment]
probably it should translate into `{% component Something key="new-feature-' ~ features|length ~ '" %}`

**Comment by weaverryan** [comment]
Exactly what @norkunas said: we separate the string into  non-dynamic parts (`new-feature-`) and dynamic parts and then use Twig concatenation to connect them. Though I think the final syntax precisely would look like this:

```twig
{% component Something with { key: 'new-feature-'~(features|length') } %}
```

(notice `()` added around the dynamic `features|length` part - that's probably just a safe thing to always add so that the order of operations is correct)

**Comment by weaverryan** [comment]
@WebMamba If you're have any availability, this is the last known bug with the new syntax - I'd like to get it squashed before we release :)
