### ISSUE TITLE
[TwigComponent] Provide class/trait for testing component

### ISSUE THREAD

**Issue by ker0x** [symfony/ux#818]
It would be great to provide a `ComponentTestCase` class or `ComponentAssertionTrait` trait to help testing component.

I was thinking of something similar to [MailerAssertionsTrait](https://github.com/symfony/symfony/blob/6.3/src/Symfony/Bundle/FrameworkBundle/Test/MailerAssertionsTrait.php) so we can:

- get an instance of the component from its name and parameters
- assert that the output of the component is similar to an expected value
- etc ...

**Comment by weaverryan** [comment]
@kbond may have some ideas on this -it’s definitely missing

**Comment by kbond** [comment]
Yep, for twig components, this would be pretty straight forward.

I'm working on a new [selector api for `zenstruck/browser`](https://github.com/zenstruck/browser/pull/125). Included in this PR is a proposed new package: `zenstruck/dom`, that extracts the selector system to be used with any html string. The following could be possible:

```php
class MyComponentTest extends KernelTestCase
{
    use InteractsWithTwigComponents;

    public function test_render(): void
    {
        // simple
        $this->assertStringContainsString('some text', $this->renderComponent(MyComponent::class, ['some' => 'attributes']));

        // with zenstruck/dom
        $this->renderComponent(MyComponent::class, ['some' => 'attributes'])
            ->contains('some text')
            ->containsIn('h1', 'my title')
            ->fieldEquals('input', 'some value')
            ->containsIn(Selector::xpath('...'), 'something')
            // ...
        ;
    }
}
```
