### ISSUE TITLE
[TwigComponent] Html-like attributes aren't parsed correctly

### ISSUE THREAD

**Issue by Jupi007** [symfony/ux#829]
Some attributes are not parsed correctly and throw exceptions or render badly when using html-like syntax.

**All these ones works fine:**

```twig
<twig:foo id="bar" />
```

```twig
{% set id = 'bar' %}
<twig:foo :id="id" />
<twig:foo id="{{ id }}" />
```

```twig
{% set id = 'foo' %}
{% set idSuffix = 'bar' %}
<twig:foo :id="id ~ idSuffix" />
```

**But these ones aren't working as expected:**

```twig
{% set id = 'bar' %}
<twig:foo id="prefix-{{ id }}" />

Twig\Error\SyntaxError:
Expected attribute name when parsing the "<twig:foo" syntax.
```
```twig
{% set id = 'bar' %}
<twig:foo id="{{ id }}-suffix" />

{# No exception, but only the id var is passed to the template: #}

<div id="bar"></div>
{# Instead of: #}
<div id="bar-suffix"></div>
```

```twig
{% set id = 'bar' %}
<twig:foo :id="id ~ '-suffix'" />
<twig:foo :id="'prefix-' ~ id" />

Twig\Error\SyntaxError:
Unexpected character "\".
```

**Note:** the last one came after I updated my dependencies to get #824, so I think it is a regression because it was working fine before.

**Comment by weaverryan** [comment]
Hi!

I just tried all of these (thanks for the GREAT report, btw) and they all work fine. About 1 hour ago, I merged #827, which really overhauled all of this handling. If you grab that commit and still have problems, definitely let me know.

Cheers!

**Comment by Jupi007** [comment]
Hi @weaverryan,
you are right, I just pull the latest changes and now it works like a charm.
I was unlucky to update my dependencies a few hours too early :D

Thanks a lot !

**Comment by weaverryan** [comment]
Haha, indeed - it was unlucky timing!
