### ISSUE TITLE
UX Turbo Mercure - Basic config returns 401

### ISSUE THREAD

**Issue by jmsche** [symfony/ux#84]
Hi,

I've tried last week to set up a demo project, as simple as possible, to try UX Turbo with Mercure.

Unfortunately, I can't find a way to make this work.
The best I managed to get is a 401 Unauthorized response when the browser tries to connect to the Mercure server, while I seem to manage to connect to it correctly in my terminal using curl.

Here is the reproducer: https://github.com/jmsche/turbo-reproducer
You can read its README to launch it "easily" (using Symfony CLI & Docker Compose).

What I noted though: I don't see any token passed to the XHR request sent to Mercure.

Here is the request I got from Firefox (using right click on the request => copy as curl):

```
curl 'http://127.0.0.1:3010/.well-known/mercure?topic=chat' -H 'User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0' -H 'Accept: text/event-stream' -H 'Accept-Language: fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3' --compressed -H 'Origin: https://127.0.0.1:8000' -H 'Connection: keep-alive' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache'
```

As you can see the request is sent to the correct URL/port; so Symfony CLI does not seem to be the issue here.

**Comment by dunglas** [comment]
The problem is that you currently use an external hub when using Symfony CLI. You need to use the built-in hub provided by Symfony CLI and the JWT key must be the default one (`!ChangeMe!`).

See https://github.com/symfony/cli/issues/424 for more details and a workaround.

**Comment by chalasr** [comment]
The Symfony CLI built-in mercure hub has been removed (see https://github.com/symfony/cli/issues/449).
