### ISSUE TITLE
Error with a dash in new syntax for twig component

### ISSUE THREAD

**Issue by seb-jean** [symfony/ux#841]
Hi,

I got an error using an attribute with a dash in new syntax for twig component.

`Error rendering "Input" component: A hash key must be followed by a colon (:). Unexpected token "operator" of value "-" ("punctuation" expected with value ":").`

```twig
<twig:Input type="text" autofocus aria-expanded="true" />
```

**Comment by WebMamba** [comment]
Should be resolved really soon by #837

**Comment by seb-jean** [comment]
I will close it if the PR solves the problem.

**Comment by weaverryan** [comment]
Should be good now - but please re-open if it's not.

Cheers!

**Comment by seb-jean** [comment]
It works perfectly now
