### ISSUE TITLE
Unable to add global

### ISSUE THREAD

**Issue by seb-jean** [symfony/ux#843]
I updated `symfony/ux-twig-component` to version `2.8.0` but since I got the error `Unable to add global "xxxxxx" as the runtime or the extensions have already been initialized.`
I added addGlobal the same way as here: https://symfony.com/doc/6.2/the-fast-track/en/12-event.html#implementing-a-subscriber

**Comment by WebMamba** [comment]
Hey @seb-jean do you think it can be related to #835, if yes this fix should resolve your issue #836 😁

**Comment by seb-jean** [comment]
I open tickets but there are already PRs. Contributors go too fast 😄

**Comment by weaverryan** [comment]
This is now fixed in Twig! 2.15.5 contains it. It looks like 3.6.0 WILL fix it also, but it's not released yet. You can bring in the 3.x-dev branch in your project until then to work around the issue.

Cheers!

**Comment by seb-jean** [comment]
it works perfectly with Twig 3.6.0
