### ISSUE TITLE
[TwigComponent] Let HTML components work together with stimulus helpers

### ISSUE THREAD

**Issue by veewee** [symfony/ux#845]
First and for all: the new HTML syntax is very nice! 💣 
There are some bugs in 2.8 (which seem to be resolved on master already)

Yet this on was not reported yet:

When using the twig `stimulus_` helper functions, you get an error:

```twig
<twig:atoms:button theme="danger" class="flex-no-shrink"
    {{ stimulus_controller('confirm', {
        message: 'Are you sure you want to delete task: "'~todo.task~ '"?',
    }) }}
    {{ stimulus_action('confirm', 'ask')|stimulus_action('live', 'action') }}
    data-action-name="remove"
>
    <twig:block name="children">Remove</twig:block>

    <twig:block name="icon">
        <twig:atoms:icon icon="garbage" class="fill-gray" />
    </twig:block>

</twig:atoms:button>
```

> Error rendering "molecules:xxx" component: Expected attribute name when parsing the "<twig:atoms:button" syntax.

The expectation here is that the data attributes should be rendered prior to parsing the html.

Maybe in the same line:

```twig
{% set attrs = {class: 'bg-black'}%}
<twig:atoms:button {{ attrs }} />
```

One might expect this to work as well.

**Comment by weaverryan** [comment]
Good catch! I agree 100% with the Stimulus helpers. And you're right that thinking about this:

```
{% set attrs = {class: 'bg-black'}%}
<twig:atoms:button {{ attrs }} />
```

May help motivate *how* to make that happen. I like to borrow from existing things. So in Vue, I believe we can:

```
<div v-bind="attrs">This is a div element</div>
```

And in React, you can:

```
<div {...attr}>
```

**Comment by norkunas** [comment]
react variant is more similar to twig, I'd prefer it :)

**Comment by weaverryan** [comment]
Thinking about the root problem:

```
<twig:atoms:button theme="danger" class="flex-no-shrink"
    {{ stimulus_controller('confirm', {
        message: 'Are you sure you want to delete task: "'~todo.task~ '"?',
    }) }}
    {{ stimulus_action('confirm', 'ask')|stimulus_action('live', 'action') }}
    data-action-name="remove"
>
```

Right now (because Twig's lexer is quite internal), we use a pre-lexing system that translates the HTML syntax into Twig syntax (and then the normal Twig lexer takes over). So, the question is: is doing something like this supported yet in the native Twig syntax? I think the answer is now. But I think it would need to look like this:

```
{% component 'atoms:button' with {
    theme: 'danger',
    class: 'no-flex-shrink',
    ...stimulus_controller('confirm', {
        message: 'Are you sure you want to delete task: "'~todo.task~ '"?',
    })
} %}
```

Notice the `...`, like JSX/React. So, if you just dump something - `<twig:HTML {{ dumpSomething }} />` - inside the HTML syntax, we would expect that "something" to be an array (or array-like structure that can be "spread" - perhaps anything "Traversable").

Unfortunately, Twig doesn't support the spread operator (`...`) yet... though I personally think that'd be awesome :). I think our options are:

A) Add `...` support to Twig itself... then I think this might "just work". 
B) Add `...` support specifically into the `{% component %}` syntax.

**Comment by weaverryan** [comment]
Update:

I've got the `...` spread operator working in Twig on my local machine... so I THINK that's going to be solved!

Then, if we make the `AbstractStimulusDto` implement `IteratorAggregate` and basically return the `toArray()` method, we should be good. We would just update our pre-lexer to add the `...` Twig operator if we find a `{{ something }}` where an attribute name should be.

**Comment by weaverryan** [comment]
And... here's the Twig PR: https://github.com/twigphp/Twig/pull/3839

**Comment by WebMamba** [comment]
I think this issue can be close since https://github.com/twigphp/Twig/pull/3839 has been merged. What do you think @veewee?

**Comment by tacman** [comment]
OT: @veewee   the <twig:atoms:icon> tag looks interesting -- is that a twig component that can be installed?

**Comment by veewee** [comment]
> I think this issue can be close since [twigphp/Twig#3839](https://github.com/twigphp/Twig/pull/3839) has been merged. What do you think @veewee?

Not sure if that was the only thing that needed to be done in order for this to work.
Can try it out again once I'm back from my vacation in a week or 3.


About the icon component: it's something custom in our application. But it could be something like a font awesome (or fiends) twig component bundle.

**Comment by norkunas** [comment]
> I think this issue can be close since [twigphp/Twig#3839](https://github.com/twigphp/Twig/pull/3839) has been merged. What do you think @veewee?

I don't think so, as pre lexer still doesn't support spreading syntax as it expects attributes and values
