### ISSUE TITLE
[TwigComponent] Html component syntax and whitespace control

### ISSUE THREAD

**Issue by norkunas** [symfony/ux#849]
With the old syntax like `{{- component() -%}` and `{%- component .. -%}` it is possible to control [whitespace](https://twig.symfony.com/doc/3.x/templates.html#whitespace-control) but with the html syntax I don't see a way.

What are the options? :)

**Comment by kbond** [comment]
Is there a non-aesthetic reason for controlling whitespace?

**Comment by norkunas** [comment]
saving bytes :)

**Comment by AmProsius** [comment]
As a workaround you can use the `spaceless` filter:

```twig
{% apply spaceless %}
    <twig:Component>
        <div>Some text</div>
    </twig:Component>
{% endapply %}
```

**Comment by kbond** [comment]
> saving bytes :)

I don't think it's an issue if your web server is using content encoding like gzip/brotli.

From https://symfony.com/blog/better-white-space-control-in-twig-templates:

> Controlling white spaces is very important when using Twig to generate contents like YAML, text emails or any other format where the white spaces are significant.

> In contrast, when generating HTML contents, most of the times you should ignore this feature, because the HTML contents are minified and compressed before sending them to the users, so trying to generate perfectly aligned HTML code is just a waste of time.

**Comment by norkunas** [comment]
What about emails?
My point is not to align or something but squeeze as possible :)

**Comment by kbond** [comment]
Yeah, not sure about emails. I just remember reading that blog post and never bothering with spaceless in HTML again.

**Comment by weaverryan** [comment]
My thinking is this:

```
{% apply spaceless %}
    <twig:Component>
        <div>Some text</div>
    </twig:Component>
{% endapply %}
```

I'm not excited about adding a `<-twig:Component->` type of thing :)

**Comment by norkunas** [comment]
> I'm not excited about adding a `<-twig:Component->` type of thing :)

Me too :) strange that when `{% apply spaceless %}` is used in base template it sometimes still not enough and needs to be done in nested templates
