### ISSUE TITLE
[LiveComponent] Support UnionTypes for LiveProps

### ISSUE THREAD

**Issue by sneakyvv** [symfony/ux#853]
## Problem

```
Call to undefined method ReflectionUnionType::getName()
```

## Cause

https://github.com/symfony/ux/blob/2.x/src/LiveComponent/src/Metadata/LiveComponentMetadataFactory.php#L77 assuming to work with a `ReflectionNamedType`.

## Reproduce

Create a LiveComponent with
```
#[LiveProp] public int|string $someProperty;
```
Use it somewhere

## Expected behavior

Either:

1. Support using UnionTypes for LiveProps
2. Throw clear error that UnionTypes are not supported

---
I want to contribute, but am not sure if option 1 or 2 is desired. The current `$metadatas` array is keyed by the property name and is flat, i.e. does not allow multiple types for one property (nor does the `LivePropMetadata` object), so allowing union types (option 1) will require some changes.

**Comment by kbond** [comment]
> Support using UnionTypes for LiveProps

I definitely prefer this but yeah, would require some work.

**Comment by weaverryan** [comment]
The types are also used during the dehydration process, so this gets tricky. Even with this simple situation of `int|string`, if the user enters `2` into a box (which would be entered and, iirc, sent to the server as a string), do so cast that to an `int`? Or do we only cast of it doesn't match one of the types in the union?

For more complex things, I think it can't be allowed - e.g. to choose a wild example - `public Product|int $product`. In that case, would se use the entity hydrator to query for the `Product` or leave it as an `int`?

**Comment by sneakyvv** [comment]
Implementing a custom `mount()` method and transforming the string value into an object is also always an option when some non-standard logic needs to be done, for example when working with Value Objects or other non-Doctrine-entity objects. 

So I can agree that it can get complicated pretty fast, which I think means option 1 is out of the window?
I'll create a PR to throw a more helpful error when using union types.
