### ISSUE TITLE
[Chart.js] v3 support

### ISSUE THREAD

**Issue by duboiss** [symfony/ux#86]
Currently Symfony UX offers version 2.9.4 of Chart.js.
In december and the beginning of 2021 it was good.

But since april version 3 has been released. And we are already at 3.2 as I write this.

I also think it would be a good idea to specify on the repository readme (for each integration) which version is supported (or did I not see it?).
It would have saved me a few hours of trying to figure out why certain options weren't working.

[Migration guide](https://www.chartjs.org/docs/latest/getting-started/v3-migration.html)

Can you tell us what the procedure would be for the update?

**Comment by weaverryan** [comment]
Starting in version 1.3 (#93), the user now controls their version of Turbo (in their `package.json`).

So, to support v3, we just need 2 things :)

1) Update the controller - https://github.com/symfony/ux/blob/main/src/Chartjs/Resources/assets/src/controller.js if it needs to be updated. From a quick look... it looks like we might (?) need to call `Chart.register`?

2) Update the peer dependency version https://github.com/symfony/ux/blob/main/src/Chartjs/Resources/assets/package.json#L22 - ideally we could support v2 and v3 for awhile. But that depends on part (1) - if it's reasonable to have a controller that is smart enough to work with both.

If someone wants to make a PR, that would be awesome :)

**Comment by duboiss** [comment]
I close this issue since the support was added in #185.
