### ISSUE TITLE
[TwigComponents] Provide example of how to write a test

### ISSUE THREAD

**Issue by tacman** [symfony/ux#860]
Is there an example of how to test a component?  

That is, a functional test? Unit test?  I assume it'll be something like inject twig, create a twig snippet, then render?  Or is there a way to invoke the component class directly?

An example with the simple AlertComponent would be helpful.

Thanks.

**Comment by kbond** [comment]
Did you take a look at https://github.com/symfony/ux/pull/821?

**Comment by tacman** [comment]
EXACTLY what I was looking for.  Thanks!!
