### ISSUE TITLE
[LiveComponent] `ComponentWithFormTrait::extractValues` does not properly flattens data

### ISSUE THREAD

**Issue by norkunas** [symfony/ux#864]
Comment from the trait:

> This is used to pass the initial values into the live component's
    frontend, and it's meant to equal the raw POST data that would
    be sent if the form were submitted without modification.

But "would be sent if the form were submitted without modification" is not correct. When you render an empty form and select entity in autocomplete the value is an string ID which is converted to an entity in backend and not the entity itself. So when using form with DTO and ux autocomplete when property in DTO is predefined - aka entity is set on it the value is not flattened to the ID.

Now after upgrade to the latest dev in tests we started to get:

`Uncaught PHP Exception Twig\Error\RuntimeError: "Error rendering "InvoiceCreateForm" component: The LiveProp "formValues" on component "InvoiceCreateFormComponent" is an array, but it contains one or more keys that are not scalars: formValues.customer: Proxies\__CG__\App\Entity\User" at /var/www/html/templates/Invoice/create.html.twig`

Also based on the autocomplete structure it should be flattened to `formValues.customer[autocomplete]` but I see only `formValues.customer`

**Comment by weaverryan** [comment]
Did this not happen on 2.8.0 but is happening on the latest dev?

**Comment by norkunas** [comment]
- symfony/ux-live-component updated from 2.x-dev@e9d5b60 to 2.x-dev@9dd9eb3 patch

living on the edge :)

not sure how it was working before, but was :D

**Comment by weaverryan** [comment]
This is likely the cause then - https://github.com/symfony/ux/commit/2dbade4d041e535aaf1464ef4bc67450ccf07b60 - if you unpatch that, does it work again? Is the problem only with this autocomplete situation? I’m not surprised that logic isn’t quite right yet - it’s surprisingly tricky.

**Comment by norkunas** [comment]
Yup `if (!($child->vars['expanded'] ?? false) && ($child->vars['compound'] ?? false)) {` is the cause
Before it was properly flattening it:
![image](https://github.com/symfony/ux/assets/2722872/43ea8f84-5d50-4561-acca-f91fb9dd3392)

**Comment by weaverryan** [comment]
I'll make a PR - I think an OR condition with the old and new logic will do it. In both cases, we were under-doing the recursive flattening.
