### ISSUE TITLE
[LiveComponent] sensio/framework-extra-bundle will make your app fail under certain circumstances

### ISSUE THREAD

**Issue by Jim56450** [symfony/ux#865]
Hi !

Imagine you create a brand new project using :

`symfony new test_live_components --version="6.2.*" --webapp`

It installs **by default** the `sensio/framework-extra-bundle`.

Now add the `symfony/ux-live-component `package to your project.

Now, create your components (the one I used was similar to the the [Product Form + Category modal](https://ux.symfony.com/live-component/demos/product-form#newproductform-php)).

It uses the **Category type-hint** between NewCategoryForm.php

```
$this->emit('category:created', [
            'category' => $category->getId(),
        ]);
```

and NewProductForm.php

```
#[LiveListener('category:created')]
 public function onCategoryCreated(#[LiveArg] Category $category): void
{

    $this->category = $category;   
}
```

The problem is there is a big chance you encounter an `'Unable to guess how to get a Doctrine instance from the request information for parameter "category"'` exception when 'onCategoryCreated' is executed. **This is because** of the presence of `sensio/framework-extra-bundle`.

You have to remove it to make all this work.

`composer remove sensio/framework-extra-bundle`

It will work now and hope it will be useful to anybody, avoiding time to debug.

Maybe this could be added to the doc ?

Unfortunately, this doesn't solve the problems exposed [here](https://github.com/symfony/ux/issues/790#issuecomment-1536567581)

Thanks for reading,

Marc.

**Comment by weaverryan** [comment]
Hey @Jim56450!

Thanks for reporting this! Do you understand WHY SensioFWExtraBundle is having problems? We set `category` into `$request->attributes` like a normal request. Perhaps there's a priority problem? Perhaps this code - https://github.com/sensiolabs/SensioFrameworkExtraBundle/blob/2f886f4b31f23c76496901acaedfedb6936ba61f/src/Request/ParamConverter/DoctrineParamConverter.php#L72 - is running before our https://github.com/symfony/ux/blob/2.x/src/LiveComponent/src/EventListener/LiveComponentSubscriber.php#L139

Both listen to ControllerEvent - https://github.com/sensiolabs/SensioFrameworkExtraBundle/blob/master/src/EventListener/ParamConverterListener.php - and both have a priority of 0. I wonder if you switched the order of the bundles in `bundles.php` (to make LiveComponent) first if that fixes it. If so, we could give our listener a slight positive priority - like 10 - to make sure it runs first.

**Comment by Jim56450** [comment]
Hi Ryan,

Thanks for the feedback !

Indeed, if I put back `sensio/framework-extra-bundle`, the app works great.

If I change `bundle.php` and set `Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle::class => ['all' => true],` **before** `Symfony\UX\LiveComponent\LiveComponentBundle::class => ['all' => true],` , the app fails.

This must be a priority issue.

Indeed, updating `LiveComponentSubscriber.php` with 

`ControllerEvent::class => ['onKernelController', 20],` 

makes the app work.

Thanks !
