### ISSUE TITLE
[TwigComponent] bind twig namespace for syntax highlighting in PhpStorm

### ISSUE THREAD

**Issue by tacman** [symfony/ux#871]
I *love* the HTML component syntax!  

Is there any way to tell PhpStorm about the installed components?  

![image](https://github.com/symfony/ux/assets/619585/0620ec77-c741-4355-a2b4-abb2ad8920a1)

That is, to bind the twig namespace?

**Comment by jdreesen** [comment]
Did you try (the latest version of) the [Symfony Plugin](https://plugins.jetbrains.com/plugin/7219-symfony-support)?

**Comment by tacman** [comment]
I thought I was current, but I was not.  Working perfectly now, thanks!
