### ISSUE TITLE
ux-notify show notification to only a specific user.

### ISSUE THREAD

**Issue by Guervyl** [symfony/ux#876]
Hi, I have read the [documentation](https://symfony.com/bundles/ux-notify/current/index.html), but it does not contain more information.

I have successfully sent notification to the browser but the notification is shown for every users. I've set `{{ stream_notifications(['user1']) }}` where `user1` is not a configured hub but a dynamic string to target a specific user like the user with the id 1. As the documentation does not explain how to use `$this->notifier->send(new Notification('Flash sales has been started!', ['...]),...);` to send to dynamic string instead of **specify the topics to send the notification in the MERCURE_DSN environment variable by specifying the topics query parameter**  I'm stuck.

Also it would be great to have more information about the `notifier.yaml` config file wich include `channel_policy`,  why `chatter_transports` refers to as just `chat`, why use `texter_transports`...

**Comment by weaverryan** [comment]
You're right - it was not obvious how to specify the topics dynamically. I've fixed this in #878.

Please let me know if it's helpful.

Cheers!

**Comment by Guervyl** [comment]
Your solution is working now. But there are some problem-ish.

- First problem:
   I have set `stream_notifications()` in the base template. But, the notification is being sent to the user for every currently tab opened. I mean, I have 3 tabs open of my website, the browser shows me the notification 3 times. It would be better if the notification shows only once.

- Second problem or inconvenient:
    I want to be able to set the link on which the browser should redirect the user if he/she clicks the notification or to be able to handle click event from JavaScript or stimulus.

- Third problem-ish:
    From the documentation I didn't know that `ChatterInterface`, `ChatMessage` neither `MercureOptions` exist. It would be great to have a complete list of classes that developers can use to customize the notifier.

**Comment by weaverryan** [comment]
> I have set stream_notifications() in the base template. But, the notification is being sent to the user for every currently tab opened. I mean, I have 3 tabs open of my website, the browser shows me the notification 3 times. It would be better if the notification shows only once.

Hmm... yea, that's tricky. I'm not sure how to solve that. You have the JavaScript running 3 times and so all 3 versions of the JavaScript receive the update. This is normally not an issue when you are, for example, updating an element on the page (you actually DO want the element to be updated on all 3 pages). But I see your point in this case. But I can't think of how you would solve that.

> I want to be able to set the link on which the browser should redirect the user if he/she clicks the notification or to be able to handle click event from JavaScript or stimulus.

Not sure about this - I'm not terribly familiar with the Notification API

> From the documentation I didn't know that ChatterInterface, ChatMessage neither MercureOptions exist. It would be great to have a complete list of classes that developers can use to customize the notifier.

Those are the only 3 classes that are relevant - and they're now mentioned in the docs :). I wasn't aware of these either until I started digging for your question.

Cheers!

**Comment by Guervyl** [comment]
Thanks for your help and answers.
