### ISSUE TITLE
[LiveComponent] Upgrade to 2.8.1 fails with "property_info" error

### ISSUE THREAD

**Issue by benr77** [symfony/ux#888]
When I upgrade from 2.4 to 2.8.1 I get the following error during cache clear, even though the `symfony/property-info` package is installed. Am running Symfony 6.2.10.

```
The service "ux.live_component.metadata_factory" has a dependency on a non-existent service "property_info". Did  
   you mean one of these: "cache.property_info", "cache.property_info.recorder_inner"? 
```

If I run `bin/console debug:container property_info` I get:

```
 Select one of the following services to display its information:
  [0] cache.property_info
  [1] property_info.serializer_extractor
  [2] doctrine.orm.default_entity_manager.property_info_extractor
  [3] cache.property_info.recorder_inner
```

Seems to be coming from here which has changed recently.

https://github.com/symfony/ux-live-component/blob/a184466f5b9e9e20c5d6c843e83a70b49b687726/src/DependencyInjection/LiveComponentExtension.php#L163

Any thoughts?

**Comment by weaverryan** [comment]
Odd. You have the property info component… but not the service. I can’t reasonably see how that’s possible.

What version of symfony/framework-bundle do you have? And what do you see if you run “bin/console debug:config framework” for the property_info section? Do you see enabled: true?

cheers!

**Comment by benr77** [comment]
FramworkBundle is 6.2.10. 

But good catch, it turns out I do have `property_info: enabled: false` for some reason. I have no idea how this came to be but obviously that's a different problem.

Thanks Ryan!

**Comment by weaverryan** [comment]
Phew! Carry on then :)
