### ISSUE TITLE
[LiveComponent] Strange behavior

### ISSUE THREAD

**Issue by seb-jean** [symfony/ux#889]
Hi,

There is a strange behavior. Here are the explanations:
I went to the https://ux.symfony.com/live-component page, and typed `abcdefghijklmnopqrstuvwxyz`. I deleted the characters by hitting the `Backspace` key but not by holding it down but by tapping it 26 times. And at some point characters came back.

You can see what it looks like with the video. The "hi" characters come back:

https://github.com/symfony/ux/assets/12116264/33a46542-8abe-4883-b004-2f2499b329da

Here is what it looks like in detail:
- abcdefghijklm
- abcdefghijkl
- abcdefghijk
- abcdefghij
- abcdefghi
- abcdefgh
- abcdefg
- abcdefghi
- abcdefgh
- abcdefg
- abcdef
- abcde
- abcd
- abc
- ab
- a

I have the same problem on a personal project.

**Comment by weaverryan** [comment]
Hmm, we specifically have code to handle this. What browser are you using? I cannot seem to replicate this, even on https://ux.symfony.com/live-component like you did.

**Comment by seb-jean** [comment]
I use Google Chrome version 113.0.5672.127 (Official Build) (64 bits).

I selected "Slow 3G"

![throttle2](https://github.com/symfony/ux/assets/12116264/6a86e2d7-9553-43e9-adba-06264f0ee5f4)

Here is another example:

https://github.com/symfony/ux/assets/12116264/cc758fb5-51b9-46b1-99fc-c3faaa4262c0
