### ISSUE TITLE
Using Routes in webpack as with UX Translator

### ISSUE THREAD

**Issue by ValentinRgt** [symfony/ux#893]
Hello,

I recently discovered the new UX called Translator and it is still very interesting.
I wanted to know if anyone has planned to redo the same system but for the use of Routes?

**Comment by jdreesen** [comment]
https://github.com/symfony/ux/pull/616#issuecomment-1480001911

**Comment by ValentinRgt** [comment]
> [#616 (comment)](https://github.com/symfony/ux/pull/616#issuecomment-1480001911)

I wonder if the Core Team has planned to integrate this functionality into Symfony UX so as to no longer use a library that works strangely...

**Comment by Kocal** [comment]
Hi, this is something I've planned to work on when I got some free time
