### ISSUE TITLE
Manually using the Stimulus Controller - custom controller onChange 

### ISSUE THREAD

**Issue by stloc** [symfony/ux#921]
How to work with change event in symfony/ux-autocomplete/autocomplete ?
as custom-autocomplete controller https://symfony.com/bundles/ux-autocomplete/current/index.html#extending-tom-select 

```
   _onPreConnect(event) {
        event.detail.options.onChange = (value) => {
            // ...
        };
    }
```

If I change to custom-autocomplete rendering autocomplete is KO : 
```
<select
    name="food"
    {{ stimulus_controller('custom-autocomplete', {
        url: path('ux_entity_autocomplete', { alias: 'food' })
    }) }}
>
```

**Comment by weaverryan** [comment]
Hi!

Add both controllers to your element. Order doesn’t matter, but add the normal symfony one first with the url option. Then add the second one via |stimulus_controller(custom-autocomplete).

Cheers!

**Comment by stloc** [comment]
thanks,
it's better but it doesn't pass in _onPreConnect of custom-autocomplete (only in initialize)
