### ISSUE TITLE
[TwigComponent] SyntaxError when using HTML syntax and an attribute is empty

### ISSUE THREAD

**Issue by predakanga** [symfony/ux#925]
I've been attempting to write a component to display user info in my app, as shown below:

```
<twig:UserInfo id="{{ app.user.id }}" display="status,title" />
```

The problem occurs when I set display="", i.e. `<twig:UserInfo id="{{ app.user.id }}" display="" />`.

This gets translated by TwigPreLexer into `{{ component('UserInfo' {'id': (app.user.id), 'display': }) }}`, which causes a syntax error.

symfony/ux-twig-component version: v2.9.1
Twig version: v2.15.5
symfony/twig-bundle version: v6.3.0

EDIT: Added version info

**Comment by weaverryan** [comment]
Yup, definitely looks like a bug! Well-reported
