### ISSUE TITLE
[StimulusBundle] Add stimulus_outlet() twig function

### ISSUE THREAD

**Issue by pmishev** [symfony/ux#933]
### Description

Do you have plans to add a `stimulus_outlet()` twig function in `symfony/stimulus-bundle`?

https://stimulus.hotwired.dev/reference/outlets

### Example

`{{ stimulus_outlet('controllerName', 'targetControllerName', 'cssSelector') }}`

**Comment by weaverryan** [comment]
Yes! In fact, it’s partially done - https://github.com/symfony/webpack-encore-bundle/pull/206 - someone just needs to take that work, move it here and finish it. It can be anyone - we can give credit to the original author if someone builds off of it, so that’s not a problem :)

**Comment by norkunas** [comment]
This can be closed as this was implemented in https://github.com/symfony/ux/pull/942 just differently
