### ISSUE TITLE
[Translator] TranslationsDumper generates duplicate keys in JS translation files 

### ISSUE THREAD

**Issue by jkgroupe** [symfony/ux#938]
When I generate JS translation files, I cannot use it because I have duplicate keys. 

For instance, if I have 2 different translations ids like `Error` and `Error.` in my translation files, it generates the same key in JS file as `ERROR` so I have it twice in my translation file and I cannot build my JS files

![Capture d’écran 2023-06-13 à 16 09 55](https://github.com/symfony/ux/assets/4007104/c629fc3b-5c1f-4d68-8a13-5c2f3c2c5e4d)

The problem comes from the `TranslationsDumper` class which using `translation id` instead of `constant name` in `getTranslations` method

The `id` should be the final `constant name` to exclude duplicate keys instead of the translation id like below 
```
$constantName = s($id)->ascii()->snake()->upper()->toString();

$translations[$constantName] ??= [];
$translations[$constantName][$realDomain] ??= [];
$translations[$constantName][$realDomain][$locale] = $message;
```

Hope this is clear for everyone

**Comment by weaverryan** [comment]
Ping @Kocal :). I actually noticed this issue also - thanks @jkgroupe for opening up the nice issue.

**Comment by Kocal** [comment]
Hi, to me this looks like a bug to fix on your side, you must choose between `Error` and `Error.` translation key

**Comment by jkgroupe** [comment]
Hi @Kocal, I should have specified that it doesn't come from my translation files but from third party packages but I don't not which ones. They both have the "validators" domain

**Comment by Kocal** [comment]
Alright. Well, the thing is that we cannot use the same constant name `ERROR` for both `Error` and `Error.` translations, they **are not** the same translations and it can leads to undesired behaviours (what if both translations are defined for the same locale?).

We can try to prefix the constant name by a number to prevent collisions. I will work on it asap.

**Comment by Kocal** [comment]
Opened #945

**Comment by berryerlouis** [comment]
I have the same issue with another key : 
'THE_NUMBER_OF_ELEMENTS_IN_THIS_COLLECTION_SHOULD_BE_A_MULTIPLE_OF_COMPARED_VALUE' .
The duplicates is in vendor/symfony/validator/Resources/translations/validators.hy.xlf file and the difference is on the final dot '.'
![image](https://github.com/symfony/ux/assets/15996552/5bea4348-adfa-446c-af5d-75f0db5d5151)

If I remove the final dot, the editor is able to find the same sentence :
![image](https://github.com/symfony/ux/assets/15996552/44f1a654-e632-4173-920f-d818a9e9378e)

Thanks

**Comment by jkgroupe** [comment]
Yes, I have this issue too. The first one is a dot and the second one is an unicode converted dot 

![Capture d’écran 2023-06-16 à 10 04 16](https://github.com/symfony/ux/assets/4007104/62edd756-2b68-4e53-985b-8107d738380c)
