### ISSUE TITLE
[Live] Better DTO Dehydration

### ISSUE THREAD

**Issue by weaverryan** [symfony/ux#955]
Hi!

LiveComponent can dehydrate many different `LiveProp` data types - scalars, DateTime objects, entities, collection of entities, etc. But it can't dehydrate DTO's out-of-the-box.

### The Setup:

Suppose you have a live component and you want to leverage DTO. This example uses a form, but that's not a requirement:

```php
CustomerDetails
{
    use DefaultActionTrait;
    use ComponentWithFormTrait;
​
    #[LiveProp]
    public CustomerInfoDto $customerInfoDto;

    protected function instantiateForm(): FormInterface
    {
        return $this->createForm(CustomInfoType::class, $this->customerInfoDto);
    }
}
```

And the DTO:

```php
class CustomerInfoDto
{
    public string $name;
    public string $address1;
    private string $city;

    public User $owner;

    // getter and setter for city since it's private
}
```

Currently, the `$customerDto` can't be dehydrated. You COULD set `useSerializerForHydration: true`, but that would result in the `CustomerInfoDto.owner` entity in being serialized... which could expose data and can result in a circular reference if that entity has more relationships where both sides are mapped.

### Proposed Solution

Introduce a new "mode" where we "cascade" the (de)hydration process onto the DTO.

```diff
CustomerDetails
{
-    #[LiveProp]
+    #[LiveProp(cascadeHydration: true)]
    public CustomerInfoDto $customerInfoDto;
}
```

With this set, live components WOULD dehydrate `CustomInfoDto` using the same logic it uses for LiveProp. Specifically, it would:

A) find all properties that are both readable & writable inside `CustomerInfoDto` and (de)hydrate these (using the property access component)
B) For (de)hydration, read the property type, like with a normal `LiveProp`.

There will likely be some edge-cases that we wouldn't handle on purpose - e.g. there would not be any way to "exclude" a property from being (de)hydrated. We don't want to reinvent the serializer.

WDYT - helpful? Should this, perhaps, be the default mode for `LiveProp` objects?

**Comment by axel37** [comment]
Maybe I'm just not familiar enough with the topic, but how does this solution differ from serializing the entity ?

I'm simply trying to understand how it would work ^^
Thanks for giving some thoughts about this issue !

**Comment by norkunas** [comment]
Additional thing to this topic:

When using DTO's with generics hydration fails badly. For example in the form component I declare (because in SomeDTO I use `@template`):
```php
/**
 * @var SomeDTO<MyEntity>
 */
#[LiveProp(fieldName: 'data')]
public SomeDTO $input;
```

Then when hydaring the `MyEntity` is passed as the **COLLECTION** type for some reason. Maybe property info component does not understand it properly? And then `DoctrineEntityHydrationExtension` kicks in and tries to find that entity with the value of the `SomeDTO` fields which is clearly not right because properties of SomeDTO are not `MyEntity` identifiers.

Part of stack trace:
```
Doctrine\ORM\Exception\MissingIdentifierField:
The identifier id is missing for a query of App\Entity\MyEntity

  at vendor/doctrine/orm/lib/Doctrine/ORM/Exception/MissingIdentifierField.php:13
  at Doctrine\ORM\Exception\MissingIdentifierField::fromFieldAndClass('id', 'App\\Entity\\MyEntity')
     (vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:462)
  at Doctrine\ORM\EntityManager->find('App\\Entity\\MyEntity', array(array('language' => 'lt', 'proficiency' => 'native_or_bilingual'), array('language' => 'en', 'proficiency' => 'professional_working')))
     (vendor/symfony/ux-live-component/src/Hydration/DoctrineEntityHydrationExtension.php:48)
  at Symfony\UX\LiveComponent\Hydration\DoctrineEntityHydrationExtension->hydrate(array(array('language' => 'lt', 'proficiency' => 'native_or_bilingual'), array('language' => 'en', 'proficiency' => 'professional_working')), 'App\\Entity\\MyEntity')
     (vendor/symfony/ux-live-component/src/LiveComponentHydrator.php:466)
  at Symfony\UX\LiveComponent\LiveComponentHydrator->hydrateObjectValue(array(array('language' => 'lt', 'proficiency' => 'native_or_bilingual'), array('language' => 'en', 'proficiency' => 'professional_working')), 'App\\Entity\\MyEntity', true, 'App\\Twig\\WorkInformationFormComponent', 'input.spokenLanguages')
     (vendor/symfony/ux-live-component/src/LiveComponentHydrator.php:415)
  at Symfony\UX\LiveComponent\LiveComponentHydrator->hydrateValue(array(..., 'spokenLanguages' => array(array('language' => 'lt', 'proficiency' => 'native_or_bilingual'), array('language' => 'en', 'proficiency' => 'professional_working')), ...), object(LivePropMetadata), object(WorkInformationFormComponent))
     (vendor/symfony/ux-live-component/src/LiveComponentHydrator.php:154)
```

In this case are there any easy workarounds without moving SCA errors to baseline?

**Comment by weaverryan** [comment]
> @axel37 Maybe I'm just not familiar enough with the topic, but how does this solution differ from serializing the entity ?

It's a fair question - serializing and dehydrating are quite similar. The main difference in practice is that, when we "dehydrate" an entity, we only want to dehydrate to its id, whereas the serializer gives us an array of all the properties (including an array of related objects, etc). The serializer will also happily serialize things that can't be deserialized to the same thing - imagine a property that holds a `Post` object, but the property is not typed. The serializers will serialize the `Post` just fine, but during deserialization, it won't know that it should turn the data back into a `Post` object. With the hydration system, we check for this.

Still, they are super similar, and that totally bothers me :). I really tried in 2.8 to continue using the serializer, but I was fighting a lot - at one point I had large parts of `ObjectNormalizer` duplicated inside live components.

@norkunas can you open a separate issue? It sounds like a bug. And, on that issue, to clarify, are you documenting that `SomeDto` can be iterated over to get `MyEntity` objects?

**Comment by norkunas** [comment]
> And, on that issue, to clarify, are you documenting that SomeDto can be iterated over to get MyEntity objects?

No. I'm just filling in the template of SomeDTO for SA tools that is `MyEntity`.

There is an issue in Symfony itself already but currently I'm just asking for workarounds :)
