### ISSUE TITLE
Modify tooltip text with a callback (Chartjs UX)

### ISSUE THREAD

**Issue by Mis0u** [symfony/ux#99]
Hi guys,

It's so hard to work with ChartJs in symfony UX. It's not the same doc than the pure ChartJS, for example I was re-writing the tooltip and the doc in ChartJs is : 
```javascript
options: {
        plugins: {
            tooltip:
```

and in Symfony  : 
```php
 $chart->setOptions(
            [
                'legend' => false,
                'tooltips' => [
                    'backgroundColor' => 'red',
```
plugins has disappeared and tooltip became tooltips, why ? It make me lost a lot of time ...

Anyway, now I'm trying to modify the text in my tooltipS and I'm stuck with the callback, I know it's a syntax problem but I can't find what is wrong : 

```php
'tooltips' => [
                    'backgroundColor' => 'red',
                    'callbacks' => [
                        'title' => fn($tooltipItem) => 'Here is my new text'
                    ]
```

An idea ?

**Comment by Kocal** [comment]
Hi,

You are reading the Chart.js 3 documentation while using Chart.js 2 (Symfony UX only supports Chart.js 2 ATM), so things have changed and options are different.

**Comment by Mis0u** [comment]
Thx Kocal
